//! BitNet HLS engine-top emitter (Wave 36f, R-BN-6).
//!
//! Exposes a single emitter:
//!
//!   * `bitnet_engine_top` -- the top-level wrapper that turns the
//!     compute / buffering / I/O blocks emitted in W36a..W36e into a
//!     complete multi-layer BitNet inference engine. The wrapper
//!     instantiates a `multilayer_sequencer` (high-level layer-driver
//!     FSM) and a `double_buffer_ctrl` (ping-pong activation storage)
//!     and adds a 32-bit free-running cycle counter gated by `busy`
//!     so the host can profile inference latency.
//!
//! Port summary:
//!
//! | Group         | Signals                                                |
//! |---------------|--------------------------------------------------------|
//! | Clock / reset | clk, rst_n                                             |
//! | Control       | start, num_layers[5:0], neurons_per_layer[15:0],       |
//! |               | chunks_per_neuron[7:0], signed threshold[15:0]         |
//! | External mem  | mem_addr[31:0], mem_rd_en, mem_rd_data[63:0],          |
//! |               | mem_rd_valid                                           |
//! | Status        | busy, done, cycle_count[31:0]                          |
//!
//! Note: the emitted Verilog references two sub-modules by name --
//! `multilayer_sequencer` and `double_buffer_ctrl`. The latter is
//! produced by the W36c `gen-double-buffer-ctrl` emitter. The former
//! is currently expected from the upstream vibee-lang library and is
//! left as a black-box reference here; the rest of the engine-top is
//! self-contained.
//!
//! Algorithm ported from `gHashTag/vibee-lang`
//! `src/vibeec/verilog_codegen.zig` lines 1667-1725
//! (`writeBitNetEngineTop`). Original author: Dmitrii Vasilev.
//!
//! Constitutional notes:
//!   L2: lives only under `bootstrap/`; emitter is a pure additive
//!       string builder; no edits under `gen/`, `coq/`, `trios-coq/`,
//!       `proofs/`, `specs/`, `conformance/`, `architecture/`,
//!       `rings/`, or root `Cargo.toml`.
//!   L3: ASCII source, English doc-comments only.
//!   L5: numeric kernel untouched -- this emitter is a structural
//!       wrapper; it does not redefine any constant inside the
//!       trinity invariant `phi^2 + 1/phi^2 = 3`.
//!   L7: no `*.sh` invoked.

/// Default identifier for the engine-top module.
pub const DEFAULT_BITNET_ENGINE_TOP_NAME: &str = "bitnet_engine_top";

fn is_valid_verilog_ident(s: &str) -> bool {
    let mut chars = s.chars();
    let first = match chars.next() {
        Some(c) => c,
        None => return false,
    };
    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn resolve_ident<'a>(candidate: &'a str, default: &'a str) -> &'a str {
    if is_valid_verilog_ident(candidate) {
        candidate
    } else {
        default
    }
}

/// Build the `bitnet_engine_top` SystemVerilog module text.
///
/// Parameters:
///   * `module_name` -- Verilog identifier; falls back to
///     `bitnet_engine_top` if the candidate is not a valid Verilog
///     identifier (must start with `[A-Za-z_]` and contain only
///     `[A-Za-z0-9_]`).
pub fn build_bitnet_engine_top(module_name: &str) -> String {
    let name = resolve_ident(module_name, DEFAULT_BITNET_ENGINE_TOP_NAME);
    let mut s = String::new();

    s.push_str("// ===========================================================================\n");
    s.push_str("// BITNET INFERENCE ENGINE TOP - Complete multi-layer inference\n");
    s.push_str("// ===========================================================================\n");
    s.push_str("// Generated by t27c gen-bitnet-engine-top (Wave 36f, R-BN-6).\n");
    s.push_str("// Wraps multilayer_sequencer + double_buffer_ctrl + cycle counter\n");
    s.push_str("// into a host-startable multi-layer BitNet inference engine.\n");
    s.push_str("\n");

    s.push_str(&format!("module {} (\n", name));
    s.push_str("    input  wire        clk,\n");
    s.push_str("    input  wire        rst_n,\n");
    s.push_str("    input  wire        start,\n");
    s.push_str("    input  wire [5:0]  num_layers,\n");
    s.push_str("    input  wire [15:0] neurons_per_layer,\n");
    s.push_str("    input  wire [7:0]  chunks_per_neuron,\n");
    s.push_str("    input  wire signed [15:0] threshold,\n");
    s.push_str("    // External memory interface (simplified)\n");
    s.push_str("    output wire [31:0] mem_addr,\n");
    s.push_str("    output wire        mem_rd_en,\n");
    s.push_str("    input  wire [63:0] mem_rd_data,\n");
    s.push_str("    input  wire        mem_rd_valid,\n");
    s.push_str("    // Status\n");
    s.push_str("    output wire        busy,\n");
    s.push_str("    output wire        done,\n");
    s.push_str("    output wire [31:0] cycle_count,\n");
    s.push_str("    // Neuron output (post-threshold), now that the MAC is wired\n");
    s.push_str("    output wire        neuron_out,\n");
    s.push_str("    output wire        neuron_out_valid\n");
    s.push_str(");\n");
    s.push_str("\n");

    s.push_str("    // Multi-layer sequencer\n");
    s.push_str("    wire [5:0] current_layer;\n");
    s.push_str("    wire layer_start, start_prefetch, prefetch_done;\n");
    s.push_str("    multilayer_sequencer seq (\n");
    s.push_str("        .clk(clk), .rst_n(rst_n), .start(start), .num_layers(num_layers),\n");
    s.push_str("        .layer_done(layer_done_pulse), .prefetch_done(prefetch_done),\n");
    s.push_str("        .current_layer(current_layer), .layer_start(layer_start),\n");
    s.push_str("        .start_prefetch(start_prefetch), .inference_done(done)\n");
    s.push_str("    );\n");
    s.push_str("\n");

    s.push_str("    // Double buffer controller\n");
    s.push_str("    wire use_buffer_a;\n");
    s.push_str("    wire [11:0] buf_read_addr, buf_write_addr;\n");
    s.push_str("    // Per-layer sequencer drives neuron_id\n");
    s.push_str("    wire [15:0] neuron_id;\n");
    s.push_str("    wire [7:0]  chunk_id;\n");
    s.push_str("    wire first_chunk, last_chunk, layer_valid, layer_done_pulse;\n");
    s.push_str("    layer_sequencer lseq (\n");
    s.push_str("        .clk(clk), .rst_n(rst_n),\n");
    s.push_str("        .start(layer_start),\n");
    s.push_str("        .num_neurons(neurons_per_layer),\n");
    s.push_str("        .num_chunks(chunks_per_neuron),\n");
    s.push_str("        .neuron_id(neuron_id),\n");
    s.push_str("        .chunk_id(chunk_id),\n");
    s.push_str("        .first_chunk(first_chunk),\n");
    s.push_str("        .last_chunk(last_chunk),\n");
    s.push_str("        .valid(layer_valid),\n");
    s.push_str("        .done(layer_done_pulse)\n");
    s.push_str("    );\n");
    s.push_str("    // prefetch_done tied off until weight_prefetch_ctrl is wired\n");
    s.push_str("    assign prefetch_done = 1'b1;\n");
    s.push_str("\n");
    s.push_str("    double_buffer_ctrl dbl_buf (\n");
    s.push_str("        .clk(clk), .rst_n(rst_n), .layer_done(layer_done_pulse),\n");
    s.push_str("        .current_layer(current_layer), .use_buffer_a(use_buffer_a),\n");
    s.push_str("        .read_addr(buf_read_addr), .write_addr(buf_write_addr), .neuron_id(neuron_id[11:0])\n");
    s.push_str("    );\n");
    s.push_str("\n");

    s.push_str("    // ------------------------------------------------------------------\n");
    s.push_str("    // Datapath: weight memory, activation memory, and the MAC.\n");
    s.push_str("    //\n");
    s.push_str("    // Until 2026-08-09 this top instantiated only the three control-plane\n");
    s.push_str("    // sequencers; pipeline_stage2_compute and weight_bram were emitted but\n");
    s.push_str("    // never wired, so nine modules existed and no data flowed. See\n");
    s.push_str("    // docs/BITNET_V2_POSITION.md section 2.3.\n");
    s.push_str("    //\n");
    s.push_str("    // weight_bram has a ONE-CYCLE read latency (`rd_data <= mem[rd_addr]`),\n");
    s.push_str("    // so the sequencer's valid/first/last and the activation word are\n");
    s.push_str("    // delayed by one cycle to meet the weight word at the MAC. Feeding the\n");
    s.push_str("    // MAC directly from the sequencer would pair chunk N's control with\n");
    s.push_str("    // chunk N-1's weights. Proved aligned in\n");
    s.push_str("    // formal/engine_top_props.sv (a_mac_control_aligned).\n");
    s.push_str("    // ------------------------------------------------------------------\n");
    s.push_str("\n");
    s.push_str("    // Chunk-sequential address: the sequencer walks (neuron, chunk) in\n");
    s.push_str("    // order, so a running counter equals neuron_id*num_chunks + chunk_id\n");
    s.push_str("    // without needing a multiplier.\n");
    s.push_str("    reg [11:0] chunk_addr;\n");
    s.push_str("    always @(posedge clk or negedge rst_n)\n");
    s.push_str("        if (!rst_n)          chunk_addr <= 12'd0;\n");
    s.push_str("        else if (layer_start) chunk_addr <= 12'd0;\n");
    s.push_str("        else if (layer_valid) chunk_addr <= chunk_addr + 12'd1;\n");
    s.push_str("\n");
    s.push_str("    wire [53:0] weight_word, activation_word;\n");
    s.push_str("\n");
    s.push_str("    weight_bram wmem (\n");
    s.push_str("        .clk(clk), .rd_addr(chunk_addr), .rd_data(weight_word),\n");
    s.push_str("        .wr_addr(12'd0), .wr_data(54'd0), .wr_en(1'b0)\n");
    s.push_str("    );\n");
    s.push_str("\n");
    s.push_str("    // Activation storage reuses the same generic BRAM block, addressed by\n");
    s.push_str("    // the double-buffer controller rather than the chunk counter.\n");
    s.push_str("    weight_bram amem (\n");
    s.push_str("        .clk(clk), .rd_addr(buf_read_addr), .rd_data(activation_word),\n");
    s.push_str("        .wr_addr(buf_write_addr), .wr_data(54'd0), .wr_en(1'b0)\n");
    s.push_str("    );\n");
    s.push_str("\n");
    s.push_str("    // One-cycle skew to match the BRAM read latency.\n");
    s.push_str("    reg mac_valid_q, mac_first_q, mac_last_q;\n");
    s.push_str("    always @(posedge clk or negedge rst_n)\n");
    s.push_str("        if (!rst_n) begin\n");
    s.push_str("            mac_valid_q <= 1'b0; mac_first_q <= 1'b0; mac_last_q <= 1'b0;\n");
    s.push_str("        end else begin\n");
    s.push_str("            mac_valid_q <= layer_valid;\n");
    s.push_str("            mac_first_q <= first_chunk;\n");
    s.push_str("            mac_last_q  <= last_chunk;\n");
    s.push_str("        end\n");
    s.push_str("\n");
    s.push_str("    wire        mac_valid_out, mac_result_final;\n");
    s.push_str("    wire signed [15:0] mac_result;\n");
    s.push_str("    pipeline_stage2_compute mac (\n");
    s.push_str("        .clk(clk), .rst_n(rst_n),\n");
    s.push_str("        .valid_in(mac_valid_q),\n");
    s.push_str("        .input_chunk(activation_word),\n");
    s.push_str("        .weight_chunk(weight_word),\n");
    s.push_str("        .first_chunk(mac_first_q),\n");
    s.push_str("        .last_chunk(mac_last_q),\n");
    s.push_str("        .valid_out(mac_valid_out),\n");
    s.push_str("        .result(mac_result),\n");
    s.push_str("        .result_final(mac_result_final)\n");
    s.push_str("    );\n");
    s.push_str("\n");
    s.push_str("    // Neuron output: compare the accumulated dot product against the\n");
    s.push_str("    // host-programmed threshold. `threshold` was previously declared and\n");
    s.push_str("    // never referenced.\n");
    s.push_str("    assign neuron_out       = mac_valid_out && (mac_result >= threshold);\n");
    s.push_str("    assign neuron_out_valid = mac_valid_out;\n");
    s.push_str("\n");
    s.push_str("    // Cycle counter\n");
    s.push_str("    reg [31:0] cycles;\n");
    s.push_str("    always @(posedge clk or negedge rst_n)\n");
    s.push_str("        if (!rst_n) cycles <= 32'd0;\n");
    s.push_str("        else if (start) cycles <= 32'd0;\n");
    s.push_str("        else if (busy) cycles <= cycles + 32'd1;\n");
    s.push_str("    assign cycle_count = cycles;\n");
    s.push_str("    assign busy = (current_layer != 6'd0) || layer_start;\n");
    s.push_str("\n");

    s.push_str("`ifdef FORMAL\n");
    s.push_str("    // ------------------------------------------------------------------\n");
    s.push_str("    // Integration properties. These are the first properties in this repo\n");
    s.push_str("    // that range over more than one module: everything proved before now\n");
    s.push_str("    // was module-scoped, because until the datapath was wired there was no\n");
    s.push_str("    // system behaviour to state a property about.\n");
    s.push_str("    //\n");
    s.push_str("    // They live inside the module under `ifdef FORMAL rather than in a\n");
    s.push_str("    // wrapper because the alignment they check is internal, and yosys's\n");
    s.push_str("    // `sat` needs a single flattened module -- which mangles the names a\n");
    s.push_str("    // wrapper would have to reference.\n");
    s.push_str("    //\n");
    s.push_str("    // Prove with:\n");
    s.push_str("    //   yosys -p \"read_verilog -sv -formal -DFORMAL <bundle>/*.sv; \\\n");
    s.push_str("    //             prep -top bitnet_engine_top -flatten; async2sync; \\\n");
    s.push_str("    //             chformal -lower; sat -verify -prove-asserts -seq 12 \\\n");
    s.push_str("    //             -set-init-zero -set-assumes\"\n");
    s.push_str("    // ------------------------------------------------------------------\n");
    s.push_str("\n");
    s.push_str("    // Harness sanity: a tautology. If this refutes, the run is not\n");
    s.push_str("    // evaluating what it appears to.\n");
    s.push_str("    always @(posedge clk) if (rst_n)\n");
    s.push_str("        a_sanity: assert (chunk_addr == chunk_addr);\n");
    s.push_str("\n");
    s.push_str("    // THE integration property, stated on the MAC's OUTPUT rather than on\n");
    s.push_str("    // the skew registers. An earlier version asserted only that\n");
    s.push_str("    // mac_valid_q == $past(layer_valid), which is true of the registers no\n");
    s.push_str("    // matter what the MAC is actually connected to -- rewiring valid_in\n");
    s.push_str("    // straight to layer_valid left every such property PROVING. A property\n");
    s.push_str("    // about a signal is not a property about the wire it feeds.\n");
    s.push_str("    //\n");
    s.push_str("    // pipeline_stage2_compute sets valid_out <= last_chunk when valid_in,\n");
    s.push_str("    // else 0. So the MAC's own output pins down which control it consumed.\n");
    s.push_str("    always @(posedge clk) if (rst_n && $past(rst_n))\n");
    s.push_str("        a_mac_consumed_skewed_control:\n");
    s.push_str("            assert (mac_valid_out == ($past(mac_valid_q) && $past(mac_last_q)));\n");
    s.push_str("\n");
    s.push_str("    // Supporting: the skew registers themselves lag by exactly one cycle.\n");
    s.push_str("    // latency, so the MAC's control must lag the sequencer by exactly one\n");
    s.push_str("    // cycle. Off by one in either direction pairs chunk N's control with\n");
    s.push_str("    // chunk N-1's or N+1's weights, and every module-level property would\n");
    s.push_str("    // still pass.\n");
    s.push_str("    always @(posedge clk) if (rst_n && $past(rst_n))\n");
    s.push_str("        a_mac_control_aligned: assert (mac_valid_q == $past(layer_valid));\n");
    s.push_str("    always @(posedge clk) if (rst_n && $past(rst_n))\n");
    s.push_str("        a_mac_first_aligned: assert (mac_first_q == $past(first_chunk));\n");
    s.push_str("    always @(posedge clk) if (rst_n && $past(rst_n))\n");
    s.push_str("        a_mac_last_aligned: assert (mac_last_q == $past(last_chunk));\n");
    s.push_str("\n");
    s.push_str("    // The MAC may only be fed while the layer sequencer is producing work.\n");
    s.push_str("    always @(posedge clk) if (rst_n && $past(rst_n))\n");
    s.push_str("        a_no_mac_work_without_sequencer: assert (!mac_valid_q || $past(layer_valid));\n");
    s.push_str("\n");
    s.push_str("    // The chunk address is bounded by the buffer it indexes, and is reset\n");
    s.push_str("    // at layer start so layers do not read each other's weights.\n");
    s.push_str("    always @(posedge clk) if (rst_n && $past(rst_n) && $past(layer_start))\n");
    s.push_str("        a_chunk_addr_resets: assert (chunk_addr == 12'd0);\n");
    s.push_str("\n");
    s.push_str("    // threshold now gates the output; it was declared and unused before.\n");
    s.push_str("    always @(posedge clk) if (rst_n)\n");
    s.push_str("        a_output_needs_valid: assert (!neuron_out || neuron_out_valid);\n");
    s.push_str("    always @(posedge clk) if (rst_n && neuron_out_valid && (mac_result >= threshold))\n");
    s.push_str("        a_threshold_gates: assert (neuron_out);\n");
    s.push_str("`endif\n");
    s.push_str("\n");
    s.push_str("    // External memory port currently unused at this level; sub-modules\n");
    s.push_str("    // drive it in higher-fidelity assemblies. Tie off the explicit\n");
    s.push_str("    // outputs so synthesis does not infer X-drivers.\n");
    s.push_str("    assign mem_addr  = 32'd0;\n");
    s.push_str("    assign mem_rd_en = 1'b0;\n");
    s.push_str("\n");

    s.push_str("endmodule\n");

    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ident_validator_basics() {
        assert!(is_valid_verilog_ident("bitnet_engine_top"));
        assert!(is_valid_verilog_ident("a"));
        assert!(is_valid_verilog_ident("_x"));
        assert!(is_valid_verilog_ident("Foo123"));
        assert!(!is_valid_verilog_ident(""));
        assert!(!is_valid_verilog_ident("9foo"));
        assert!(!is_valid_verilog_ident("has space"));
        assert!(!is_valid_verilog_ident("dash-name"));
        assert!(!is_valid_verilog_ident("uni\u{00e9}"));
    }

    #[test]
    fn default_name_used_when_invalid() {
        let v = build_bitnet_engine_top("");
        assert!(v.contains("module bitnet_engine_top ("));
        let v2 = build_bitnet_engine_top("9bad");
        assert!(v2.contains("module bitnet_engine_top ("));
    }

    #[test]
    fn custom_name_propagates() {
        let v = build_bitnet_engine_top("engine_top_v1");
        assert!(v.contains("module engine_top_v1 ("));
        assert!(!v.contains("module bitnet_engine_top ("));
    }

    #[test]
    fn control_ports_present() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        for port in [
            "input  wire        start,",
            "input  wire [5:0]  num_layers,",
            "input  wire [15:0] neurons_per_layer,",
            "input  wire [7:0]  chunks_per_neuron,",
            "input  wire signed [15:0] threshold,",
        ] {
            assert!(v.contains(port), "missing control port `{}`", port);
        }
    }

    #[test]
    fn status_ports_present() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.contains("output wire        busy,"));
        assert!(v.contains("output wire        done,"));
        assert!(v.contains("output wire [31:0] cycle_count"));
    }

    #[test]
    fn external_memory_ports_present() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.contains("output wire [31:0] mem_addr,"));
        assert!(v.contains("output wire        mem_rd_en,"));
        assert!(v.contains("input  wire [63:0] mem_rd_data,"));
        assert!(v.contains("input  wire        mem_rd_valid,"));
    }

    #[test]
    fn multilayer_sequencer_instance() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.contains("multilayer_sequencer seq ("));
        assert!(v.contains(".current_layer(current_layer)"));
        assert!(v.contains(".inference_done(done)"));
    }

    #[test]
    fn double_buffer_instance() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.contains("double_buffer_ctrl dbl_buf ("));
        assert!(v.contains(".use_buffer_a(use_buffer_a)"));
        assert!(v.contains(".neuron_id(neuron_id[11:0])"));
    }

    #[test]
    fn cycle_counter_logic() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.contains("reg [31:0] cycles;"));
        assert!(v.contains("if (!rst_n) cycles <= 32'd0;"));
        assert!(v.contains("else if (start) cycles <= 32'd0;"));
        assert!(v.contains("else if (busy) cycles <= cycles + 32'd1;"));
        assert!(v.contains("assign cycle_count = cycles;"));
    }

    #[test]
    fn busy_derived_from_current_layer_or_layer_start() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.contains("assign busy = (current_layer != 6'd0) || layer_start;"));
    }

    #[test]
    fn external_memory_outputs_tied_off() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.contains("assign mem_addr  = 32'd0;"));
        assert!(v.contains("assign mem_rd_en = 1'b0;"));
    }

    #[test]
    fn module_ends_with_endmodule() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.trim_end().ends_with("endmodule"));
    }

    #[test]
    fn emitted_text_is_pure_ascii() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.is_ascii(), "emitted Verilog must be ASCII");
    }
}
