//! BitNet HLS pipeline emitters (Wave 36b, R-BN-2).
//!
//! Two self-contained SystemVerilog module emitters for the BitNet ternary
//! inference engine:
//!
//!   * `pipeline_stage2_compute` -- SIMD compute stage that consumes one
//!     54-bit input/weight chunk per cycle, dot-products them through a
//!     `trit27_dot_product` sub-instance (from `trit_stdlib`, W33), and
//!     accumulates the partial result into a 16-bit signed accumulator.
//!   * `layer_sequencer` -- three-state FSM (IDLE/RUN/DONE_ST) that walks
//!     `(neuron_id, chunk_id)` across the neuron-chunk grid and emits the
//!     `valid`, `first_chunk`, `last_chunk`, `done` strobes consumed by
//!     `pipeline_stage2_compute`.
//!
//! Algorithms ported from `gHashTag/vibee-lang`
//! `src/vibeec/verilog_codegen.zig` lines ~1100-1190 (`writePipelineStage2`
//! and `writeLayerSequencer`). Original author: Dmitrii Vasilev.
//!
//! Constitutional notes:
//!   L2: lives only under `bootstrap/`; both emitters are pure additive
//!       string builders, no edits under `gen/`, `coq/`, `trios-coq/`,
//!       `proofs/`, `specs/`, `conformance/`, `architecture/`, `rings/`,
//!       root `Cargo.toml`.
//!   L3: ASCII source, English doc-comments only.
//!   L5: numeric kernel untouched -- these emitters only wire together
//!       existing primitives (`trit27_dot_product` from W33), they do not
//!       redefine any constant inside the trinity invariant.
//!   L7: no `*.sh` invoked.

/// Default identifier for the SIMD compute stage module.
pub const DEFAULT_PIPELINE_STAGE2_NAME: &str = "pipeline_stage2_compute";

/// Default identifier for the layer-sequencer FSM module.
pub const DEFAULT_LAYER_SEQUENCER_NAME: &str = "layer_sequencer";

/// Return `true` if `s` is a syntactically valid Verilog identifier:
/// non-empty, ASCII, starts with `[A-Za-z_]`, followed by `[A-Za-z0-9_]*`.
fn is_valid_verilog_ident(s: &str) -> bool {
    let mut chars = s.chars();
    let first = match chars.next() {
        Some(c) => c,
        None => return false,
    };
    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn resolve_ident<'a>(candidate: &'a str, default: &'a str) -> &'a str {
    if is_valid_verilog_ident(candidate) {
        candidate
    } else {
        default
    }
}

/// Build the `pipeline_stage2_compute` SystemVerilog module text.
///
/// The emitted module:
///   * accepts a 54-bit `input_chunk` + 54-bit `weight_chunk` per cycle,
///   * instantiates `trit27_dot_product` (provided by `trit_stdlib`, W33),
///   * keeps a signed-16 accumulator gated by `first_chunk`,
///   * raises `valid_out` and `result_final` on `last_chunk`.
///
/// Invalid module identifiers fall back to [`DEFAULT_PIPELINE_STAGE2_NAME`].
pub fn build_pipeline_stage2(module_name: &str) -> String {
    let name = resolve_ident(module_name, DEFAULT_PIPELINE_STAGE2_NAME);

    let mut out = String::new();
    out.push_str("// ===========================================================================\n");
    out.push_str("// PIPELINE STAGE 2 - SIMD Compute with Accumulator\n");
    out.push_str("// ===========================================================================\n");
    out.push_str("// Generated by t27c gen-pipeline-stage2 (Wave 36b, R-BN-2).\n");
    out.push_str("// Consumes one 54-bit input/weight chunk per cycle and accumulates the\n");
    out.push_str("// dot-product result into a signed 16-bit accumulator. Depends on the\n");
    out.push_str("// `trit27_dot_product` primitive emitted by `t27c gen-trit-stdlib` (W33).\n");
    out.push_str("\n");
    out.push_str(&format!("module {} (\n", name));
    out.push_str("    input  wire        clk,\n");
    out.push_str("    input  wire        rst_n,\n");
    out.push_str("    input  wire        valid_in,\n");
    out.push_str("    input  wire [53:0] input_chunk,\n");
    out.push_str("    input  wire [53:0] weight_chunk,\n");
    out.push_str("    input  wire        first_chunk,\n");
    out.push_str("    input  wire        last_chunk,\n");
    out.push_str("    output reg         valid_out,\n");
    out.push_str("    output reg  signed [15:0] result,\n");
    out.push_str("    output reg         result_final\n");
    out.push_str(");\n");
    out.push_str("\n");
    out.push_str("    // SIMD dot product\n");
    out.push_str("    wire signed [5:0] dot_result;\n");
    out.push_str("    trit27_dot_product simd (.input_vec(input_chunk), .weight_vec(weight_chunk), .result(dot_result));\n");
    out.push_str("\n");
    out.push_str("    // Accumulator\n");
    // BOUND note. Prop. 83: this accumulator has no chunk counter and no
    // num_chunks input, so nothing here limits how long it sums. Its width is
    // sufficient only because the caller bounds the chunk run, and that
    // reasoning belonged in the RTL rather than only in a proof.
    out.push_str("    // BOUND: accumulator layer_sequencer walks chunk_id over an 8-bit\n");
    out.push_str("    // port, so at most 255 chunks separate two first_chunk restarts and the\n");
    out.push_str("    // sum stays within 255*27 = 6885 of zero. This module has no chunk\n");
    out.push_str("    // counter and no num_chunks input: in isolation it wraps after 1214\n");
    out.push_str("    // chunks. Proved unbounded by k-induction; widening num_chunks past 8\n");
    out.push_str("    // bits reintroduces the wrap. See FORMAL_FOUNDATIONS Prop. 83.\n");
    out.push_str("    reg signed [15:0] accumulator;\n");
    out.push_str("\n");
    out.push_str("    always @(posedge clk or negedge rst_n) begin\n");
    out.push_str("        if (!rst_n) begin\n");
    out.push_str("            accumulator <= 0; valid_out <= 0; result_final <= 0; result <= 0;\n");
    out.push_str("        end else if (valid_in) begin\n");
    out.push_str("            accumulator <= first_chunk ? dot_result : accumulator + dot_result;\n");
    out.push_str("            valid_out <= last_chunk;\n");
    out.push_str("            result <= first_chunk ? dot_result : accumulator + dot_result;\n");
    out.push_str("            result_final <= last_chunk;\n");
    out.push_str("        end else valid_out <= 0;\n");
    out.push_str("    end\n");
    out.push_str("\n");
    out.push_str("endmodule\n");

    out
}

/// Build the `layer_sequencer` SystemVerilog module text.
///
/// The emitted module is a three-state Mealy/Moore hybrid FSM
/// (IDLE / RUN / DONE_ST) that walks `(neuron_id, chunk_id)` across
/// `num_neurons * num_chunks` and drives the `valid`, `first_chunk`,
/// `last_chunk`, `done` strobes consumed by `pipeline_stage2_compute`.
///
/// Invalid module identifiers fall back to [`DEFAULT_LAYER_SEQUENCER_NAME`].
pub fn build_layer_sequencer(module_name: &str) -> String {
    let name = resolve_ident(module_name, DEFAULT_LAYER_SEQUENCER_NAME);

    let mut out = String::new();
    out.push_str("// ===========================================================================\n");
    out.push_str("// LAYER SEQUENCER - FSM for layer execution\n");
    out.push_str("// ===========================================================================\n");
    out.push_str("// Generated by t27c gen-layer-sequencer (Wave 36b, R-BN-2).\n");
    out.push_str("// Walks (neuron_id, chunk_id) across the neuron-chunk grid and emits the\n");
    out.push_str("// valid / first_chunk / last_chunk / done strobes consumed by the\n");
    out.push_str("// `pipeline_stage2_compute` SIMD stage.\n");
    out.push_str("\n");
    out.push_str(&format!("module {} (\n", name));
    out.push_str("    input  wire        clk,\n");
    out.push_str("    input  wire        rst_n,\n");
    out.push_str("    input  wire        start,\n");
    out.push_str("    input  wire [15:0] num_neurons,\n");
    out.push_str("    input  wire [7:0]  num_chunks,\n");
    out.push_str("    // BOUND: neuron_id compared against num_neurons-1, a 16-bit input port, so\n");
    out.push_str("    // the limit is the caller's and fits this register by construction. Prop. 84.\n");
    out.push_str("    output reg  [15:0] neuron_id,\n");
    out.push_str("    // BOUND: chunk_id compared against num_chunks-1, an 8-bit input port. This is\n");
    out.push_str("    // the contract the MAC accumulator's width depends on: 8 bits here means at\n");
    out.push_str("    // most 255 chunks per neuron, which is what keeps that 16-bit sum from\n");
    out.push_str("    // wrapping. Widening this port is not a local change. Props. 83, 84.\n");
    out.push_str("    output reg  [7:0]  chunk_id,\n");
    out.push_str("    output reg         first_chunk,\n");
    out.push_str("    output reg         last_chunk,\n");
    out.push_str("    output reg         valid,\n");
    out.push_str("    output reg         done\n");
    out.push_str(");\n");
    out.push_str("\n");
    out.push_str("    localparam IDLE=0, RUN=1, DONE_ST=2;\n");
    out.push_str("    reg [1:0] state;\n");
    out.push_str("\n");
    out.push_str("    always @(posedge clk or negedge rst_n) begin\n");
    out.push_str("        if (!rst_n) begin\n");
    out.push_str("    // INIT-ZERO: state resets to IDLE, encoded 2'd0, so the zero state and the\n");
    out.push_str("    // reset state coincide by coincidence of the encoding rather than by\n");
    out.push_str("    // construction. Prop. 96.\n");
    out.push_str("            state<=IDLE; neuron_id<=0; chunk_id<=0; valid<=0; done<=0; first_chunk<=0; last_chunk<=0;\n");
    out.push_str("        end else case(state)\n");
    out.push_str("            IDLE: begin done<=0; if(start) begin state<=RUN; neuron_id<=0; chunk_id<=0; end end\n");
    out.push_str("            RUN: begin\n");
    out.push_str("                // Both counts, not just chunks. `neuron_id==num_neurons-1`\n");
    out.push_str("                // compares against 16'hFFFF when num_neurons is zero, so the\n");
    out.push_str("                // terminator never matches and the sequencer emits valid work\n");
    out.push_str("                // for neuron indices 0,1,2,... indefinitely. The zero case was\n");
    out.push_str("                // already handled for chunks and missed for neurons; Yosys\n");
    out.push_str("                // refuted `valid |-> neuron_id < num_neurons` from a reachable\n");
    out.push_str("                // state while the chunk twin proved. See FORMAL_FOUNDATIONS\n");
    out.push_str("                // Prop. 13.\n");
    out.push_str("                if(num_chunks==0 || num_neurons==0) begin state<=DONE_ST; end\n");
    out.push_str("                else begin\n");
    out.push_str("                    valid<=1; first_chunk<=(chunk_id==0); last_chunk<=(chunk_id==num_chunks-1);\n");
    out.push_str("                    if(chunk_id==num_chunks-1) begin chunk_id<=0;\n");
    out.push_str("                        if(neuron_id==num_neurons-1) state<=DONE_ST; else neuron_id<=neuron_id+1;\n");
    out.push_str("                    end else chunk_id<=chunk_id+1;\n");
    out.push_str("                end\n");
    out.push_str("            end\n");
    out.push_str("            DONE_ST: begin valid<=0; done<=1; state<=IDLE; end\n");
    out.push_str("            default: state<=IDLE;\n");
    out.push_str("        endcase\n");
    out.push_str("    end\n");
    out.push_str("\n");
    out.push_str("endmodule\n");

    out
}

pub const DEFAULT_MULTILAYER_SEQUENCER_NAME: &str = "multilayer_sequencer";

pub fn build_multilayer_sequencer(module_name: &str) -> String {
    let name = resolve_ident(module_name, DEFAULT_MULTILAYER_SEQUENCER_NAME);

    let mut out = String::new();
    out.push_str("// ===========================================================================\n");
    out.push_str("// MULTILAYER SEQUENCER - Multi-layer iteration FSM\n");
    out.push_str("// ===========================================================================\n");
    out.push_str("// Iterates over num_layers layers. For each layer:\n");
    out.push_str("//   1. Asserts layer_start for one cycle\n");
    out.push_str("//   2. Waits for layer_done from the layer_sequencer\n");
    out.push_str("//   3. Optionally asserts start_prefetch for the next layer\n");
    out.push_str("//   4. Advances to the next layer or signals inference_done\n");
    out.push_str("\n");

    out.push_str(&format!("module {} (\n", name));
    out.push_str("    input  wire        clk,\n");
    out.push_str("    input  wire        rst_n,\n");
    out.push_str("    input  wire        start,\n");
    out.push_str("    input  wire [5:0]  num_layers,\n");
    out.push_str("    input  wire        layer_done,\n");
    out.push_str("    input  wire        prefetch_done,\n");
    out.push_str("    // BOUND: current_layer compared against num_layers-1, a 6-bit input port, so\n");
    out.push_str("    // the caller cannot request more layers than this counter holds. Prop. 84.\n");
    out.push_str("    output reg  [5:0]  current_layer,\n");
    out.push_str("    output reg         layer_start,\n");
    out.push_str("    output reg         start_prefetch,\n");
    out.push_str("    output reg         inference_done,\n");
    out.push_str("    // Quiescence, for interlocks above this module. bitnet_engine_top\n");
    out.push_str("    // could observe a host *request* (a control-register bit) but not\n");
    out.push_str("    // whether this sequencer had actually stopped -- clearing the request\n");
    out.push_str("    // mid-inference left this state machine running, and three successive\n");
    out.push_str("    // top-level guards each narrowed that window without closing it.\n");
    out.push_str("    // Quiescence is a property of this module, so this module exports it.\n");
    out.push_str("    // See FORMAL_FOUNDATIONS Prop. 22.\n");
    out.push_str("    output wire        idle\n");
    out.push_str(");\n");
    out.push_str("\n");
    out.push_str("    localparam IDLE=0, LAYER_RUN=1, PREFETCH=2, DONE_ST=3;\n");
    out.push_str("    assign idle = (state == IDLE);\n");
    out.push_str("    reg [1:0] state;\n");
    // Prop. 131: marks the PREFETCH pass that loads layer 0 rather than
    // the next layer, so the shared state does not advance current_layer.
    out.push_str("    reg       first_load;\n");
    out.push_str("    reg       pf_ack;   // controller acknowledged this prefetch request\n");
    out.push_str("\n");
    out.push_str("    always @(posedge clk or negedge rst_n) begin\n");
    out.push_str("        if (!rst_n) begin\n");
    out.push_str("            state <= IDLE;\n");
    out.push_str("            current_layer <= 6'd0;\n");
    out.push_str("            layer_start <= 1'b0;\n");
    out.push_str("            start_prefetch <= 1'b0;\n");
    out.push_str("            inference_done <= 1'b0;\n");
    out.push_str("            pf_ack <= 1'b0;\n");
    // Prop. 131: distinguishes the initial weight load from the between-layer
    // prefetch, so the shared PREFETCH state can serve both without adding a
    // fifth state to a two-bit encoding.
    out.push_str("            first_load <= 1'b0;\n");
    out.push_str("        end else case(state)\n");
    out.push_str("            IDLE: begin\n");
    out.push_str("                layer_start <= 1'b0;\n");
    out.push_str("                start_prefetch <= 1'b0;\n");
    out.push_str("                inference_done <= 1'b0;\n");
    out.push_str("                // A zero-layer inference completes immediately. It used to be\n");
    out.push_str("                // dropped -- start ignored, no inference_done, no error -- so a\n");
    out.push_str("                // host waiting on the IRQ waited forever. Proved by zs_multilayer\n");
    out.push_str("                // in formal/zero_size_props.sv. layer_sequencer and\n");
    out.push_str("                // weight_prefetch_ctrl already completed their zero jobs; four\n");
    out.push_str("                // modules disagreeing on this was the real defect.\n");
    out.push_str("                if (start && num_layers == 6'd0) state <= DONE_ST;\n");
    // Prop. 129/131: this ran layer 0 immediately, so layer 0 computed
    // against a weight BRAM nothing had written -- start_prefetch was
    // asserted only when a layer FINISHED and another followed, making the
    // prefetcher a between-layers mechanism with no initial load. Route the
    // start through PREFETCH instead; first_load keeps current_layer at 0.
    out.push_str("                else if (start) begin\n");
    out.push_str("                    current_layer <= 6'd0;\n");
    out.push_str("                    first_load <= 1'b1;\n");
    out.push_str("                    start_prefetch <= 1'b1;\n");
    out.push_str("                    pf_ack <= 1'b0;\n");
    out.push_str("                    state <= PREFETCH;\n");
    out.push_str("                end\n");
    out.push_str("            end\n");
    out.push_str("            LAYER_RUN: begin\n");
    out.push_str("                layer_start <= 1'b0;\n");
    out.push_str("                if (layer_done) begin\n");
    out.push_str("                    if (current_layer == num_layers - 6'd1) begin\n");
    out.push_str("                        state <= DONE_ST;\n");
    out.push_str("                    end else begin\n");
    out.push_str("                        start_prefetch <= 1'b1;\n");
    out.push_str("                        pf_ack <= 1'b0;\n");
    out.push_str("                        state <= PREFETCH;\n");
    out.push_str("                    end\n");
    out.push_str("                end\n");
    out.push_str("            end\n");
    out.push_str("            // Request/acknowledge, not a bare level check.\n");
    out.push_str("            // prefetch_done stays high after a completed prefetch, and the\n");
    out.push_str("            // controller can only clear it one cycle after seeing\n");
    out.push_str("            // start_prefetch. Testing it in the first PREFETCH cycle read\n");
    out.push_str("            // the PREVIOUS transaction's completion, so this sequencer\n");
    out.push_str("            // restarted compute while the prefetcher was still streaming\n");
    out.push_str("            // into the shared weight BRAM. pf_ack records that the\n");
    out.push_str("            // controller has acknowledged THIS request by dropping done.\n");
    out.push_str("            // Yosys refuted !(bram_we && mac_valid_q) at the top level; the\n");
    out.push_str("            // trace showed layer_start one cycle after start_prefetch.\n");
    out.push_str("            // See FORMAL_FOUNDATIONS Prop. 18.\n");
    out.push_str("            PREFETCH: begin\n");
    out.push_str("                start_prefetch <= 1'b0;\n");
    out.push_str("                if (!prefetch_done) pf_ack <= 1'b1;\n");
    out.push_str("                if (pf_ack && prefetch_done) begin\n");
    out.push_str("                    if (!first_load) current_layer <= current_layer + 6'd1;\n");
    out.push_str("                    first_load <= 1'b0;\n");
    out.push_str("                    layer_start <= 1'b1;\n");
    out.push_str("                    state <= LAYER_RUN;\n");
    out.push_str("                end\n");
    out.push_str("            end\n");
    out.push_str("            DONE_ST: begin\n");
    out.push_str("                inference_done <= 1'b1;\n");
    out.push_str("    // INIT-ZERO: state resets to IDLE, encoded 2'd0 -- coincidence of the\n");
    out.push_str("    // encoding, not construction. Prop. 96.\n");
    out.push_str("                state <= IDLE;\n");
    out.push_str("            end\n");
    out.push_str("            default: state <= IDLE;\n");
    out.push_str("        endcase\n");
    out.push_str("    end\n");
    out.push_str("\n");
    out.push_str("endmodule\n");

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    // ---- pipeline_stage2_compute --------------------------------------

    #[test]
    fn stage2_header_uses_default_name() {
        let v = build_pipeline_stage2(DEFAULT_PIPELINE_STAGE2_NAME);
        assert!(v.contains("module pipeline_stage2_compute ("));
        assert!(v.contains("endmodule"));
    }

    #[test]
    fn stage2_invalid_name_falls_back_to_default() {
        let v = build_pipeline_stage2("9bad-name");
        assert!(v.contains("module pipeline_stage2_compute ("));
    }

    #[test]
    fn stage2_empty_name_falls_back_to_default() {
        let v = build_pipeline_stage2("");
        assert!(v.contains("module pipeline_stage2_compute ("));
    }

    #[test]
    fn stage2_custom_name_is_honored() {
        let v = build_pipeline_stage2("my_stage2");
        assert!(v.contains("module my_stage2 ("));
    }

    #[test]
    fn stage2_instantiates_trit27_dot_product() {
        let v = build_pipeline_stage2(DEFAULT_PIPELINE_STAGE2_NAME);
        assert!(
            v.contains("trit27_dot_product simd"),
            "must instantiate trit27_dot_product"
        );
        assert!(v.contains(".input_vec(input_chunk)"));
        assert!(v.contains(".weight_vec(weight_chunk)"));
        assert!(v.contains(".result(dot_result)"));
    }

    #[test]
    fn stage2_has_54bit_chunk_ports() {
        let v = build_pipeline_stage2(DEFAULT_PIPELINE_STAGE2_NAME);
        assert!(v.contains("input  wire [53:0] input_chunk,"));
        assert!(v.contains("input  wire [53:0] weight_chunk,"));
    }

    #[test]
    fn stage2_has_signed_16bit_accumulator() {
        let v = build_pipeline_stage2(DEFAULT_PIPELINE_STAGE2_NAME);
        assert!(v.contains("reg signed [15:0] accumulator;"));
        assert!(v.contains("output reg  signed [15:0] result,"));
    }

    #[test]
    fn stage2_resets_on_negedge_rst_n() {
        let v = build_pipeline_stage2(DEFAULT_PIPELINE_STAGE2_NAME);
        assert!(v.contains("always @(posedge clk or negedge rst_n) begin"));
        assert!(v.contains("if (!rst_n) begin"));
        assert!(v.contains("accumulator <= 0; valid_out <= 0; result_final <= 0; result <= 0;"));
    }

    #[test]
    fn stage2_accumulator_gated_by_first_chunk() {
        let v = build_pipeline_stage2(DEFAULT_PIPELINE_STAGE2_NAME);
        assert!(v.contains("accumulator <= first_chunk ? dot_result : accumulator + dot_result;"));
    }

    #[test]
    fn stage2_valid_out_strobed_on_last_chunk() {
        let v = build_pipeline_stage2(DEFAULT_PIPELINE_STAGE2_NAME);
        assert!(v.contains("valid_out <= last_chunk;"));
        assert!(v.contains("result_final <= last_chunk;"));
    }

    // ---- layer_sequencer ----------------------------------------------

    #[test]
    fn sequencer_header_uses_default_name() {
        let v = build_layer_sequencer(DEFAULT_LAYER_SEQUENCER_NAME);
        assert!(v.contains("module layer_sequencer ("));
        assert!(v.contains("endmodule"));
    }

    #[test]
    fn sequencer_invalid_name_falls_back_to_default() {
        let v = build_layer_sequencer("9bad-name");
        assert!(v.contains("module layer_sequencer ("));
    }

    #[test]
    fn sequencer_custom_name_is_honored() {
        let v = build_layer_sequencer("my_seq");
        assert!(v.contains("module my_seq ("));
    }

    #[test]
    fn sequencer_declares_three_state_fsm() {
        let v = build_layer_sequencer(DEFAULT_LAYER_SEQUENCER_NAME);
        assert!(v.contains("localparam IDLE=0, RUN=1, DONE_ST=2;"));
        assert!(v.contains("reg [1:0] state;"));
    }

    #[test]
    fn sequencer_port_list_has_neuron_chunk_counters() {
        let v = build_layer_sequencer(DEFAULT_LAYER_SEQUENCER_NAME);
        assert!(v.contains("input  wire [15:0] num_neurons,"));
        assert!(v.contains("input  wire [7:0]  num_chunks,"));
        assert!(v.contains("output reg  [15:0] neuron_id,"));
        assert!(v.contains("output reg  [7:0]  chunk_id,"));
    }

    #[test]
    fn sequencer_emits_first_last_chunk_strobes() {
        let v = build_layer_sequencer(DEFAULT_LAYER_SEQUENCER_NAME);
        assert!(v.contains("first_chunk<=(chunk_id==0);"));
        assert!(v.contains("last_chunk<=(chunk_id==num_chunks-1);"));
    }

    #[test]
    fn sequencer_idle_arms_on_start() {
        let v = build_layer_sequencer(DEFAULT_LAYER_SEQUENCER_NAME);
        assert!(v.contains("IDLE: begin done<=0; if(start) begin state<=RUN; neuron_id<=0; chunk_id<=0; end end"));
    }

    #[test]
    fn sequencer_done_st_returns_to_idle() {
        let v = build_layer_sequencer(DEFAULT_LAYER_SEQUENCER_NAME);
        assert!(v.contains("DONE_ST: begin valid<=0; done<=1; state<=IDLE; end"));
    }

    #[test]
    fn sequencer_resets_on_negedge_rst_n() {
        let v = build_layer_sequencer(DEFAULT_LAYER_SEQUENCER_NAME);
        assert!(v.contains("always @(posedge clk or negedge rst_n) begin"));
        assert!(v.contains("state<=IDLE; neuron_id<=0; chunk_id<=0; valid<=0; done<=0; first_chunk<=0; last_chunk<=0;"));
    }

    // ---- shared invariants --------------------------------------------

    #[test]
    fn both_emitters_are_ascii() {
        let s2 = build_pipeline_stage2(DEFAULT_PIPELINE_STAGE2_NAME);
        let lq = build_layer_sequencer(DEFAULT_LAYER_SEQUENCER_NAME);
        assert!(s2.is_ascii(), "pipeline_stage2 must be ASCII (L3)");
        assert!(lq.is_ascii(), "layer_sequencer must be ASCII (L3)");
    }

    #[test]
    fn ident_validator_smoke() {
        assert!(is_valid_verilog_ident("foo"));
        assert!(is_valid_verilog_ident("_bar"));
        assert!(!is_valid_verilog_ident(""));
        assert!(!is_valid_verilog_ident("9foo"));
        assert!(!is_valid_verilog_ident("foo-bar"));
    }

    // Wave 575. Companion to the DMA guard above: a zero-layer inference used
    // to be dropped, so the host's IRQ never arrived. layer_sequencer and
    // weight_prefetch_ctrl already completed their zero jobs -- four modules
    // disagreeing on this was the defect. Proved by zs_multilayer in
    // formal/zero_size_props.sv.
    #[test]
    fn zero_layer_inference_completes_rather_than_vanishing() {
        let v = build_multilayer_sequencer("multilayer_sequencer");
        assert!(v.contains("if (start && num_layers == 6'd0) state <= DONE_ST;"));
        assert!(
            !v.contains("if (start && num_layers > 6'd0) begin"),
            "a start with zero layers must not be silently ignored"
        );
    }
}
