//! BitNet HLS DMA-controller emitter (Wave 36e, R-BN-5).
//!
//! Exposes a single emitter:
//!
//!   * `dma_controller` -- an AXI4 master DMA engine that streams
//!     bulk activation/weight data between an off-chip DDR backing
//!     store and an on-chip BRAM (or any local 64-bit-wide memory).
//!
//! Port summary:
//!
//! | Group                | Signals                                                |
//! |----------------------|--------------------------------------------------------|
//! | Control              | start, src_addr[63:0], dst_addr[63:0], length[31:0],   |
//! |                      | direction (0=read DDR->local, 1=write local->DDR),     |
//! |                      | busy, done                                             |
//! | AXI4 master read     | araddr[63:0], arlen[7:0], arvalid, arready,            |
//! |                      | rdata[63:0], rlast, rvalid, rready                     |
//! | AXI4 master write    | awaddr[63:0], awlen[7:0], awvalid, awready,            |
//! |                      | wdata[63:0], wlast, wvalid, wready, bvalid, bready     |
//! | Local memory         | local_addr[11:0], local_wdata[63:0], local_we,         |
//! |                      | local_rdata[63:0]                                      |
//!
//! State machine (6 states):
//!
//!   IDLE -> READ_ADDR  -> READ_DATA  -> DONE_ST -> IDLE   (direction = 0)
//!   IDLE -> WRITE_ADDR -> WRITE_DATA -> DONE_ST -> IDLE   (direction = 1)
//!
//! Each beat moves 8 bytes (one 64-bit word). `bytes_remaining`
//! starts at `length` and is decremented by 8 every accepted beat;
//! the transfer terminates when it reaches the last word or the AXI
//! peer asserts `rlast`. `local_addr` autoincrements per beat.
//!
//! Algorithm ported from `gHashTag/vibee-lang`
//! `src/vibeec/verilog_codegen.zig` lines 1452-1548
//! (`writeDmaController`). Original author: Dmitrii Vasilev.
//!
//! Constitutional notes:
//!   L2: lives only under `bootstrap/`; emitter is a pure additive
//!       string builder; no edits under `gen/`, `coq/`, `trios-coq/`,
//!       `proofs/`, `specs/`, `conformance/`, `architecture/`,
//!       `rings/`, or root `Cargo.toml`.
//!   L3: ASCII source, English doc-comments only.
//!   L5: numeric kernel untouched -- this emitter is a data-mover;
//!       it does not redefine any constant inside the trinity
//!       invariant `phi^2 + 1/phi^2 = 3`.
//!   L7: no `*.sh` invoked.

/// Default identifier for the DMA-controller module.
pub const DEFAULT_DMA_CONTROLLER_NAME: &str = "dma_controller";

fn is_valid_verilog_ident(s: &str) -> bool {
    let mut chars = s.chars();
    let first = match chars.next() {
        Some(c) => c,
        None => return false,
    };
    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn resolve_ident<'a>(candidate: &'a str, default: &'a str) -> &'a str {
    if is_valid_verilog_ident(candidate) {
        candidate
    } else {
        default
    }
}

/// Build the `dma_controller` SystemVerilog module text.
///
/// Parameters:
///   * `module_name` -- Verilog identifier; falls back to
///     `dma_controller` if the candidate is not a valid Verilog
///     identifier (must start with `[A-Za-z_]` and contain only
///     `[A-Za-z0-9_]`).
pub fn build_dma_controller(module_name: &str) -> String {
    let name = resolve_ident(module_name, DEFAULT_DMA_CONTROLLER_NAME);
    let mut s = String::new();

    s.push_str("// ===========================================================================\n");
    s.push_str("// DMA CONTROLLER - High-bandwidth data transfer\n");
    s.push_str("// ===========================================================================\n");
    s.push_str("// Generated by t27c gen-dma-controller (Wave 36e, R-BN-5).\n");
    s.push_str("// AXI4 master DMA between off-chip DDR and on-chip local memory.\n");
    s.push_str("// direction = 0 -> DDR (src_addr) read into local memory.\n");
    s.push_str("// direction = 1 -> local memory written out to DDR (dst_addr).\n");
    s.push_str("// One beat = 8 bytes (64-bit). length is byte-count.\n");
    s.push_str("\n");

    s.push_str(&format!("module {} (\n", name));
    s.push_str("    input  wire        clk,\n");
    s.push_str("    input  wire        rst_n,\n");
    s.push_str("    // Control\n");
    s.push_str("    input  wire        start,\n");
    s.push_str("    input  wire [63:0] src_addr,\n");
    s.push_str("    input  wire [63:0] dst_addr,\n");
    s.push_str("    input  wire [31:0] length,\n");
    s.push_str("    input  wire        direction,  // 0=read, 1=write\n");
    s.push_str("    output reg         busy,\n");
    s.push_str("    output reg         done,\n");
    s.push_str("    // Asserted for one transfer when the request exceeded the local\n");
    s.push_str("    // address space and was clamped. Routed to the error IRQ.\n");
    s.push_str("    output reg         overflow,\n");
    s.push_str("    // AXI4 Master Read\n");
    s.push_str("    output reg  [63:0] m_axi_araddr,\n");
    s.push_str("    output reg  [7:0]  m_axi_arlen,\n");
    s.push_str("    output reg         m_axi_arvalid,\n");
    s.push_str("    input  wire        m_axi_arready,\n");
    s.push_str("    input  wire [63:0] m_axi_rdata,\n");
    s.push_str("    input  wire        m_axi_rlast,\n");
    s.push_str("    input  wire        m_axi_rvalid,\n");
    s.push_str("    output wire        m_axi_rready,\n");
    s.push_str("    // AXI4 Master Write\n");
    s.push_str("    output reg  [63:0] m_axi_awaddr,\n");
    s.push_str("    output reg  [7:0]  m_axi_awlen,\n");
    s.push_str("    output reg         m_axi_awvalid,\n");
    s.push_str("    input  wire        m_axi_awready,\n");
    s.push_str("    output reg  [63:0] m_axi_wdata,\n");
    s.push_str("    output reg         m_axi_wlast,\n");
    s.push_str("    output reg         m_axi_wvalid,\n");
    s.push_str("    input  wire        m_axi_wready,\n");
    s.push_str("    input  wire        m_axi_bvalid,\n");
    s.push_str("    output wire        m_axi_bready,\n");
    s.push_str("    // Local memory interface\n");
    s.push_str("    output reg  [11:0] local_addr,\n");
    s.push_str("    output reg  [63:0] local_wdata,\n");
    s.push_str("    output reg         local_we,\n");
    s.push_str("    input  wire [63:0] local_rdata\n");
    s.push_str(");\n");
    s.push_str("\n");

    s.push_str("    localparam IDLE       = 3'd0;\n");
    s.push_str("    localparam READ_ADDR  = 3'd1;\n");
    s.push_str("    localparam READ_DATA  = 3'd2;\n");
    s.push_str("    localparam WRITE_ADDR = 3'd3;\n");
    s.push_str("    localparam WRITE_DATA = 3'd4;\n");
    s.push_str("    localparam DONE_ST    = 3'd5;\n");
    s.push_str("    reg [2:0]  state;\n");
    s.push_str("    reg [31:0] bytes_remaining;\n");
    s.push_str("    reg [11:0] word_index;\n");
    s.push_str("    reg [7:0]  burst_count;\n");
    s.push_str("\n");

    s.push_str("    // Burst sizing. One beat is 8 bytes, so the beats still owed are\n");
    s.push_str("    // ceil(bytes_remaining/8); AXI4 caps a burst at 256 beats and encodes\n");
    s.push_str("    // the length as beats-1. arlen/awlen were previously hardwired to\n");
    s.push_str("    // 8'hFF (256 beats) for every transfer, while the FSM stopped once\n");
    s.push_str("    // bytes_remaining fell to a beat -- so a short transfer requested 256\n");
    s.push_str("    // beats and then abandoned the burst, which an AXI master may not do.\n");
    s.push_str("    // Yosys refuted `rready held until rlast` from a reachable state; see\n");
    s.push_str("    // formal/dma_controller_props.sv and FORMAL_FOUNDATIONS Prop. 9.\n");
    s.push_str("    wire [31:0] beats_owed   = (bytes_remaining + 32'd7) >> 3;\n");
    s.push_str("    wire [8:0]  beats_burst  = (beats_owed > 32'd256) ? 9'd256 : beats_owed[8:0];\n");
    s.push_str("    wire [7:0]  burst_len    = beats_burst[7:0] - 8'd1;\n");
    s.push_str("    // Bytes covered by the burst just issued, for address advance.\n");
    s.push_str("    wire [63:0] burst_bytes_r = ({56'd0, m_axi_arlen} + 64'd1) << 3;\n");
    s.push_str("    wire [63:0] burst_bytes_w = ({56'd0, m_axi_awlen} + 64'd1) << 3;\n");
    s.push_str("\n");
    s.push_str("    assign m_axi_rready = (state == READ_DATA);\n");
    s.push_str("    assign m_axi_bready = 1'b1;\n");
    s.push_str("\n");

    s.push_str("    always @(posedge clk or negedge rst_n) begin\n");
    s.push_str("        if (!rst_n) begin\n");
    s.push_str("            state          <= IDLE;\n");
    s.push_str("            busy           <= 1'b0;\n");
    s.push_str("            done           <= 1'b0;\n");
    s.push_str("            m_axi_arvalid  <= 1'b0;\n");
    s.push_str("            m_axi_awvalid  <= 1'b0;\n");
    s.push_str("            m_axi_wvalid   <= 1'b0;\n");
    s.push_str("            m_axi_wlast    <= 1'b0;\n");
    s.push_str("            m_axi_araddr   <= 64'd0;\n");
    s.push_str("            m_axi_awaddr   <= 64'd0;\n");
    s.push_str("            m_axi_arlen    <= 8'd0;\n");
    s.push_str("            m_axi_awlen    <= 8'd0;\n");
    s.push_str("            m_axi_wdata    <= 64'd0;\n");
    s.push_str("            local_we       <= 1'b0;\n");
    s.push_str("            local_addr     <= 12'd0;\n");
    s.push_str("            word_index     <= 12'd0;\n");
    s.push_str("            local_wdata    <= 64'd0;\n");
    s.push_str("            bytes_remaining <= 32'd0;\n");
    s.push_str("            overflow       <= 1'b0;\n");
    s.push_str("            burst_count    <= 8'd0;\n");
    s.push_str("        end else begin\n");
    s.push_str("        // local_we defaults low every cycle. It used to be cleared only\n");
    s.push_str("        // inside READ_DATA's else, so in every other state -- READ_ADDR\n");
    s.push_str("        // between bursts, above all -- it simply held its previous value and\n");
    s.push_str("        // kept writing at a stale address. A trace showed 24 write-enable\n");
    s.push_str("        // cycles for 6 distinct addresses, 8 of them with no beat behind\n");
    s.push_str("        // them. A write strobe must be a pulse, not a level. Prop. 32.\n");
    s.push_str("        local_we <= 1'b0;\n");
    s.push_str("        case (state)\n");
    s.push_str("            // A zero-length request moves no data and completes immediately.\n");
    s.push_str("            //\n");
    s.push_str("            // The comment above was true of the intent and false of the code for\n");
    s.push_str("            // several waves: the guard was `start && length != 0`, so a\n");
    s.push_str("            // zero-length request was silently DROPPED -- no data, no done, no\n");
    s.push_str("            // error, and a host waiting on the completion IRQ waits forever.\n");
    s.push_str("            // Proved by zs_dma in formal/zero_size_props.sv. Dropping a request\n");
    s.push_str("            // is the one outcome a host cannot observe, so the zero case now\n");
    s.push_str("            // takes the DONE path: it moves no data and it does say so.\n");
    s.push_str("            IDLE: if (start) begin\n");
    s.push_str("                done <= 1'b0;\n");
    s.push_str("                // Reset the pointer on EVERY start, not only inside the\n");
    s.push_str("                // length != 0 branch. A zero-length request takes the DONE path\n");
    s.push_str("                // and used to leave local_addr and word_index where the previous\n");
    s.push_str("                // transfer left them, so the next transfer's first write landed\n");
    s.push_str("                // at a stale address instead of 0. Prop. 31.\n");
    s.push_str("                local_addr      <= 12'd0;\n");
    s.push_str("                word_index      <= 12'd0;\n");
    s.push_str("                if (length != 32'd0) begin\n");
    s.push_str("                    busy            <= 1'b1;\n");
    s.push_str("                    // length is 32 bits; local_addr is 12, one address per 8\n");
    s.push_str("                    // bytes, so the local side holds 4096*8 = 32768 bytes. A\n");
    s.push_str("                    // longer request used to wrap the address and overwrite\n");
    s.push_str("                    // data already transferred, then report done. Clamping also\n");
    s.push_str("                    // removes the (bytes_remaining + 7) overflow near 2^32.\n");
    s.push_str("                    // See FORMAL_FOUNDATIONS Prop. 29.\n");
    s.push_str("                    bytes_remaining <= (length > 32'd32768) ? 32'd32768 : length;\n");
    s.push_str("                    overflow        <= (length > 32'd32768);\n");
    s.push_str("                    state           <= direction ? WRITE_ADDR : READ_ADDR;\n");
    s.push_str("                    if (!direction) m_axi_araddr <= src_addr;\n");
    s.push_str("                    else            m_axi_awaddr <= dst_addr;\n");
    s.push_str("                end else begin\n");
    s.push_str("                    state           <= DONE_ST;\n");
    s.push_str("                end\n");
    s.push_str("            end\n");
    s.push_str("            READ_ADDR: begin\n");
    s.push_str("                m_axi_arlen   <= burst_len;\n");
    s.push_str("                m_axi_arvalid <= 1'b1;\n");
    s.push_str("                // Both sides, not just ready: with `if (m_axi_arready)` alone\n");
    s.push_str("                // a ready-without-valid advanced the FSM into READ_DATA having\n");
    s.push_str("                // issued no address, leaving it waiting for a burst nobody owed.\n");
    s.push_str("                if (m_axi_arvalid && m_axi_arready) begin\n");
    s.push_str("                    m_axi_arvalid <= 1'b0;\n");
    s.push_str("                    state         <= READ_DATA;\n");
    s.push_str("                end\n");
    s.push_str("            end\n");
    s.push_str("            // Stay until rlast: the burst we asked for must be consumed in\n");
    s.push_str("            // full. If bytes are still owed afterwards, issue the next burst\n");
    s.push_str("            // from the advanced address rather than dropping rready.\n");
    s.push_str("            READ_DATA: if (m_axi_rvalid) begin\n");
    s.push_str("                local_wdata     <= m_axi_rdata;\n");
    s.push_str("                local_we        <= 1'b1;\n");
    s.push_str("                // Write at the word's OWN index -- local_wdata, local_we and\n");
    s.push_str("                // the address register together, so incrementing here made\n");
    s.push_str("                // word N land at address N+1, never writing slot 0 and\n");
    s.push_str("                // wrapping the last word over it. Prop. 29.\n");
    s.push_str("                local_addr      <= word_index;\n");
    s.push_str("                word_index      <= word_index + 12'd1;\n");
    s.push_str("                bytes_remaining <= bytes_remaining - 32'd8;\n");
    s.push_str("                if (m_axi_rlast) begin\n");
    s.push_str("                    if (bytes_remaining <= 32'd8) state <= DONE_ST;\n");
    s.push_str("                    else begin\n");
    s.push_str("                        m_axi_araddr <= m_axi_araddr + burst_bytes_r;\n");
    s.push_str("                        state        <= READ_ADDR;\n");
    s.push_str("                    end\n");
    s.push_str("                end\n");
    s.push_str("            end\n");
    s.push_str("            WRITE_ADDR: begin\n");
    s.push_str("                m_axi_awlen   <= burst_len;\n");
    s.push_str("                m_axi_awvalid <= 1'b1;\n");
    s.push_str("                if (m_axi_awvalid && m_axi_awready) begin\n");
    s.push_str("                    m_axi_awvalid <= 1'b0;\n");
    s.push_str("                    state         <= WRITE_DATA;\n");
    s.push_str("                    burst_count   <= 8'd0;\n");
    s.push_str("                end\n");
    s.push_str("            end\n");
    s.push_str("            // Emit exactly awlen+1 beats, with wlast on the final one. The\n");
    s.push_str("            // previous form raised wlast when the *transfer* ended, which for\n");
    s.push_str("            // a short transfer is earlier than the burst it announced.\n");
    s.push_str("            WRITE_DATA: begin\n");
    s.push_str("                m_axi_wdata  <= local_rdata;\n");
    s.push_str("                m_axi_wvalid <= 1'b1;\n");
    s.push_str("                m_axi_wlast  <= (burst_count == m_axi_awlen);\n");
    s.push_str("                if (m_axi_wready) begin\n");
    s.push_str("                    // Same index as the read path. local_addr serves two roles --\n");
    s.push_str("                    // write pointer when data comes FROM the bus, read pointer\n");
    s.push_str("                    // when it goes TO it -- and giving only one role its own\n");
    s.push_str("                    // counter left the two fighting: a transfer could enter\n");
    s.push_str("                    // READ_DATA with local_addr already advanced by this path, so\n");
    s.push_str("                    // the first write landed at 1 instead of 0. One transfer, one\n");
    s.push_str("                    // sequential index. Prop. 31.\n");
    s.push_str("                    local_addr      <= word_index;\n");
    s.push_str("                    word_index      <= word_index + 12'd1;\n");
    s.push_str("                    bytes_remaining <= bytes_remaining - 32'd8;\n");
    s.push_str("                    burst_count     <= burst_count + 8'd1;\n");
    s.push_str("                    if (burst_count == m_axi_awlen) begin\n");
    s.push_str("                        m_axi_wvalid <= 1'b0;\n");
    s.push_str("                        m_axi_wlast  <= 1'b0;\n");
    s.push_str("                        if (bytes_remaining <= 32'd8) state <= DONE_ST;\n");
    s.push_str("                        else begin\n");
    s.push_str("                            m_axi_awaddr <= m_axi_awaddr + burst_bytes_w;\n");
    s.push_str("                            state        <= WRITE_ADDR;\n");
    s.push_str("                        end\n");
    s.push_str("                    end\n");
    s.push_str("                end\n");
    s.push_str("            end\n");
    s.push_str("            DONE_ST: begin\n");
    s.push_str("                busy     <= 1'b0;\n");
    s.push_str("                done     <= 1'b1;\n");
    s.push_str("                local_we <= 1'b0;\n");
    s.push_str("                state    <= IDLE;\n");
    s.push_str("            end\n");
    s.push_str("            default: state <= IDLE;\n");
    s.push_str("        endcase\n");
    s.push_str("        end\n");
    s.push_str("    end\n");
    s.push_str("\n");

    s.push_str("endmodule\n");

    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ident_validator_basics() {
        assert!(is_valid_verilog_ident("dma_controller"));
        assert!(is_valid_verilog_ident("a"));
        assert!(is_valid_verilog_ident("_x"));
        assert!(is_valid_verilog_ident("Foo123"));
        assert!(!is_valid_verilog_ident(""));
        assert!(!is_valid_verilog_ident("9foo"));
        assert!(!is_valid_verilog_ident("has space"));
        assert!(!is_valid_verilog_ident("dash-name"));
        assert!(!is_valid_verilog_ident("uni\u{00e9}"));
    }

    #[test]
    fn default_name_used_when_invalid() {
        let v = build_dma_controller("");
        assert!(v.contains("module dma_controller ("));
        let v2 = build_dma_controller("9bad");
        assert!(v2.contains("module dma_controller ("));
        let v3 = build_dma_controller("has space");
        assert!(v3.contains("module dma_controller ("));
    }

    #[test]
    fn custom_name_propagates() {
        let v = build_dma_controller("dma_ddr_to_bram");
        assert!(v.contains("module dma_ddr_to_bram ("));
        assert!(!v.contains("module dma_controller ("));
    }

    #[test]
    fn all_six_states_emitted() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        for st in [
            "IDLE",
            "READ_ADDR",
            "READ_DATA",
            "WRITE_ADDR",
            "WRITE_DATA",
            "DONE_ST",
        ] {
            assert!(v.contains(&format!("localparam {}", st)), "missing localparam {}", st);
        }
    }

    #[test]
    fn axi_read_channel_ports_present() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        for port in [
            "m_axi_araddr",
            "m_axi_arlen",
            "m_axi_arvalid",
            "m_axi_arready",
            "m_axi_rdata",
            "m_axi_rlast",
            "m_axi_rvalid",
            "m_axi_rready",
        ] {
            assert!(v.contains(port), "missing AXI-read port `{}`", port);
        }
    }

    #[test]
    fn axi_write_channel_ports_present() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        for port in [
            "m_axi_awaddr",
            "m_axi_awlen",
            "m_axi_awvalid",
            "m_axi_awready",
            "m_axi_wdata",
            "m_axi_wlast",
            "m_axi_wvalid",
            "m_axi_wready",
            "m_axi_bvalid",
            "m_axi_bready",
        ] {
            assert!(v.contains(port), "missing AXI-write port `{}`", port);
        }
    }

    #[test]
    fn local_memory_interface_present() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        assert!(v.contains("output reg  [11:0] local_addr"));
        assert!(v.contains("output reg  [63:0] local_wdata"));
        assert!(v.contains("output reg         local_we"));
        assert!(v.contains("input  wire [63:0] local_rdata"));
    }

    #[test]
    fn rready_and_bready_continuous_assigns() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        assert!(v.contains("assign m_axi_rready = (state == READ_DATA);"));
        assert!(v.contains("assign m_axi_bready = 1'b1;"));
    }

    #[test]
    fn idle_branches_on_direction() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        assert!(v.contains("state           <= direction ? WRITE_ADDR : READ_ADDR;"));
        assert!(v.contains("if (!direction) m_axi_araddr <= src_addr;"));
        assert!(v.contains("else            m_axi_awaddr <= dst_addr;"));
        // Burst length is no longer hardwired to 256 beats. It is computed in
        // READ_ADDR/WRITE_ADDR from the bytes still owed -- pinning 8'hFF here
        // is what let a short transfer request 256 beats and then abandon the
        // burst. See formal/dma_controller_props.sv (a_read_burst_not_abandoned).
        // Narrow to the assignment forms: the explanatory comment in the
        // emitted RTL legitimately mentions the old 8'hFF value.
        assert!(!v.contains("m_axi_arlen  <= 8'hFF;"), "burst length must not be hardwired");
        assert!(!v.contains("m_axi_awlen  <= 8'hFF;"), "burst length must not be hardwired");
        assert!(v.contains("m_axi_arlen   <= burst_len;"));
        assert!(v.contains("m_axi_awlen   <= burst_len;"));
    }

    #[test]
    fn beat_size_is_eight_bytes() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        // Both read and write paths decrement by 8.
        let occurrences = v.matches("bytes_remaining - 32'd8").count();
        assert!(occurrences >= 2, "expected >=2 `- 32'd8` decrements, got {}", occurrences);
    }

    #[test]
    // wlast marks the last beat of the *burst*, not of the transfer. The old
    // form raised it when bytes_remaining fell to one beat, which for a short
    // transfer is earlier than the burst the master had announced.
    fn write_last_set_on_final_beat() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        assert!(v.contains("m_axi_wlast  <= (burst_count == m_axi_awlen);"));
    }

    #[test]
    fn done_state_clears_busy_and_returns_to_idle() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        assert!(v.contains("busy     <= 1'b0;"));
        assert!(v.contains("done     <= 1'b1;"));
        assert!(v.contains("state    <= IDLE;"));
    }

    #[test]
    fn reset_initializes_all_outputs() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        for line in [
            "state          <= IDLE;",
            "busy           <= 1'b0;",
            "done           <= 1'b0;",
            "m_axi_arvalid  <= 1'b0;",
            "m_axi_awvalid  <= 1'b0;",
            "m_axi_wvalid   <= 1'b0;",
            "local_we       <= 1'b0;",
            "local_addr     <= 12'd0;",
        ] {
            assert!(v.contains(line), "missing reset line `{}`", line);
        }
    }

    #[test]
    fn module_ends_with_endmodule() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        assert!(v.trim_end().ends_with("endmodule"));
    }

    #[test]
    fn emitted_text_is_pure_ascii() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        assert!(v.is_ascii(), "emitted Verilog must be ASCII");
    }

    // Wave 575. A zero-length request used to be dropped: the IDLE guard was
    // `start && length != 0`, so no data moved, `done` never asserted, and a
    // host waiting on the completion IRQ waited forever. Proved by zs_dma in
    // formal/zero_size_props.sv. Dropping a request is the one outcome a host
    // cannot observe, so the zero case now takes the DONE path.
    #[test]
    fn zero_length_request_completes_rather_than_vanishing() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        assert!(
            !v.contains("IDLE: if (start && (length != 32'd0))"),
            "gating the whole IDLE transition on a nonzero length drops the request"
        );
        assert!(v.contains("IDLE: if (start) begin"));
        let idle = v.find("IDLE: if (start) begin").unwrap();
        let rest = &v[idle..];
        let zero_branch = rest.find("end else begin").expect("zero-length branch present");
        assert!(
            rest[zero_branch..zero_branch + 120].contains("DONE_ST"),
            "the zero-length branch must complete, not fall through to nothing"
        );
    }
}
