//! BitNet HLS pipeline emitters (Wave 36b, R-BN-2).
//!
//! Two self-contained SystemVerilog module emitters for the BitNet ternary
//! inference engine:
//!
//!   * `pipeline_stage2_compute` -- SIMD compute stage that consumes one
//!     54-bit input/weight chunk per cycle, dot-products them through a
//!     `trit27_dot_product` sub-instance (from `trit_stdlib`, W33), and
//!     accumulates the partial result into a 16-bit signed accumulator.
//!   * `layer_sequencer` -- three-state FSM (IDLE/RUN/DONE_ST) that walks
//!     `(neuron_id, chunk_id)` across the neuron-chunk grid and emits the
//!     `valid`, `first_chunk`, `last_chunk`, `done` strobes consumed by
//!     `pipeline_stage2_compute`.
//!
//! Algorithms ported from `gHashTag/vibee-lang`
//! `src/vibeec/verilog_codegen.zig` lines ~1100-1190 (`writePipelineStage2`
//! and `writeLayerSequencer`). Original author: Dmitrii Vasilev.
//!
//! Constitutional notes:
//!   L2: lives only under `bootstrap/`; both emitters are pure additive
//!       string builders, no edits under `gen/`, `coq/`, `trios-coq/`,
//!       `proofs/`, `specs/`, `conformance/`, `architecture/`, `rings/`,
//!       root `Cargo.toml`.
//!   L3: ASCII source, English doc-comments only.
//!   L5: numeric kernel untouched -- these emitters only wire together
//!       existing primitives (`trit27_dot_product` from W33), they do not
//!       redefine any constant inside the trinity invariant.
//!   L7: no `*.sh` invoked.

/// Default identifier for the SIMD compute stage module.
pub const DEFAULT_PIPELINE_STAGE2_NAME: &str = "pipeline_stage2_compute";

/// Default identifier for the layer-sequencer FSM module.
pub const DEFAULT_LAYER_SEQUENCER_NAME: &str = "layer_sequencer";

/// Default identifier for the multi-layer sequencer FSM module.
pub const DEFAULT_MULTILAYER_SEQUENCER_NAME: &str = "multilayer_sequencer";

/// Return `true` if `s` is a syntactically valid Verilog identifier:
/// non-empty, ASCII, starts with `[A-Za-z_]`, followed by `[A-Za-z0-9_]*`.
fn is_valid_verilog_ident(s: &str) -> bool {
    let mut chars = s.chars();
    let first = match chars.next() {
        Some(c) => c,
        None => return false,
    };
    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn resolve_ident<'a>(candidate: &'a str, default: &'a str) -> &'a str {
    if is_valid_verilog_ident(candidate) {
        candidate
    } else {
        default
    }
}

/// Build the `pipeline_stage2_compute` SystemVerilog module text.
///
/// The emitted module:
///   * accepts a 54-bit `input_chunk` + 54-bit `weight_chunk` per cycle,
///   * instantiates `trit27_dot_product` (provided by `trit_stdlib`, W33),
///   * keeps a signed-16 accumulator gated by `first_chunk`,
///   * raises `valid_out` and `result_final` on `last_chunk`.
///
/// Invalid module identifiers fall back to [`DEFAULT_PIPELINE_STAGE2_NAME`].
pub fn build_pipeline_stage2(module_name: &str) -> String {
    let name = resolve_ident(module_name, DEFAULT_PIPELINE_STAGE2_NAME);

    let mut out = String::new();
    out.push_str("// ===========================================================================\n");
    out.push_str("// PIPELINE STAGE 2 - SIMD Compute with Accumulator\n");
    out.push_str("// ===========================================================================\n");
    out.push_str("// Generated by t27c gen-pipeline-stage2 (Wave 36b, R-BN-2).\n");
    out.push_str("// Consumes one 54-bit input/weight chunk per cycle and accumulates the\n");
    out.push_str("// dot-product result into a signed 16-bit accumulator. Depends on the\n");
    out.push_str("// `trit27_dot_product` primitive emitted by `t27c gen-trit-stdlib` (W33).\n");
    out.push_str("\n");
    out.push_str(&format!("module {} (\n", name));
    out.push_str("    input  wire        clk,\n");
    out.push_str("    input  wire        rst_n,\n");
    out.push_str("    input  wire        valid_in,\n");
    out.push_str("    input  wire [53:0] input_chunk,\n");
    out.push_str("    input  wire [53:0] weight_chunk,\n");
    out.push_str("    input  wire        first_chunk,\n");
    out.push_str("    input  wire        last_chunk,\n");
    out.push_str("    output reg         valid_out,\n");
    out.push_str("    output reg  signed [15:0] result,\n");
    out.push_str("    output reg         result_final\n");
    out.push_str(");\n");
    out.push_str("\n");
    out.push_str("    // SIMD dot product\n");
    out.push_str("    wire signed [5:0] dot_result;\n");
    out.push_str("    trit27_dot_product simd (.input_vec(input_chunk), .weight_vec(weight_chunk), .result(dot_result));\n");
    out.push_str("\n");
    out.push_str("    // Accumulator\n");
    out.push_str("    reg signed [15:0] accumulator;\n");
    out.push_str("\n");
    out.push_str("    always @(posedge clk or negedge rst_n) begin\n");
    out.push_str("        if (!rst_n) begin\n");
    out.push_str("            accumulator <= 0; valid_out <= 0; result_final <= 0;\n");
    out.push_str("        end else if (valid_in) begin\n");
    out.push_str("            accumulator <= first_chunk ? dot_result : accumulator + dot_result;\n");
    out.push_str("            valid_out <= last_chunk;\n");
    out.push_str("            result <= first_chunk ? dot_result : accumulator + dot_result;\n");
    out.push_str("            result_final <= last_chunk;\n");
    out.push_str("        end else valid_out <= 0;\n");
    out.push_str("    end\n");
    out.push_str("\n");
    out.push_str("endmodule\n");

    out
}

/// Build the `layer_sequencer` SystemVerilog module text.
///
/// The emitted module is a three-state Mealy/Moore hybrid FSM
/// (IDLE / RUN / DONE_ST) that walks `(neuron_id, chunk_id)` across
/// `num_neurons * num_chunks` and drives the `valid`, `first_chunk`,
/// `last_chunk`, `done` strobes consumed by `pipeline_stage2_compute`.
///
/// Invalid module identifiers fall back to [`DEFAULT_LAYER_SEQUENCER_NAME`].
pub fn build_layer_sequencer(module_name: &str) -> String {
    let name = resolve_ident(module_name, DEFAULT_LAYER_SEQUENCER_NAME);

    let mut out = String::new();
    out.push_str("// ===========================================================================\n");
    out.push_str("// LAYER SEQUENCER - FSM for layer execution\n");
    out.push_str("// ===========================================================================\n");
    out.push_str("// Generated by t27c gen-layer-sequencer (Wave 36b, R-BN-2).\n");
    out.push_str("// Walks (neuron_id, chunk_id) across the neuron-chunk grid and emits the\n");
    out.push_str("// valid / first_chunk / last_chunk / done strobes consumed by the\n");
    out.push_str("// `pipeline_stage2_compute` SIMD stage.\n");
    out.push_str("\n");
    out.push_str(&format!("module {} (\n", name));
    out.push_str("    input  wire        clk,\n");
    out.push_str("    input  wire        rst_n,\n");
    out.push_str("    input  wire        start,\n");
    out.push_str("    input  wire [15:0] num_neurons,\n");
    out.push_str("    input  wire [7:0]  num_chunks,\n");
    out.push_str("    output reg  [15:0] neuron_id,\n");
    out.push_str("    output reg  [7:0]  chunk_id,\n");
    out.push_str("    output reg         first_chunk,\n");
    out.push_str("    output reg         last_chunk,\n");
    out.push_str("    output reg         valid,\n");
    out.push_str("    output reg         done\n");
    out.push_str(");\n");
    out.push_str("\n");
    out.push_str("    localparam IDLE=0, RUN=1, DONE_ST=2;\n");
    out.push_str("    reg [1:0] state;\n");
    out.push_str("\n");
    out.push_str("    always @(posedge clk or negedge rst_n) begin\n");
    out.push_str("        if (!rst_n) begin\n");
    out.push_str("            state<=IDLE; neuron_id<=0; chunk_id<=0; valid<=0; done<=0;\n");
    out.push_str("        end else case(state)\n");
    out.push_str("            IDLE: begin done<=0; if(start) begin state<=RUN; neuron_id<=0; chunk_id<=0; end end\n");
    out.push_str("            RUN: begin\n");
    out.push_str("                // ZERO-COUNT GUARD. Both terminators are `== count-1` compares against\n");
    out.push_str("                // an unsigned input port, and the literal `1` makes each subtraction\n");
    out.push_str("                // 32 bits wide, so a zero count borrows to 32'hFFFFFFFF while the\n");
    out.push_str("                // index zero-extends. Neither `neuron_id==num_neurons-1` nor\n");
    out.push_str("                // `chunk_id==num_chunks-1` can then ever match, whatever the index\n");
    out.push_str("                // counts up to, so the FSM never leaves RUN and keeps asserting\n");
    out.push_str("                // `valid` for work nobody asked for.\n");
    out.push_str("                // Zero neurons or zero chunks is zero work: retire straight to DONE_ST\n");
    out.push_str("                // with `valid` low, which is what keeps the safety bound\n");
    out.push_str("                // `valid |-> neuron_id < num_neurons && chunk_id < num_chunks` true.\n");
    out.push_str("                if(num_neurons==0 || num_chunks==0) begin valid<=0; state<=DONE_ST; end\n");
    out.push_str("                else begin\n");
    out.push_str("                valid<=1; first_chunk<=(chunk_id==0); last_chunk<=(chunk_id==num_chunks-1);\n");
    out.push_str("                if(chunk_id==num_chunks-1) begin chunk_id<=0;\n");
    out.push_str("                    if(neuron_id==num_neurons-1) state<=DONE_ST; else neuron_id<=neuron_id+1;\n");
    out.push_str("                end else chunk_id<=chunk_id+1;\n");
    out.push_str("                end\n");
    out.push_str("            end\n");
    out.push_str("            DONE_ST: begin valid<=0; done<=1; state<=IDLE; end\n");
    out.push_str("        endcase\n");
    out.push_str("    end\n");
    out.push_str("\n");
    out.push_str("endmodule\n");

    out
}

/// Build the `multilayer_sequencer` SystemVerilog module text.
///
/// The emitted module is the high-level layer-driver FSM consumed by
/// `bitnet_engine_top`. It walks `current_layer` from 0 to
/// `num_layers - 1`, issuing a one-cycle `start_prefetch` pulse at the
/// top of each layer, waiting for the `prefetch_done` acknowledge, then
/// issuing a one-cycle `layer_start` pulse, and finally waiting for the
/// `layer_done` acknowledge before advancing. When the last layer
/// finishes it asserts `inference_done` for one cycle and returns to
/// IDLE.
///
/// Port contract (must match the `multilayer_sequencer seq (...)`
/// instantiation in `bitnet_top.rs`):
///   inputs : clk, rst_n, start, num_layers[5:0], layer_done,
///            prefetch_done
///   outputs: current_layer[5:0], layer_start, start_prefetch,
///            inference_done
///
/// Invalid module identifiers fall back to
/// [`DEFAULT_MULTILAYER_SEQUENCER_NAME`].
pub fn build_multilayer_sequencer(module_name: &str) -> String {
    let name = resolve_ident(module_name, DEFAULT_MULTILAYER_SEQUENCER_NAME);

    let mut out = String::new();
    out.push_str("// ===========================================================================\n");
    out.push_str("// MULTILAYER SEQUENCER - top-level layer-driver FSM\n");
    out.push_str("// ===========================================================================\n");
    out.push_str("// Generated by t27c gen-multilayer-sequencer (Wave 36b, R-BN-2).\n");
    out.push_str("// Drives current_layer across [0, num_layers); per layer it pulses\n");
    out.push_str("// start_prefetch, waits for prefetch_done, pulses layer_start, then waits\n");
    out.push_str("// for layer_done before advancing. Asserts inference_done after the last\n");
    out.push_str("// layer. This module is referenced by name from bitnet_engine_top.\n");
    out.push_str("\n");
    out.push_str(&format!("module {} (\n", name));
    out.push_str("    input  wire        clk,\n");
    out.push_str("    input  wire        rst_n,\n");
    out.push_str("    input  wire        start,\n");
    out.push_str("    input  wire [5:0]  num_layers,\n");
    out.push_str("    input  wire        layer_done,\n");
    out.push_str("    input  wire        prefetch_done,\n");
    out.push_str("    output reg  [5:0]  current_layer,\n");
    out.push_str("    output reg         layer_start,\n");
    out.push_str("    output reg         start_prefetch,\n");
    out.push_str("    output reg         inference_done\n");
    out.push_str(");\n");
    out.push_str("\n");
    out.push_str("    localparam IDLE=0, PREFETCH=1, WAIT_PF=2, RUN=3, WAIT_LAYER=4, FINISH=5;\n");
    out.push_str("    reg [2:0] state;\n");
    out.push_str("\n");
    out.push_str("    always @(posedge clk or negedge rst_n) begin\n");
    out.push_str("        if (!rst_n) begin\n");
    out.push_str("            state<=IDLE; current_layer<=6'd0;\n");
    out.push_str("            layer_start<=1'b0; start_prefetch<=1'b0; inference_done<=1'b0;\n");
    out.push_str("        end else begin\n");
    out.push_str("            // default: all strobes low unless a state asserts them\n");
    out.push_str("            layer_start<=1'b0; start_prefetch<=1'b0; inference_done<=1'b0;\n");
    out.push_str("            case(state)\n");
    out.push_str("                IDLE: if(start) begin current_layer<=6'd0; state<=PREFETCH; end\n");
    out.push_str("                PREFETCH: begin start_prefetch<=1'b1; state<=WAIT_PF; end\n");
    out.push_str("                WAIT_PF: if(prefetch_done) state<=RUN;\n");
    out.push_str("                RUN: begin layer_start<=1'b1; state<=WAIT_LAYER; end\n");
    out.push_str("                WAIT_LAYER: if(layer_done) begin\n");
    out.push_str("                    if(current_layer==num_layers-6'd1) state<=FINISH;\n");
    out.push_str("                    else begin current_layer<=current_layer+6'd1; state<=PREFETCH; end\n");
    out.push_str("                end\n");
    out.push_str("                FINISH: begin inference_done<=1'b1; state<=IDLE; end\n");
    out.push_str("                default: state<=IDLE;\n");
    out.push_str("            endcase\n");
    out.push_str("        end\n");
    out.push_str("    end\n");
    out.push_str("\n");
    out.push_str("endmodule\n");

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    // ---- pipeline_stage2_compute --------------------------------------

    #[test]
    fn stage2_header_uses_default_name() {
        let v = build_pipeline_stage2(DEFAULT_PIPELINE_STAGE2_NAME);
        assert!(v.contains("module pipeline_stage2_compute ("));
        assert!(v.contains("endmodule"));
    }

    #[test]
    fn stage2_invalid_name_falls_back_to_default() {
        let v = build_pipeline_stage2("9bad-name");
        assert!(v.contains("module pipeline_stage2_compute ("));
    }

    #[test]
    fn stage2_empty_name_falls_back_to_default() {
        let v = build_pipeline_stage2("");
        assert!(v.contains("module pipeline_stage2_compute ("));
    }

    #[test]
    fn stage2_custom_name_is_honored() {
        let v = build_pipeline_stage2("my_stage2");
        assert!(v.contains("module my_stage2 ("));
    }

    #[test]
    fn stage2_instantiates_trit27_dot_product() {
        let v = build_pipeline_stage2(DEFAULT_PIPELINE_STAGE2_NAME);
        assert!(
            v.contains("trit27_dot_product simd"),
            "must instantiate trit27_dot_product"
        );
        assert!(v.contains(".input_vec(input_chunk)"));
        assert!(v.contains(".weight_vec(weight_chunk)"));
        assert!(v.contains(".result(dot_result)"));
    }

    #[test]
    fn stage2_has_54bit_chunk_ports() {
        let v = build_pipeline_stage2(DEFAULT_PIPELINE_STAGE2_NAME);
        assert!(v.contains("input  wire [53:0] input_chunk,"));
        assert!(v.contains("input  wire [53:0] weight_chunk,"));
    }

    #[test]
    fn stage2_has_signed_16bit_accumulator() {
        let v = build_pipeline_stage2(DEFAULT_PIPELINE_STAGE2_NAME);
        assert!(v.contains("reg signed [15:0] accumulator;"));
        assert!(v.contains("output reg  signed [15:0] result,"));
    }

    #[test]
    fn stage2_resets_on_negedge_rst_n() {
        let v = build_pipeline_stage2(DEFAULT_PIPELINE_STAGE2_NAME);
        assert!(v.contains("always @(posedge clk or negedge rst_n) begin"));
        assert!(v.contains("if (!rst_n) begin"));
        assert!(v.contains("accumulator <= 0; valid_out <= 0; result_final <= 0;"));
    }

    #[test]
    fn stage2_accumulator_gated_by_first_chunk() {
        let v = build_pipeline_stage2(DEFAULT_PIPELINE_STAGE2_NAME);
        assert!(v.contains("accumulator <= first_chunk ? dot_result : accumulator + dot_result;"));
    }

    #[test]
    fn stage2_valid_out_strobed_on_last_chunk() {
        let v = build_pipeline_stage2(DEFAULT_PIPELINE_STAGE2_NAME);
        assert!(v.contains("valid_out <= last_chunk;"));
        assert!(v.contains("result_final <= last_chunk;"));
    }

    // ---- layer_sequencer ----------------------------------------------

    #[test]
    fn sequencer_header_uses_default_name() {
        let v = build_layer_sequencer(DEFAULT_LAYER_SEQUENCER_NAME);
        assert!(v.contains("module layer_sequencer ("));
        assert!(v.contains("endmodule"));
    }

    #[test]
    fn sequencer_invalid_name_falls_back_to_default() {
        let v = build_layer_sequencer("9bad-name");
        assert!(v.contains("module layer_sequencer ("));
    }

    #[test]
    fn sequencer_custom_name_is_honored() {
        let v = build_layer_sequencer("my_seq");
        assert!(v.contains("module my_seq ("));
    }

    #[test]
    fn sequencer_declares_three_state_fsm() {
        let v = build_layer_sequencer(DEFAULT_LAYER_SEQUENCER_NAME);
        assert!(v.contains("localparam IDLE=0, RUN=1, DONE_ST=2;"));
        assert!(v.contains("reg [1:0] state;"));
    }

    #[test]
    fn sequencer_port_list_has_neuron_chunk_counters() {
        let v = build_layer_sequencer(DEFAULT_LAYER_SEQUENCER_NAME);
        assert!(v.contains("input  wire [15:0] num_neurons,"));
        assert!(v.contains("input  wire [7:0]  num_chunks,"));
        assert!(v.contains("output reg  [15:0] neuron_id,"));
        assert!(v.contains("output reg  [7:0]  chunk_id,"));
    }

    #[test]
    fn sequencer_emits_first_last_chunk_strobes() {
        let v = build_layer_sequencer(DEFAULT_LAYER_SEQUENCER_NAME);
        assert!(v.contains("first_chunk<=(chunk_id==0);"));
        assert!(v.contains("last_chunk<=(chunk_id==num_chunks-1);"));
    }

    #[test]
    fn sequencer_idle_arms_on_start() {
        // After the W88 fix the IDLE state both clears `done` and arms
        // the run on `start`. The transition to RUN with neuron / chunk
        // counters zeroed is unchanged from the original form.
        let v = build_layer_sequencer(DEFAULT_LAYER_SEQUENCER_NAME);
        assert!(v.contains("if(start) begin state<=RUN; neuron_id<=0; chunk_id<=0; end"),
            "IDLE must still arm RUN on start with counters cleared; got:\n{v}");
    }

    #[test]
    fn sequencer_done_st_returns_to_idle() {
        let v = build_layer_sequencer(DEFAULT_LAYER_SEQUENCER_NAME);
        assert!(v.contains("DONE_ST: begin valid<=0; done<=1; state<=IDLE; end"));
    }

    #[test]
    fn sequencer_idle_clears_done_w88() {
        // Regression for W88: layer_sequencer sets `done<=1` in DONE_ST
        // and transitions back to IDLE without clearing `done`, so the
        // `done` output was sticky forever. The first layer always
        // appeared finished, so multilayer_sequencer skipped layers 2..N.
        // Fix: clear `done` unconditionally at the top of IDLE so the
        // pulse only lives one cycle (the DONE_ST cycle) before being
        // cleared on the very next IDLE entry.
        let v = build_layer_sequencer(DEFAULT_LAYER_SEQUENCER_NAME);
        assert!(v.contains("IDLE: begin done<=0;"),
            "IDLE must clear `done` before any start handling; got:\n{v}");
        // The buggy form (no done<=0 in IDLE) must not be present.
        assert!(!v.contains("IDLE: if(start) begin state<=RUN;"),
            "old buggy IDLE form must be gone; got:\n{v}");
    }

    /// Return the RUN-state zero-count guard line from an emitted sequencer.
    ///
    /// Selected by all three of: it is an `if(` line, it retires to `DONE_ST`,
    /// and it drops `valid`. That triple is unique -- `DONE_ST: begin valid<=0;`
    /// does not branch to `DONE_ST`, and the `neuron_id==num_neurons-1`
    /// terminator does not touch `valid` -- so these tests cannot be satisfied
    /// by some other line that merely happens to mention `DONE_ST`.
    fn sequencer_zero_guard_line(v: &str) -> &str {
        v.lines()
            .find(|l| {
                l.trim_start().starts_with("if(")
                    && l.contains("state<=DONE_ST;")
                    && l.contains("valid<=0;")
            })
            .unwrap_or_else(|| panic!("no RUN-state zero-count guard line in:\n{v}"))
    }

    #[test]
    fn sequencer_run_guards_zero_neurons() {
        let v = build_layer_sequencer(DEFAULT_LAYER_SEQUENCER_NAME);
        let guard = sequencer_zero_guard_line(&v);
        assert!(
            guard.contains("num_neurons==0"),
            "RUN-state zero-count guard must test num_neurons==0; without it \
             `neuron_id==num_neurons-1` compares against 32'hFFFFFFFF and the \
             FSM never reaches DONE_ST. Guard line was:\n{guard}"
        );
    }

    #[test]
    fn sequencer_run_guards_zero_chunks() {
        let v = build_layer_sequencer(DEFAULT_LAYER_SEQUENCER_NAME);
        let guard = sequencer_zero_guard_line(&v);
        assert!(
            guard.contains("num_chunks==0"),
            "RUN-state zero-count guard must test num_chunks==0; without it \
             `chunk_id==num_chunks-1` compares against 32'hFFFFFFFF, which no \
             8-bit chunk_id can equal, so the FSM never reaches DONE_ST. Guard \
             line was:\n{guard}"
        );
    }

    /// The guard is only worth anything if it runs *before* the compares it
    /// protects. Pins the ordering so the guard cannot be demoted into dead
    /// text below the arithmetic it is supposed to dominate.
    #[test]
    fn sequencer_zero_guard_dominates_the_compares() {
        let v = build_layer_sequencer(DEFAULT_LAYER_SEQUENCER_NAME);
        let guard_at = v
            .find("if(num_neurons==0 || num_chunks==0)")
            .unwrap_or_else(|| panic!("zero-count guard missing entirely:\n{v}"));
        let valid_at = v
            .find("valid<=1; first_chunk<=")
            .unwrap_or_else(|| panic!("RUN-state work block missing:\n{v}"));
        let term_at = v
            .find("if(neuron_id==num_neurons-1) state<=DONE_ST;")
            .unwrap_or_else(|| panic!("neuron terminator missing:\n{v}"));
        assert!(
            guard_at < valid_at && guard_at < term_at,
            "zero-count guard must precede both `valid<=1` (at {valid_at}) and \
             the neuron terminator (at {term_at}), but sits at {guard_at}"
        );
    }

    #[test]
    fn sequencer_resets_on_negedge_rst_n() {
        let v = build_layer_sequencer(DEFAULT_LAYER_SEQUENCER_NAME);
        assert!(v.contains("always @(posedge clk or negedge rst_n) begin"));
        assert!(v.contains("state<=IDLE; neuron_id<=0; chunk_id<=0; valid<=0; done<=0;"));
    }

    // ---- shared invariants --------------------------------------------

    #[test]
    fn both_emitters_are_ascii() {
        let s2 = build_pipeline_stage2(DEFAULT_PIPELINE_STAGE2_NAME);
        let lq = build_layer_sequencer(DEFAULT_LAYER_SEQUENCER_NAME);
        assert!(s2.is_ascii(), "pipeline_stage2 must be ASCII (L3)");
        assert!(lq.is_ascii(), "layer_sequencer must be ASCII (L3)");
    }

    #[test]
    fn ident_validator_smoke() {
        assert!(is_valid_verilog_ident("foo"));
        assert!(is_valid_verilog_ident("_bar"));
        assert!(!is_valid_verilog_ident(""));
        assert!(!is_valid_verilog_ident("9foo"));
        assert!(!is_valid_verilog_ident("foo-bar"));
    }

    // ---- multilayer_sequencer (issue #926 Bug 1) ----------------------

    #[test]
    fn multilayer_header_uses_default_name() {
        let v = build_multilayer_sequencer(DEFAULT_MULTILAYER_SEQUENCER_NAME);
        assert!(v.contains("module multilayer_sequencer ("));
        assert!(v.trim_end().ends_with("endmodule"));
    }

    #[test]
    fn multilayer_invalid_name_falls_back() {
        let v = build_multilayer_sequencer("9bad-name");
        assert!(v.contains("module multilayer_sequencer ("));
    }

    #[test]
    fn multilayer_port_contract_matches_engine_top() {
        // Ports MUST match the `multilayer_sequencer seq (...)` instance in
        // bitnet_top.rs, otherwise synthesis fails on a port mismatch.
        let v = build_multilayer_sequencer(DEFAULT_MULTILAYER_SEQUENCER_NAME);
        assert!(v.contains("input  wire        start,"));
        assert!(v.contains("input  wire [5:0]  num_layers,"));
        assert!(v.contains("input  wire        layer_done,"));
        assert!(v.contains("input  wire        prefetch_done,"));
        assert!(v.contains("output reg  [5:0]  current_layer,"));
        assert!(v.contains("output reg         layer_start,"));
        assert!(v.contains("output reg         start_prefetch,"));
        assert!(v.contains("output reg         inference_done"));
    }

    #[test]
    fn multilayer_drives_inference_done_after_last_layer() {
        let v = build_multilayer_sequencer(DEFAULT_MULTILAYER_SEQUENCER_NAME);
        assert!(v.contains("if(current_layer==num_layers-6'd1) state<=FINISH;"));
        assert!(v.contains("FINISH: begin inference_done<=1'b1; state<=IDLE; end"));
    }

    #[test]
    fn multilayer_is_ascii() {
        let v = build_multilayer_sequencer(DEFAULT_MULTILAYER_SEQUENCER_NAME);
        assert!(v.is_ascii(), "multilayer_sequencer must be ASCII (L3)");
    }
}
