//! BitNet HLS buffering emitters (Wave 36c, R-BN-3).
//!
//! Two self-contained SystemVerilog module emitters for the BitNet
//! ternary inference engine activation/weight buffering layer:
//!
//!   * `double_buffer_ctrl` -- ping-pong activation buffer controller.
//!     Toggles `use_buffer_a` on every `layer_done` strobe so that even
//!     layers read buffer A / write buffer B, and odd layers read B /
//!     write A. The neuron_id input is forwarded as both read and write
//!     address (the layer scheduler guarantees no aliasing between the
//!     producing layer N and the consuming layer N+1, since they target
//!     opposite buffers).
//!   * `weight_prefetch_ctrl` -- DDR-to-BRAM weight streaming FSM
//!     (`IDLE`/`FETCH`/`DONE`). Issues AXI read transactions, accepts
//!     64-bit AXI words, truncates them to the BitNet 54-bit packed-
//!     trit format, and streams them into the on-chip weight BRAM at
//!     consecutive addresses while the compute pipeline runs against
//!     the previous layer's weights. `axi_rready` is hard-wired to
//!     `(state == FETCH)` per the source design.
//!
//! Algorithms ported from `gHashTag/vibee-lang`
//! `src/vibeec/verilog_codegen.zig` lines ~1187-1281
//! (`writeDoubleBufferCtrl` and `writeWeightPrefetchCtrl`).
//! Original author: Dmitrii Vasilev.
//!
//! Constitutional notes:
//!   L2: lives only under `bootstrap/`; both emitters are pure additive
//!       string builders, no edits under `gen/`, `coq/`, `trios-coq/`,
//!       `proofs/`, `specs/`, `conformance/`, `architecture/`, `rings/`,
//!       root `Cargo.toml`.
//!   L3: ASCII source, English doc-comments only.
//!   L5: numeric kernel untouched -- these emitters are control-plane
//!       only; they do not redefine any constant inside the trinity
//!       invariant `phi^2 + 1/phi^2 = 3`.
//!   L7: no `*.sh` invoked.

/// Default identifier for the ping-pong activation buffer controller.
pub const DEFAULT_DOUBLE_BUFFER_CTRL_NAME: &str = "double_buffer_ctrl";

/// Default identifier for the DDR-to-BRAM weight prefetch FSM.
pub const DEFAULT_WEIGHT_PREFETCH_CTRL_NAME: &str = "weight_prefetch_ctrl";

/// Return `true` if `s` is a syntactically valid Verilog identifier:
/// non-empty, ASCII, starts with `[A-Za-z_]`, followed by `[A-Za-z0-9_]*`.
fn is_valid_verilog_ident(s: &str) -> bool {
    let mut chars = s.chars();
    let first = match chars.next() {
        Some(c) => c,
        None => return false,
    };
    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn resolve_ident<'a>(candidate: &'a str, default: &'a str) -> &'a str {
    if is_valid_verilog_ident(candidate) {
        candidate
    } else {
        default
    }
}

/// Build the `double_buffer_ctrl` SystemVerilog module text.
///
/// The emitted module:
///   * Holds a single 1-bit register `use_buffer_a` that toggles on
///     every `layer_done` pulse. Reset state: `1` (so layer 0 reads
///     buffer A, writes buffer B -- matching the vibee-lang convention).
///   * Forwards `neuron_id` to both `read_addr` and `write_addr` via
///     combinational `assign`. Address widths are fixed at 12 bits to
///     match `weight_bram` (W36a) default depth = 4096.
///   * Accepts an unused `current_layer[5:0]` input for forward-
///     compatibility with multi-layer schedulers (W36d / `multilayer_
///     sequencer`); the controller itself does not need the layer id
///     because it toggles purely off `layer_done`.
pub fn build_double_buffer_ctrl(module_name: &str) -> String {
    let name = resolve_ident(module_name, DEFAULT_DOUBLE_BUFFER_CTRL_NAME);
    let mut s = String::new();

    s.push_str("// ===========================================================================\n");
    s.push_str("// DOUBLE BUFFER CONTROLLER - Ping-pong activation buffers\n");
    s.push_str("// ===========================================================================\n");
    s.push_str("// Generated by t27c gen-double-buffer-ctrl (Wave 36c, R-BN-3).\n");
    s.push_str("// Toggles `use_buffer_a` on every `layer_done` strobe. Even layers\n");
    s.push_str("// read buffer A / write buffer B; odd layers read B / write A.\n");
    s.push_str("// Reset state: use_buffer_a = 1 (layer 0 reads A, writes B).\n");
    s.push_str("\n");

    s.push_str(&format!("module {} (\n", name));
    s.push_str("    input  wire        clk,\n");
    s.push_str("    input  wire        rst_n,\n");
    s.push_str("    input  wire        layer_done,\n");
    s.push_str("    input  wire [5:0]  current_layer,\n");
    s.push_str("    output reg         use_buffer_a,\n");
    s.push_str("    output wire [11:0] read_addr,\n");
    s.push_str("    output wire [11:0] write_addr,\n");
    s.push_str("    input  wire [11:0] neuron_id\n");
    s.push_str(");\n");
    s.push_str("\n");
    s.push_str("    // Tie unused forward-compatibility port to suppress lint warnings.\n");
    s.push_str("    wire _unused_current_layer = &{1'b0, current_layer};\n");
    s.push_str("\n");
    s.push_str("    // Even layers: read A, write B.\n");
    s.push_str("    // Odd layers: read B, write A.\n");
    s.push_str("    always @(posedge clk or negedge rst_n) begin\n");
    s.push_str("        if (!rst_n) use_buffer_a <= 1'b1;\n");
    s.push_str("        else if (layer_done) use_buffer_a <= ~use_buffer_a;\n");
    s.push_str("    end\n");
    s.push_str("\n");
    s.push_str("    assign read_addr  = neuron_id;\n");
    s.push_str("    assign write_addr = neuron_id;\n");
    s.push_str("\n");
    s.push_str("endmodule\n");

    s
}

/// Build the `weight_prefetch_ctrl` SystemVerilog module text.
///
/// The emitted module:
///   * Three-state FSM: `IDLE` (waits for `start_prefetch`), `FETCH`
///     (issues AXI reads + writes 54-bit packed-trit words into the
///     on-chip BRAM), `DONE` (one-cycle pulse on `prefetch_done`, then
///     returns to `IDLE`).
///   * `prefetch_done` is retired on entry to `IDLE`, unconditionally,
///     so it really is the one-cycle pulse documented above. Clearing it
///     only inside the `start_prefetch` guard left the flag asserted for
///     the whole idle gap, and a requester that samples it in the same
///     cycle it raises `start_prefetch` -- which is exactly what the
///     `multilayer_sequencer` `WAIT_PF` state does -- would read the
///     *previous* transaction's completion and skip its own prefetch
///     (issue #1985).
///   * Truncates incoming 64-bit AXI words to 54 bits to match the
///     `weight_bram` (W36a) default data width.
///   * Hard-wires `axi_rready = (state == FETCH)` per the source
///     design; `axi_araddr` advances by 8 bytes per accepted AR beat.
///   * `bram_addr` starts at 0 and increments per accepted R beat;
///     `bram_we` is single-cycle per word.
pub fn build_weight_prefetch_ctrl(module_name: &str) -> String {
    let name = resolve_ident(module_name, DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
    let mut s = String::new();

    s.push_str("// ===========================================================================\n");
    s.push_str("// WEIGHT PREFETCH CONTROLLER - Stream weights from DDR into on-chip BRAM\n");
    s.push_str("// ===========================================================================\n");
    s.push_str("// Generated by t27c gen-weight-prefetch-ctrl (Wave 36c, R-BN-3).\n");
    s.push_str("// Three-state FSM (IDLE/FETCH/DONE). Issues AXI reads, truncates\n");
    s.push_str("// 64-bit AXI words to 54-bit BitNet packed-trit format, and writes\n");
    s.push_str("// them into the weight BRAM at consecutive addresses while the\n");
    s.push_str("// compute pipeline runs against the previous layer's weights.\n");
    s.push_str("\n");

    s.push_str(&format!("module {} (\n", name));
    s.push_str("    input  wire        clk,\n");
    s.push_str("    input  wire        rst_n,\n");
    s.push_str("    input  wire        start_prefetch,\n");
    s.push_str("    input  wire [31:0] src_addr,\n");
    s.push_str("    input  wire [15:0] num_words,\n");
    s.push_str("    output reg         prefetch_active,\n");
    s.push_str("    output reg         prefetch_done,\n");
    // Raised for the whole of a prefetch whose `num_words` exceeded the BRAM
    // and was therefore clamped, so a truncated request is observable rather
    // than merely bounded. Held until the next `start_prefetch`.
    s.push_str("    output reg         overflow,\n");
    s.push_str("    // AXI read interface\n");
    s.push_str("    output reg  [31:0] axi_araddr,\n");
    s.push_str("    output reg         axi_arvalid,\n");
    s.push_str("    input  wire        axi_arready,\n");
    s.push_str("    input  wire [63:0] axi_rdata,\n");
    s.push_str("    input  wire        axi_rvalid,\n");
    s.push_str("    output wire        axi_rready,\n");
    s.push_str("    // BRAM write interface\n");
    s.push_str("    output reg  [11:0] bram_addr,\n");
    s.push_str("    output reg  [53:0] bram_data,\n");
    s.push_str("    output reg         bram_we\n");
    s.push_str(");\n");
    s.push_str("\n");
    s.push_str("    reg [15:0] words_remaining;\n");
    // `bram_addr` is 12 bits, so the BRAM holds 4096 words, while `num_words`
    // is 16 bits and can name 65536 -- a 16x overrange.
    s.push_str("    localparam [15:0] MAX_WORDS = 16'd4096;  // bram_addr is 12 bits\n");
    s.push_str("    localparam IDLE = 2'd0, FETCH = 2'd1, DONE_ST = 2'd2;\n");
    s.push_str("    reg [1:0] state;\n");
    s.push_str("\n");
    s.push_str("    assign axi_rready = (state == FETCH);\n");
    s.push_str("\n");
    s.push_str("    always @(posedge clk or negedge rst_n) begin\n");
    s.push_str("        if (!rst_n) begin\n");
    s.push_str("            state <= IDLE; prefetch_active <= 1'b0; prefetch_done <= 1'b0;\n");
    s.push_str("            axi_arvalid <= 1'b0; bram_we <= 1'b0; overflow <= 1'b0;\n");
    s.push_str("            axi_araddr <= 32'd0; bram_addr <= 12'd0; bram_data <= 54'd0;\n");
    s.push_str("            words_remaining <= 16'd0;\n");
    s.push_str("        end else case (state)\n");
    s.push_str("            IDLE: begin\n");
    s.push_str("                prefetch_done <= 1'b0;\n");
    s.push_str("                if (start_prefetch) begin\n");
    s.push_str("                    state <= FETCH; prefetch_active <= 1'b1;\n");
    s.push_str("                    axi_araddr <= src_addr;\n");
    // Clamp, and say so. `words_remaining` is what bounds `bram_addr`.
    s.push_str("                    words_remaining <= (num_words > MAX_WORDS) ? MAX_WORDS : num_words;\n");
    s.push_str("                    overflow        <= (num_words > MAX_WORDS);\n");
    s.push_str("                    bram_addr <= 12'd0;\n");
    s.push_str("                end\n");
    s.push_str("            end\n");
    s.push_str("            FETCH: begin\n");
    s.push_str("                axi_arvalid <= 1'b1;\n");
    s.push_str("                if (axi_arready) axi_araddr <= axi_araddr + 32'd8;\n");
    s.push_str("                if (axi_rvalid) begin\n");
    s.push_str("                    bram_data <= axi_rdata[53:0];\n");
    s.push_str("                    bram_we <= 1'b1;\n");
    s.push_str("                    bram_addr <= bram_addr + 12'd1;\n");
    s.push_str("                    words_remaining <= words_remaining - 16'd1;\n");
    s.push_str("                    if (words_remaining == 16'd1) state <= DONE_ST;\n");
    s.push_str("                end else bram_we <= 1'b0;\n");
    s.push_str("            end\n");
    s.push_str("            DONE_ST: begin\n");
    s.push_str("                prefetch_active <= 1'b0;\n");
    s.push_str("                prefetch_done   <= 1'b1;\n");
    s.push_str("                axi_arvalid     <= 1'b0;\n");
    s.push_str("                bram_we         <= 1'b0;\n");
    s.push_str("                state           <= IDLE;\n");
    s.push_str("            end\n");
    s.push_str("            default: state <= IDLE;\n");
    s.push_str("        endcase\n");
    s.push_str("    end\n");
    s.push_str("\n");
    s.push_str("endmodule\n");

    s
}

#[cfg(test)]
mod tests {
    use super::*;

    // ----- ident validator -----------------------------------------------

    #[test]
    fn ident_validator_accepts_basic() {
        assert!(is_valid_verilog_ident("double_buffer_ctrl"));
        assert!(is_valid_verilog_ident("weight_prefetch_ctrl"));
        assert!(is_valid_verilog_ident("a"));
        assert!(is_valid_verilog_ident("_x"));
        assert!(is_valid_verilog_ident("X9"));
    }

    #[test]
    fn ident_validator_rejects_bad() {
        assert!(!is_valid_verilog_ident(""));
        assert!(!is_valid_verilog_ident("9foo"));
        assert!(!is_valid_verilog_ident("has space"));
        assert!(!is_valid_verilog_ident("dash-name"));
        assert!(!is_valid_verilog_ident("uni\u{00e9}"));
    }

    #[test]
    fn resolve_ident_falls_back_on_invalid() {
        assert_eq!(resolve_ident("9bad", "ok"), "ok");
        assert_eq!(resolve_ident("good", "ok"), "good");
    }

    // ----- double_buffer_ctrl --------------------------------------------

    #[test]
    fn double_buffer_default_name() {
        let v = build_double_buffer_ctrl(DEFAULT_DOUBLE_BUFFER_CTRL_NAME);
        assert!(v.contains("module double_buffer_ctrl ("));
        assert!(v.contains("endmodule"));
    }

    #[test]
    fn double_buffer_invalid_name_falls_back() {
        let v = build_double_buffer_ctrl("9 bad name");
        assert!(v.contains("module double_buffer_ctrl ("));
    }

    #[test]
    fn double_buffer_custom_name() {
        let v = build_double_buffer_ctrl("my_dbuf");
        assert!(v.contains("module my_dbuf ("));
    }

    #[test]
    fn double_buffer_has_all_ports() {
        let v = build_double_buffer_ctrl(DEFAULT_DOUBLE_BUFFER_CTRL_NAME);
        for port in [
            "input  wire        clk",
            "input  wire        rst_n",
            "input  wire        layer_done",
            "input  wire [5:0]  current_layer",
            "output reg         use_buffer_a",
            "output wire [11:0] read_addr",
            "output wire [11:0] write_addr",
            "input  wire [11:0] neuron_id",
        ] {
            assert!(v.contains(port), "missing port `{}`", port);
        }
    }

    #[test]
    fn double_buffer_toggles_on_layer_done() {
        let v = build_double_buffer_ctrl(DEFAULT_DOUBLE_BUFFER_CTRL_NAME);
        assert!(v.contains("if (!rst_n) use_buffer_a <= 1'b1;"));
        assert!(v.contains("else if (layer_done) use_buffer_a <= ~use_buffer_a;"));
    }

    #[test]
    fn double_buffer_addr_assigns() {
        let v = build_double_buffer_ctrl(DEFAULT_DOUBLE_BUFFER_CTRL_NAME);
        assert!(v.contains("assign read_addr  = neuron_id;"));
        assert!(v.contains("assign write_addr = neuron_id;"));
    }

    #[test]
    fn double_buffer_pure_ascii() {
        let v = build_double_buffer_ctrl(DEFAULT_DOUBLE_BUFFER_CTRL_NAME);
        assert!(v.is_ascii(), "emitted Verilog must be ASCII");
    }

    // ----- weight_prefetch_ctrl ------------------------------------------

    #[test]
    fn prefetch_default_name() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        assert!(v.contains("module weight_prefetch_ctrl ("));
        assert!(v.contains("endmodule"));
    }

    #[test]
    fn prefetch_invalid_name_falls_back() {
        let v = build_weight_prefetch_ctrl("bad name!");
        assert!(v.contains("module weight_prefetch_ctrl ("));
    }

    #[test]
    fn prefetch_custom_name() {
        let v = build_weight_prefetch_ctrl("my_pfetch");
        assert!(v.contains("module my_pfetch ("));
    }

    #[test]
    fn prefetch_has_all_axi_ports() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        for port in [
            "output reg  [31:0] axi_araddr",
            "output reg         axi_arvalid",
            "input  wire        axi_arready",
            "input  wire [63:0] axi_rdata",
            "input  wire        axi_rvalid",
            "output wire        axi_rready",
        ] {
            assert!(v.contains(port), "missing axi port `{}`", port);
        }
    }

    #[test]
    fn prefetch_has_all_bram_ports() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        for port in [
            "output reg  [11:0] bram_addr",
            "output reg  [53:0] bram_data",
            "output reg         bram_we",
        ] {
            assert!(v.contains(port), "missing bram port `{}`", port);
        }
    }

    #[test]
    fn prefetch_has_control_ports() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        for port in [
            "input  wire        start_prefetch",
            "input  wire [31:0] src_addr",
            "input  wire [15:0] num_words",
            "output reg         prefetch_active",
            "output reg         prefetch_done",
        ] {
            assert!(v.contains(port), "missing ctrl port `{}`", port);
        }
    }

    #[test]
    fn prefetch_fsm_states_present() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        assert!(v.contains("localparam IDLE = 2'd0, FETCH = 2'd1, DONE_ST = 2'd2;"));
        assert!(v.contains("IDLE: begin"));
        assert!(v.contains("if (start_prefetch) begin"));
        assert!(v.contains("FETCH: begin"));
        assert!(v.contains("DONE_ST: begin"));
    }

    /// Issue #1985. `DONE_ST` raises `prefetch_done` and drops straight back
    /// to `IDLE`. If the flag is cleared only inside the `start_prefetch`
    /// guard, the clear is one cycle too late: a requester that samples
    /// `prefetch_done` in the same cycle it raises `start_prefetch` reads the
    /// *previous* transaction's completion. Require the clear to sit in the
    /// `IDLE` arm ahead of the guard, so the flag is already retired when the
    /// next request arrives.
    ///
    /// The assertion is anchored to the `IDLE` case arm on purpose: the reset
    /// block also contains `prefetch_done <= 1'b0;`, so an unanchored
    /// `contains` check would pass on the defective emitter.
    #[test]
    fn prefetch_done_retired_in_idle_before_start_guard() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);

        let case_body = v
            .split_once("end else case (state)")
            .expect("FSM case statement missing")
            .1;
        let idle_arm = case_body
            .split_once("FETCH: begin")
            .expect("FETCH arm missing")
            .0;

        let clear = idle_arm.find("prefetch_done <= 1'b0;").unwrap_or_else(|| {
            panic!(
                "IDLE arm never clears prefetch_done. IDLE arm:\n{}",
                idle_arm
            )
        });
        let guard = idle_arm.find("if (start_prefetch)").unwrap_or_else(|| {
            panic!(
                "IDLE arm missing start_prefetch guard. IDLE arm:\n{}",
                idle_arm
            )
        });

        assert!(
            clear < guard,
            "prefetch_done must be cleared on entry to IDLE, before the \
             `if (start_prefetch)` guard, so a new requester never observes \
             the previous transaction's completion (#1985). IDLE arm:\n{}",
            idle_arm
        );
    }

    #[test]
    fn prefetch_rready_combinational() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        assert!(v.contains("assign axi_rready = (state == FETCH);"));
    }

    #[test]
    fn prefetch_advances_axi_araddr_by_8() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        assert!(v.contains("if (axi_arready) axi_araddr <= axi_araddr + 32'd8;"));
    }

    #[test]
    fn prefetch_truncates_axi_to_54_bits() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        assert!(v.contains("bram_data <= axi_rdata[53:0];"));
    }

    #[test]
    fn prefetch_pure_ascii() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        assert!(v.is_ascii(), "emitted Verilog must be ASCII");
    }

    // ---- issue #2002: maximum-sized requests must not silently truncate ----

    /// Slice one region out of the emitted module, so an assertion cannot be
    /// satisfied by an identical-looking line somewhere else.
    fn region<'a>(v: &'a str, from: &str, to: &str) -> &'a str {
        let a = v.find(from).unwrap_or_else(|| panic!("missing region `{}`", from));
        let b = v[a..]
            .find(to)
            .unwrap_or_else(|| panic!("missing `{}` after `{}`", to, from));
        &v[a..a + b]
    }

    /// `num_words` is 16 bits; `bram_addr` is 12. A prefetch larger than the
    /// BRAM must be clamped to it, or `bram_addr` wraps and the transfer
    /// overwrites words it already fetched.
    ///
    /// Anchored to the `IDLE` start branch: `words_remaining` is also assigned
    /// in the reset block and decremented in `FETCH`.
    #[test]
    fn idle_clamps_num_words_to_bram_depth() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        let arm = region(&v, "IDLE: begin", "FETCH: begin");
        assert!(
            !arm.contains("words_remaining <= num_words;"),
            "IDLE must not load `words_remaining` from `num_words` unclamped: \
             `num_words` can name 65536 words against a 4096-entry BRAM, so \
             `bram_addr` wraps and the prefetch overwrites weights it already \
             fetched. IDLE arm was:\n{}",
            arm
        );
        assert!(
            arm.contains("words_remaining <= (num_words > MAX_WORDS) ? MAX_WORDS : num_words;"),
            "IDLE must clamp `words_remaining` to MAX_WORDS, which is what \
             bounds `bram_addr`. IDLE arm was:\n{}",
            arm
        );
    }

    /// A clamp with no output turns silent corruption into a silent short
    /// prefetch: the compute pipeline then runs against stale weights in the
    /// slots that were never overwritten, with nothing reported.
    #[test]
    fn idle_raises_overflow_when_request_is_clamped() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        let arm = region(&v, "IDLE: begin", "FETCH: begin");
        assert!(
            arm.contains("overflow        <= (num_words > MAX_WORDS);"),
            "IDLE must raise `overflow` exactly when it clamps, so a truncated \
             prefetch is observable rather than merely bounded. \
             IDLE arm was:\n{}",
            arm
        );
    }

    #[test]
    fn reset_block_clears_overflow() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        let blk = region(&v, "if (!rst_n) begin", "end else case (state)");
        assert!(
            blk.contains("overflow <= 1'b0;"),
            "`overflow` must be cleared in the asynchronous reset block, or it \
             reads as X until the first prefetch starts. Reset block was:\n{}",
            blk
        );
    }

    #[test]
    fn overflow_output_port_declared() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        assert!(
            v.contains("    output reg         overflow,\n"),
            "`weight_prefetch_ctrl` must expose an `overflow` output port; \
             without it the clamp is invisible to the host"
        );
    }

    #[test]
    fn prefetch_reset_block_initializes_all_regs() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        for line in [
            "state <= IDLE;",
            "prefetch_active <= 1'b0;",
            "prefetch_done <= 1'b0;",
            "axi_arvalid <= 1'b0;",
            "bram_we <= 1'b0;",
        ] {
            assert!(v.contains(line), "missing reset line `{}`", line);
        }
    }
}
