//! BitNet HLS activation requantizer (layer boundary).
//!
//! `pipeline_stage2_compute` produces a `signed [15:0]` accumulator; the next
//! layer's `input_chunk` port is `[53:0]` packed trits. Until now **nothing
//! converted between them** -- the bundle had no module at the layer boundary
//! at all (see `docs/BITNET_V2_POSITION.md` section 2.2). This emitter fills
//! that gap.
//!
//! ## The activation-width fork lives here
//!
//! This module is where the open design question becomes a concrete port.
//! `docs/BITNET_V2_POSITION.md` records that this line quantises activations to
//! **ternary**, which is more aggressive than any published BitNet variant --
//! BitNet v2 reaches 4-bit activations and needs an online Hadamard transform
//! to get there. That choice was previously implicit in the absence of a
//! requantizer; it is now explicit in this module's output port.
//!
//! A 4-bit variant would change `trit [1:0]` to `act [3:0]` and replace the
//! dead-zone comparison with a scale-and-round. Nothing else in the datapath
//! would move. Recording the fork at a single interface is the point.
//!
//! ## Quantisation rule
//!
//! Symmetric dead-zone, driven by the host-programmed `threshold` CSR:
//!
//! | condition                | trit    |
//! |--------------------------|---------|
//! | `acc >=  threshold`      | `TRIT_P` (+1) |
//! | `acc <= -threshold`      | `TRIT_N` (-1) |
//! | otherwise                | `TRIT_Z` ( 0) |
//!
//! Encoding follows the trit stdlib: `2'b00 = -1`, `2'b01 = 0`, `2'b10 = +1`,
//! and **`2'b11` is reserved/invalid**. Emitting `2'b11` would corrupt every
//! downstream `trit27_*` primitive silently, so `a_trit_never_invalid` is the
//! load-bearing property.
//!
//! A negative `threshold` makes the two comparisons overlap. The rule is
//! written as a priority chain so the positive branch wins and the output
//! stays legal for every input, rather than relying on the host to behave.
//!
//! Constitutional notes: L2 additive emitter under `bootstrap/` only; L3 ASCII
//! source and English comments; L7 no shell.

/// Default identifier for the requantizer module.
pub const DEFAULT_REQUANT_NAME: &str = "activation_requant";

/// Trits packed into one activation word (54 bits / 2 bits per trit).
pub const TRITS_PER_WORD: usize = 27;

fn is_valid_verilog_ident(s: &str) -> bool {
    let mut chars = s.chars();
    let first = match chars.next() {
        Some(c) => c,
        None => return false,
    };
    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn resolve_ident<'a>(candidate: &'a str, default: &'a str) -> &'a str {
    if is_valid_verilog_ident(candidate) {
        candidate
    } else {
        default
    }
}

/// Build the activation-requantizer SystemVerilog module text.
pub fn build_activation_requant(module_name: &str) -> String {
    let name = resolve_ident(module_name, DEFAULT_REQUANT_NAME);
    let mut s = String::with_capacity(4096);

    s.push_str("// ===========================================================================\n");
    s.push_str("// ACTIVATION REQUANTIZER - layer boundary, signed accumulator -> packed trits\n");
    s.push_str("// ===========================================================================\n");
    s.push_str("// Generated by t27c gen-activation-requant.\n");
    s.push_str("//\n");
    s.push_str("// pipeline_stage2_compute emits signed [15:0]; the next layer consumes\n");
    s.push_str("// [53:0] packed trits. Nothing converted between them before this module\n");
    s.push_str("// existed -- see docs/BITNET_V2_POSITION.md section 2.2.\n");
    s.push_str("//\n");
    s.push_str("// THIS IS WHERE THE ACTIVATION-WIDTH CHOICE LIVES. This line quantises\n");
    s.push_str("// activations to ternary, which is more aggressive than any published\n");
    s.push_str("// BitNet variant: BitNet v2 reaches 4-bit activations and needs an online\n");
    s.push_str("// Hadamard transform to do it. A 4-bit variant changes `trit [1:0]` to\n");
    s.push_str("// `act [3:0]` and swaps the dead-zone for a scale-and-round; nothing else\n");
    s.push_str("// in the datapath moves.\n");
    s.push_str("//\n");
    s.push_str("// Encoding (trit stdlib): 2'b00 = -1, 2'b01 = 0, 2'b10 = +1.\n");
    s.push_str("// 2'b11 is RESERVED/INVALID and would corrupt every downstream trit27_*\n");
    s.push_str("// primitive silently, so a_trit_never_invalid is the load-bearing property.\n");
    s.push_str("\n");

    s.push_str(&format!("module {} (\n", name));
    s.push_str("    input  wire               clk,\n");
    s.push_str("    input  wire               rst_n,\n");
    s.push_str("    // Accumulator stream from pipeline_stage2_compute\n");
    s.push_str("    input  wire               valid_in,\n");
    s.push_str("    input  wire signed [15:0] acc,\n");
    s.push_str("    // Host-programmed symmetric dead-zone\n");
    s.push_str("    input  wire signed [15:0] threshold,\n");
    s.push_str("    // Per-neuron trit\n");
    s.push_str("    output reg  [1:0]         trit,\n");
    s.push_str("    output reg                trit_valid,\n");
    s.push_str("    // Packed activation word for the next layer\n");
    s.push_str("    output reg  [53:0]        word,\n");
    s.push_str("    output reg                word_valid\n");
    s.push_str(");\n");
    s.push_str("\n");

    s.push_str("    localparam [1:0] TRIT_N = 2'b00;  // -1\n");
    s.push_str("    localparam [1:0] TRIT_Z = 2'b01;  //  0\n");
    s.push_str("    localparam [1:0] TRIT_P = 2'b10;  // +1\n");
    s.push_str("\n");

    s.push_str("    // Priority chain, not parallel comparisons. A negative `threshold`\n");
    s.push_str("    // makes `acc >= threshold` and `acc <= -threshold` both true; writing\n");
    s.push_str("    // this as a chain keeps the output legal for every input rather than\n");
    s.push_str("    // trusting the host to program a sane value.\n");
    s.push_str("    wire [1:0] trit_next = (acc >= threshold)  ? TRIT_P :\n");
    s.push_str("                           (acc <= -threshold) ? TRIT_N :\n");
    s.push_str("                                                 TRIT_Z;\n");
    s.push_str("\n");

    s.push_str(&format!(
        "    // {} trits fill one activation word.\n",
        TRITS_PER_WORD
    ));
    s.push_str("    reg [4:0]  trit_count;\n");
    s.push_str("    reg [53:0] shift_word;\n");
    s.push_str("\n");

    s.push_str("    always @(posedge clk or negedge rst_n) begin\n");
    s.push_str("        if (!rst_n) begin\n");
    s.push_str("    // INIT-ZERO: trit resets to TRIT_Z = 2'b01, so -set-init-zero starts it at\n");
    s.push_str("    // 2'b00 -- which decodes as -1, a legal trit but not the reset value. Any\n");
    s.push_str("    // property reading trit over the zero state reads a minus-one the reset\n");
    s.push_str("    // never produces. Prop. 96.\n");
    s.push_str("            trit       <= TRIT_Z;\n");
    s.push_str("            trit_valid <= 1'b0;\n");
    s.push_str("            word       <= 54'd0;\n");
    s.push_str("            word_valid <= 1'b0;\n");
    s.push_str("            trit_count <= 5'd0;\n");
    s.push_str("            shift_word <= 54'd0;\n");
    s.push_str("        end else begin\n");
    s.push_str("            trit_valid <= valid_in;\n");
    s.push_str("            word_valid <= 1'b0;\n");
    s.push_str("            if (valid_in) begin\n");
    s.push_str("                trit <= trit_next;\n");
    s.push_str("                // Trit i occupies bits [2i+1:2i].\n");
    s.push_str("                shift_word <= {trit_next, shift_word[53:2]};\n");
    s.push_str(&format!(
        "                if (trit_count == 5'd{}) begin\n",
        TRITS_PER_WORD - 1
    ));
    s.push_str("                    word       <= {trit_next, shift_word[53:2]};\n");
    s.push_str("                    word_valid <= 1'b1;\n");
    s.push_str("                    trit_count <= 5'd0;\n");
    s.push_str("                end else begin\n");
    s.push_str("                    trit_count <= trit_count + 5'd1;\n");
    s.push_str("                end\n");
    s.push_str("            end\n");
    s.push_str("        end\n");
    s.push_str("    end\n");
    s.push_str("\n");

    s.push_str("`ifdef T27_FORMAL\n");
    s.push_str("    // Load-bearing: 2'b11 is reserved. Emitting it would corrupt every\n");
    s.push_str("    // downstream trit27_* primitive with no error anywhere.\n");
    s.push_str("    always @(posedge clk) if (rst_n)\n");
    s.push_str("        a_trit_never_invalid: assert (trit != 2'b11);\n");
    s.push_str("\n");
    s.push_str("    // The dead-zone rule, stated per branch so a miswired comparison is\n");
    s.push_str("    // caught rather than absorbed.\n");
    s.push_str("    always @(posedge clk)\n");
    s.push_str("        if (rst_n && $past(rst_n) && $past(valid_in) && ($past(acc) >= $past(threshold)))\n");
    s.push_str("            a_positive_branch: assert (trit == TRIT_P);\n");
    s.push_str("    always @(posedge clk)\n");
    s.push_str("        if (rst_n && $past(rst_n) && $past(valid_in) && ($past(acc) < $past(threshold))\n");
    s.push_str("            && ($past(acc) <= -$past(threshold)))\n");
    s.push_str("            a_negative_branch: assert (trit == TRIT_N);\n");
    s.push_str("\n");
    s.push_str("    // trit_valid tracks valid_in by exactly one cycle.\n");
    s.push_str("    always @(posedge clk) if (rst_n && $past(rst_n))\n");
    s.push_str("        a_trit_valid_follows_input: assert (trit_valid == $past(valid_in));\n");
    s.push_str("\n");
    s.push_str(&format!(
        "    // The packer never emits a word before {} trits have arrived.\n",
        TRITS_PER_WORD
    ));
    s.push_str("    always @(posedge clk) if (rst_n)\n");
    s.push_str(&format!(
        "        a_count_in_range: assert (trit_count <= 5'd{});\n",
        TRITS_PER_WORD - 1
    ));
    s.push_str("    always @(posedge clk) if (rst_n && $past(rst_n) && word_valid)\n");
    s.push_str(&format!(
        "        a_word_only_on_full: assert ($past(trit_count) == 5'd{} && $past(valid_in));\n",
        TRITS_PER_WORD - 1
    ));
    s.push_str("`endif\n");
    s.push_str("\n");

    s.push_str("endmodule\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn module_header_and_footer() {
        let v = build_activation_requant(DEFAULT_REQUANT_NAME);
        assert!(v.contains("module activation_requant ("));
        assert!(v.trim_end().ends_with("endmodule"));
    }

    #[test]
    fn custom_name_propagates() {
        let v = build_activation_requant("act_rq");
        assert!(v.contains("module act_rq ("));
    }

    #[test]
    fn invalid_name_falls_back() {
        assert!(build_activation_requant("9bad").contains("module activation_requant ("));
        assert!(build_activation_requant("").contains("module activation_requant ("));
    }

    // 2'b11 is reserved by the trit stdlib. The emitter must never produce a
    // path that can select it.
    #[test]
    fn never_emits_the_reserved_code() {
        let v = build_activation_requant(DEFAULT_REQUANT_NAME);
        // Narrow to assignment contexts: the module's own comments legitimately
        // name 2'b11 to explain why it must never be produced. A blanket
        // `!contains` here fails on the documentation that justifies the rule.
        for line in v.lines() {
            let code = line.split("//").next().unwrap_or("");
            // The assertion that forbids 2'b11 must itself name it, and so must
            // any comparison against it. Only an *assignment* is the defect.
            if code.contains("assert") || code.contains("!=") {
                continue;
            }
            assert!(!code.contains("2'b11"), "2'b11 assignable in: {line}");
        }
    }

    #[test]
    fn encoding_matches_the_trit_stdlib() {
        let v = build_activation_requant(DEFAULT_REQUANT_NAME);
        assert!(v.contains("TRIT_N = 2'b00"));
        assert!(v.contains("TRIT_Z = 2'b01"));
        assert!(v.contains("TRIT_P = 2'b10"));
    }

    // A negative threshold makes both comparisons true; a priority chain keeps
    // the output legal where parallel assignment would not.
    #[test]
    fn quantiser_is_a_priority_chain() {
        let v = build_activation_requant(DEFAULT_REQUANT_NAME);
        let p = v.find("(acc >= threshold)").expect("positive branch");
        let n = v.find("(acc <= -threshold)").expect("negative branch");
        assert!(p < n, "positive branch must take priority");
        let z = v.find("TRIT_Z;").expect("dead-zone fall-through");
        assert!(n < z, "dead-zone must be the final fall-through");
    }

    #[test]
    fn packs_twenty_seven_trits() {
        let v = build_activation_requant(DEFAULT_REQUANT_NAME);
        assert_eq!(TRITS_PER_WORD, 27);
        assert!(v.contains("5'd26"), "wraps at trit 26 (0-indexed)");
        assert!(v.contains("output reg  [53:0]        word,"));
    }

    #[test]
    fn formal_block_is_guarded() {
        let v = build_activation_requant(DEFAULT_REQUANT_NAME);
        assert!(v.contains("`ifdef T27_FORMAL"));
        assert!(v.contains("`endif"));
        assert!(v.contains("a_trit_never_invalid"));
    }

    #[test]
    fn emitted_text_is_pure_ascii() {
        assert!(build_activation_requant(DEFAULT_REQUANT_NAME).is_ascii());
    }
}
