//! BitNet HLS engine-top emitter (Wave 36f, R-BN-6).
//!
//! Exposes a single emitter:
//!
//!   * `bitnet_engine_top` -- the top-level wrapper that turns the
//!     compute / buffering / I/O blocks emitted in W36a..W36e into a
//!     complete multi-layer BitNet inference engine. The wrapper
//!     instantiates a `multilayer_sequencer` (high-level layer-driver
//!     FSM) and a `double_buffer_ctrl` (ping-pong activation storage)
//!     and adds a 32-bit free-running cycle counter gated by `busy`
//!     so the host can profile inference latency.
//!
//! Port summary:
//!
//! | Group         | Signals                                                |
//! |---------------|--------------------------------------------------------|
//! | Clock / reset | clk, rst_n                                             |
//! | Control       | start, num_layers[5:0], neurons_per_layer[15:0],       |
//! |               | chunks_per_neuron[7:0], signed threshold[15:0]         |
//! | External mem  | mem_addr[31:0], mem_rd_en, mem_rd_data[63:0],          |
//! |               | mem_rd_valid                                           |
//! | Status        | busy, done, cycle_count[31:0]                          |
//!
//! Note: the emitted Verilog references two sub-modules by name --
//! `multilayer_sequencer` and `double_buffer_ctrl`. The latter is
//! produced by the W36c `gen-double-buffer-ctrl` emitter. The former
//! is currently expected from the upstream vibee-lang library and is
//! left as a black-box reference here; the rest of the engine-top is
//! self-contained.
//!
//! Algorithm ported from `gHashTag/vibee-lang`
//! `src/vibeec/verilog_codegen.zig` lines 1667-1725
//! (`writeBitNetEngineTop`). Original author: Dmitrii Vasilev.
//!
//! Constitutional notes:
//!   L2: lives only under `bootstrap/`; emitter is a pure additive
//!       string builder; no edits under `gen/`, `coq/`, `trios-coq/`,
//!       `proofs/`, `specs/`, `conformance/`, `architecture/`,
//!       `rings/`, or root `Cargo.toml`.
//!   L3: ASCII source, English doc-comments only.
//!   L5: numeric kernel untouched -- this emitter is a structural
//!       wrapper; it does not redefine any constant inside the
//!       trinity invariant `phi^2 + 1/phi^2 = 3`.
//!   L7: no `*.sh` invoked.

/// Default identifier for the engine-top module.
pub const DEFAULT_BITNET_ENGINE_TOP_NAME: &str = "bitnet_engine_top";

fn is_valid_verilog_ident(s: &str) -> bool {
    let mut chars = s.chars();
    let first = match chars.next() {
        Some(c) => c,
        None => return false,
    };
    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn resolve_ident<'a>(candidate: &'a str, default: &'a str) -> &'a str {
    if is_valid_verilog_ident(candidate) {
        candidate
    } else {
        default
    }
}

/// Build the `bitnet_engine_top` SystemVerilog module text.
///
/// Parameters:
///   * `module_name` -- Verilog identifier; falls back to
///     `bitnet_engine_top` if the candidate is not a valid Verilog
///     identifier (must start with `[A-Za-z_]` and contain only
///     `[A-Za-z0-9_]`).
pub fn build_bitnet_engine_top(module_name: &str) -> String {
    let name = resolve_ident(module_name, DEFAULT_BITNET_ENGINE_TOP_NAME);
    let mut s = String::new();

    s.push_str("// ===========================================================================\n");
    s.push_str("// BITNET INFERENCE ENGINE TOP - Complete multi-layer inference\n");
    s.push_str("// ===========================================================================\n");
    s.push_str("// Generated by t27c gen-bitnet-engine-top (Wave 36f, R-BN-6).\n");
    s.push_str("// Wraps multilayer_sequencer + double_buffer_ctrl + cycle counter\n");
    s.push_str("// into a host-startable multi-layer BitNet inference engine.\n");
    s.push_str("\n");

    s.push_str(&format!("module {} (\n", name));
    s.push_str("    input  wire        clk,\n");
    s.push_str("    input  wire        rst_n,\n");
    s.push_str("    input  wire        start,\n");
    s.push_str("    input  wire [5:0]  num_layers,\n");
    s.push_str("    input  wire [15:0] neurons_per_layer,\n");
    s.push_str("    input  wire [7:0]  chunks_per_neuron,\n");
    s.push_str("    input  wire signed [15:0] threshold,\n");
    s.push_str("    // External memory interface (simplified)\n");
    s.push_str("    output wire [31:0] mem_addr,\n");
    s.push_str("    output wire        mem_rd_en,\n");
    s.push_str("    input  wire [63:0] mem_rd_data,\n");
    s.push_str("    input  wire        mem_rd_valid,\n");
    s.push_str("    // Status\n");
    s.push_str("    output wire        busy,\n");
    s.push_str("    output wire        done,\n");
    s.push_str("    output wire [31:0] cycle_count\n");
    s.push_str(");\n");
    s.push_str("\n");

    s.push_str("    // Multi-layer sequencer\n");
    s.push_str("    wire [5:0] current_layer;\n");
    s.push_str("    wire layer_start, layer_done, start_prefetch, prefetch_done;\n");
    s.push_str("    multilayer_sequencer seq (\n");
    s.push_str("        .clk(clk), .rst_n(rst_n), .start(start), .num_layers(num_layers),\n");
    s.push_str("        .layer_done(layer_done), .prefetch_done(prefetch_done),\n");
    s.push_str("        .current_layer(current_layer), .layer_start(layer_start),\n");
    s.push_str("        .start_prefetch(start_prefetch), .inference_done(done)\n");
    s.push_str("    );\n");
    s.push_str("\n");

    s.push_str("    // Double buffer controller\n");
    s.push_str("    wire use_buffer_a;\n");
    s.push_str("    wire [11:0] buf_read_addr, buf_write_addr;\n");
    s.push_str("    double_buffer_ctrl dbl_buf (\n");
    s.push_str("        .clk(clk), .rst_n(rst_n), .layer_done(layer_done),\n");
    s.push_str("        .current_layer(current_layer), .use_buffer_a(use_buffer_a),\n");
    s.push_str("        .read_addr(buf_read_addr), .write_addr(buf_write_addr), .neuron_id(12'd0)\n");
    s.push_str("    );\n");
    s.push_str("\n");

    // Busy / cycle counter
    // `busy` must be high for the entire inference, starting on `start`
    // and dropping when the multilayer_sequencer asserts `done`. Deriving
    // it from `(current_layer != 0) || layer_start` (the previous form)
    // misses the first layer almost entirely: layer 0 has
    // `current_layer == 0`, and `layer_start` is a 1-cycle pulse, so the
    // cycle counter stalled while layer 0 was running.
    s.push_str("    // Busy tracker: high from `start` until top-level `done`.\n");
    s.push_str("    reg started;\n");
    s.push_str("    always @(posedge clk or negedge rst_n) begin\n");
    s.push_str("        if (!rst_n)      started <= 1'b0;\n");
    s.push_str("        else if (done)   started <= 1'b0;\n");
    s.push_str("        else if (start)  started <= 1'b1;\n");
    s.push_str("    end\n");
    s.push_str("    assign busy = started && !done;\n");
    s.push_str("\n");
    s.push_str("    // Cycle counter\n");
    s.push_str("    reg [31:0] cycles;\n");
    s.push_str("    always @(posedge clk or negedge rst_n)\n");
    s.push_str("        if (!rst_n) cycles <= 32'd0;\n");
    s.push_str("        else if (start) cycles <= 32'd0;\n");
    s.push_str("        else if (busy) cycles <= cycles + 32'd1;\n");
    s.push_str("    assign cycle_count = cycles;\n");
    s.push_str("\n");

    // ----------------------------------------------------------------------
    // Structural datapath wiring (R-BN-6, issue #926 Bug 2).
    //
    // The remaining seven W36 modules are now instantiated and connected
    // into a coherent inference path instead of sitting as standalone IPs:
    //
    //   weight_prefetch_ctrl --(AXI read)--> weight_bram --(rd_data)-->
    //       pipeline_stage2_compute, driven by layer_sequencer; the CSR
    //       block (axi_lite_slave) parameterises the run, dma_controller
    //       moves activations, and interrupt_controller raises `irq` on
    //       completion. The multilayer_sequencer's per-layer handshake
    //       (layer_start / start_prefetch) feeds the inner sequencer and
    //       prefetch controller; their `done` strobes close the loop via
    //       `layer_done` / `prefetch_done`.
    //
    // All sub-module *master* outputs that have no on-chip consumer at this
    // integration level are observed through a 1-bit `tieoff_obs` reduction
    // so synthesis keeps the logic without inferring multiple drivers.
    // ----------------------------------------------------------------------
    s.push_str("    // ---- Inner layer sequencer (neuron/chunk walk) --------------------\n");
    s.push_str("    wire [15:0] seq_neuron_id;\n");
    s.push_str("    wire [7:0]  seq_chunk_id;\n");
    s.push_str("    wire        seq_first_chunk, seq_last_chunk, seq_valid;\n");
    s.push_str("    layer_sequencer lseq (\n");
    s.push_str("        .clk(clk), .rst_n(rst_n), .start(layer_start),\n");
    s.push_str("        .num_neurons(neurons_per_layer), .num_chunks(chunks_per_neuron),\n");
    s.push_str("        .neuron_id(seq_neuron_id), .chunk_id(seq_chunk_id),\n");
    s.push_str("        .first_chunk(seq_first_chunk), .last_chunk(seq_last_chunk),\n");
    s.push_str("        .valid(seq_valid), .done(layer_done)\n");
    s.push_str("    );\n");
    s.push_str("\n");

    s.push_str("    // ---- Weight prefetch controller (AXI read -> BRAM write) ----------\n");
    s.push_str("    wire [31:0] pf_axi_araddr;\n");
    s.push_str("    wire        pf_axi_arvalid, pf_axi_rready;\n");
    s.push_str("    wire [11:0] pf_bram_addr;\n");
    s.push_str("    wire [53:0] pf_bram_data;\n");
    s.push_str("    wire        pf_bram_we, pf_active;\n");
    s.push_str("    weight_prefetch_ctrl pf (\n");
    s.push_str("        .clk(clk), .rst_n(rst_n), .start_prefetch(start_prefetch),\n");
    s.push_str("        .src_addr(32'd0), .num_words(16'd0),\n");
    s.push_str("        .prefetch_active(pf_active), .prefetch_done(prefetch_done),\n");
    s.push_str("        .axi_araddr(pf_axi_araddr), .axi_arvalid(pf_axi_arvalid),\n");
    s.push_str("        .axi_arready(1'b1), .axi_rdata(mem_rd_data), .axi_rvalid(mem_rd_valid),\n");
    s.push_str("        .axi_rready(pf_axi_rready),\n");
    s.push_str("        .bram_addr(pf_bram_addr), .bram_data(pf_bram_data), .bram_we(pf_bram_we)\n");
    s.push_str("    );\n");
    s.push_str("\n");

    s.push_str("    // ---- Weight BRAM (prefetch writes, pipeline reads) ----------------\n");
    s.push_str("    wire [53:0] bram_rd_data;\n");
    s.push_str("    weight_bram #(.DEPTH(4096), .ADDR_WIDTH(12)) wbram (\n");
    s.push_str("        .clk(clk),\n");
    s.push_str("        .rd_addr(buf_read_addr), .rd_data(bram_rd_data),\n");
    s.push_str("        .wr_addr(pf_bram_addr), .wr_data(pf_bram_data), .wr_en(pf_bram_we)\n");
    s.push_str("    );\n");
    s.push_str("\n");

    s.push_str("    // ---- Stage-2 SIMD compute (consumes BRAM weights + sequencer strobes)\n");
    s.push_str("    wire        cmp_valid_out, cmp_result_final;\n");
    s.push_str("    wire signed [15:0] cmp_result;\n");
    s.push_str("    pipeline_stage2_compute pstage (\n");
    s.push_str("        .clk(clk), .rst_n(rst_n), .valid_in(seq_valid),\n");
    s.push_str("        .input_chunk(bram_rd_data), .weight_chunk(bram_rd_data),\n");
    s.push_str("        .first_chunk(seq_first_chunk), .last_chunk(seq_last_chunk),\n");
    s.push_str("        .valid_out(cmp_valid_out), .result(cmp_result),\n");
    s.push_str("        .result_final(cmp_result_final)\n");
    s.push_str("    );\n");
    s.push_str("\n");

    s.push_str("    // ---- AXI-Lite CSR slave (host configuration register file) --------\n");
    s.push_str("    wire [31:0] csr_ctrl, csr_irq_en, csr_num_layers, csr_neurons;\n");
    s.push_str("    wire [31:0] csr_chunks, csr_threshold;\n");
    s.push_str("    wire [63:0] csr_weight_addr, csr_input_addr, csr_output_addr;\n");
    s.push_str("    wire        csr_awready, csr_wready, csr_bvalid, csr_arready, csr_rvalid;\n");
    s.push_str("    wire [1:0]  csr_bresp, csr_rresp;\n");
    s.push_str("    wire [31:0] csr_rdata;\n");
    s.push_str("    axi_lite_slave #(.ADDR_WIDTH(8), .DATA_WIDTH(32)) csr (\n");
    s.push_str("        .clk(clk), .rst_n(rst_n),\n");
    s.push_str("        .s_axi_awaddr(8'd0), .s_axi_awvalid(1'b0), .s_axi_awready(csr_awready),\n");
    s.push_str("        .s_axi_wdata(32'd0), .s_axi_wstrb(4'd0), .s_axi_wvalid(1'b0),\n");
    s.push_str("        .s_axi_wready(csr_wready),\n");
    s.push_str("        .s_axi_bresp(csr_bresp), .s_axi_bvalid(csr_bvalid), .s_axi_bready(1'b1),\n");
    s.push_str("        .s_axi_araddr(8'd0), .s_axi_arvalid(1'b0), .s_axi_arready(csr_arready),\n");
    s.push_str("        .s_axi_rdata(csr_rdata), .s_axi_rresp(csr_rresp), .s_axi_rvalid(csr_rvalid),\n");
    s.push_str("        .s_axi_rready(1'b1),\n");
    s.push_str("        .reg_ctrl(csr_ctrl), .reg_status({31'd0, done}),\n");
    s.push_str("        .reg_irq_en(csr_irq_en), .reg_irq_stat(32'd0),\n");
    s.push_str("        .reg_num_layers(csr_num_layers), .reg_neurons(csr_neurons),\n");
    s.push_str("        .reg_chunks(csr_chunks), .reg_threshold(csr_threshold),\n");
    s.push_str("        .reg_weight_addr(csr_weight_addr), .reg_input_addr(csr_input_addr),\n");
    s.push_str("        .reg_output_addr(csr_output_addr)\n");
    s.push_str("    );\n");
    s.push_str("\n");

    s.push_str("    // ---- DMA controller (activation movement) -------------------------\n");
    s.push_str("    wire        dma_busy, dma_done;\n");
    s.push_str("    wire [63:0] dma_araddr, dma_awaddr, dma_wdata;\n");
    s.push_str("    wire [7:0]  dma_arlen, dma_awlen;\n");
    s.push_str("    wire        dma_arvalid, dma_rready, dma_awvalid, dma_wvalid, dma_wlast, dma_bready;\n");
    s.push_str("    wire [11:0] dma_local_addr;\n");
    s.push_str("    wire [63:0] dma_local_wdata;\n");
    s.push_str("    wire        dma_local_we;\n");
    s.push_str("    dma_controller dma (\n");
    s.push_str("        .clk(clk), .rst_n(rst_n),\n");
    s.push_str("        .start(start_prefetch), .src_addr(csr_input_addr), .dst_addr(csr_output_addr),\n");
    s.push_str("        .length(32'd0), .direction(1'b0), .busy(dma_busy), .done(dma_done),\n");
    s.push_str("        .m_axi_araddr(dma_araddr), .m_axi_arlen(dma_arlen), .m_axi_arvalid(dma_arvalid),\n");
    s.push_str("        .m_axi_arready(1'b1), .m_axi_rdata(mem_rd_data), .m_axi_rlast(1'b1),\n");
    s.push_str("        .m_axi_rvalid(mem_rd_valid), .m_axi_rready(dma_rready),\n");
    s.push_str("        .m_axi_awaddr(dma_awaddr), .m_axi_awlen(dma_awlen), .m_axi_awvalid(dma_awvalid),\n");
    s.push_str("        .m_axi_awready(1'b1), .m_axi_wdata(dma_wdata), .m_axi_wlast(dma_wlast),\n");
    s.push_str("        .m_axi_wvalid(dma_wvalid), .m_axi_wready(1'b1), .m_axi_bvalid(1'b1),\n");
    s.push_str("        .m_axi_bready(dma_bready),\n");
    s.push_str("        .local_addr(dma_local_addr), .local_wdata(dma_local_wdata),\n");
    s.push_str("        .local_we(dma_local_we), .local_rdata(64'd0)\n");
    s.push_str("    );\n");
    s.push_str("\n");

    s.push_str("    // ---- Interrupt controller (done / dma_done / error) ---------------\n");
    s.push_str("    wire [2:0] irq_status;\n");
    s.push_str("    wire       irq_out;\n");
    s.push_str("    interrupt_controller irq (\n");
    s.push_str("        .clk(clk), .rst_n(rst_n),\n");
    s.push_str("        .inference_done(done), .dma_done(dma_done), .error(1'b0),\n");
    s.push_str("        .irq_enable(csr_irq_en[2:0]), .irq_status(irq_status),\n");
    s.push_str("        .status_read(1'b0), .irq_out(irq_out)\n");
    s.push_str("    );\n");
    s.push_str("\n");

    s.push_str("    // External memory port: this integration level reads weights through\n");
    s.push_str("    // weight_prefetch_ctrl, so drive mem_addr from the prefetch AXI read\n");
    s.push_str("    // address and gate mem_rd_en on an outstanding prefetch read.\n");
    s.push_str("    assign mem_addr  = pf_axi_araddr;\n");
    s.push_str("    assign mem_rd_en = pf_axi_arvalid;\n");
    s.push_str("\n");

    s.push_str("    // Observability tie-off: fold every sub-module output that has no\n");
    s.push_str("    // top-level port at this integration level into a single 1-bit net so\n");
    s.push_str("    // synthesis retains the modules without inferring unconnected-driver\n");
    s.push_str("    // warnings or pruning them away. Not a functional output.\n");
    s.push_str("    wire tieoff_obs;\n");
    s.push_str("    assign tieoff_obs =\n");
    s.push_str("        use_buffer_a ^ (|buf_write_addr) ^ (|seq_neuron_id) ^ (|seq_chunk_id) ^\n");
    s.push_str("        pf_active ^ pf_axi_rready ^ cmp_valid_out ^ cmp_result_final ^ (|cmp_result) ^\n");
    s.push_str("        csr_awready ^ csr_wready ^ csr_bvalid ^ (|csr_bresp) ^ csr_arready ^\n");
    s.push_str("        csr_rvalid ^ (|csr_rresp) ^ (|csr_rdata) ^ (|csr_ctrl) ^ (|csr_num_layers) ^\n");
    s.push_str("        (|csr_neurons) ^ (|csr_chunks) ^ (|csr_threshold) ^ (|csr_weight_addr) ^\n");
    s.push_str("        dma_busy ^ (|dma_araddr) ^ (|dma_arlen) ^ dma_arvalid ^ dma_rready ^\n");
    s.push_str("        (|dma_awaddr) ^ (|dma_awlen) ^ dma_awvalid ^ (|dma_wdata) ^ dma_wvalid ^\n");
    s.push_str("        dma_wlast ^ dma_bready ^ (|dma_local_addr) ^ (|dma_local_wdata) ^\n");
    s.push_str("        dma_local_we ^ (|irq_status) ^ irq_out;\n");
    s.push_str("    // synthesis keep tieoff_obs\n");
    s.push_str("\n");

    s.push_str("endmodule\n");

    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ident_validator_basics() {
        assert!(is_valid_verilog_ident("bitnet_engine_top"));
        assert!(is_valid_verilog_ident("a"));
        assert!(is_valid_verilog_ident("_x"));
        assert!(is_valid_verilog_ident("Foo123"));
        assert!(!is_valid_verilog_ident(""));
        assert!(!is_valid_verilog_ident("9foo"));
        assert!(!is_valid_verilog_ident("has space"));
        assert!(!is_valid_verilog_ident("dash-name"));
        assert!(!is_valid_verilog_ident("uni\u{00e9}"));
    }

    #[test]
    fn default_name_used_when_invalid() {
        let v = build_bitnet_engine_top("");
        assert!(v.contains("module bitnet_engine_top ("));
        let v2 = build_bitnet_engine_top("9bad");
        assert!(v2.contains("module bitnet_engine_top ("));
    }

    #[test]
    fn custom_name_propagates() {
        let v = build_bitnet_engine_top("engine_top_v1");
        assert!(v.contains("module engine_top_v1 ("));
        assert!(!v.contains("module bitnet_engine_top ("));
    }

    #[test]
    fn control_ports_present() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        for port in [
            "input  wire        start,",
            "input  wire [5:0]  num_layers,",
            "input  wire [15:0] neurons_per_layer,",
            "input  wire [7:0]  chunks_per_neuron,",
            "input  wire signed [15:0] threshold,",
        ] {
            assert!(v.contains(port), "missing control port `{}`", port);
        }
    }

    #[test]
    fn status_ports_present() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.contains("output wire        busy,"));
        assert!(v.contains("output wire        done,"));
        assert!(v.contains("output wire [31:0] cycle_count"));
    }

    #[test]
    fn external_memory_ports_present() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.contains("output wire [31:0] mem_addr,"));
        assert!(v.contains("output wire        mem_rd_en,"));
        assert!(v.contains("input  wire [63:0] mem_rd_data,"));
        assert!(v.contains("input  wire        mem_rd_valid,"));
    }

    #[test]
    fn multilayer_sequencer_instance() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.contains("multilayer_sequencer seq ("));
        assert!(v.contains(".current_layer(current_layer)"));
        assert!(v.contains(".inference_done(done)"));
    }

    #[test]
    fn double_buffer_instance() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.contains("double_buffer_ctrl dbl_buf ("));
        assert!(v.contains(".use_buffer_a(use_buffer_a)"));
        assert!(v.contains(".neuron_id(12'd0)"));
    }

    #[test]
    fn cycle_counter_logic() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.contains("reg [31:0] cycles;"));
        assert!(v.contains("if (!rst_n) cycles <= 32'd0;"));
        assert!(v.contains("else if (start) cycles <= 32'd0;"));
        assert!(v.contains("else if (busy) cycles <= cycles + 32'd1;"));
        assert!(v.contains("assign cycle_count = cycles;"));
    }

    #[test]
    fn busy_tracks_start_to_done_w88() {
        // Regression for W88: previously
        //   assign busy = (current_layer != 6'd0) || layer_start;
        // which missed layer 0 entirely (current_layer == 0 the whole
        // time, layer_start is a 1-cycle pulse), so the cycle counter
        // stalled. The fixed form latches a `started` flag from `start`
        // and clears it on top-level `done`.
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.contains("reg started;"));
        assert!(v.contains("else if (done)   started <= 1'b0;"));
        assert!(v.contains("else if (start)  started <= 1'b1;"));
        assert!(v.contains("assign busy = started && !done;"));
        // Old buggy form must be gone.
        assert!(!v.contains("assign busy = (current_layer != 6'd0) || layer_start;"));
    }


    #[test]
    fn external_memory_outputs_driven_by_prefetch() {
        // After issue #926 Bug 2 the engine-top wires the external memory
        // read port to the weight_prefetch_ctrl AXI read channel instead of
        // tying it to constants.
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.contains("assign mem_addr  = pf_axi_araddr;"));
        assert!(v.contains("assign mem_rd_en = pf_axi_arvalid;"));
    }

    #[test]
    fn all_nine_submodules_instantiated_926() {
        // issue #926 Bug 2: all nine W36 modules must be structurally
        // instantiated inside the engine-top, not left as standalone IPs.
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.contains("multilayer_sequencer seq ("));
        assert!(v.contains("double_buffer_ctrl dbl_buf ("));
        assert!(v.contains("layer_sequencer lseq ("));
        assert!(v.contains("weight_prefetch_ctrl pf ("));
        assert!(v.contains("weight_bram #(.DEPTH(4096), .ADDR_WIDTH(12)) wbram ("));
        assert!(v.contains("pipeline_stage2_compute pstage ("));
        assert!(v.contains("axi_lite_slave #(.ADDR_WIDTH(8), .DATA_WIDTH(32)) csr ("));
        assert!(v.contains("dma_controller dma ("));
        assert!(v.contains("interrupt_controller irq ("));
    }

    #[test]
    fn datapath_chains_prefetch_bram_compute_926() {
        // The inter-module data path (prefetch -> BRAM -> compute) must be
        // wired through shared nets, closing issue #926's "data path absent".
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        // prefetch writes BRAM
        assert!(v.contains(".wr_addr(pf_bram_addr), .wr_data(pf_bram_data), .wr_en(pf_bram_we)"));
        // BRAM read data feeds the compute stage
        assert!(v.contains(".rd_data(bram_rd_data)"));
        assert!(v.contains(".input_chunk(bram_rd_data), .weight_chunk(bram_rd_data)"));
        // sequencer strobes drive the compute stage
        assert!(v.contains(".valid_in(seq_valid)"));
    }

    #[test]
    fn engine_top_emitted_text_is_pure_ascii() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.is_ascii(), "emitted engine-top Verilog must be ASCII");
    }

    #[test]
    fn module_ends_with_endmodule() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.trim_end().ends_with("endmodule"));
    }

    #[test]
    fn emitted_text_is_pure_ascii() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.is_ascii(), "emitted Verilog must be ASCII");
    }
}
