//! BitNet HLS engine-top emitter (Wave 36f, R-BN-6).
//!
//! Exposes a single emitter:
//!
//!   * `bitnet_engine_top` -- the top-level wrapper that turns the
//!     compute / buffering / I/O blocks emitted in W36a..W36e into a
//!     complete multi-layer BitNet inference engine. The wrapper
//!     instantiates a `multilayer_sequencer` (high-level layer-driver
//!     FSM) and a `double_buffer_ctrl` (ping-pong activation storage)
//!     and adds a 32-bit free-running cycle counter gated by `busy`
//!     so the host can profile inference latency.
//!
//! Port summary:
//!
//! | Group         | Signals                                                |
//! |---------------|--------------------------------------------------------|
//! | Clock / reset | clk, rst_n                                             |
//! | Control       | start, num_layers[5:0], neurons_per_layer[15:0],       |
//! |               | chunks_per_neuron[7:0], signed threshold[15:0]         |
//! | External mem  | mem_addr[31:0], mem_rd_en, mem_rd_data[63:0],          |
//! |               | mem_rd_valid                                           |
//! | Status        | busy, done, cycle_count[31:0]                          |
//!
//! Note: the emitted Verilog references two sub-modules by name --
//! `multilayer_sequencer` and `double_buffer_ctrl`. The latter is
//! produced by the W36c `gen-double-buffer-ctrl` emitter. The former
//! is currently expected from the upstream vibee-lang library and is
//! left as a black-box reference here; the rest of the engine-top is
//! self-contained.
//!
//! Algorithm ported from `gHashTag/vibee-lang`
//! `src/vibeec/verilog_codegen.zig` lines 1667-1725
//! (`writeBitNetEngineTop`). Original author: Dmitrii Vasilev.
//!
//! Constitutional notes:
//!   L2: lives only under `bootstrap/`; emitter is a pure additive
//!       string builder; no edits under `gen/`, `coq/`, `trios-coq/`,
//!       `proofs/`, `specs/`, `conformance/`, `architecture/`,
//!       `rings/`, or root `Cargo.toml`.
//!   L3: ASCII source, English doc-comments only.
//!   L5: numeric kernel untouched -- this emitter is a structural
//!       wrapper; it does not redefine any constant inside the
//!       trinity invariant `phi^2 + 1/phi^2 = 3`.
//!   L7: no `*.sh` invoked.

/// Default identifier for the engine-top module.
pub const DEFAULT_BITNET_ENGINE_TOP_NAME: &str = "bitnet_engine_top";

fn is_valid_verilog_ident(s: &str) -> bool {
    let mut chars = s.chars();
    let first = match chars.next() {
        Some(c) => c,
        None => return false,
    };
    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn resolve_ident<'a>(candidate: &'a str, default: &'a str) -> &'a str {
    if is_valid_verilog_ident(candidate) {
        candidate
    } else {
        default
    }
}

/// Build the `bitnet_engine_top` SystemVerilog module text.
///
/// Parameters:
///   * `module_name` -- Verilog identifier; falls back to
///     `bitnet_engine_top` if the candidate is not a valid Verilog
///     identifier (must start with `[A-Za-z_]` and contain only
///     `[A-Za-z0-9_]`).
pub fn build_bitnet_engine_top(module_name: &str) -> String {
    let name = resolve_ident(module_name, DEFAULT_BITNET_ENGINE_TOP_NAME);
    let mut s = String::new();

    s.push_str("// ===========================================================================\n");
    s.push_str("// BITNET INFERENCE ENGINE TOP - Complete multi-layer inference\n");
    s.push_str("// ===========================================================================\n");
    s.push_str("// Generated by t27c gen-bitnet-engine-top (Wave 36f, R-BN-6).\n");
    s.push_str("// Wraps multilayer_sequencer + double_buffer_ctrl + cycle counter\n");
    s.push_str("// into a host-startable multi-layer BitNet inference engine.\n");
    s.push_str("\n");

    s.push_str(&format!("module {} (\n", name));
    s.push_str("    input  wire        clk,\n");
    s.push_str("    input  wire        rst_n,\n");
    s.push_str("    // AXI4-Lite control aperture. The configuration that used to arrive\n");
    s.push_str("    // as top-level input ports (start, num_layers, neurons_per_layer,\n");
    s.push_str("    // chunks_per_neuron, threshold, weight_words) is now written by a host\n");
    s.push_str("    // through this bus into axi_lite_slave's CSRs -- which is what makes\n");
    s.push_str("    // this an engine a host can drive rather than a block with a wide\n");
    s.push_str("    // config bundle its instantiator has to synthesise.\n");
    s.push_str("    input  wire [7:0]  s_axi_awaddr,\n");
    s.push_str("    input  wire        s_axi_awvalid,\n");
    s.push_str("    output wire        s_axi_awready,\n");
    s.push_str("    input  wire [31:0] s_axi_wdata,\n");
    s.push_str("    input  wire [3:0]  s_axi_wstrb,\n");
    s.push_str("    input  wire        s_axi_wvalid,\n");
    s.push_str("    output wire        s_axi_wready,\n");
    s.push_str("    output wire [1:0]  s_axi_bresp,\n");
    s.push_str("    output wire        s_axi_bvalid,\n");
    s.push_str("    input  wire        s_axi_bready,\n");
    s.push_str("    input  wire [7:0]  s_axi_araddr,\n");
    s.push_str("    input  wire        s_axi_arvalid,\n");
    s.push_str("    output wire        s_axi_arready,\n");
    s.push_str("    output wire [31:0] s_axi_rdata,\n");
    s.push_str("    output wire [1:0]  s_axi_rresp,\n");
    s.push_str("    output wire        s_axi_rvalid,\n");
    s.push_str("    input  wire        s_axi_rready,\n");
    s.push_str("    // AXI4 master for the input-activation DMA. Until now the activation\n");
    s.push_str("    // buffers were written only by the requantizer, i.e. only from the\n");
    s.push_str("    // PREVIOUS layer -- so layer 0 read uninitialised memory and there was\n");
    s.push_str("    // no way to get input data into the engine at all.\n");
    s.push_str("    output wire [63:0] m_axi_araddr,\n");
    s.push_str("    output wire [7:0]  m_axi_arlen,\n");
    s.push_str("    output wire        m_axi_arvalid,\n");
    s.push_str("    input  wire        m_axi_arready,\n");
    s.push_str("    input  wire [63:0] m_axi_rdata,\n");
    s.push_str("    input  wire        m_axi_rlast,\n");
    s.push_str("    input  wire        m_axi_rvalid,\n");
    s.push_str("    output wire        m_axi_rready,\n");
    s.push_str("    // External memory interface (simplified)\n");
    s.push_str("    output wire [31:0] mem_addr,\n");
    s.push_str("    output wire        mem_rd_en,\n");
    s.push_str("    input  wire [63:0] mem_rd_data,\n");
    s.push_str("    input  wire        mem_rd_valid,\n");
    s.push_str("    // Status\n");
    s.push_str("    output wire        busy,\n");
    s.push_str("    output wire        done,\n");
    s.push_str("    output wire [31:0] cycle_count,\n");
    s.push_str("    // Neuron output (post-threshold), now that the MAC is wired\n");
    s.push_str("    output wire        neuron_out,\n");
    s.push_str("    output wire        neuron_out_valid,\n");
    s.push_str("    // Packed activation word for the next layer (requantized)\n");
    s.push_str("    output wire [53:0] act_word_out,\n");
    s.push_str("    output wire        act_word_out_valid,\n");
    s.push_str("    // Host interrupt (interrupt_controller now wired)\n");
    s.push_str("    output wire        irq\n");
    s.push_str(");\n");
    s.push_str("\n");

    s.push_str("    // ------------------------------------------------------------------\n");
    s.push_str("    // Host control aperture. axi_lite_slave was the last emitted module\n");
    s.push_str("    // not instantiated anywhere -- verified in isolation (its lost-write\n");
    s.push_str("    // response defect was fixed in FORMAL_FOUNDATIONS Prop. 8) and\n");
    s.push_str("    // unreachable from the top.\n");
    s.push_str("    //\n");
    s.push_str("    // Register map (word index = addr[5:2]):\n");
    s.push_str("    //   0 ctrl      bit 0 = start\n");
    s.push_str("    //   1 status    bit 0 = busy, bit 1 = done   (read-only)\n");
    s.push_str("    //   4 num_layers        5 neurons\n");
    s.push_str("    //   6 chunks    [7:0] chunks per neuron, [31:16] weight words per\n");
    s.push_str("    //               layer -- packed because the aperture has no spare word\n");
    s.push_str("    //   7 threshold (signed)\n");
    s.push_str("    // ------------------------------------------------------------------\n");
    s.push_str("    wire [31:0] reg_ctrl, reg_irq_en, reg_num_layers, reg_neurons;\n");
    s.push_str("    wire [31:0] reg_chunks, reg_threshold;\n");
    s.push_str("    wire [63:0] reg_weight_addr, reg_input_addr, reg_output_addr;\n");
    s.push_str("    wire [31:0] reg_status = {30'd0, done, busy};\n");
    s.push_str("    axi_lite_slave csr (\n");
    s.push_str("        .clk(clk), .rst_n(rst_n),\n");
    s.push_str("        .s_axi_awaddr(s_axi_awaddr), .s_axi_awvalid(s_axi_awvalid),\n");
    s.push_str("        .s_axi_awready(s_axi_awready),\n");
    s.push_str("        .s_axi_wdata(s_axi_wdata), .s_axi_wstrb(s_axi_wstrb),\n");
    s.push_str("        .s_axi_wvalid(s_axi_wvalid), .s_axi_wready(s_axi_wready),\n");
    s.push_str("        .s_axi_bresp(s_axi_bresp), .s_axi_bvalid(s_axi_bvalid),\n");
    s.push_str("        .s_axi_bready(s_axi_bready),\n");
    s.push_str("        .s_axi_araddr(s_axi_araddr), .s_axi_arvalid(s_axi_arvalid),\n");
    s.push_str("        .s_axi_arready(s_axi_arready),\n");
    s.push_str("        .s_axi_rdata(s_axi_rdata), .s_axi_rresp(s_axi_rresp),\n");
    s.push_str("        .s_axi_rvalid(s_axi_rvalid), .s_axi_rready(s_axi_rready),\n");
    s.push_str("        .reg_ctrl(reg_ctrl), .reg_status(reg_status),\n");
    s.push_str("        .reg_irq_en(reg_irq_en), .reg_irq_stat({29'd0, irq_status_w}),\n");
    s.push_str("        .reg_num_layers(reg_num_layers), .reg_neurons(reg_neurons),\n");
    s.push_str("        .reg_chunks(reg_chunks), .reg_threshold(reg_threshold),\n");
    s.push_str("        .reg_weight_addr(reg_weight_addr), .reg_input_addr(reg_input_addr),\n");
    s.push_str("        .reg_output_addr(reg_output_addr), .reg_cycles({32'd0, cycles})\n");
    s.push_str("    );\n");
    s.push_str("\n");
    s.push_str("    // Symmetric interlock. Gating only the DMA left the other direction\n");
    s.push_str("    // open: a host that starts a DMA (ctrl = 2) and then requests an\n");
    s.push_str("    // inference (ctrl = 3) had compute running against a buffer the DMA\n");
    s.push_str("    // was still filling. An interlock that names only one of two mutually\n");
    s.push_str("    // exclusive activities is half an interlock.\n");
    s.push_str("    // ...and not before the input buffer has been loaded. A cross-layer\n");
    s.push_str("    // property (Prop. 25) refuted without this: with no DMA the engine ran\n");
    s.push_str("    // layer 0 against an activation buffer nothing had ever written, and\n");
    s.push_str("    // every module-level and single-layer property still passed -- reading\n");
    s.push_str("    // uninitialised memory is not a protocol violation anywhere, it is only\n");
    s.push_str("    // wrong across the DMA-to-layer-0 seam. Preferring an interlock to a\n");
    s.push_str("    // documented host contract, as in Prop. 15b.\n");
    s.push_str("    //\n");
    s.push_str("    // Gated on an actual local write, not on dma_done. Gating on completion\n");
    s.push_str("    // was tried first and the property still refuted: a zero-length DMA\n");
    s.push_str("    // reaches DONE without ever asserting dma_local_we, so it satisfies its\n");
    s.push_str("    // completion contract while writing nothing. That is the third member of\n");
    s.push_str("    // the same family -- zero neurons (Prop. 9), zero words (Prop. 10), zero\n");
    s.push_str("    // bytes here -- where a zero-sized job is vacuously complete.\n");
    s.push_str("    wire        start;\n");
    s.push_str("    wire [5:0]  num_layers        = reg_num_layers[5:0];\n");
    s.push_str("    wire [15:0] neurons_per_layer = reg_neurons[15:0];\n");
    s.push_str("    wire [7:0]  chunks_per_neuron = reg_chunks[7:0];\n");
    s.push_str("    wire [15:0] weight_words      = reg_chunks[31:16];\n");
    s.push_str("    wire signed [15:0] threshold  = reg_threshold[15:0];\n");
    s.push_str("\n");
    s.push_str("    wire [2:0]  irq_status_w;\n");
    s.push_str("    wire        dma_busy;\n");
    s.push_str("    wire        seq_idle;\n");
    s.push_str("    reg  [31:0] cycles;\n");
    s.push_str("    // Multi-layer sequencer\n");
    s.push_str("    wire [5:0] current_layer;\n");
    s.push_str("    wire layer_start, start_prefetch;\n");
    s.push_str("    wire prefetch_done;\n");
    s.push_str("    multilayer_sequencer seq (\n");
    s.push_str("        .clk(clk), .rst_n(rst_n), .start(start), .num_layers(num_layers),\n");
    s.push_str("        .layer_done(layer_done_pulse), .prefetch_done(prefetch_done),\n");
    s.push_str("        .current_layer(current_layer), .layer_start(layer_start),\n");
    s.push_str("        .start_prefetch(start_prefetch), .inference_done(done),\n");
    s.push_str("        .idle(seq_idle)\n");
    s.push_str("    );\n");
    s.push_str("\n");

    s.push_str("    // Double buffer controller\n");
    s.push_str("    wire use_buffer_a;\n");
    s.push_str("    wire [11:0] buf_read_addr, buf_write_addr;\n");
    s.push_str("    // Per-layer sequencer drives neuron_id\n");
    s.push_str("    wire [15:0] neuron_id;\n");
    s.push_str("    wire [7:0]  chunk_id;\n");
    s.push_str("    wire first_chunk, last_chunk, layer_valid, layer_done_pulse;\n");
    s.push_str("    // Configuration is LATCHED at layer start, not read live.\n");
    s.push_str("    //\n");
    s.push_str("    // The sequencer compares neuron_id against num_neurons every cycle. Wired\n");
    s.push_str("    // straight to the CSR, a host write during a run changes the terminator\n");
    s.push_str("    // underneath a layer already in flight -- the sequencer keeps emitting\n");
    s.push_str("    // work against a count that no longer describes the buffer that was\n");
    s.push_str("    // filled, and the MAC reads slots nothing wrote. Prop. 45 first read this\n");
    s.push_str("    // as a zero-neuron defect; it is not. A count that is STABLE, including a\n");
    s.push_str("    // stable zero, satisfies the property. What breaks it is the change.\n");
    s.push_str("    // See Prop. 46.\n");
    s.push_str("    reg [15:0] neurons_q;\n");
    s.push_str("    reg [7:0]  chunks_q;\n");
    s.push_str("    always @(posedge clk)\n");
    s.push_str("        if (!rst_n) begin\n");
    s.push_str("            neurons_q <= 16'd0; chunks_q <= 8'd0;\n");
    s.push_str("        end else if (layer_start_g) begin\n");
    s.push_str("            neurons_q <= neurons_per_layer;\n");
    s.push_str("            chunks_q  <= chunks_per_neuron;\n");
    s.push_str("        end\n");
    s.push_str("\n");
    s.push_str("    layer_sequencer lseq (\n");
    s.push_str("        .clk(clk), .rst_n(rst_n),\n");
    s.push_str("        .start(layer_start_g),\n");
    s.push_str("        .num_neurons(neurons_q),\n");
    s.push_str("        .num_chunks(chunks_q),\n");
    s.push_str("        .neuron_id(neuron_id),\n");
    s.push_str("        .chunk_id(chunk_id),\n");
    s.push_str("        .first_chunk(first_chunk),\n");
    s.push_str("        .last_chunk(last_chunk),\n");
    s.push_str("        .valid(layer_valid),\n");
    s.push_str("        .done(layer_done_pulse)\n");
    s.push_str("    );\n");
    s.push_str("    // Weight prefetch: streams the next layer's weights from external\n");
    s.push_str("    // memory into wmem between layers. `prefetch_done` was tied to 1'b1\n");
    s.push_str("    // and wmem's write port to 1'b0, so weights were never loaded at all.\n");
    s.push_str("    //\n");
    s.push_str("    // A single weight BRAM is only safe because multilayer_sequencer keeps\n");
    s.push_str("    // PREFETCH and LAYER_RUN in separate states -- prefetch writes while\n");
    s.push_str("    // compute is idle. a_no_weight_write_while_computing holds that\n");
    s.push_str("    // invariant; without it the MAC would read weights being overwritten.\n");
    s.push_str("    wire [11:0] pf_bram_addr;\n");
    s.push_str("    wire [53:0] pf_bram_data;\n");
    s.push_str("    wire        pf_bram_we;\n");
    s.push_str("    wire [31:0] pf_araddr;\n");
    s.push_str("    wire        pf_arvalid, pf_rready;\n");
    s.push_str("    wire        prefetch_active;\n");
    s.push_str("    weight_prefetch_ctrl prefetch (\n");
    s.push_str("        .clk(clk), .rst_n(rst_n),\n");
    s.push_str("        .start_prefetch(start_prefetch),\n");
    s.push_str("        .src_addr(32'd0),\n");
    s.push_str("        .num_words(weight_words),\n");
    s.push_str("        .prefetch_active(prefetch_active),\n");
    s.push_str("        .prefetch_done(prefetch_done),\n");
    s.push_str("        .axi_araddr(pf_araddr),\n");
    s.push_str("        .axi_arvalid(pf_arvalid),\n");
    s.push_str("        .axi_arready(1'b1),\n");
    s.push_str("        .axi_rdata(mem_rd_data),\n");
    s.push_str("        .axi_rvalid(mem_rd_valid),\n");
    s.push_str("        .axi_rready(pf_rready),\n");
    s.push_str("        .bram_addr(pf_bram_addr),\n");
    s.push_str("        .bram_data(pf_bram_data),\n");
    s.push_str("        .bram_we(pf_bram_we), .overflow(pf_overflow)\n");
    s.push_str("    );\n");
    s.push_str("\n");
    s.push_str("    double_buffer_ctrl dbl_buf (\n");
    s.push_str("        .clk(clk), .rst_n(rst_n), .layer_done(layer_done_pulse),\n");
    s.push_str("        .current_layer(current_layer), .use_buffer_a(use_buffer_a),\n");
    s.push_str("        .read_addr(buf_read_addr), .write_addr(buf_write_addr), .neuron_id(neuron_id[11:0])\n");
    s.push_str("    );\n");
    s.push_str("\n");

    s.push_str("    // ------------------------------------------------------------------\n");
    s.push_str("    // Datapath: weight memory, activation memory, and the MAC.\n");
    s.push_str("    //\n");
    s.push_str("    // Until 2026-08-09 this top instantiated only the three control-plane\n");
    s.push_str("    // sequencers; pipeline_stage2_compute and weight_bram were emitted but\n");
    s.push_str("    // never wired, so nine modules existed and no data flowed. See\n");
    s.push_str("    // docs/BITNET_V2_POSITION.md section 2.3.\n");
    s.push_str("    //\n");
    s.push_str("    // weight_bram has a ONE-CYCLE read latency (`rd_data <= mem[rd_addr]`),\n");
    s.push_str("    // so the sequencer's valid/first/last and the activation word are\n");
    s.push_str("    // delayed by one cycle to meet the weight word at the MAC. Feeding the\n");
    s.push_str("    // MAC directly from the sequencer would pair chunk N's control with\n");
    s.push_str("    // chunk N-1's weights. Proved aligned in\n");
    s.push_str("    // formal/engine_top_props.sv (a_mac_control_aligned).\n");
    s.push_str("    // ------------------------------------------------------------------\n");
    s.push_str("\n");
    s.push_str("    // Chunk-sequential address: the sequencer walks (neuron, chunk) in\n");
    s.push_str("    // order, so a running counter equals neuron_id*num_chunks + chunk_id\n");
    s.push_str("    // without needing a multiplier.\n");
    s.push_str("    reg [11:0] chunk_addr;\n");
    s.push_str("    always @(posedge clk or negedge rst_n)\n");
    s.push_str("        if (!rst_n)          chunk_addr <= 12'd0;\n");
    s.push_str("        else if (layer_start) chunk_addr <= 12'd0;\n");
    s.push_str("        else if (layer_valid) chunk_addr <= chunk_addr + 12'd1;\n");
    s.push_str("\n");
    s.push_str("    wire [53:0] weight_word, activation_word;\n");
    s.push_str("    wire [1:0]  act_trit;\n");
    s.push_str("    wire        act_trit_valid;\n");
    s.push_str("    wire [53:0] act_word;\n");
    s.push_str("    wire        act_word_valid;\n");
    s.push_str("\n");
    s.push_str("    weight_bram wmem (\n");
    s.push_str("        .clk(clk), .rd_addr(chunk_addr), .rd_data(weight_word),\n");
    s.push_str("        .wr_addr(pf_bram_addr), .wr_data(pf_bram_data), .wr_en(pf_bram_we)\n");
    s.push_str("    );\n");
    s.push_str("\n");
    s.push_str("    // Activation double buffer -- the real ping-pong the controller was\n");
    s.push_str("    // written for. Until now `use_buffer_a` was connected and never\n");
    s.push_str("    // consumed, and the single activation BRAM had wr_en tied to 1'b0, so\n");
    s.push_str("    // nothing was ever written back and the engine could not iterate.\n");
    s.push_str("    //\n");
    s.push_str("    // Per double_buffer_ctrl: use_buffer_a = 1 means READ A / WRITE B.\n");
    s.push_str("    // Reading and writing the same buffer in one layer would let a neuron\n");
    s.push_str("    // consume activations this layer just produced; a_no_read_write_same\n");
    s.push_str("    // forbids it, and no module-level property could have.\n");
    s.push_str("    //\n");
    s.push_str("    // The requantizer emits one packed word per 27 neurons, so the write\n");
    s.push_str("    // address is a word counter -- not buf_write_addr, which counts neurons.\n");
    s.push_str("    reg [11:0] act_wr_word;\n");
    s.push_str("    always @(posedge clk or negedge rst_n)\n");
    s.push_str("        if (!rst_n)           act_wr_word <= 12'd0;\n");
    s.push_str("        else if (layer_start) act_wr_word <= 12'd0;\n");
    s.push_str("        else if (act_word_valid) act_wr_word <= act_wr_word + 12'd1;\n");
    s.push_str("\n");
    s.push_str("    // Input DMA: loads layer 0's activations from DDR into the buffer the\n");
    s.push_str("    // first layer will READ, while the requantizer writes the other one.\n");
    s.push_str("    wire        dma_done, dma_local_we;\n");
    s.push_str("    wire        pf_overflow, dma_overflow;\n");
    s.push_str("    wire [11:0] dma_local_addr;\n");
    s.push_str("    wire [63:0] dma_local_wdata;\n");
    s.push_str("    wire [63:0] dma_awaddr_nc, dma_wdata_nc;\n");
    s.push_str("    wire [7:0]  dma_awlen_nc;\n");
    s.push_str("    wire        dma_awvalid_nc, dma_wvalid_nc, dma_wlast_nc, dma_bready_nc;\n");
    s.push_str("    dma_controller dma (\n");
    s.push_str("        .clk(clk), .rst_n(rst_n),\n");
    s.push_str("        // Interlocked against inference. reg_ctrl is host-writable at any\n");
    s.push_str("        // time, so a host writing ctrl = 3 starts a DMA and an inference in\n");
    s.push_str("        // the same cycle; the DMA then loads activations into the buffer the\n");
    s.push_str("        // MAC is reading. Yosys found exactly that trace. Gating on !busy\n");
    s.push_str("        // makes the hardware total rather than relying on the host to\n");
    s.push_str("        // sequence its own register writes -- the same choice as the\n");
    s.push_str("        // requantizer's priority chain (FORMAL_FOUNDATIONS Prop. 15b).\n");
    s.push_str("        // busy alone is too weak: it is (current_layer != 0) || layer_start,\n");
    s.push_str("        // which is false during the very first layer. Gate on the inference\n");
    s.push_str("        // REQUEST as well, so ctrl = 3 loads nothing rather than corrupting\n");
    s.push_str("        // the buffer layer 0 is about to read.\n");
    s.push_str("        // One condition that answers the right question, replacing four\n");
    s.push_str("        // that nearly did. seq_idle is multilayer_sequencer's own state,\n");
    s.push_str("        // not a host request or a decode of a counter -- the sequencer is\n");
    s.push_str("        // the only thing that knows whether it has stopped. The pipeline\n");
    s.push_str("        // valids stay in the guard because seq_idle covers the sequencer,\n");
    s.push_str("        // not the beats still draining out of the MAC behind it.\n");
    s.push_str("        // !reg_ctrl[0] is still needed alongside seq_idle: a host writing\n");
    s.push_str("        // both bits at once is idle at that instant, so seq_idle alone lets\n");
    s.push_str("        // both start in the same cycle. Replacing a guard is where terms\n");
    s.push_str("        // get dropped -- the new condition answered a different question\n");
    s.push_str("        // than one of the old ones, not all of them.\n");
    s.push_str("        .start(reg_ctrl[1] && !reg_ctrl[0] && seq_idle\n");
    s.push_str("               && !layer_valid && !mac_valid_q && !act_trit_valid),\n");
    s.push_str("        .src_addr(reg_input_addr),\n");
    s.push_str("        .dst_addr(reg_output_addr),\n");
    s.push_str("        .length(reg_neurons),\n");
    s.push_str("        .direction(1'b0),\n");
    s.push_str("        .busy(dma_busy), .done(dma_done),\n");
    s.push_str("        .m_axi_araddr(m_axi_araddr), .m_axi_arlen(m_axi_arlen),\n");
    s.push_str("        .m_axi_arvalid(m_axi_arvalid), .m_axi_arready(m_axi_arready),\n");
    s.push_str("        .m_axi_rdata(m_axi_rdata), .m_axi_rlast(m_axi_rlast),\n");
    s.push_str("        .m_axi_rvalid(m_axi_rvalid), .m_axi_rready(m_axi_rready),\n");
    s.push_str("        .m_axi_awaddr(dma_awaddr_nc), .m_axi_awlen(dma_awlen_nc),\n");
    s.push_str("        .m_axi_awvalid(dma_awvalid_nc), .m_axi_awready(1'b1),\n");
    s.push_str("        .m_axi_wdata(dma_wdata_nc), .m_axi_wlast(dma_wlast_nc),\n");
    s.push_str("        .m_axi_wvalid(dma_wvalid_nc), .m_axi_wready(1'b1),\n");
    s.push_str("        .m_axi_bvalid(1'b1), .m_axi_bready(dma_bready_nc),\n");
    s.push_str("        .local_addr(dma_local_addr), .local_wdata(dma_local_wdata),\n");
    s.push_str("        .local_we(dma_local_we), .local_rdata(64'd0), .overflow(dma_overflow)\n");
    s.push_str("    );\n");
    s.push_str("\n");
    s.push_str("    // Two writers, one port each. The DMA fills the buffer being read;\n");
    s.push_str("    // the requantizer fills the one being written. a_two_writers_disjoint\n");
    s.push_str("    // holds them apart -- both memories and both writers are individually\n");
    s.push_str("    // correct, so only a property spanning them can see a collision.\n");
    s.push_str("    // Inference must not consume an activation buffer nothing has written.\n");
    s.push_str("    // Declared here, after dma_local_we is in scope (Prop. 25e), and driven\n");
    s.push_str("    // by an actual write rather than by dma_done, because a completed\n");
    s.push_str("    // transfer is not evidence that work was done (Prop. 26).\n");
    s.push_str("    reg input_loaded;\n");
    s.push_str("    always @(posedge clk)\n");
    s.push_str("        if (!rst_n)            input_loaded <= 1'b0;\n");
    s.push_str("        else if (dma_local_we) input_loaded <= 1'b1;\n");
    s.push_str("\n");
    s.push_str("    wire wr_en_a = dma_local_we ?  use_buffer_a : (act_word_valid && !use_buffer_a);\n");
    s.push_str("    wire wr_en_b = dma_local_we ? !use_buffer_a : (act_word_valid &&  use_buffer_a);\n");
    s.push_str("    wire [11:0] act_wr_addr = dma_local_we ? dma_local_addr : act_wr_word;\n");
    s.push_str("    wire [53:0] act_wr_data = dma_local_we ? dma_local_wdata[53:0] : act_word;\n");
    s.push_str("    assign start = reg_ctrl[0] && !dma_busy && input_loaded;\n");
    s.push_str("\n");
    s.push_str("    // Per-buffer written flags, in real hardware. A single global\n");
    s.push_str("    // input_loaded bit is the wrong shape: it answers \"did anything get\n");
    s.push_str("    // written\" when the question is \"was the buffer this layer reads\n");
    s.push_str("    // written\". The counterexample: layer 0 completes having emitted no\n");
    s.push_str("    // activation words at all -- legal, since a zero-neuron layer completes\n");
    s.push_str("    // immediately by design (Prop. 26) -- the ping-pong flips, and layer 1\n");
    s.push_str("    // then reads a buffer nothing ever wrote. See Prop. 33.\n");
    s.push_str("    // Prop. 33's boolean interlock. A COUNT version was attempted in\n");
    s.push_str("    // Wave 594 and withdrawn: `nwrote >= neurons_per_layer` checked at layer\n");
    s.push_str("    // start neither closed Prop. 43 nor left the proved set intact.\n");
    s.push_str("    //\n");
    s.push_str("    // Why it cannot close it, recorded for the next attempt: the property\n");
    s.push_str("    // compares the READ ADDRESS against written slots at the moment of the\n");
    s.push_str("    // read, while a start-time gate says nothing about writes and reads\n");
    s.push_str("    // interleaving WITHIN a layer. A start-time count is the wrong instrument\n");
    s.push_str("    // for a per-cycle claim; the fix is either a per-read check or a proof\n");
    s.push_str("    // that the write stream stays ahead of the read stream.\n");
    s.push_str("    reg wrote_a, wrote_b;\n");
    s.push_str("    always @(posedge clk)\n");
    s.push_str("        if (!rst_n) begin wrote_a <= 1'b0; wrote_b <= 1'b0; end\n");
    s.push_str("        else begin\n");
    s.push_str("            if (wr_en_a) wrote_a <= 1'b1;\n");
    s.push_str("            if (wr_en_b) wrote_b <= 1'b1;\n");
    s.push_str("        end\n");
    s.push_str("\n");
    s.push_str("    // Reading an unwritten buffer is an error, not a stall. Refusing to\n");
    s.push_str("    // start would hang the engine on a legitimately empty layer, and a\n");
    s.push_str("    // stalled engine satisfies every safety property (Prop. 24). So the\n");
    s.push_str("    // layer is not started, and the host is told through the error IRQ that\n");
    s.push_str("    // Prop. 29c gave a driver.\n");
    s.push_str("    // Error, not stall (Prop. 33d).\n");
    s.push_str("    // How far each buffer was filled, carried with the buffer across the\n");
    s.push_str("    // ping-pong. Prop. 46c named the residue exactly: layer N fills to its\n");
    s.push_str("    // own extent and layer N+1 reads to its own, with nothing relating them.\n");
    s.push_str("    // This relates them. A fill restarts when the buffer becomes the write\n");
    s.push_str("    // target, which is the layer boundary.\n");
    s.push_str("    //\n");
    s.push_str("    // Wave 594 tried a start-time count and it failed, because the count\n");
    s.push_str("    // could change mid-run (Prop. 44). Prop. 46b latched the configuration,\n");
    s.push_str("    // so the read extent is now fixed at layer start and a start-time\n");
    s.push_str("    // comparison IS sufficient: the reads are 0..neurons_q-1 and the fill\n");
    s.push_str("    // covered 0..filled-1. Same shape, different design underneath.\n");
    s.push_str("    reg [15:0] filled_a, filled_b;\n");
    s.push_str("    always @(posedge clk)\n");
    s.push_str("        if (!rst_n) begin filled_a <= 16'd0; filled_b <= 16'd0; end\n");
    s.push_str("        else begin\n");
    s.push_str("            if (layer_done_pulse &&  use_buffer_a) filled_a <= 16'd0;\n");
    s.push_str("            else if (wr_en_a) filled_a <= {4'd0, act_wr_addr} + 16'd1;\n");
    s.push_str("            if (layer_done_pulse && !use_buffer_a) filled_b <= 16'd0;\n");
    s.push_str("            else if (wr_en_b) filled_b <= {4'd0, act_wr_addr} + 16'd1;\n");
    s.push_str("        end\n");
    s.push_str("\n");
    s.push_str("    wire [15:0] filled = use_buffer_a ? filled_a : filled_b;\n");
    s.push_str("    wire input_ready   = (use_buffer_a ? wrote_a : wrote_b)\n");
    s.push_str("                      && (filled >= neurons_per_layer);\n");
    s.push_str("    wire layer_start_g = layer_start && input_ready;\n");
    s.push_str("    wire buffer_unwritten = layer_start && !input_ready;\n");
    s.push_str("    wire [53:0] act_rd_a, act_rd_b;\n");
    s.push_str("\n");
    s.push_str("    weight_bram amem_a (\n");
    s.push_str("        .clk(clk), .rd_addr(buf_read_addr), .rd_data(act_rd_a),\n");
    s.push_str("        .wr_addr(act_wr_addr), .wr_data(act_wr_data), .wr_en(wr_en_a)\n");
    s.push_str("    );\n");
    s.push_str("    weight_bram amem_b (\n");
    s.push_str("        .clk(clk), .rd_addr(buf_read_addr), .rd_data(act_rd_b),\n");
    s.push_str("        .wr_addr(act_wr_addr), .wr_data(act_wr_data), .wr_en(wr_en_b)\n");
    s.push_str("    );\n");
    s.push_str("\n");
    s.push_str("    assign activation_word = use_buffer_a ? act_rd_a : act_rd_b;\n");
    s.push_str("\n");
    s.push_str("    // One-cycle skew to match the BRAM read latency.\n");
    s.push_str("    reg mac_valid_q, mac_first_q, mac_last_q;\n");
    s.push_str("    always @(posedge clk or negedge rst_n)\n");
    s.push_str("        if (!rst_n) begin\n");
    s.push_str("            mac_valid_q <= 1'b0; mac_first_q <= 1'b0; mac_last_q <= 1'b0;\n");
    s.push_str("        end else begin\n");
    s.push_str("            mac_valid_q <= layer_valid;\n");
    s.push_str("            mac_first_q <= first_chunk;\n");
    s.push_str("            mac_last_q  <= last_chunk;\n");
    s.push_str("        end\n");
    s.push_str("\n");
    s.push_str("    wire        mac_valid_out, mac_result_final;\n");
    s.push_str("    wire signed [15:0] mac_result;\n");
    s.push_str("    pipeline_stage2_compute mac (\n");
    s.push_str("        .clk(clk), .rst_n(rst_n),\n");
    s.push_str("        .valid_in(mac_valid_q),\n");
    s.push_str("        .input_chunk(activation_word),\n");
    s.push_str("        .weight_chunk(weight_word),\n");
    s.push_str("        .first_chunk(mac_first_q),\n");
    s.push_str("        .last_chunk(mac_last_q),\n");
    s.push_str("        .valid_out(mac_valid_out),\n");
    s.push_str("        .result(mac_result),\n");
    s.push_str("        .result_final(mac_result_final)\n");
    s.push_str("    );\n");
    s.push_str("\n");
    s.push_str("    // Layer-boundary requantizer: the MAC's signed accumulator becomes\n");
    s.push_str("    // packed trits for the next layer. This interface is where the\n");
    s.push_str("    // activation-width choice lives -- see docs/BITNET_V2_POSITION.md.\n");
    s.push_str("    activation_requant requant (\n");
    s.push_str("        .clk(clk), .rst_n(rst_n),\n");
    s.push_str("        .valid_in(mac_valid_out),\n");
    s.push_str("        .acc(mac_result),\n");
    s.push_str("        .threshold(threshold),\n");
    s.push_str("        .trit(act_trit),\n");
    s.push_str("        .trit_valid(act_trit_valid),\n");
    s.push_str("        .word(act_word),\n");
    s.push_str("        .word_valid(act_word_valid)\n");
    s.push_str("    );\n");
    s.push_str("\n");
    s.push_str("    // Neuron output: compare the accumulated dot product against the\n");
    s.push_str("    // host-programmed threshold. `threshold` was previously declared and\n");
    s.push_str("    // never referenced.\n");
    s.push_str("    assign neuron_out       = mac_valid_out && (mac_result >= threshold);\n");
    s.push_str("    assign neuron_out_valid = mac_valid_out;\n");
    s.push_str("    assign act_word_out       = act_word;\n");
    s.push_str("    assign act_word_out_valid = act_word_valid;\n");
    s.push_str("\n");
    s.push_str("    // Cycle counter\n");
    s.push_str("    always @(posedge clk or negedge rst_n)\n");
    s.push_str("        if (!rst_n) cycles <= 32'd0;\n");
    s.push_str("        else if (start) cycles <= 32'd0;\n");
    s.push_str("        else if (busy) cycles <= cycles + 32'd1;\n");
    s.push_str("    assign cycle_count = cycles;\n");
    s.push_str("    // busy is a real state register, not a decode. It used to be\n");
    s.push_str("    // (current_layer != 0) || layer_start -- false during the entire first\n");
    s.push_str("    // layer, so any interlock keyed off it had a hole exactly where the\n");
    s.push_str("    // first inference happens. A counter comparison that is usually\n");
    s.push_str("    // equivalent to \"running\" is not the same object as a flag set at\n");
    s.push_str("    // start and cleared at done, and the difference shows at the\n");
    s.push_str("    // boundaries where interlocks matter. See FORMAL_FOUNDATIONS Prop. 21.\n");
    s.push_str("    reg inference_active;\n");
    s.push_str("    always @(posedge clk or negedge rst_n)\n");
    s.push_str("        if (!rst_n)                        inference_active <= 1'b0;\n");
    s.push_str("        else if (start && !inference_active) inference_active <= 1'b1;\n");
    s.push_str("        else if (done)                      inference_active <= 1'b0;\n");
    s.push_str("    assign busy = inference_active;\n");
    s.push_str("\n");

    s.push_str("`ifdef T27_FORMAL\n");
    s.push_str("    // ------------------------------------------------------------------\n");
    s.push_str("    // Integration properties. These are the first properties in this repo\n");
    s.push_str("    // that range over more than one module: everything proved before now\n");
    s.push_str("    // was module-scoped, because until the datapath was wired there was no\n");
    s.push_str("    // system behaviour to state a property about.\n");
    s.push_str("    //\n");
    s.push_str("    // They live inside the module under `ifdef T27_FORMAL rather than in a\n");
    s.push_str("    // wrapper because the alignment they check is internal, and yosys's\n");
    s.push_str("    // `sat` needs a single flattened module -- which mangles the names a\n");
    s.push_str("    // wrapper would have to reference.\n");
    s.push_str("    //\n");
    s.push_str("    // Prove with:\n");
    s.push_str("    //   yosys -p \"read_verilog -sv -formal -DFORMAL <bundle>/*.sv; \\\n");
    s.push_str("    //             prep -top bitnet_engine_top -flatten; async2sync; \\\n");
    s.push_str("    //             chformal -lower; sat -verify -prove-asserts -seq 12 \\\n");
    s.push_str("    //             -set-init-zero -set-assumes\"\n");
    s.push_str("    // ------------------------------------------------------------------\n");
    s.push_str("\n");
    s.push_str("    // Harness sanity: a tautology. If this refutes, the run is not\n");
    s.push_str("    // evaluating what it appears to.\n");
    s.push_str("    // a_sanity was removed in Wave 591: its body was `chunk_addr ==\n");
    s.push_str("    // chunk_addr`, folded to constant true before any signal is read. It\n");
    s.push_str("    // proved unconditionally, tested nothing, and still emitted a $check\n");
    s.push_str("    // cell that inflated the non-empty-property gate. See Prop. 41.\n");
    s.push_str("\n");
    s.push_str("    // THE integration property, stated on the MAC's OUTPUT rather than on\n");
    s.push_str("    // the skew registers. An earlier version asserted only that\n");
    s.push_str("    // mac_valid_q == $past(layer_valid), which is true of the registers no\n");
    s.push_str("    // matter what the MAC is actually connected to -- rewiring valid_in\n");
    s.push_str("    // straight to layer_valid left every such property PROVING. A property\n");
    s.push_str("    // about a signal is not a property about the wire it feeds.\n");
    s.push_str("    //\n");
    s.push_str("    // pipeline_stage2_compute sets valid_out <= last_chunk when valid_in,\n");
    s.push_str("    // else 0. So the MAC's own output pins down which control it consumed.\n");
    s.push_str("    always @(posedge clk) if (rst_n && $past(rst_n))\n");
    s.push_str("        a_mac_consumed_skewed_control:\n");
    s.push_str("            assert (mac_valid_out == ($past(mac_valid_q) && $past(mac_last_q)));\n");
    s.push_str("\n");
    s.push_str("    // Supporting: the skew registers themselves lag by exactly one cycle.\n");
    s.push_str("    // latency, so the MAC's control must lag the sequencer by exactly one\n");
    s.push_str("    // cycle. Off by one in either direction pairs chunk N's control with\n");
    s.push_str("    // chunk N-1's or N+1's weights, and every module-level property would\n");
    s.push_str("    // still pass.\n");
    s.push_str("    always @(posedge clk) if (rst_n && $past(rst_n))\n");
    s.push_str("        a_mac_control_aligned: assert (mac_valid_q == $past(layer_valid));\n");
    s.push_str("    always @(posedge clk) if (rst_n && $past(rst_n))\n");
    s.push_str("        a_mac_first_aligned: assert (mac_first_q == $past(first_chunk));\n");
    s.push_str("    always @(posedge clk) if (rst_n && $past(rst_n))\n");
    s.push_str("        a_mac_last_aligned: assert (mac_last_q == $past(last_chunk));\n");
    s.push_str("\n");
    s.push_str("    // The MAC may only be fed while the layer sequencer is producing work.\n");
    s.push_str("    always @(posedge clk) if (rst_n && $past(rst_n))\n");
    s.push_str("        a_no_mac_work_without_sequencer: assert (!mac_valid_q || $past(layer_valid));\n");
    s.push_str("\n");
    s.push_str("    // The chunk address is bounded by the buffer it indexes, and is reset\n");
    s.push_str("    // at layer start so layers do not read each other's weights.\n");
    s.push_str("    always @(posedge clk) if (rst_n && $past(rst_n) && $past(layer_start))\n");
    s.push_str("        a_chunk_addr_resets: assert (chunk_addr == 12'd0);\n");
    s.push_str("\n");
    s.push_str("    // The host aperture actually drives the engine: start is a CSR bit,\n");
    s.push_str("    // and status reflects the engine rather than being a constant. Both\n");
    s.push_str("    // would hold vacuously if the slave were instantiated but ignored --\n");
    s.push_str("    // which is precisely how use_buffer_a was dead for four waves.\n");
    s.push_str("    always @(posedge clk) if (rst_n)\n");
    s.push_str("        a_start_follows_ctrl_unless_interlocked:\n");
    s.push_str("            assert (start == (reg_ctrl[0] && !dma_busy && input_loaded));\n");
    s.push_str("    // ...and the interlock is the ONLY thing that may suppress a start.\n");
    s.push_str("    always @(posedge clk) if (rst_n && !dma_busy && input_loaded)\n");
    s.push_str("        a_start_is_ctrl_bit0: assert (start == reg_ctrl[0]);\n");
    s.push_str("    always @(posedge clk) if (rst_n)\n");
    s.push_str("        a_status_reflects_engine: assert (reg_status[0] == busy && reg_status[1] == done);\n");
    s.push_str("\n");
    s.push_str("    // Minimal external-memory model: read data only ever follows a\n");
    s.push_str("    // request. Without it mem_rd_valid is a free input, and a memory\n");
    s.push_str("    // answering a question nobody asked is indistinguishable from a\n");
    s.push_str("    // design defect.\n");
    s.push_str("    always @(posedge clk) if (rst_n && $past(rst_n))\n");
    s.push_str("        assume (!mem_rd_valid || $past(mem_rd_en));\n");
    s.push_str("\n");
    s.push_str("    // A single weight BRAM is safe only if prefetch never writes while the\n");
    s.push_str("    // MAC is reading. This refuted when the host path was first wired and\n");
    s.push_str("    // was recorded as an open gap rather than weakened; the cause was a\n");
    s.push_str("    // stale completion flag plus a missing request/acknowledge handshake\n");
    s.push_str("    // (FORMAL_FOUNDATIONS Prop. 18). It now holds.\n");
    s.push_str("    always @(posedge clk) if (rst_n)\n");
    s.push_str("        a_no_weight_write_while_computing: assert (!(pf_bram_we && mac_valid_q));\n");
    s.push_str("    // The external memory port is driven by the prefetcher and nothing else.\n");
    s.push_str("    always @(posedge clk) if (rst_n)\n");
    s.push_str("        a_mem_port_is_prefetch: assert (mem_rd_en == pf_arvalid);\n");
    s.push_str("\n");
    s.push_str("    // Two independent writers now target the activation buffers. If both\n");
    s.push_str("    // fire in one cycle the arbitration mux silently drops one of them.\n");
    s.push_str("    always @(posedge clk) if (rst_n)\n");
    s.push_str("        a_two_writers_disjoint: assert (!(dma_local_we && act_word_valid));\n");
    s.push_str("\n");
    s.push_str("    // The third write port, and the one never checked. Prop. 29 found the\n");
    s.push_str("    // weight and DMA ports each writing word N at address N+1, never writing\n");
    s.push_str("    // slot 0. The activation port pairs a registered index with a\n");
    s.push_str("    // combinational valid, which is the correct shape -- this proves it\n");
    s.push_str("    // rather than asserting it by inspection. Writes within a layer must\n");
    s.push_str("    // land on 0,1,2,... with no gap and no repeat. The DMA path is excluded:\n");
    s.push_str("    // it drives its own address sequence, covered by max_size_props.\n");
    s.push_str("    reg [11:0] fv_next_act_addr;\n");
    s.push_str("    always @(posedge clk or negedge rst_n)\n");
    s.push_str("        if (!rst_n)                        fv_next_act_addr <= 12'd0;\n");
    s.push_str("        else if (layer_start)              fv_next_act_addr <= 12'd0;\n");
    s.push_str("        else if (wr_en_a || wr_en_b)       fv_next_act_addr <= fv_next_act_addr + 12'd1;\n");
    s.push_str("\n");
    s.push_str("    always @(posedge clk)\n");
    s.push_str("        if (rst_n && (wr_en_a || wr_en_b) && !dma_local_we)\n");
    s.push_str("            a_act_writes_contiguous: assert (act_wr_addr == fv_next_act_addr);\n");
    s.push_str("\n");
    s.push_str("    // ---- zero-count sweep, READ side (Prop. 48) ----\n");
    s.push_str("    //\n");
    s.push_str("    // Zero-sized inputs were swept exhaustively on the WRITE side (Prop. 26)\n");
    s.push_str("    // and found four defects. The read side was asked once, in Prop. 45, and\n");
    s.push_str("    // answered with a fifth. These ask the remaining read pointers.\n");
    s.push_str("    always @(posedge clk)\n");
    s.push_str("        if (rst_n && chunks_q == 8'd0)\n");
    s.push_str("            a_zero_chunks_no_mac: assert (!mac_valid_q);\n");
    s.push_str("\n");
    s.push_str("    always @(posedge clk)\n");
    s.push_str("        if (rst_n && chunks_q == 8'd0)\n");
    s.push_str("            a_zero_chunks_no_weight_walk: assert (chunk_addr == 12'd0);\n");
    s.push_str("\n");
    s.push_str("    always @(posedge clk)\n");
    s.push_str("        if (rst_n && neurons_q == 16'd0)\n");
    s.push_str("            a_zero_neurons_no_act_walk: assert (buf_read_addr == 12'd0);\n");
    s.push_str("\n");
    s.push_str("    // ---- read-side pairing (the mirror of Props. 29d and 32) ----\n");
    s.push_str("    //\n");
    s.push_str("    // Every property until now constrained writes. The read path has the\n");
    s.push_str("    // same hazards reflected: the activation BRAMs have a one-cycle read\n");
    s.push_str("    // latency, so the address is issued one cycle before the word arrives,\n");
    s.push_str("    // while `activation_word = use_buffer_a ? act_rd_a : act_rd_b` selects\n");
    s.push_str("    // with the CURRENT use_buffer_a. If the ping-pong flips in between, the\n");
    s.push_str("    // mux returns a word from the buffer that was not addressed. See\n");
    s.push_str("    // Prop. 39.\n");
    s.push_str("    always @(posedge clk)\n");
    s.push_str("        if (rst_n && $past(rst_n) && mac_valid_q)\n");
    s.push_str("            a_act_read_select_stable: assert (use_buffer_a == $past(use_buffer_a));\n");
    s.push_str("\n");
    s.push_str("    // The weight side of the same seam: the word the MAC consumes was\n");
    s.push_str("    // addressed by the chunk counter one cycle earlier, so that counter must\n");
    s.push_str("    // not have been reset in between -- a layer_start between the address\n");
    s.push_str("    // and the data would pair chunk 0's weights with the previous layer's\n");
    s.push_str("    // control.\n");
    s.push_str("    always @(posedge clk)\n");
    s.push_str("        if (rst_n && $past(rst_n) && mac_valid_q)\n");
    s.push_str("            a_weight_addr_not_reset_mid_read: assert (!$past(layer_start));\n");
    s.push_str("\n");
    s.push_str("    // Prop. 25 closed \"the buffer was never written at all\". This is the\n");
    s.push_str("    // slot-level extension: the MAC must not consume a slot beyond the\n");
    s.push_str("    // highest one ever written to the buffer it is reading. The address is\n");
    s.push_str("    // issued a cycle before the word arrives, so the comparison is against\n");
    s.push_str("    // $past(buf_read_addr). See Prop. 39.\n");
    s.push_str("    reg [11:0] fv_maxwr_a, fv_maxwr_b;\n");
    s.push_str("    reg        fv_any_a, fv_any_b;\n");
    s.push_str("    always @(posedge clk)\n");
    s.push_str("        if (!rst_n) begin\n");
    s.push_str("            fv_maxwr_a <= 12'd0; fv_maxwr_b <= 12'd0;\n");
    s.push_str("            fv_any_a   <= 1'b0;  fv_any_b   <= 1'b0;\n");
    s.push_str("        end else begin\n");
    s.push_str("            if (wr_en_a) begin\n");
    s.push_str("                fv_any_a <= 1'b1;\n");
    s.push_str("                if (!fv_any_a || act_wr_addr > fv_maxwr_a) fv_maxwr_a <= act_wr_addr;\n");
    s.push_str("            end\n");
    s.push_str("            if (wr_en_b) begin\n");
    s.push_str("                fv_any_b <= 1'b1;\n");
    s.push_str("                if (!fv_any_b || act_wr_addr > fv_maxwr_b) fv_maxwr_b <= act_wr_addr;\n");
    s.push_str("            end\n");
    s.push_str("        end\n");
    s.push_str("\n");
    s.push_str("    // An EXACT formulation of the same claim, as a discriminator. The\n");
    s.push_str("    // property below bounds the read address by the HIGHEST address ever\n");
    s.push_str("    // written, which is an approximation: it permits reading a hole. This\n");
    s.push_str("    // one tracks each slot individually over the proof-sized memory\n");
    s.push_str("    // (chparam DEPTH 4), so it is exact. If the two disagree, the bound is\n");
    s.push_str("    // the fault; if they agree, the engine is. Prop. 43.\n");
    s.push_str("    reg [3:0] fv_bm_a, fv_bm_b;\n");
    s.push_str("    // $past(x)[1:0] is not legal Verilog -- part-selecting a system function\n");
    s.push_str("    // call. Register the previous read address instead.\n");
    s.push_str("    reg [11:0] fv_prev_rd;\n");
    s.push_str("    always @(posedge clk) fv_prev_rd <= buf_read_addr;\n");
    s.push_str("    always @(posedge clk)\n");
    s.push_str("        if (!rst_n) begin fv_bm_a <= 4'd0; fv_bm_b <= 4'd0; end\n");
    s.push_str("        else begin\n");
    s.push_str("            if (wr_en_a) fv_bm_a[act_wr_addr[1:0]] <= 1'b1;\n");
    s.push_str("            if (wr_en_b) fv_bm_b[act_wr_addr[1:0]] <= 1'b1;\n");
    s.push_str("        end\n");
    s.push_str("\n");
    s.push_str("    // CLOSED in Wave 597 and promoted into the default set. It stood open\n");
    s.push_str("    // for eight waves. The fix was not one change but three, each necessary\n");
    s.push_str("    // and none sufficient: per-buffer written flags (Prop. 33), latching the\n");
    s.push_str("    // configuration at layer start (Prop. 46b), and carrying the fill extent\n");
    s.push_str("    // across the ping-pong (Prop. 47).\n");
    s.push_str("    always @(posedge clk)\n");
    s.push_str("        if (rst_n && $past(rst_n) && mac_valid_q)\n");
    s.push_str("            a_read_slot_written: assert (use_buffer_a ? fv_bm_a[fv_prev_rd[1:0]]\n");
    s.push_str("                                                     : fv_bm_b[fv_prev_rd[1:0]]);\n");

    s.push_str("    // OPEN: this REFUTES. Prop. 25 closed \"the buffer was never written at\n");
    s.push_str("    // all\"; this is the slot-level extension and it does not hold. Gated as\n");
    s.push_str("    // an expected refutation so closing it turns the build red and asks for\n");
    s.push_str("    // promotion -- the mechanism that closed Prop. 25 after eight waves.\n");
    s.push_str("    // Whether the fault is the engine or the tracking registers above is\n");
    s.push_str("    // NOT yet established; the counterexample has not been read. See\n");
    s.push_str("    // Prop. 39e.\n");
    s.push_str("    always @(posedge clk)\n");
    s.push_str("        if (rst_n && $past(rst_n) && mac_valid_q)\n");
    s.push_str("            a_read_within_written: assert (use_buffer_a ? ($past(buf_read_addr) <= fv_maxwr_a)\n");
    s.push_str("                                                       : ($past(buf_read_addr) <= fv_maxwr_b));\n");
    s.push_str("\n");
    s.push_str("    // ---- cross-layer properties (the first spanning two layers) ----\n");
    s.push_str("    reg fv_wrote_a, fv_wrote_b;\n");
    s.push_str("    always @(posedge clk or negedge rst_n)\n");
    s.push_str("        if (!rst_n) begin fv_wrote_a <= 1'b0; fv_wrote_b <= 1'b0; end\n");
    s.push_str("        else begin\n");
    s.push_str("            if (wr_en_a) fv_wrote_a <= 1'b1;\n");
    s.push_str("            if (wr_en_b) fv_wrote_b <= 1'b1;\n");
    s.push_str("        end\n");
    s.push_str("\n");
    s.push_str("    // The ping-pong actually alternates across a layer boundary, so the\n");
    s.push_str("    // buffer layer N wrote is the buffer layer N+1 reads.\n");
    s.push_str("    always @(posedge clk) if (rst_n && $past(rst_n) && $past(layer_done_pulse))\n");
    s.push_str("        a_buffer_alternates: assert (use_buffer_a == !$past(use_buffer_a));\n");
    s.push_str("\n");
    s.push_str("    // No activation is consumed from a buffer nothing has written.\n");
    s.push_str("    //\n");
    s.push_str("    // CLOSED in Wave 582 and promoted into the default set. It stood\n");
    s.push_str("    // open for eight waves. Three interlocks were tried and withdrawn in\n");
    s.push_str("    // Wave 574; all three were the wrong SHAPE -- a single global\n");
    s.push_str("    // input_loaded bit answers \"did anything get written\" when the\n");
    s.push_str("    // question is \"was the buffer this layer reads written\". The\n");
    s.push_str("    // counterexample only became readable once the trace reader existed.\n");
    s.push_str("    // See Prop. 33.\n");
    s.push_str("    always @(posedge clk) if (rst_n && mac_valid_q)\n");
    s.push_str("        a_no_read_before_write: assert (use_buffer_a ? fv_wrote_a : fv_wrote_b);\n");
    s.push_str("\n");
    s.push_str("    // The double-buffer invariant. Reading and writing the same buffer in\n");
    s.push_str("    // one layer lets a neuron consume activations this layer just wrote --\n");
    s.push_str("    // the classic ping-pong inversion, invisible to every module-level\n");
    s.push_str("    // property because both BRAMs and the controller are individually fine.\n");
    s.push_str("    // Scoped to the REQUANTIZER path. This invariant was written when the\n");
    s.push_str("    // requantizer was the only writer; the input DMA is a second writer\n");
    s.push_str("    // with the opposite intent -- it deliberately fills the buffer that is\n");
    s.push_str("    // about to be READ, because that is where layer 0's input belongs.\n");
    s.push_str("    // Leaving the invariant unscoped made a correct DMA look like a\n");
    s.push_str("    // violation. What must still never happen is a requantizer write into\n");
    s.push_str("    // the buffer being read, and the DMA loading while compute is live --\n");
    s.push_str("    // stated separately below.\n");
    s.push_str("    always @(posedge clk) if (rst_n && !dma_local_we)\n");
    s.push_str("        a_no_read_write_same: assert (!(use_buffer_a && wr_en_a) && !(!use_buffer_a && wr_en_b));\n");
    s.push_str("    // Closed by exporting quiescence from multilayer_sequencer (Prop. 23)\n");
    s.push_str("    // after three top-level narrowings that each moved the window and none\n");
    s.push_str("    // of which could close it.\n");
    s.push_str("    always @(posedge clk) if (rst_n)\n");
    s.push_str("        a_dma_not_during_compute: assert (!(dma_local_we && mac_valid_q));\n");
    s.push_str("    always @(posedge clk) if (rst_n)\n");
    s.push_str("        a_at_most_one_buffer_written: assert (!(wr_en_a && wr_en_b));\n");
    s.push_str("    always @(posedge clk) if (rst_n && $past(rst_n) && $past(layer_start))\n");
    s.push_str("        a_act_wr_word_resets: assert (act_wr_word == 12'd0);\n");
    s.push_str("\n");
    s.push_str("    // threshold now gates the output; it was declared and unused before.\n");
    s.push_str("    always @(posedge clk) if (rst_n)\n");
    s.push_str("        a_output_needs_valid: assert (!neuron_out || neuron_out_valid);\n");
    s.push_str("    always @(posedge clk) if (rst_n && neuron_out_valid && (mac_result >= threshold))\n");
    s.push_str("        a_threshold_gates: assert (neuron_out);\n");
    s.push_str("`endif\n");
    s.push_str("\n");
    s.push_str("    // External memory port, now driven by the prefetch controller rather\n");
    s.push_str("    // than tied to zero.\n");
    s.push_str("    assign mem_addr  = pf_araddr;\n");
    s.push_str("    assign mem_rd_en = pf_arvalid;\n");
    s.push_str("\n");
    s.push_str("    // Host interrupt aggregation. inference_done is the multilayer\n");
    s.push_str("    // sequencer's completion; dma_done reports a finished prefetch.\n");

    s.push_str("    interrupt_controller irqc (\n");
    s.push_str("        .clk(clk), .rst_n(rst_n),\n");
    s.push_str("        .inference_done(done),\n");
    s.push_str("        .dma_done(prefetch_done),\n");
    s.push_str("        // The error source was tied off while nothing could report one. Both\n");
    s.push_str("        // transfer engines now raise overflow when a request exceeds the local\n");
    s.push_str("        // address space, which is exactly what this sticky, maskable,\n");
    s.push_str("        // read-to-clear bit exists for. See FORMAL_FOUNDATIONS Prop. 29.\n");
    s.push_str("        .error(pf_overflow || dma_overflow || buffer_unwritten),\n");
    s.push_str("        .irq_enable(3'b111),\n");
    s.push_str("        .irq_status(irq_status_w),\n");
    s.push_str("        .status_read(1'b0),\n");
    s.push_str("        .irq_out(irq)\n");
    s.push_str("    );\n");
    s.push_str("\n");

    s.push_str("endmodule\n");

    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ident_validator_basics() {
        assert!(is_valid_verilog_ident("bitnet_engine_top"));
        assert!(is_valid_verilog_ident("a"));
        assert!(is_valid_verilog_ident("_x"));
        assert!(is_valid_verilog_ident("Foo123"));
        assert!(!is_valid_verilog_ident(""));
        assert!(!is_valid_verilog_ident("9foo"));
        assert!(!is_valid_verilog_ident("has space"));
        assert!(!is_valid_verilog_ident("dash-name"));
        assert!(!is_valid_verilog_ident("uni\u{00e9}"));
    }

    #[test]
    fn default_name_used_when_invalid() {
        let v = build_bitnet_engine_top("");
        assert!(v.contains("module bitnet_engine_top ("));
        let v2 = build_bitnet_engine_top("9bad");
        assert!(v2.contains("module bitnet_engine_top ("));
    }

    #[test]
    fn custom_name_propagates() {
        let v = build_bitnet_engine_top("engine_top_v1");
        assert!(v.contains("module engine_top_v1 ("));
        assert!(!v.contains("module bitnet_engine_top ("));
    }

    #[test]
    // Renamed from control_ports_present, which listed start/num_layers/
    // chunks_per_neuron/threshold as top-level inputs. Those are now CSRs
    // written over AXI-Lite -- the point of wiring axi_lite_slave.
    fn host_aperture_replaces_config_ports() {
        let v = build_bitnet_engine_top("bitnet_engine_top");
        for gone in [
            "input  wire        start,",
            "input  wire [5:0]  num_layers,",
            "input  wire signed [15:0] threshold,",
        ] {
            assert!(!v.contains(gone), "config port should be a CSR now: {gone}");
        }
        for port in [
            "input  wire [7:0]  s_axi_awaddr,",
            "input  wire [31:0] s_axi_wdata,",
            "output wire [31:0] s_axi_rdata,",
        ] {
            assert!(v.contains(port), "missing AXI-Lite port `{port}`");
        }
        // ...and the CSRs actually drive the engine.
        assert!(v.contains("assign start = reg_ctrl[0] && !dma_busy && input_loaded;"));
        assert!(v.contains("wire [5:0]  num_layers        = reg_num_layers[5:0];"));
    }

    #[test]
    fn status_ports_present() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.contains("output wire        busy,"));
        assert!(v.contains("output wire        done,"));
        assert!(v.contains("output wire [31:0] cycle_count"));
    }

    #[test]
    fn external_memory_ports_present() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.contains("output wire [31:0] mem_addr,"));
        assert!(v.contains("output wire        mem_rd_en,"));
        assert!(v.contains("input  wire [63:0] mem_rd_data,"));
        assert!(v.contains("input  wire        mem_rd_valid,"));
    }

    #[test]
    fn multilayer_sequencer_instance() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.contains("multilayer_sequencer seq ("));
        assert!(v.contains(".current_layer(current_layer)"));
        assert!(v.contains(".inference_done(done)"));
    }

    #[test]
    fn double_buffer_instance() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.contains("double_buffer_ctrl dbl_buf ("));
        assert!(v.contains(".use_buffer_a(use_buffer_a)"));
        assert!(v.contains(".neuron_id(neuron_id[11:0])"));
    }

    #[test]
    fn cycle_counter_logic() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.contains("reg  [31:0] cycles;"));
        assert!(v.contains("if (!rst_n) cycles <= 32'd0;"));
        assert!(v.contains("else if (start) cycles <= 32'd0;"));
        assert!(v.contains("else if (busy) cycles <= cycles + 32'd1;"));
        assert!(v.contains("assign cycle_count = cycles;"));
    }

    #[test]
    fn busy_derived_from_current_layer_or_layer_start() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        // busy is a registered state now, not a decode of current_layer.
        assert!(v.contains("assign busy = inference_active;"));
        assert!(v.contains("else if (start && !inference_active) inference_active <= 1'b1;"));
    }

    #[test]
    // Renamed from `external_memory_outputs_tied_off`, which asserted the
    // tie-off as if it were the contract -- the same shape as
    // dma_burst_length_is_max. mem_addr/mem_rd_en are now driven by the weight
    // prefetch controller, so the external memory port is real.
    fn external_memory_port_is_driven_by_prefetch() {
        let v = build_bitnet_engine_top("bitnet_engine_top");
        assert!(!v.contains("assign mem_addr  = 32'd0;"));
        assert!(!v.contains("assign mem_rd_en = 1'b0;"));
        assert!(v.contains("assign mem_addr  = pf_araddr;"));
        assert!(v.contains("assign mem_rd_en = pf_arvalid;"));
    }

    #[test]
    fn module_ends_with_endmodule() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.trim_end().ends_with("endmodule"));
    }

    #[test]
    fn emitted_text_is_pure_ascii() {
        let v = build_bitnet_engine_top(DEFAULT_BITNET_ENGINE_TOP_NAME);
        assert!(v.is_ascii(), "emitted Verilog must be ASCII");
    }

    // Wave 27. The first cross-layer properties: everything before them held
    // inside one module or one layer. `a_buffer_alternates` proves the
    // ping-pong really does swap at a layer boundary, so the buffer layer N
    // wrote is the buffer layer N+1 reads. `a_no_read_before_write` REFUTES and
    // sits behind its own guard on purpose -- see Prop. 25. These pin the
    // arrangement, not the outcome: the outcome is gated in formal-yosys.yml.
    #[test]
    fn cross_layer_properties_are_emitted() {
        let v = build_bitnet_engine_top("bitnet_engine_top");
        assert!(v.contains("a_buffer_alternates: assert (use_buffer_a == !$past(use_buffer_a));"));
        assert!(v.contains("a_no_read_before_write:"));
        assert!(v.contains("if (wr_en_a) fv_wrote_a <= 1'b1;"));
    }

    #[test]
    fn the_formerly_open_property_is_now_in_the_proved_set() {
        let v = build_bitnet_engine_top("bitnet_engine_top");
        // Closed in Wave 582 after eight waves open. It must NOT sit behind the
        // open guard any more, and no open guard should remain at all.
        assert!(v.contains("a_no_read_before_write:"));
        // Wave 589 gated a NEW open property (Prop. 39e, slot-level
        // read-before-write), so an open guard exists again -- deliberately.
        // What must hold is that the CLOSED property is not behind it.
        // Position ordering is the wrong test -- the closed property sits after
        // the new guard BLOCK, not inside it. What matters is containment.
        let closed_at = v.find("a_no_read_before_write:").expect("closed property present");
        if let Some(o) = v.find("`ifdef T27_FORMAL_OPEN") {
            let end = v[o..].find("`endif").expect("open guard is closed") + o;
            assert!(
                !(o..end).contains(&closed_at),
                "a_no_read_before_write closed in Wave 582 and must not sit inside the open guard"
            );
        }
    }

    // Wave 579. Prop. 29d found two write ports pairing a data/enable pair with
    // a post-increment address, so word N landed at N+1 and slot 0 was never
    // written. The activation port is the third, and was never checked. This
    // pins that the contiguity property exists; formal-yosys.yml proves it.
    #[test]
    fn activation_writes_are_checked_for_contiguity() {
        let v = build_bitnet_engine_top("bitnet_engine_top");
        assert!(v.contains("a_act_writes_contiguous: assert (act_wr_addr == fv_next_act_addr);"));
        assert!(v.contains("else if (layer_start)              fv_next_act_addr <= 12'd0;"));
        // The DMA drives its own sequence; conflating them would check neither.
        assert!(v.contains("(wr_en_a || wr_en_b) && !dma_local_we"));
    }
}
