//! BitNet HLS host-interface emitters (Wave 36d, R-BN-4).
//!
//! Currently exposes a single emitter:
//!
//!   * `axi_lite_slave` -- AMBA AXI4-Lite slave with a 16-entry,
//!     32-bit-wide control/status register (CSR) aperture used by the
//!     host CPU to program and observe the BitNet inference engine.
//!
//! CSR map (16 regs, 4 B each, total 64 B aperture):
//!
//! | Off  | Name           | Dir | Notes                              |
//! |------|----------------|-----|------------------------------------|
//! | 0x00 | CTRL           | RW  | enable / start                     |
//! | 0x04 | STATUS         | RO  | engine status                      |
//! | 0x08 | IRQ_EN         | RW  | per-cause interrupt enable         |
//! | 0x0C | IRQ_STAT       | RO  | latched interrupt causes           |
//! | 0x10 | NUM_LAYERS     | RW  | inference depth                    |
//! | 0x14 | NEURONS        | RW  | per-layer width                    |
//! | 0x18 | CHUNKS         | RW  | chunks per neuron                  |
//! | 0x1C | THRESHOLD      | RW  | ternary activation threshold       |
//! | 0x20 | WEIGHT_ADDR_LO | RW  | DDR weight base (low 32 bits)      |
//! | 0x24 | WEIGHT_ADDR_HI | RW  | DDR weight base (high 32 bits)     |
//! | 0x28 | INPUT_ADDR_LO  | RW  | DDR input base (low)               |
//! | 0x2C | INPUT_ADDR_HI  | RW  | DDR input base (high)              |
//! | 0x30 | OUTPUT_ADDR_LO | RW  | DDR output base (low)              |
//! | 0x34 | OUTPUT_ADDR_HI | RW  | DDR output base (high)             |
//! | 0x38 | CYCLES_LO      | RO  | retired cycle counter (low)        |
//! | 0x3C | CYCLES_HI      | RO  | retired cycle counter (high)       |
//!
//! Reads to unmapped offsets return `32'hDEADBEEF`. Write responses
//! always return `OKAY` (BRESP = 2'b00); read responses likewise.
//!
//! Algorithm ported from `gHashTag/vibee-lang`
//! `src/vibeec/verilog_codegen.zig` lines ~1344-1450
//! (`writeAxiLiteSlave`). Original author: Dmitrii Vasilev.
//!
//! Constitutional notes:
//!   L2: lives only under `bootstrap/`; emitter is a pure additive
//!       string builder; no edits under `gen/`, `coq/`, `trios-coq/`,
//!       `proofs/`, `specs/`, `conformance/`, `architecture/`,
//!       `rings/`, or root `Cargo.toml`.
//!   L3: ASCII source, English doc-comments only.
//!   L5: numeric kernel untouched -- this emitter is control-plane
//!       only; it does not redefine any constant inside the trinity
//!       invariant `phi^2 + 1/phi^2 = 3`.
//!   L7: no `*.sh` invoked.

/// Default identifier for the AXI-Lite slave module.
pub const DEFAULT_AXI_LITE_SLAVE_NAME: &str = "axi_lite_slave";

/// Default AXI address-bus width.
pub const DEFAULT_AXI_LITE_ADDR_WIDTH: u32 = 8;

/// Default AXI data-bus width.
pub const DEFAULT_AXI_LITE_DATA_WIDTH: u32 = 32;

fn is_valid_verilog_ident(s: &str) -> bool {
    let mut chars = s.chars();
    let first = match chars.next() {
        Some(c) => c,
        None => return false,
    };
    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn resolve_ident<'a>(candidate: &'a str, default: &'a str) -> &'a str {
    if is_valid_verilog_ident(candidate) {
        candidate
    } else {
        default
    }
}

/// Clamp a parameter into a sane integer range. Returns `default` if
/// the candidate is zero, larger than the upper bound, or otherwise
/// outside `1..=max`.
fn resolve_param(candidate: u32, default: u32, max: u32) -> u32 {
    if candidate == 0 || candidate > max {
        default
    } else {
        candidate
    }
}

/// Build the `axi_lite_slave` SystemVerilog module text.
///
/// Parameters:
///   * `module_name` -- Verilog identifier; falls back to
///     `axi_lite_slave` if invalid.
///   * `addr_width`  -- AXI address-bus width in bits. Clamped to
///     `1..=16`; defaults to 8.
///   * `data_width`  -- AXI data-bus width in bits. Clamped to
///     `1..=64`; defaults to 32. (The CSR map itself is always 32-bit
///     wide; `data_width` only sets the AXI port width.)
pub fn build_axi_lite_slave(module_name: &str, addr_width: u32, data_width: u32) -> String {
    let name = resolve_ident(module_name, DEFAULT_AXI_LITE_SLAVE_NAME);
    let aw = resolve_param(addr_width, DEFAULT_AXI_LITE_ADDR_WIDTH, 16);
    let dw = resolve_param(data_width, DEFAULT_AXI_LITE_DATA_WIDTH, 64);
    let mut s = String::new();

    s.push_str("// ===========================================================================\n");
    s.push_str("// AXI-LITE SLAVE - Control/Status Register Interface\n");
    s.push_str("// ===========================================================================\n");
    s.push_str("// Generated by t27c gen-axi-lite-slave (Wave 36d, R-BN-4).\n");
    s.push_str("// Host-facing CSR aperture for the BitNet HLS pipeline.\n");
    s.push_str("// 16 registers x 4 bytes = 64-byte aperture. Word-aligned\n");
    s.push_str("// AXI accesses are decoded from awaddr[5:2] / araddr[5:2].\n");
    s.push_str("// Unmapped reads return 32'hDEADBEEF. All responses OKAY.\n");
    s.push_str("\n");

    s.push_str(&format!("module {} #(\n", name));
    s.push_str(&format!("    parameter ADDR_WIDTH = {},\n", aw));
    s.push_str(&format!("    parameter DATA_WIDTH = {}\n", dw));
    s.push_str(") (\n");
    s.push_str("    input  wire                    clk,\n");
    s.push_str("    input  wire                    rst_n,\n");
    s.push_str("    // AXI-Lite Write Address channel\n");
    s.push_str("    input  wire [ADDR_WIDTH-1:0]   s_axi_awaddr,\n");
    s.push_str("    input  wire                    s_axi_awvalid,\n");
    s.push_str("    output reg                     s_axi_awready,\n");
    s.push_str("    // AXI-Lite Write Data channel\n");
    s.push_str("    input  wire [DATA_WIDTH-1:0]   s_axi_wdata,\n");
    s.push_str("    input  wire [3:0]              s_axi_wstrb,\n");
    s.push_str("    input  wire                    s_axi_wvalid,\n");
    s.push_str("    output reg                     s_axi_wready,\n");
    s.push_str("    // AXI-Lite Write Response channel\n");
    s.push_str("    output reg  [1:0]              s_axi_bresp,\n");
    s.push_str("    output reg                     s_axi_bvalid,\n");
    s.push_str("    input  wire                    s_axi_bready,\n");
    s.push_str("    // AXI-Lite Read Address channel\n");
    s.push_str("    input  wire [ADDR_WIDTH-1:0]   s_axi_araddr,\n");
    s.push_str("    input  wire                    s_axi_arvalid,\n");
    s.push_str("    output reg                     s_axi_arready,\n");
    s.push_str("    // AXI-Lite Read Data channel\n");
    s.push_str("    output reg  [DATA_WIDTH-1:0]   s_axi_rdata,\n");
    s.push_str("    output reg  [1:0]              s_axi_rresp,\n");
    s.push_str("    output reg                     s_axi_rvalid,\n");
    s.push_str("    input  wire                    s_axi_rready,\n");
    s.push_str("    // CSR outputs / inputs\n");
    s.push_str("    output reg  [31:0]             reg_ctrl,\n");
    s.push_str("    input  wire [31:0]             reg_status,\n");
    s.push_str("    output reg  [31:0]             reg_irq_en,\n");
    s.push_str("    input  wire [31:0]             reg_irq_stat,\n");
    s.push_str("    output reg  [31:0]             reg_num_layers,\n");
    s.push_str("    output reg  [31:0]             reg_neurons,\n");
    s.push_str("    output reg  [31:0]             reg_chunks,\n");
    s.push_str("    output reg  [31:0]             reg_threshold,\n");
    s.push_str("    output reg  [63:0]             reg_weight_addr,\n");
    s.push_str("    output reg  [63:0]             reg_input_addr,\n");
    s.push_str("    output reg  [63:0]             reg_output_addr,\n");
    s.push_str("    input  wire [63:0]             reg_cycles\n");
    s.push_str(");\n");
    s.push_str("\n");
    s.push_str("    // Strobe input tied off (word-granular writes only).\n");
    s.push_str("    wire _unused_wstrb = &{1'b0, s_axi_wstrb};\n");
    s.push_str("\n");
    s.push_str("    always @(posedge clk or negedge rst_n) begin\n");
    s.push_str("        if (!rst_n) begin\n");
    s.push_str("            s_axi_awready <= 1'b1; s_axi_wready <= 1'b1; s_axi_bvalid <= 1'b0;\n");
    s.push_str("            s_axi_arready <= 1'b1; s_axi_rvalid <= 1'b0;\n");
    s.push_str("            s_axi_bresp <= 2'b00;  s_axi_rresp <= 2'b00;\n");
    s.push_str("            reg_ctrl <= 32'd0; reg_irq_en <= 32'd0;\n");
    s.push_str("            reg_num_layers <= 32'd0; reg_neurons <= 32'd0;\n");
    s.push_str("            reg_chunks <= 32'd0; reg_threshold <= 32'd0;\n");
    s.push_str("            reg_weight_addr <= 64'd0; reg_input_addr <= 64'd0;\n");
    s.push_str("            reg_output_addr <= 64'd0;\n");
    s.push_str("            s_axi_rdata <= {DATA_WIDTH{1'b0}};\n");
    s.push_str("        end else begin\n");
    s.push_str("            // ---- Write channel --------------------------------------------\n");
    s.push_str("            // #925 fix: clear handshakes BEFORE accept so a same-cycle\n");
    s.push_str("            // (accept + BREADY/RREADY) race lets the accept NBA win; the\n");
    s.push_str("            // response is never silently dropped and the master never hangs.\n");
    s.push_str("            // #1968 fix: this module holds ONE bvalid/bresp register, so it\n");
    s.push_str("            // can owe at most one write response. awready/wready drop on\n");
    s.push_str("            // accept and are restored only when that response is taken. Held\n");
    s.push_str("            // high permanently they let a second write be accepted while the\n");
    s.push_str("            // first is unanswered, merging two transactions into one B beat;\n");
    s.push_str("            // the master then waits forever for a beat nobody will send.\n");
    s.push_str("            if (s_axi_bvalid && s_axi_bready) begin\n");
    s.push_str("                s_axi_bvalid <= 1'b0;\n");
    s.push_str("                s_axi_awready <= 1'b1; s_axi_wready <= 1'b1;\n");
    s.push_str("            end\n");
    s.push_str("            if (s_axi_awvalid && s_axi_wvalid && s_axi_awready && s_axi_wready) begin\n");
    s.push_str("                case (s_axi_awaddr[5:2])\n");
    s.push_str("                    4'h0: reg_ctrl                 <= s_axi_wdata[31:0];\n");
    s.push_str("                    4'h2: reg_irq_en               <= s_axi_wdata[31:0];\n");
    s.push_str("                    4'h4: reg_num_layers           <= s_axi_wdata[31:0];\n");
    s.push_str("                    4'h5: reg_neurons              <= s_axi_wdata[31:0];\n");
    s.push_str("                    4'h6: reg_chunks               <= s_axi_wdata[31:0];\n");
    s.push_str("                    4'h7: reg_threshold            <= s_axi_wdata[31:0];\n");
    s.push_str("                    4'h8: reg_weight_addr[31:0]    <= s_axi_wdata[31:0];\n");
    s.push_str("                    4'h9: reg_weight_addr[63:32]   <= s_axi_wdata[31:0];\n");
    s.push_str("                    4'hA: reg_input_addr[31:0]     <= s_axi_wdata[31:0];\n");
    s.push_str("                    4'hB: reg_input_addr[63:32]    <= s_axi_wdata[31:0];\n");
    s.push_str("                    4'hC: reg_output_addr[31:0]    <= s_axi_wdata[31:0];\n");
    s.push_str("                    4'hD: reg_output_addr[63:32]   <= s_axi_wdata[31:0];\n");
    s.push_str("                    default: ; // no-op for RO / unmapped writes\n");
    s.push_str("                endcase\n");
    s.push_str("                s_axi_bvalid <= 1'b1; s_axi_bresp <= 2'b00;\n");
    s.push_str("                s_axi_awready <= 1'b0; s_axi_wready <= 1'b0;\n");
    s.push_str("            end\n");
    s.push_str("            // ---- Read channel ---------------------------------------------\n");
    s.push_str("            // #1968: one rvalid/rdata register, so arready drops on accept\n");
    s.push_str("            // and returns on the R handshake. Same defect, same shape.\n");
    s.push_str("            if (s_axi_rvalid && s_axi_rready) begin\n");
    s.push_str("                s_axi_rvalid <= 1'b0;\n");
    s.push_str("                s_axi_arready <= 1'b1;\n");
    s.push_str("            end\n");
    s.push_str("            if (s_axi_arvalid && s_axi_arready) begin\n");
    s.push_str("                case (s_axi_araddr[5:2])\n");
    s.push_str("                    4'h0: s_axi_rdata <= reg_ctrl;\n");
    s.push_str("                    4'h1: s_axi_rdata <= reg_status;\n");
    s.push_str("                    4'h2: s_axi_rdata <= reg_irq_en;\n");
    s.push_str("                    4'h3: s_axi_rdata <= reg_irq_stat;\n");
    s.push_str("                    4'h4: s_axi_rdata <= reg_num_layers;\n");
    s.push_str("                    4'h5: s_axi_rdata <= reg_neurons;\n");
    s.push_str("                    4'h6: s_axi_rdata <= reg_chunks;\n");
    s.push_str("                    4'h7: s_axi_rdata <= reg_threshold;\n");
    s.push_str("                    4'h8: s_axi_rdata <= reg_weight_addr[31:0];\n");
    s.push_str("                    4'h9: s_axi_rdata <= reg_weight_addr[63:32];\n");
    s.push_str("                    4'hA: s_axi_rdata <= reg_input_addr[31:0];\n");
    s.push_str("                    4'hB: s_axi_rdata <= reg_input_addr[63:32];\n");
    s.push_str("                    4'hC: s_axi_rdata <= reg_output_addr[31:0];\n");
    s.push_str("                    4'hD: s_axi_rdata <= reg_output_addr[63:32];\n");
    s.push_str("                    4'hE: s_axi_rdata <= reg_cycles[31:0];\n");
    s.push_str("                    4'hF: s_axi_rdata <= reg_cycles[63:32];\n");
    s.push_str("                    default: s_axi_rdata <= 32'hDEADBEEF;\n");
    s.push_str("                endcase\n");
    s.push_str("                s_axi_rvalid <= 1'b1; s_axi_rresp <= 2'b00;\n");
    s.push_str("                s_axi_arready <= 1'b0;\n");
    s.push_str("            end\n");
    s.push_str("        end\n");
    s.push_str("    end\n");
    s.push_str("\n");
    s.push_str("endmodule\n");

    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ident_validator_works() {
        assert!(is_valid_verilog_ident("axi_lite_slave"));
        assert!(is_valid_verilog_ident("a"));
        assert!(is_valid_verilog_ident("_x"));
        assert!(!is_valid_verilog_ident(""));
        assert!(!is_valid_verilog_ident("9foo"));
        assert!(!is_valid_verilog_ident("has space"));
        assert!(!is_valid_verilog_ident("uni\u{00e9}"));
    }

    #[test]
    fn param_resolver_clamps() {
        assert_eq!(resolve_param(0, 8, 16), 8);
        assert_eq!(resolve_param(17, 8, 16), 8);
        assert_eq!(resolve_param(12, 8, 16), 12);
        assert_eq!(resolve_param(1, 8, 16), 1);
        assert_eq!(resolve_param(16, 8, 16), 16);
    }

    #[test]
    fn axi_default_name_and_params() {
        let v = build_axi_lite_slave(DEFAULT_AXI_LITE_SLAVE_NAME, 8, 32);
        assert!(v.contains("module axi_lite_slave #("));
        assert!(v.contains("parameter ADDR_WIDTH = 8,"));
        assert!(v.contains("parameter DATA_WIDTH = 32"));
        assert!(v.contains("endmodule"));
    }

    #[test]
    fn axi_invalid_name_falls_back() {
        let v = build_axi_lite_slave("9 bad!", 8, 32);
        assert!(v.contains("module axi_lite_slave #("));
    }

    #[test]
    fn axi_custom_name_and_params() {
        let v = build_axi_lite_slave("my_csr", 12, 64);
        assert!(v.contains("module my_csr #("));
        assert!(v.contains("parameter ADDR_WIDTH = 12,"));
        assert!(v.contains("parameter DATA_WIDTH = 64"));
    }

    #[test]
    fn axi_param_clamps_to_defaults() {
        let v = build_axi_lite_slave(DEFAULT_AXI_LITE_SLAVE_NAME, 0, 99);
        assert!(v.contains("parameter ADDR_WIDTH = 8,"));
        assert!(v.contains("parameter DATA_WIDTH = 32"));
    }

    #[test]
    fn axi_has_all_write_channel_ports() {
        let v = build_axi_lite_slave(DEFAULT_AXI_LITE_SLAVE_NAME, 8, 32);
        for port in [
            "input  wire [ADDR_WIDTH-1:0]   s_axi_awaddr",
            "input  wire                    s_axi_awvalid",
            "output reg                     s_axi_awready",
            "input  wire [DATA_WIDTH-1:0]   s_axi_wdata",
            "input  wire [3:0]              s_axi_wstrb",
            "input  wire                    s_axi_wvalid",
            "output reg                     s_axi_wready",
            "output reg  [1:0]              s_axi_bresp",
            "output reg                     s_axi_bvalid",
            "input  wire                    s_axi_bready",
        ] {
            assert!(v.contains(port), "missing write-channel port `{}`", port);
        }
    }

    #[test]
    fn axi_has_all_read_channel_ports() {
        let v = build_axi_lite_slave(DEFAULT_AXI_LITE_SLAVE_NAME, 8, 32);
        for port in [
            "input  wire [ADDR_WIDTH-1:0]   s_axi_araddr",
            "input  wire                    s_axi_arvalid",
            "output reg                     s_axi_arready",
            "output reg  [DATA_WIDTH-1:0]   s_axi_rdata",
            "output reg  [1:0]              s_axi_rresp",
            "output reg                     s_axi_rvalid",
            "input  wire                    s_axi_rready",
        ] {
            assert!(v.contains(port), "missing read-channel port `{}`", port);
        }
    }

    #[test]
    fn axi_has_all_csr_ports() {
        let v = build_axi_lite_slave(DEFAULT_AXI_LITE_SLAVE_NAME, 8, 32);
        for port in [
            "output reg  [31:0]             reg_ctrl",
            "input  wire [31:0]             reg_status",
            "output reg  [31:0]             reg_irq_en",
            "input  wire [31:0]             reg_irq_stat",
            "output reg  [31:0]             reg_num_layers",
            "output reg  [31:0]             reg_neurons",
            "output reg  [31:0]             reg_chunks",
            "output reg  [31:0]             reg_threshold",
            "output reg  [63:0]             reg_weight_addr",
            "output reg  [63:0]             reg_input_addr",
            "output reg  [63:0]             reg_output_addr",
            "input  wire [63:0]             reg_cycles",
        ] {
            assert!(v.contains(port), "missing CSR port `{}`", port);
        }
    }

    #[test]
    fn axi_write_case_covers_all_writable_offsets() {
        let v = build_axi_lite_slave(DEFAULT_AXI_LITE_SLAVE_NAME, 8, 32);
        for off in [
            "4'h0: reg_ctrl",
            "4'h2: reg_irq_en",
            "4'h4: reg_num_layers",
            "4'h5: reg_neurons",
            "4'h6: reg_chunks",
            "4'h7: reg_threshold",
            "4'h8: reg_weight_addr[31:0]",
            "4'h9: reg_weight_addr[63:32]",
            "4'hA: reg_input_addr[31:0]",
            "4'hB: reg_input_addr[63:32]",
            "4'hC: reg_output_addr[31:0]",
            "4'hD: reg_output_addr[63:32]",
        ] {
            assert!(v.contains(off), "missing write case `{}`", off);
        }
    }

    #[test]
    fn axi_read_case_covers_all_readable_offsets() {
        let v = build_axi_lite_slave(DEFAULT_AXI_LITE_SLAVE_NAME, 8, 32);
        for off in [
            "4'h0: s_axi_rdata <= reg_ctrl",
            "4'h1: s_axi_rdata <= reg_status",
            "4'h2: s_axi_rdata <= reg_irq_en",
            "4'h3: s_axi_rdata <= reg_irq_stat",
            "4'hE: s_axi_rdata <= reg_cycles[31:0]",
            "4'hF: s_axi_rdata <= reg_cycles[63:32]",
        ] {
            assert!(v.contains(off), "missing read case `{}`", off);
        }
    }

    #[test]
    fn axi_unmapped_read_returns_deadbeef() {
        let v = build_axi_lite_slave(DEFAULT_AXI_LITE_SLAVE_NAME, 8, 32);
        assert!(v.contains("default: s_axi_rdata <= 32'hDEADBEEF;"));
    }

    #[test]
    fn axi_responses_are_okay() {
        let v = build_axi_lite_slave(DEFAULT_AXI_LITE_SLAVE_NAME, 8, 32);
        assert!(v.contains("s_axi_bvalid <= 1'b1; s_axi_bresp <= 2'b00;"));
        assert!(v.contains("s_axi_rvalid <= 1'b1; s_axi_rresp <= 2'b00;"));
    }

    #[test]
    fn axi_handshake_dropbacks_present() {
        let v = build_axi_lite_slave(DEFAULT_AXI_LITE_SLAVE_NAME, 8, 32);
        assert!(v.contains("if (s_axi_bvalid && s_axi_bready) begin"));
        assert!(v.contains("if (s_axi_rvalid && s_axi_rready) begin"));
        assert!(v.contains("s_axi_bvalid <= 1'b0;"));
        assert!(v.contains("s_axi_rvalid <= 1'b0;"));
    }

    // Regression for #925: the handshake clear must come BEFORE the accept that
    // raises bvalid/rvalid, so on a same-cycle (accept + BREADY/RREADY) race the
    // accept NBA wins and the response is not silently dropped (master deadlock).
    #[test]
    fn axi_clear_precedes_accept_no_deadlock() {
        let v = build_axi_lite_slave(DEFAULT_AXI_LITE_SLAVE_NAME, 8, 32);
        let b_clear = v.find("if (s_axi_bvalid && s_axi_bready) begin").unwrap();
        let b_accept = v.find("s_axi_bvalid <= 1'b1; s_axi_bresp <= 2'b00;").unwrap();
        assert!(b_clear < b_accept, "B-channel clear must precede accept (#925)");
        let r_clear = v.find("if (s_axi_rvalid && s_axi_rready) begin").unwrap();
        let r_accept = v.find("s_axi_rvalid <= 1'b1; s_axi_rresp <= 2'b00;").unwrap();
        assert!(r_clear < r_accept, "R-channel clear must precede accept (#925)");
    }

    /// Regression guard for the lost-response defect (issue 1968).
    ///
    /// `awready`, `wready` and `arready` were asserted at reset and never
    /// deasserted anywhere. The module holds exactly one `bvalid`/`bresp`
    /// register and one `rvalid`/`rdata` register, so it can owe at most one
    /// response per channel; accepting a second transaction while the first is
    /// unanswered merges two transactions into one response beat and the
    /// master waits forever for a beat that is never sent.
    ///
    /// The general shape of that defect is "a ready that has no deassertion at
    /// all", so that is what is asserted -- not the text of the current
    /// expression. A reformulation that still drops ready while a response is
    /// owed passes; pinning any ready high again fails, however it is spelled.
    #[test]
    fn axi_ready_drops_while_a_response_is_owed() {
        let v = build_axi_lite_slave(DEFAULT_AXI_LITE_SLAVE_NAME, 8, 32);
        for sig in ["s_axi_awready", "s_axi_wready", "s_axi_arready"] {
            assert!(
                v.contains(&format!("{} <= 1'b0", sig)),
                "`{}` is never deasserted: it is asserted at reset and left \
                 high, so a second transaction is accepted while the first \
                 response is still unacknowledged and one of the two responses \
                 is lost. Emitted:\n{}",
                sig,
                v
            );
        }
    }

    /// The deassertion must sit in the accept block and the reassertion in the
    /// response-handshake block -- a ready dropped and restored anywhere else
    /// (or in the wrong order) does not bound the outstanding count.
    #[test]
    fn axi_ready_release_is_tied_to_the_response_handshake() {
        let v = build_axi_lite_slave(DEFAULT_AXI_LITE_SLAVE_NAME, 8, 32);
        let b_clear = v.find("if (s_axi_bvalid && s_axi_bready) begin").unwrap();
        let w_accept = v
            .find("if (s_axi_awvalid && s_axi_wvalid && s_axi_awready && s_axi_wready) begin")
            .unwrap();
        let aw_release = v[b_clear..w_accept]
            .find("s_axi_awready <= 1'b1;")
            .expect("awready must be released inside the B handshake block");
        assert!(v[b_clear..w_accept].contains("s_axi_wready <= 1'b1;"));
        let aw_drop = v[w_accept..]
            .find("s_axi_awready <= 1'b0;")
            .expect("awready must drop inside the write-accept block");
        assert!(v[w_accept..].contains("s_axi_wready <= 1'b0;"));
        let _ = (aw_release, aw_drop);

        let r_clear = v.find("if (s_axi_rvalid && s_axi_rready) begin").unwrap();
        let r_accept = v.find("if (s_axi_arvalid && s_axi_arready) begin").unwrap();
        assert!(
            v[r_clear..r_accept].contains("s_axi_arready <= 1'b1;"),
            "arready must be released inside the R handshake block"
        );
        assert!(
            v[r_accept..].contains("s_axi_arready <= 1'b0;"),
            "arready must drop inside the read-accept block"
        );
    }

    #[test]
    fn axi_reset_initializes_all_outputs() {
        let v = build_axi_lite_slave(DEFAULT_AXI_LITE_SLAVE_NAME, 8, 32);
        // Scoped to the reset branch on purpose. Since #1968 the ready signals
        // are also assigned outside reset, so a whole-module `contains` would
        // be satisfied by the release block and would no longer notice a reset
        // line going missing.
        let start = v.find("if (!rst_n) begin").expect("reset branch");
        let end = v.find("end else begin").expect("reset branch end");
        let reset_block = &v[start..end];
        for line in [
            "s_axi_awready <= 1'b1;",
            "s_axi_wready <= 1'b1;",
            "s_axi_bvalid <= 1'b0;",
            "s_axi_arready <= 1'b1;",
            "s_axi_rvalid <= 1'b0;",
            "reg_ctrl <= 32'd0;",
            "reg_irq_en <= 32'd0;",
            "reg_weight_addr <= 64'd0;",
        ] {
            assert!(
                reset_block.contains(line),
                "missing reset line `{}` in the reset branch",
                line
            );
        }
    }

    #[test]
    fn axi_pure_ascii() {
        let v = build_axi_lite_slave(DEFAULT_AXI_LITE_SLAVE_NAME, 8, 32);
        assert!(v.is_ascii(), "emitted Verilog must be ASCII");
    }
}
