//! BitNet HLS buffering emitters (Wave 36c, R-BN-3).
//!
//! Two self-contained SystemVerilog module emitters for the BitNet
//! ternary inference engine activation/weight buffering layer:
//!
//!   * `double_buffer_ctrl` -- ping-pong activation buffer controller.
//!     Toggles `use_buffer_a` on every `layer_done` strobe so that even
//!     layers read buffer A / write buffer B, and odd layers read B /
//!     write A. The neuron_id input is forwarded as both read and write
//!     address (the layer scheduler guarantees no aliasing between the
//!     producing layer N and the consuming layer N+1, since they target
//!     opposite buffers).
//!   * `weight_prefetch_ctrl` -- DDR-to-BRAM weight streaming FSM
//!     (`IDLE`/`FETCH`/`DONE`). Issues AXI read transactions, accepts
//!     64-bit AXI words, truncates them to the BitNet 54-bit packed-
//!     trit format, and streams them into the on-chip weight BRAM at
//!     consecutive addresses while the compute pipeline runs against
//!     the previous layer's weights. `axi_rready` is hard-wired to
//!     `(state == FETCH)` per the source design.
//!
//! Algorithms ported from `gHashTag/vibee-lang`
//! `src/vibeec/verilog_codegen.zig` lines ~1187-1281
//! (`writeDoubleBufferCtrl` and `writeWeightPrefetchCtrl`).
//! Original author: Dmitrii Vasilev.
//!
//! Constitutional notes:
//!   L2: lives only under `bootstrap/`; both emitters are pure additive
//!       string builders, no edits under `gen/`, `coq/`, `trios-coq/`,
//!       `proofs/`, `specs/`, `conformance/`, `architecture/`, `rings/`,
//!       root `Cargo.toml`.
//!   L3: ASCII source, English doc-comments only.
//!   L5: numeric kernel untouched -- these emitters are control-plane
//!       only; they do not redefine any constant inside the trinity
//!       invariant `phi^2 + 1/phi^2 = 3`.
//!   L7: no `*.sh` invoked.

/// Default identifier for the ping-pong activation buffer controller.
pub const DEFAULT_DOUBLE_BUFFER_CTRL_NAME: &str = "double_buffer_ctrl";

/// Default identifier for the DDR-to-BRAM weight prefetch FSM.
pub const DEFAULT_WEIGHT_PREFETCH_CTRL_NAME: &str = "weight_prefetch_ctrl";

/// Return `true` if `s` is a syntactically valid Verilog identifier:
/// non-empty, ASCII, starts with `[A-Za-z_]`, followed by `[A-Za-z0-9_]*`.
fn is_valid_verilog_ident(s: &str) -> bool {
    let mut chars = s.chars();
    let first = match chars.next() {
        Some(c) => c,
        None => return false,
    };
    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn resolve_ident<'a>(candidate: &'a str, default: &'a str) -> &'a str {
    if is_valid_verilog_ident(candidate) {
        candidate
    } else {
        default
    }
}

/// Build the `double_buffer_ctrl` SystemVerilog module text.
///
/// The emitted module:
///   * Holds a single 1-bit register `use_buffer_a` that toggles on
///     every `layer_done` pulse. Reset state: `1` (so layer 0 reads
///     buffer A, writes buffer B -- matching the vibee-lang convention).
///   * Forwards `neuron_id` to both `read_addr` and `write_addr` via
///     combinational `assign`. Address widths are fixed at 12 bits to
///     match `weight_bram` (W36a) default depth = 4096.
///   * Accepts an unused `current_layer[5:0]` input for forward-
///     compatibility with multi-layer schedulers (W36d / `multilayer_
///     sequencer`); the controller itself does not need the layer id
///     because it toggles purely off `layer_done`.
pub fn build_double_buffer_ctrl(module_name: &str) -> String {
    let name = resolve_ident(module_name, DEFAULT_DOUBLE_BUFFER_CTRL_NAME);
    let mut s = String::new();

    s.push_str("// ===========================================================================\n");
    s.push_str("// DOUBLE BUFFER CONTROLLER - Ping-pong activation buffers\n");
    s.push_str("// ===========================================================================\n");
    s.push_str("// Generated by t27c gen-double-buffer-ctrl (Wave 36c, R-BN-3).\n");
    s.push_str("// Toggles `use_buffer_a` on every `layer_done` strobe. Even layers\n");
    s.push_str("// read buffer A / write buffer B; odd layers read B / write A.\n");
    s.push_str("// Reset state: use_buffer_a = 1 (layer 0 reads A, writes B).\n");
    s.push_str("\n");

    s.push_str(&format!("module {} (\n", name));
    s.push_str("    input  wire        clk,\n");
    s.push_str("    input  wire        rst_n,\n");
    s.push_str("    input  wire        layer_done,\n");
    s.push_str("    input  wire [5:0]  current_layer,\n");
    s.push_str("    output reg         use_buffer_a,\n");
    s.push_str("    output wire [11:0] read_addr,\n");
    s.push_str("    output wire [11:0] write_addr,\n");
    s.push_str("    input  wire [11:0] neuron_id\n");
    s.push_str(");\n");
    s.push_str("\n");
    s.push_str("    // Tie unused forward-compatibility port to suppress lint warnings.\n");
    s.push_str("    wire _unused_current_layer = &{1'b0, current_layer};\n");
    s.push_str("\n");
    s.push_str("    // Even layers: read A, write B.\n");
    s.push_str("    // Odd layers: read B, write A.\n");
    s.push_str("    always @(posedge clk or negedge rst_n) begin\n");
    s.push_str("        if (!rst_n) use_buffer_a <= 1'b1;\n");
    s.push_str("        else if (layer_done) use_buffer_a <= ~use_buffer_a;\n");
    s.push_str("    end\n");
    s.push_str("\n");
    s.push_str("    assign read_addr  = neuron_id;\n");
    s.push_str("    assign write_addr = neuron_id;\n");
    s.push_str("\n");
    s.push_str("endmodule\n");

    s
}

/// Build the `weight_prefetch_ctrl` SystemVerilog module text.
///
/// The emitted module:
///   * Three-state FSM: `IDLE` (waits for `start_prefetch`), `FETCH`
///     (issues AXI reads + writes 54-bit packed-trit words into the
///     on-chip BRAM), `DONE` (one-cycle pulse on `prefetch_done`, then
///     returns to `IDLE`).
///   * Truncates incoming 64-bit AXI words to 54 bits to match the
///     `weight_bram` (W36a) default data width.
///   * Hard-wires `axi_rready = (state == FETCH)` per the source
///     design; `axi_araddr` advances by 8 bytes per accepted AR beat.
///   * `bram_addr` starts at 0 and increments per accepted R beat;
///     `bram_we` is single-cycle per word.
pub fn build_weight_prefetch_ctrl(module_name: &str) -> String {
    let name = resolve_ident(module_name, DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
    let mut s = String::new();

    s.push_str("// ===========================================================================\n");
    s.push_str("// WEIGHT PREFETCH CONTROLLER - Stream weights from DDR into on-chip BRAM\n");
    s.push_str("// ===========================================================================\n");
    s.push_str("// Generated by t27c gen-weight-prefetch-ctrl (Wave 36c, R-BN-3).\n");
    s.push_str("// Three-state FSM (IDLE/FETCH/DONE). Issues AXI reads, truncates\n");
    s.push_str("// 64-bit AXI words to 54-bit BitNet packed-trit format, and writes\n");
    s.push_str("// them into the weight BRAM at consecutive addresses while the\n");
    s.push_str("// compute pipeline runs against the previous layer's weights.\n");
    s.push_str("\n");

    s.push_str(&format!("module {} (\n", name));
    s.push_str("    input  wire        clk,\n");
    s.push_str("    input  wire        rst_n,\n");
    s.push_str("    input  wire        start_prefetch,\n");
    s.push_str("    input  wire [31:0] src_addr,\n");
    s.push_str("    input  wire [15:0] num_words,\n");
    s.push_str("    output reg         prefetch_active,\n");
    s.push_str("    output reg         prefetch_done,\n");
    s.push_str("    // AXI read interface\n");
    s.push_str("    output reg  [31:0] axi_araddr,\n");
    s.push_str("    output reg         axi_arvalid,\n");
    s.push_str("    input  wire        axi_arready,\n");
    s.push_str("    input  wire [63:0] axi_rdata,\n");
    s.push_str("    input  wire        axi_rvalid,\n");
    s.push_str("    output wire        axi_rready,\n");
    s.push_str("    // BRAM write interface\n");
    s.push_str("    output reg  [11:0] bram_addr,\n");
    s.push_str("    output reg  [53:0] bram_data,\n");
    s.push_str("    output reg         bram_we\n");
    s.push_str(");\n");
    s.push_str("\n");
    s.push_str("    reg [15:0] words_remaining;\n");
    s.push_str("    localparam IDLE = 2'd0, FETCH = 2'd1, DONE_ST = 2'd2;\n");
    s.push_str("    reg [1:0] state;\n");
    s.push_str("\n");
    s.push_str("    assign axi_rready = (state == FETCH);\n");
    s.push_str("\n");
    s.push_str("    always @(posedge clk or negedge rst_n) begin\n");
    s.push_str("        if (!rst_n) begin\n");
    s.push_str("            state <= IDLE; prefetch_active <= 1'b0; prefetch_done <= 1'b0;\n");
    s.push_str("            axi_arvalid <= 1'b0; bram_we <= 1'b0;\n");
    s.push_str("            axi_araddr <= 32'd0; bram_addr <= 12'd0; bram_data <= 54'd0;\n");
    s.push_str("            words_remaining <= 16'd0;\n");
    s.push_str("        end else case (state)\n");
    s.push_str("            // A zero-word prefetch moves nothing. Without this guard\n");
    s.push_str("            // words_remaining underflows to 16'hFFFF on the first beat, the\n");
    s.push_str("            // `words_remaining == 1` terminator never matches, and the\n");
    s.push_str("            // controller writes BRAM indefinitely. Yosys refuted\n");
    s.push_str("            // `writes <= num_words` from a reachable state; with num_words > 0\n");
    s.push_str("            // assumed it proves. See FORMAL_FOUNDATIONS Prop. 13.\n");
    s.push_str("            IDLE: if (start_prefetch && (num_words != 16'd0)) begin\n");
    s.push_str("                state <= FETCH; prefetch_active <= 1'b1; prefetch_done <= 1'b0;\n");
    s.push_str("                axi_araddr <= src_addr;\n");
    s.push_str("                words_remaining <= num_words;\n");
    s.push_str("                bram_addr <= 12'd0;\n");
    s.push_str("            end\n");
    s.push_str("            FETCH: begin\n");
    s.push_str("                axi_arvalid <= 1'b1;\n");
    s.push_str("                if (axi_arready) axi_araddr <= axi_araddr + 32'd8;\n");
    s.push_str("                if (axi_rvalid) begin\n");
    s.push_str("                    bram_data <= axi_rdata[53:0];\n");
    s.push_str("                    bram_we <= 1'b1;\n");
    s.push_str("                    bram_addr <= bram_addr + 12'd1;\n");
    s.push_str("                    words_remaining <= words_remaining - 16'd1;\n");
    s.push_str("                    if (words_remaining == 16'd1) state <= DONE_ST;\n");
    s.push_str("                end else bram_we <= 1'b0;\n");
    s.push_str("            end\n");
    s.push_str("            DONE_ST: begin\n");
    s.push_str("                prefetch_active <= 1'b0;\n");
    s.push_str("                prefetch_done   <= 1'b1;\n");
    s.push_str("                axi_arvalid     <= 1'b0;\n");
    s.push_str("                bram_we         <= 1'b0;\n");
    s.push_str("                state           <= IDLE;\n");
    s.push_str("            end\n");
    s.push_str("            default: state <= IDLE;\n");
    s.push_str("        endcase\n");
    s.push_str("    end\n");
    s.push_str("\n");
    s.push_str("endmodule\n");

    s
}

#[cfg(test)]
mod tests {
    use super::*;

    // ----- ident validator -----------------------------------------------

    #[test]
    fn ident_validator_accepts_basic() {
        assert!(is_valid_verilog_ident("double_buffer_ctrl"));
        assert!(is_valid_verilog_ident("weight_prefetch_ctrl"));
        assert!(is_valid_verilog_ident("a"));
        assert!(is_valid_verilog_ident("_x"));
        assert!(is_valid_verilog_ident("X9"));
    }

    #[test]
    fn ident_validator_rejects_bad() {
        assert!(!is_valid_verilog_ident(""));
        assert!(!is_valid_verilog_ident("9foo"));
        assert!(!is_valid_verilog_ident("has space"));
        assert!(!is_valid_verilog_ident("dash-name"));
        assert!(!is_valid_verilog_ident("uni\u{00e9}"));
    }

    #[test]
    fn resolve_ident_falls_back_on_invalid() {
        assert_eq!(resolve_ident("9bad", "ok"), "ok");
        assert_eq!(resolve_ident("good", "ok"), "good");
    }

    // ----- double_buffer_ctrl --------------------------------------------

    #[test]
    fn double_buffer_default_name() {
        let v = build_double_buffer_ctrl(DEFAULT_DOUBLE_BUFFER_CTRL_NAME);
        assert!(v.contains("module double_buffer_ctrl ("));
        assert!(v.contains("endmodule"));
    }

    #[test]
    fn double_buffer_invalid_name_falls_back() {
        let v = build_double_buffer_ctrl("9 bad name");
        assert!(v.contains("module double_buffer_ctrl ("));
    }

    #[test]
    fn double_buffer_custom_name() {
        let v = build_double_buffer_ctrl("my_dbuf");
        assert!(v.contains("module my_dbuf ("));
    }

    #[test]
    fn double_buffer_has_all_ports() {
        let v = build_double_buffer_ctrl(DEFAULT_DOUBLE_BUFFER_CTRL_NAME);
        for port in [
            "input  wire        clk",
            "input  wire        rst_n",
            "input  wire        layer_done",
            "input  wire [5:0]  current_layer",
            "output reg         use_buffer_a",
            "output wire [11:0] read_addr",
            "output wire [11:0] write_addr",
            "input  wire [11:0] neuron_id",
        ] {
            assert!(v.contains(port), "missing port `{}`", port);
        }
    }

    #[test]
    fn double_buffer_toggles_on_layer_done() {
        let v = build_double_buffer_ctrl(DEFAULT_DOUBLE_BUFFER_CTRL_NAME);
        assert!(v.contains("if (!rst_n) use_buffer_a <= 1'b1;"));
        assert!(v.contains("else if (layer_done) use_buffer_a <= ~use_buffer_a;"));
    }

    #[test]
    fn double_buffer_addr_assigns() {
        let v = build_double_buffer_ctrl(DEFAULT_DOUBLE_BUFFER_CTRL_NAME);
        assert!(v.contains("assign read_addr  = neuron_id;"));
        assert!(v.contains("assign write_addr = neuron_id;"));
    }

    #[test]
    fn double_buffer_pure_ascii() {
        let v = build_double_buffer_ctrl(DEFAULT_DOUBLE_BUFFER_CTRL_NAME);
        assert!(v.is_ascii(), "emitted Verilog must be ASCII");
    }

    // ----- weight_prefetch_ctrl ------------------------------------------

    #[test]
    fn prefetch_default_name() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        assert!(v.contains("module weight_prefetch_ctrl ("));
        assert!(v.contains("endmodule"));
    }

    #[test]
    fn prefetch_invalid_name_falls_back() {
        let v = build_weight_prefetch_ctrl("bad name!");
        assert!(v.contains("module weight_prefetch_ctrl ("));
    }

    #[test]
    fn prefetch_custom_name() {
        let v = build_weight_prefetch_ctrl("my_pfetch");
        assert!(v.contains("module my_pfetch ("));
    }

    #[test]
    fn prefetch_has_all_axi_ports() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        for port in [
            "output reg  [31:0] axi_araddr",
            "output reg         axi_arvalid",
            "input  wire        axi_arready",
            "input  wire [63:0] axi_rdata",
            "input  wire        axi_rvalid",
            "output wire        axi_rready",
        ] {
            assert!(v.contains(port), "missing axi port `{}`", port);
        }
    }

    #[test]
    fn prefetch_has_all_bram_ports() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        for port in [
            "output reg  [11:0] bram_addr",
            "output reg  [53:0] bram_data",
            "output reg         bram_we",
        ] {
            assert!(v.contains(port), "missing bram port `{}`", port);
        }
    }

    #[test]
    fn prefetch_has_control_ports() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        for port in [
            "input  wire        start_prefetch",
            "input  wire [31:0] src_addr",
            "input  wire [15:0] num_words",
            "output reg         prefetch_active",
            "output reg         prefetch_done",
        ] {
            assert!(v.contains(port), "missing ctrl port `{}`", port);
        }
    }

    #[test]
    fn prefetch_fsm_states_present() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        assert!(v.contains("localparam IDLE = 2'd0, FETCH = 2'd1, DONE_ST = 2'd2;"));
        // Was pinning the unguarded form, which is what let a zero-word
        // prefetch underflow and write BRAM forever.
        assert!(v.contains("IDLE: if (start_prefetch && (num_words != 16'd0)) begin"));
        assert!(v.contains("FETCH: begin"));
        assert!(v.contains("DONE_ST: begin"));
    }

    #[test]
    fn prefetch_rready_combinational() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        assert!(v.contains("assign axi_rready = (state == FETCH);"));
    }

    #[test]
    fn prefetch_advances_axi_araddr_by_8() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        assert!(v.contains("if (axi_arready) axi_araddr <= axi_araddr + 32'd8;"));
    }

    #[test]
    fn prefetch_truncates_axi_to_54_bits() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        assert!(v.contains("bram_data <= axi_rdata[53:0];"));
    }

    #[test]
    fn prefetch_pure_ascii() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        assert!(v.is_ascii(), "emitted Verilog must be ASCII");
    }

    #[test]
    fn prefetch_reset_block_initializes_all_regs() {
        let v = build_weight_prefetch_ctrl(DEFAULT_WEIGHT_PREFETCH_CTRL_NAME);
        for line in [
            "state <= IDLE;",
            "prefetch_active <= 1'b0;",
            "prefetch_done <= 1'b0;",
            "axi_arvalid <= 1'b0;",
            "bram_we <= 1'b0;",
        ] {
            assert!(v.contains(line), "missing reset line `{}`", line);
        }
    }
}
