//! BitNet HLS DMA-controller emitter (Wave 36e, R-BN-5).
//!
//! Exposes a single emitter:
//!
//!   * `dma_controller` -- an AXI4 master DMA engine that streams
//!     bulk activation/weight data between an off-chip DDR backing
//!     store and an on-chip BRAM (or any local 64-bit-wide memory).
//!
//! Port summary:
//!
//! | Group                | Signals                                                |
//! |----------------------|--------------------------------------------------------|
//! | Control              | start, src_addr[63:0], dst_addr[63:0], length[31:0],   |
//! |                      | direction (0=read DDR->local, 1=write local->DDR),     |
//! |                      | busy, done                                             |
//! | AXI4 master read     | araddr[63:0], arlen[7:0], arvalid, arready,            |
//! |                      | rdata[63:0], rlast, rvalid, rready                     |
//! | AXI4 master write    | awaddr[63:0], awlen[7:0], awvalid, awready,            |
//! |                      | wdata[63:0], wlast, wvalid, wready, bvalid, bready     |
//! | Local memory         | local_addr[11:0], local_wdata[63:0], local_we,         |
//! |                      | local_rdata[63:0]                                      |
//!
//! State machine (6 states):
//!
//!   IDLE -> READ_ADDR  -> READ_DATA  -> DONE_ST -> IDLE   (direction = 0)
//!   IDLE -> WRITE_ADDR -> WRITE_DATA -> DONE_ST -> IDLE   (direction = 1)
//!
//! Each beat moves 8 bytes (one 64-bit word). `bytes_remaining`
//! starts at `length` and is decremented by 8 every accepted beat;
//! the transfer terminates when it reaches the last word or the AXI
//! peer asserts `rlast`. `local_addr` autoincrements per beat.
//!
//! Algorithm ported from `gHashTag/vibee-lang`
//! `src/vibeec/verilog_codegen.zig` lines 1452-1548
//! (`writeDmaController`). Original author: Dmitrii Vasilev.
//!
//! Constitutional notes:
//!   L2: lives only under `bootstrap/`; emitter is a pure additive
//!       string builder; no edits under `gen/`, `coq/`, `trios-coq/`,
//!       `proofs/`, `specs/`, `conformance/`, `architecture/`,
//!       `rings/`, or root `Cargo.toml`.
//!   L3: ASCII source, English doc-comments only.
//!   L5: numeric kernel untouched -- this emitter is a data-mover;
//!       it does not redefine any constant inside the trinity
//!       invariant `phi^2 + 1/phi^2 = 3`.
//!   L7: no `*.sh` invoked.

/// Default identifier for the DMA-controller module.
pub const DEFAULT_DMA_CONTROLLER_NAME: &str = "dma_controller";

fn is_valid_verilog_ident(s: &str) -> bool {
    let mut chars = s.chars();
    let first = match chars.next() {
        Some(c) => c,
        None => return false,
    };
    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn resolve_ident<'a>(candidate: &'a str, default: &'a str) -> &'a str {
    if is_valid_verilog_ident(candidate) {
        candidate
    } else {
        default
    }
}

/// Build the `dma_controller` SystemVerilog module text.
///
/// Parameters:
///   * `module_name` -- Verilog identifier; falls back to
///     `dma_controller` if the candidate is not a valid Verilog
///     identifier (must start with `[A-Za-z_]` and contain only
///     `[A-Za-z0-9_]`).
pub fn build_dma_controller(module_name: &str) -> String {
    let name = resolve_ident(module_name, DEFAULT_DMA_CONTROLLER_NAME);
    let mut s = String::new();

    s.push_str("// ===========================================================================\n");
    s.push_str("// DMA CONTROLLER - High-bandwidth data transfer\n");
    s.push_str("// ===========================================================================\n");
    s.push_str("// Generated by t27c gen-dma-controller (Wave 36e, R-BN-5).\n");
    s.push_str("// AXI4 master DMA between off-chip DDR and on-chip local memory.\n");
    s.push_str("// direction = 0 -> DDR (src_addr) read into local memory.\n");
    s.push_str("// direction = 1 -> local memory written out to DDR (dst_addr).\n");
    s.push_str("// One beat = 8 bytes (64-bit). length is byte-count.\n");
    s.push_str("\n");

    s.push_str(&format!("module {} (\n", name));
    s.push_str("    input  wire        clk,\n");
    s.push_str("    input  wire        rst_n,\n");
    s.push_str("    // Control\n");
    s.push_str("    input  wire        start,\n");
    s.push_str("    input  wire [63:0] src_addr,\n");
    s.push_str("    input  wire [63:0] dst_addr,\n");
    s.push_str("    input  wire [31:0] length,\n");
    s.push_str("    input  wire        direction,  // 0=read, 1=write\n");
    s.push_str("    output reg         busy,\n");
    s.push_str("    output reg         done,\n");
    // Raised for the whole of a transfer whose `length` exceeded the local
    // address space and was therefore clamped. Without it a clamp would turn
    // silent corruption into a silent short transfer: the host would still be
    // told `done` and would still have no way to learn that the tail of its
    // request was dropped. Held until the next `start` re-evaluates it.
    s.push_str("    output reg         overflow,\n");
    s.push_str("    // AXI4 Master Read\n");
    s.push_str("    output reg  [63:0] m_axi_araddr,\n");
    s.push_str("    output reg  [7:0]  m_axi_arlen,\n");
    s.push_str("    output reg         m_axi_arvalid,\n");
    s.push_str("    input  wire        m_axi_arready,\n");
    s.push_str("    input  wire [63:0] m_axi_rdata,\n");
    s.push_str("    input  wire        m_axi_rlast,\n");
    s.push_str("    input  wire        m_axi_rvalid,\n");
    s.push_str("    output wire        m_axi_rready,\n");
    s.push_str("    // AXI4 Master Write\n");
    s.push_str("    output reg  [63:0] m_axi_awaddr,\n");
    s.push_str("    output reg  [7:0]  m_axi_awlen,\n");
    s.push_str("    output reg         m_axi_awvalid,\n");
    s.push_str("    input  wire        m_axi_awready,\n");
    s.push_str("    output reg  [63:0] m_axi_wdata,\n");
    s.push_str("    output reg         m_axi_wlast,\n");
    s.push_str("    output reg         m_axi_wvalid,\n");
    s.push_str("    input  wire        m_axi_wready,\n");
    s.push_str("    input  wire        m_axi_bvalid,\n");
    s.push_str("    output wire        m_axi_bready,\n");
    s.push_str("    // Local memory interface\n");
    s.push_str("    output reg  [11:0] local_addr,\n");
    s.push_str("    output reg  [63:0] local_wdata,\n");
    s.push_str("    output reg         local_we,\n");
    s.push_str("    input  wire [63:0] local_rdata\n");
    s.push_str(");\n");
    s.push_str("\n");

    s.push_str("    localparam IDLE       = 3'd0;\n");
    s.push_str("    localparam READ_ADDR  = 3'd1;\n");
    s.push_str("    localparam READ_DATA  = 3'd2;\n");
    s.push_str("    localparam WRITE_ADDR = 3'd3;\n");
    s.push_str("    localparam WRITE_DATA = 3'd4;\n");
    s.push_str("    localparam DONE_ST    = 3'd5;\n");
    s.push_str("    reg [2:0]  state;\n");
    s.push_str("    reg [31:0] bytes_remaining;\n");
    s.push_str("    reg [7:0]  burst_count;\n");
    // Index of the beat currently being captured. `local_addr` is driven from
    // this value, not from `local_addr + 1`, so the address presented to the
    // local memory belongs to the same beat as `local_wdata` and `local_we`.
    s.push_str("    reg [11:0] beat_index;\n");
    // The local memory holds 4096 words of 8 bytes: 32768 bytes is the whole
    // of it. `length` is 32 bits, so a request can name 2**29 beats against a
    // 2**12-entry address space -- a 131072x overrange, not a corner case.
    s.push_str("    localparam [31:0] MAX_BYTES = 32'd32768;  // 4096 words x 8 bytes\n");
    s.push_str("\n");

    s.push_str("    assign m_axi_rready = (state == READ_DATA);\n");
    s.push_str("    assign m_axi_bready = 1'b1;\n");
    s.push_str("\n");

    s.push_str("    always @(posedge clk or negedge rst_n) begin\n");
    s.push_str("        if (!rst_n) begin\n");
    s.push_str("            state          <= IDLE;\n");
    s.push_str("            busy           <= 1'b0;\n");
    s.push_str("            done           <= 1'b0;\n");
    s.push_str("            m_axi_arvalid  <= 1'b0;\n");
    s.push_str("            m_axi_awvalid  <= 1'b0;\n");
    s.push_str("            m_axi_wvalid   <= 1'b0;\n");
    s.push_str("            m_axi_wlast    <= 1'b0;\n");
    s.push_str("            m_axi_araddr   <= 64'd0;\n");
    s.push_str("            m_axi_awaddr   <= 64'd0;\n");
    s.push_str("            m_axi_arlen    <= 8'd0;\n");
    s.push_str("            m_axi_awlen    <= 8'd0;\n");
    s.push_str("            m_axi_wdata    <= 64'd0;\n");
    s.push_str("            local_we       <= 1'b0;\n");
    s.push_str("            local_addr     <= 12'd0;\n");
    s.push_str("            local_wdata    <= 64'd0;\n");
    s.push_str("            bytes_remaining <= 32'd0;\n");
    s.push_str("            burst_count    <= 8'd0;\n");
    s.push_str("            beat_index     <= 12'd0;\n");
    s.push_str("            overflow       <= 1'b0;\n");
    s.push_str("        end else begin\n");
    // `local_we` is a one-cycle write strobe, not a level. Defaulting it low
    // ahead of the case means any state that does not explicitly drive it
    // leaves it low, so the strobe cannot persist into a state it does not
    // belong to (READ_ADDR between bursts, IDLE, WRITE_*).
    s.push_str("            local_we <= 1'b0;\n");
    s.push_str("            case (state)\n");
    s.push_str("            IDLE: if (start) begin\n");
    s.push_str("                busy            <= 1'b1;\n");
    s.push_str("                done            <= 1'b0;\n");
    // Clamp, and say so. `bytes_remaining` is the only thing that bounds the
    // beat counter, so bounding it here bounds `local_addr` for both the read
    // path (`beat_index`) and the write path (`local_addr + 1`) at once.
    s.push_str("                bytes_remaining <= (length > MAX_BYTES) ? MAX_BYTES : length;\n");
    s.push_str("                overflow        <= (length > MAX_BYTES);\n");
    s.push_str("                local_addr      <= 12'd0;\n");
    s.push_str("                beat_index      <= 12'd0;\n");
    s.push_str("                state           <= direction ? WRITE_ADDR : READ_ADDR;\n");
    s.push_str("                if (!direction) begin\n");
    s.push_str("                    m_axi_araddr <= src_addr;\n");
    s.push_str("                    m_axi_arlen  <= 8'hFF;\n");
    s.push_str("                end else begin\n");
    s.push_str("                    m_axi_awaddr <= dst_addr;\n");
    s.push_str("                    m_axi_awlen  <= 8'hFF;\n");
    s.push_str("                end\n");
    s.push_str("            end\n");
    s.push_str("            READ_ADDR: begin\n");
    s.push_str("                m_axi_arvalid <= 1'b1;\n");
    s.push_str("                if (m_axi_arready) begin\n");
    s.push_str("                    m_axi_arvalid <= 1'b0;\n");
    s.push_str("                    state         <= READ_DATA;\n");
    s.push_str("                end\n");
    s.push_str("            end\n");
    s.push_str("            READ_DATA: if (m_axi_rvalid) begin\n");
    s.push_str("                local_wdata     <= m_axi_rdata;\n");
    s.push_str("                local_we        <= 1'b1;\n");
    s.push_str("                local_addr      <= beat_index;\n");
    s.push_str("                beat_index      <= beat_index + 12'd1;\n");
    s.push_str("                bytes_remaining <= bytes_remaining - 32'd8;\n");
    s.push_str("                if (m_axi_rlast || bytes_remaining <= 32'd8) state <= DONE_ST;\n");
    s.push_str("            end else local_we <= 1'b0;\n");
    s.push_str("            WRITE_ADDR: begin\n");
    s.push_str("                m_axi_awvalid <= 1'b1;\n");
    s.push_str("                if (m_axi_awready) begin\n");
    s.push_str("                    m_axi_awvalid <= 1'b0;\n");
    s.push_str("                    state         <= WRITE_DATA;\n");
    s.push_str("                    burst_count   <= 8'd0;\n");
    s.push_str("                end\n");
    s.push_str("            end\n");
    s.push_str("            WRITE_DATA: begin\n");
    s.push_str("                m_axi_wdata  <= local_rdata;\n");
    s.push_str("                m_axi_wvalid <= 1'b1;\n");
    s.push_str("                m_axi_wlast  <= (bytes_remaining <= 32'd8);\n");
    s.push_str("                if (m_axi_wready) begin\n");
    s.push_str("                    local_addr      <= local_addr + 12'd1;\n");
    s.push_str("                    bytes_remaining <= bytes_remaining - 32'd8;\n");
    s.push_str("                    if (bytes_remaining <= 32'd8) begin\n");
    s.push_str("                        m_axi_wvalid <= 1'b0;\n");
    s.push_str("                        state        <= DONE_ST;\n");
    s.push_str("                    end\n");
    s.push_str("                end\n");
    s.push_str("            end\n");
    s.push_str("            DONE_ST: begin\n");
    s.push_str("                busy     <= 1'b0;\n");
    s.push_str("                done     <= 1'b1;\n");
    s.push_str("                local_we <= 1'b0;\n");
    s.push_str("                state    <= IDLE;\n");
    s.push_str("            end\n");
    s.push_str("            default: state <= IDLE;\n");
    s.push_str("            endcase\n");
    s.push_str("        end\n");
    s.push_str("    end\n");
    s.push_str("\n");

    s.push_str("endmodule\n");

    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ident_validator_basics() {
        assert!(is_valid_verilog_ident("dma_controller"));
        assert!(is_valid_verilog_ident("a"));
        assert!(is_valid_verilog_ident("_x"));
        assert!(is_valid_verilog_ident("Foo123"));
        assert!(!is_valid_verilog_ident(""));
        assert!(!is_valid_verilog_ident("9foo"));
        assert!(!is_valid_verilog_ident("has space"));
        assert!(!is_valid_verilog_ident("dash-name"));
        assert!(!is_valid_verilog_ident("uni\u{00e9}"));
    }

    #[test]
    fn default_name_used_when_invalid() {
        let v = build_dma_controller("");
        assert!(v.contains("module dma_controller ("));
        let v2 = build_dma_controller("9bad");
        assert!(v2.contains("module dma_controller ("));
        let v3 = build_dma_controller("has space");
        assert!(v3.contains("module dma_controller ("));
    }

    #[test]
    fn custom_name_propagates() {
        let v = build_dma_controller("dma_ddr_to_bram");
        assert!(v.contains("module dma_ddr_to_bram ("));
        assert!(!v.contains("module dma_controller ("));
    }

    #[test]
    fn all_six_states_emitted() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        for st in [
            "IDLE",
            "READ_ADDR",
            "READ_DATA",
            "WRITE_ADDR",
            "WRITE_DATA",
            "DONE_ST",
        ] {
            assert!(v.contains(&format!("localparam {}", st)), "missing localparam {}", st);
        }
    }

    #[test]
    fn axi_read_channel_ports_present() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        for port in [
            "m_axi_araddr",
            "m_axi_arlen",
            "m_axi_arvalid",
            "m_axi_arready",
            "m_axi_rdata",
            "m_axi_rlast",
            "m_axi_rvalid",
            "m_axi_rready",
        ] {
            assert!(v.contains(port), "missing AXI-read port `{}`", port);
        }
    }

    #[test]
    fn axi_write_channel_ports_present() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        for port in [
            "m_axi_awaddr",
            "m_axi_awlen",
            "m_axi_awvalid",
            "m_axi_awready",
            "m_axi_wdata",
            "m_axi_wlast",
            "m_axi_wvalid",
            "m_axi_wready",
            "m_axi_bvalid",
            "m_axi_bready",
        ] {
            assert!(v.contains(port), "missing AXI-write port `{}`", port);
        }
    }

    #[test]
    fn local_memory_interface_present() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        assert!(v.contains("output reg  [11:0] local_addr"));
        assert!(v.contains("output reg  [63:0] local_wdata"));
        assert!(v.contains("output reg         local_we"));
        assert!(v.contains("input  wire [63:0] local_rdata"));
    }

    #[test]
    fn rready_and_bready_continuous_assigns() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        assert!(v.contains("assign m_axi_rready = (state == READ_DATA);"));
        assert!(v.contains("assign m_axi_bready = 1'b1;"));
    }

    #[test]
    fn idle_branches_on_direction() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        assert!(v.contains("state           <= direction ? WRITE_ADDR : READ_ADDR;"));
        assert!(v.contains("m_axi_araddr <= src_addr;"));
        assert!(v.contains("m_axi_awaddr <= dst_addr;"));
        assert!(v.contains("m_axi_arlen  <= 8'hFF;"));
        assert!(v.contains("m_axi_awlen  <= 8'hFF;"));
    }

    #[test]
    fn beat_size_is_eight_bytes() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        // Both read and write paths decrement by 8.
        let occurrences = v.matches("bytes_remaining - 32'd8").count();
        assert!(occurrences >= 2, "expected >=2 `- 32'd8` decrements, got {}", occurrences);
    }

    #[test]
    fn write_last_set_on_final_beat() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        assert!(v.contains("m_axi_wlast  <= (bytes_remaining <= 32'd8);"));
    }

    #[test]
    fn done_state_clears_busy_and_returns_to_idle() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        assert!(v.contains("busy     <= 1'b0;"));
        assert!(v.contains("done     <= 1'b1;"));
        assert!(v.contains("state    <= IDLE;"));
    }

    #[test]
    fn reset_initializes_all_outputs() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        for line in [
            "state          <= IDLE;",
            "busy           <= 1'b0;",
            "done           <= 1'b0;",
            "m_axi_arvalid  <= 1'b0;",
            "m_axi_awvalid  <= 1'b0;",
            "m_axi_wvalid   <= 1'b0;",
            "local_we       <= 1'b0;",
            "local_addr     <= 12'd0;",
        ] {
            assert!(v.contains(line), "missing reset line `{}`", line);
        }
    }

    /// `local_we` must default low immediately before `case (state)`.
    ///
    /// Deliberately anchored to the span between the reset block's `end else`
    /// and the `case (state)` header. The reset block itself already contains
    /// `local_we       <= 1'b0;` (asserted by `reset_initializes_all_outputs`),
    /// so a bare `v.contains("local_we <= 1'b0;")` is satisfied by the
    /// *defective* emitter and would be vacuous. Measured, not assumed.
    #[test]
    fn local_we_defaults_low_before_the_case() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        let reset_end = v
            .find("end else")
            .expect("emitted module must leave the reset block with `end else`");
        let case_at = v
            .find("case (state)")
            .expect("emitted module must contain a `case (state)` header");
        assert!(
            reset_end < case_at,
            "`end else` must precede `case (state)`"
        );
        let between = &v[reset_end..case_at];
        assert!(
            between.contains("local_we <= 1'b0;"),
            "`local_we` must be defaulted low between the reset block and \
             `case (state)`, so the strobe is a one-cycle pulse instead of a \
             level that persists through states which never drive it \
             (READ_ADDR between bursts, IDLE, WRITE_ADDR, WRITE_DATA). \
             Text found between `end else` and `case (state)` was:\n{:?}",
            between
        );
    }

    /// The `case` must stay inside the `else` branch it was moved into: an
    /// unbalanced `begin` would still emit a `local_we <= 1'b0;` in the right
    /// span while producing Verilog that does not parse.
    #[test]
    fn always_block_begin_end_balanced() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        let begins = v.matches("begin").count();
        let ends = v.matches("end").count()
            - v.matches("endcase").count()
            - v.matches("endmodule").count();
        assert_eq!(
            begins, ends,
            "unbalanced begin/end in emitted module: {} `begin` vs {} `end` \
             (excluding `endcase`/`endmodule`)",
            begins, ends
        );
    }

    /// Slice one `case` arm out of the emitted module, so an assertion cannot
    /// be satisfied by an identical-looking line in a different state.
    fn case_arm<'a>(v: &'a str, from: &str, to: &str) -> &'a str {
        let a = v.find(from).unwrap_or_else(|| panic!("missing arm `{}`", from));
        let b = v[a..]
            .find(to)
            .unwrap_or_else(|| panic!("missing arm `{}` after `{}`", to, from));
        &v[a..a + b]
    }

    /// `READ_DATA` must present address, data and enable from one stage.
    ///
    /// Anchored to the `READ_DATA` arm on purpose. `WRITE_DATA` legitimately
    /// keeps its own `local_addr <= local_addr + 12'd1;` (there the address is
    /// a *read* pointer, one beat ahead by design), so an unanchored
    /// `!v.contains("local_addr + 12'd1")` fails on the CORRECT emitter.
    #[test]
    fn read_data_pairs_address_with_data_and_enable() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        let arm = case_arm(&v, "READ_DATA: if", "WRITE_ADDR:");
        assert!(
            !arm.contains("local_addr + 12'd1"),
            "READ_DATA must not post-increment `local_addr` in the same \
             non-blocking group that raises `local_we`: the increment lands in \
             the same cycle as the strobe, so beat 0's data is written to \
             address 1 and slot 0 is never written. READ_DATA arm was:\n{}",
            arm
        );
        assert!(
            arm.contains("local_addr      <= beat_index;"),
            "READ_DATA must drive `local_addr` from `beat_index` (the index of \
             the beat being captured), so address, data and enable are \
             registered from one stage. READ_DATA arm was:\n{}",
            arm
        );
        assert!(
            arm.contains("beat_index      <= beat_index + 12'd1;"),
            "READ_DATA must advance `beat_index` for the next beat. \
             READ_DATA arm was:\n{}",
            arm
        );
    }

    /// `beat_index` must be re-armed when a transfer starts, not only at reset,
    /// or a second read transfer resumes at the previous transfer's index.
    #[test]
    fn beat_index_rearmed_in_idle_not_only_at_reset() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        let arm = case_arm(&v, "IDLE: if (start)", "READ_ADDR:");
        assert!(
            arm.contains("beat_index      <= 12'd0;"),
            "`beat_index` must be cleared in the IDLE start branch alongside \
             `local_addr`, not only in the reset block: without it the second \
             transfer after power-on starts writing at a stale index. \
             IDLE arm was:\n{}",
            arm
        );
    }

    // ---- issue #2002: maximum-sized requests must not silently truncate ----

    /// Slice the asynchronous-reset block out of the emitted module, so a
    /// reset-initialisation assertion cannot be satisfied by an assignment
    /// that only ever happens inside a `case` arm.
    fn reset_block(v: &str) -> &str {
        case_arm(v, "if (!rst_n) begin", "end else begin")
    }

    /// `length` is 32 bits; `local_addr` is 12. A request larger than the
    /// local memory must be clamped to it, or the beat counter wraps and the
    /// transfer overwrites words it already delivered while reporting `done`.
    ///
    /// Anchored to the `IDLE` start branch: `bytes_remaining` is also assigned
    /// in the reset block and decremented in both data states, so an
    /// unanchored search would be satisfied by any of them.
    #[test]
    fn idle_clamps_length_to_local_address_space() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        let arm = case_arm(&v, "IDLE: if (start)", "READ_ADDR:");
        assert!(
            !arm.contains("bytes_remaining <= length;"),
            "IDLE must not load `bytes_remaining` from `length` unclamped: \
             `length` can name 2**29 beats against a 2**12-entry address \
             space, so `local_addr` wraps and the transfer overwrites data it \
             already wrote, then reports done=1. IDLE arm was:\n{}",
            arm
        );
        assert!(
            arm.contains("bytes_remaining <= (length > MAX_BYTES) ? MAX_BYTES : length;"),
            "IDLE must clamp `bytes_remaining` to MAX_BYTES, which bounds the \
             read path (`beat_index`) and the write path (`local_addr + 1`) at \
             once. IDLE arm was:\n{}",
            arm
        );
    }

    /// Clamping alone converts silent corruption into a silent SHORT transfer.
    /// The clamp must be reported, or the host still cannot tell that the tail
    /// of its request was dropped.
    #[test]
    fn idle_raises_overflow_when_request_is_clamped() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        let arm = case_arm(&v, "IDLE: if (start)", "READ_ADDR:");
        assert!(
            arm.contains("overflow        <= (length > MAX_BYTES);"),
            "IDLE must raise `overflow` exactly when it clamps: a clamp with \
             no output makes an oversized request indistinguishable from a \
             correctly-sized one, which is the same silent failure in a new \
             shape. IDLE arm was:\n{}",
            arm
        );
    }

    /// `overflow` is a status output, so it must have a defined value out of
    /// reset rather than powering up as X.
    #[test]
    fn reset_block_clears_overflow() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        let blk = reset_block(&v);
        assert!(
            blk.contains("overflow       <= 1'b0;"),
            "`overflow` must be cleared in the asynchronous reset block, or it \
             reads as X until the first transfer starts and any host that \
             samples it early sees a spurious error. Reset block was:\n{}",
            blk
        );
    }

    #[test]
    fn overflow_output_port_declared() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        assert!(
            v.contains("    output reg         overflow,\n"),
            "`dma_controller` must expose an `overflow` output port; without \
             it the clamp is invisible to the host and `bitnet_engine_top` has \
             nothing to drive its error IRQ from"
        );
    }

    #[test]
    fn module_ends_with_endmodule() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        assert!(v.trim_end().ends_with("endmodule"));
    }

    #[test]
    fn emitted_text_is_pure_ascii() {
        let v = build_dma_controller(DEFAULT_DMA_CONTROLLER_NAME);
        assert!(v.is_ascii(), "emitted Verilog must be ASCII");
    }
}
