//! The TypeScript backend: `t27c gen-ts`.
//!
//! Why it exists beside `gen-js`, when TypeScript runs JavaScript unchanged.
//! Because a `.t27` declaration carries a TYPE, and JavaScript has nowhere to
//! put it. `const PAGE_MIN: i32 = 20` reaches an ES module as `20` and the
//! `i32` is gone -- the one piece of the declaration a consumer cannot recover
//! by reading the value. A `.d.ts` hand-written beside the artifact would put
//! it back, and would then be the thing that decides what the type is: the same
//! hole `gen-js` was written to close, dug one file over.
//!
//! **This file is the type layer only.** Every value it prints comes from
//! `codegen_js`, because TypeScript's syntax for a value is JavaScript's to the
//! character. The reserved-word list, the array-length check, the escape table
//! and the constant-expression walk are called there, not copied here; the two
//! backends differ in what they say about a value, never in what the value is.
//!
//! Three decisions worth stating, because each had a plausible alternative:
//!
//! - **`satisfies`, not an annotation.** `export const X: number = 20` widens
//!   the inferred type from `20` to `number`, which throws away exactly the
//!   precision a consumer wants from a generated constant -- a spec's string
//!   constants stop being usable as discriminants. `export const X = 20
//!   satisfies number` records the spec's claim, checks the literal against it
//!   at compile time, and leaves the literal type intact. Requires TS >= 5.0
//!   for the `as const satisfies` form used on arrays.
//! - **A frozen object and a union, not `enum`.** TS's `enum` emits a runtime
//!   IIFE -- real code, in a module whose whole promise is that nothing in it
//!   runs -- and `const enum` is rejected under `isolatedModules`. The frozen
//!   object is byte-identical to what `gen-js` emits, so the same spec produces
//!   the same runtime artifact through either backend.
//! - **Integers are `number`, and that is not a rounding of the truth.** `i64`
//!   and `u64` widen past 2^53, but the value `gen-js` prints for them IS a JS
//!   number literal. Saying `bigint` here would describe an artifact this
//!   compiler does not emit. The declared width survives in the struct
//!   descriptor's `fields` list, which keeps the spec's own spelling.
//!
//! Scope is `gen-js`'s scope: declarations, never function bodies, and anything
//! not lowered is announced in a comment rather than dropped in silence.

use crate::codegen_js::{
    array_type, const_value, describe, enum_variants, js_name, js_string, key, list, struct_fields,
    Bound, NotEmitted, TS,
};
use crate::compiler::{Node, NodeKind};
use std::collections::BTreeSet;

/// Names TypeScript refuses to let a declaration take in TYPE position.
///
/// This is a different question from `codegen_js::RESERVED`, which asks what
/// JavaScript refuses to BIND. `string` is a perfectly good variable name and a
/// forbidden interface name, so a spec with `struct string` passes the value
/// check and then fails inside `tsc` with an error naming a file nobody wrote.
/// It is refused here instead, with a sentence.
const TYPE_RESERVED: &[&str] = &[
    "any", "bigint", "boolean", "never", "number", "object", "string", "symbol", "undefined",
    "unknown", "void",
];

/// Above this many elements a declared array stops being written as a tuple.
///
/// `[4]str` as `readonly [string, string, string, string]` is worth having: it
/// carries the length into the type, and the length is checked. `[4096]u8`
/// spelled the same way is a line no one can read and a type `tsc` is slow to
/// compare. Past the ceiling the length is dropped -- and dropping it is said
/// out loud in the output, never quietly.
const TUPLE_CEILING: usize = 32;

/// A rendered TypeScript type, plus anything the reader must be told about how
/// it was arrived at.
struct TsType {
    /// The type text. Empty means the spec declared none -- which is not a
    /// failure: for a const it means "let TypeScript infer", and inference from
    /// a literal is more precise than anything this backend could write.
    text: String,
    /// Set when the mapping lost information. Printed as a comment beside the
    /// declaration it belongs to.
    note: Option<String>,
}

impl TsType {
    fn plain(text: &str) -> Self {
        TsType { text: text.to_string(), note: None }
    }
}

pub fn generate(ast: &Node, source_name: &str) -> Result<String, String> {
    generate_reported(ast, source_name).map(|(code, _)| code)
}

/// The artifact, and how many declarations it announced instead of printing.
/// The `gen-js` doc comment says why the count travels with the code.
pub fn generate_reported(ast: &Node, source_name: &str) -> Result<(String, usize), String> {
    let mut out = String::new();
    out.push_str("// Generated by `t27c gen-ts` from ");
    out.push_str(source_name);
    out.push_str(". Do not edit.\n");
    out.push_str("//\n");
    out.push_str("// Every name, value and type here comes from that spec. Change the spec and\n");
    out.push_str("// regenerate; an edit made here is lost the next time anyone builds.\n\n");

    // Which names this module declares, so a field typed with one of them gets
    // that type instead of `unknown`. It has to be a pre-pass: a struct may name
    // a struct declared below it, and the spec is under no obligation to order
    // its declarations for the convenience of a single-pass backend.
    let known: BTreeSet<String> = ast
        .children
        .iter()
        .filter(|n| matches!(n.kind, NodeKind::StructDecl | NodeKind::EnumDecl))
        .map(|n| n.name.clone())
        .collect();

    let mut struct_order: Vec<String> = Vec::new();
    let mut decl_order: Vec<String> = Vec::new();
    let mut missing = NotEmitted::default();
    let mut bound = Bound::in_spec(ast);

    for node in &ast.children {
        match node.kind {
            NodeKind::ConstDecl => {
                match js_name(&TS, &node.name)
                    .and_then(|name| Ok((name, const_value(&TS, node, &bound)?)))
                    .and_then(|(name, value)| {
                        bound.claim(&TS, &name)?;
                        Ok((name, value))
                    })
                {
                    Ok((name, value)) => {
                        let ty = ts_type(&node.extra_type, &known);
                        if let Some(note) = &ty.note {
                            out.push_str(&format!("// t27c gen-ts: {}\n", note));
                        }
                        // No declared type, or one this backend could not carry:
                        // emit the value alone. A vacuous `satisfies unknown`
                        // would read like a checked claim while checking nothing.
                        if ty.text.is_empty() || ty.text.contains("unknown") {
                            out.push_str(&format!("export const {} = {};\n", name, value));
                        } else if array_type(&node.extra_type).is_some() {
                            // An array literal infers `T[]`, which does not
                            // satisfy a tuple; `as const` makes the length
                            // checkable.
                            out.push_str(&format!(
                                "export const {} = {} as const satisfies {};\n",
                                name, value, ty.text
                            ));
                        } else {
                            out.push_str(&format!(
                                "export const {} = {} satisfies {};\n",
                                name, value, ty.text
                            ));
                        }
                        decl_order.push(node.name.clone());
                    }
                    Err(why) => {
                        bound.refuse(&node.name);
                        missing.record(&mut out, &TS, &format!("const {}", describe(node)), &why)
                    }
                }
            }
            NodeKind::EnumDecl => {
                // The body is `gen-js`'s, to the character and on purpose: the
                // two backends must not disagree about what a discriminant is.
                match type_name(&node.name)
                    .and_then(|name| Ok((name, enum_variants(&TS, node, &bound)?)))
                    .and_then(|(name, body)| {
                        bound.claim(&TS, &name)?;
                        Ok((name, body))
                    })
                {
                    Ok((name, body)) => {
                        out.push_str(&format!(
                            "export const {} = Object.freeze({{ {} }} as const);\n",
                            name, body.body
                        ));
                        for (what, why) in &body.dropped {
                            missing.record(&mut out, &TS, what, why);
                        }
                        // The type half. `keyof typeof` over a frozen literal
                        // object is the union of its values, which is what a t27
                        // enum means: one of these, nothing else.
                        out.push_str(&format!(
                            "export type {} = (typeof {})[keyof typeof {}];\n",
                            name, name, name
                        ));
                        decl_order.push(node.name.clone());
                    }
                    Err(why) => {
                        bound.refuse(&node.name);
                        missing.record(&mut out, &TS, &format!("enum {}", describe(node)), &why)
                    }
                }
            }
            NodeKind::StructDecl => {
                let name = match type_name(&node.name)
                    .and_then(|name| {
                        bound.claim(&TS, &name)?;
                        Ok(name)
                    }) {
                    Ok(name) => name,
                    Err(why) => {
                        bound.refuse(&node.name);
                        missing.record(&mut out, &TS, &format!("struct {}", describe(node)), &why);
                        continue;
                    }
                };
                let fields = struct_fields(node);
                out.push_str(&format!("export interface {} {{\n", name));
                for field in node.children.iter().filter(|f| !f.name.is_empty()) {
                    let ty = ts_type(&field.extra_type, &known);
                    let (text, note) = if ty.text.is_empty() {
                        (
                            "unknown".to_string(),
                            Some(format!("{} has no declared type in the spec", field.name)),
                        )
                    } else {
                        (ty.text, ty.note)
                    };
                    out.push_str(&format!("  readonly {}: {};", key(&TS, &field.name), text));
                    match note {
                        Some(n) => out.push_str(&format!(" // t27c gen-ts: {}\n", n)),
                        None => out.push('\n'),
                    }
                }
                out.push_str("}\n");
                // And the value half, which an interface cannot carry: the same
                // descriptor `gen-js` prints, so a consumer can read a struct's
                // field list at runtime. An interface and a const may share a
                // name -- they live in different namespaces -- and that is what
                // lets `Name` mean the type here and the descriptor there.
                out.push_str(&format!(
                    "export const {} = Object.freeze({{ __struct__: {}, fields: [{}] }} as const);\n",
                    name,
                    js_string(&node.name),
                    fields.join(", ")
                ));
                struct_order.push(node.name.clone());
                decl_order.push(node.name.clone());
            }
            NodeKind::UseDecl => {}
            // Announced, never dropped in silence.
            NodeKind::FnDecl => out.push_str(&format!(
                "// t27c gen-ts: fn {} was not emitted -- this backend lowers declarations, not bodies.\n",
                node.name
            )),
            NodeKind::TestBlock | NodeKind::BenchBlock | NodeKind::InvariantBlock => {
                out.push_str(&format!(
                    "// t27c gen-ts: a {:?} was not emitted -- it is checked by the compiler, not by the artifact.\n",
                    node.kind
                ))
            }
            // A statement at module level -- `x = 1;`, a bare call, an `if`.
            // Some specs open with a few, and refusing the file over them threw
            // away every declaration underneath.
            _ => missing.record(
                &mut out,
                &TS,
                &format!("a {:?} {}", node.kind, describe(node)),
                "this backend lowers declarations, and a statement is not one",
            ),
        }
    }

    out.push_str("\n// Declaration order, which the spec's own laws depend on.\n");
    out.push_str(&format!(
        "export const __STRUCT_ORDER__ = [{}] as const;\n",
        list(&struct_order)
    ));
    out.push_str(&format!(
        "export const __DECL_ORDER__ = [{}] as const;\n",
        list(&decl_order)
    ));
    out.push_str(&missing.finish(&TS));
    Ok((out, missing.len()))
}

/// A name that has to be legal in BOTH namespaces: a struct and an enum each
/// emit a type and a value under one spelling.
fn type_name(name: &str) -> Result<String, String> {
    let name = js_name(&TS, name)?;
    if TYPE_RESERVED.contains(&name.as_str()) {
        return Err(format!(
            "gen-ts: {:?} is a built-in TypeScript type and cannot name a declaration; rename it in the spec",
            name
        ));
    }
    Ok(name)
}

/// A t27 type, in TypeScript.
///
/// The table is `compiler.rs`'s own -- `resolve_type_str` -- read in the same
/// order, so a type this compiler accepts is a type this backend can spell.
fn ts_type(decl: &str, known: &BTreeSet<String>) -> TsType {
    let decl = decl.trim();
    if decl.is_empty() {
        return TsType { text: String::new(), note: None };
    }

    // `T?` is Optional, and the `?` binds to the WHOLE declared type -- which
    // is `resolve_type_str`'s reading, not a choice made here: it wraps in
    // Optional after everything else. So `[4]str?` is a nullable array of
    // strings, never an array of nullable strings, and an array's element type
    // can therefore never be a union needing brackets of its own.
    //
    // `null` rather than `undefined` because `null` is what the value layer
    // emits for an absent value; an artifact whose type says `undefined` and
    // whose value says `null` does not type-check against itself.
    if let Some(base) = decl.strip_suffix('?') {
        let inner = ts_type(base, known);
        if inner.text.is_empty() {
            return inner;
        }
        return TsType { text: format!("{} | null", inner.text), note: inner.note };
    }

    if let Some((count, elem)) = array_type(decl) {
        let inner = ts_type(&elem, known);
        let item = if inner.text.is_empty() { "unknown".to_string() } else { inner.text };
        if count > TUPLE_CEILING {
            let dropped = format!(
                "[{}]{} is longer than {} elements, so its length is not carried into the type",
                count, elem, TUPLE_CEILING
            );
            // Both facts, when both are true: an element type that was already
            // guessed at AND a length that was dropped are two separate things
            // the reader was not told, and reporting one of them is how the
            // other goes unnoticed.
            let note = match inner.note {
                Some(elem_note) => format!("{}; and {}", dropped, elem_note),
                None => dropped,
            };
            return TsType { text: format!("readonly {}[]", item), note: Some(note) };
        }
        let items = vec![item; count].join(", ");
        return TsType { text: format!("readonly [{}]", items), note: inner.note };
    }

    match decl {
        "void" => TsType::plain("void"),
        "bool" => TsType::plain("boolean"),
        "str" => TsType::plain("string"),
        "i8" | "i16" | "i32" | "i64" | "u8" | "u16" | "u32" | "u64" | "f32" | "f64" | "GF16"
        | "gf16" => TsType::plain("number"),
        name if known.contains(name) => TsType::plain(name),
        name => TsType {
            text: "unknown".to_string(),
            note: Some(format!(
                "{:?} is not declared in this module, so it is emitted as unknown rather than guessed at",
                name
            )),
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn known(names: &[&str]) -> BTreeSet<String> {
        names.iter().map(|n| n.to_string()).collect()
    }

    fn node(kind: NodeKind, name: &str, extra_type: &str) -> Node {
        Node { kind, name: name.to_string(), extra_type: extra_type.to_string(), ..Default::default() }
    }

    #[test]
    fn the_canonical_widths_all_become_number() {
        for t in ["i8", "i32", "i64", "u64", "f32", "f64", "GF16", "gf16"] {
            let ty = ts_type(t, &known(&[]));
            assert_eq!(ty.text, "number", "{}", t);
            assert!(ty.note.is_none(), "{} should not need a note", t);
        }
    }

    #[test]
    fn an_optional_is_a_union_with_null() {
        assert_eq!(ts_type("str?", &known(&[])).text, "string | null");
    }

    #[test]
    fn a_declared_array_carries_its_length() {
        assert_eq!(
            ts_type("[3]str", &known(&[])).text,
            "readonly [string, string, string]"
        );
    }

    #[test]
    fn a_long_array_drops_its_length_and_says_so() {
        let ty = ts_type("[4096]u8", &known(&[]));
        assert_eq!(ty.text, "readonly number[]");
        assert!(ty.note.unwrap().contains("length is not carried"));
    }

    #[test]
    fn the_question_mark_makes_the_array_nullable_not_its_elements() {
        // `resolve_type_str` wraps in Optional last, so the `?` is the outermost
        // thing in the type. `readonly` binds tighter than `|`, so this reads
        // `(readonly string[]) | null` -- the array may be absent; a present one
        // holds no nulls.
        assert_eq!(ts_type("[64]str?", &known(&[])).text, "readonly string[] | null");
        assert_eq!(
            ts_type("[3]str?", &known(&[])).text,
            "readonly [string, string, string] | null"
        );
    }

    #[test]
    fn a_long_array_of_an_unknown_type_reports_both_losses() {
        let ty = ts_type("[99]Widget", &known(&[])).note.unwrap();
        assert!(ty.contains("length is not carried"), "{}", ty);
        assert!(ty.contains("not declared in this module"), "{}", ty);
    }

    #[test]
    fn a_name_this_module_declares_is_used_as_written() {
        let ty = ts_type("HabrSearch", &known(&["HabrSearch"]));
        assert_eq!(ty.text, "HabrSearch");
        assert!(ty.note.is_none());
    }

    #[test]
    fn an_undeclared_name_is_widened_out_loud() {
        let ty = ts_type("SomethingElse", &known(&["HabrSearch"]));
        assert_eq!(ty.text, "unknown");
        assert!(ty.note.unwrap().contains("not declared in this module"));
    }

    #[test]
    fn a_builtin_type_name_is_refused_rather_than_handed_to_tsc() {
        // `export interface string` is TS2427, reported against a generated
        // file. Better a sentence here, naming the spec.
        assert!(type_name("string").is_err());
        assert!(type_name("number").is_err());
        assert!(type_name("HabrSearch").is_ok());
    }

    #[test]
    fn a_const_records_its_declared_type_without_widening_the_literal() {
        let mut ast = node(NodeKind::Module, "m", "");
        let mut c = node(NodeKind::ConstDecl, "PAGE_MIN", "i32");
        let mut lit = node(NodeKind::ExprLiteral, "", "");
        lit.value = "20".to_string();
        c.children.push(lit);
        ast.children.push(c);

        let out = generate(&ast, "t.t27").unwrap();
        assert!(out.contains("export const PAGE_MIN = 20 satisfies number;"), "{}", out);
    }

    #[test]
    fn an_enum_emits_a_frozen_object_and_a_union() {
        let mut ast = node(NodeKind::Module, "m", "");
        let mut e = node(NodeKind::EnumDecl, "Sev", "");
        let info = node(NodeKind::EnumVariant, "Info", "");
        let mut warn = node(NodeKind::EnumVariant, "Warn", "");
        warn.value = "5".to_string();
        let err = node(NodeKind::EnumVariant, "Error", "");
        e.children.extend([info, warn, err]);
        ast.children.push(e);

        let out = generate(&ast, "t.t27").unwrap();
        // The discriminant rule, asserted here as well as in the JS backend:
        // the two must not drift apart.
        assert!(out.contains("Info: 0, Warn: 5, Error: 6"), "{}", out);
        assert!(
            out.contains("export type Sev = (typeof Sev)[keyof typeof Sev];"),
            "{}",
            out
        );
    }

    #[test]
    fn a_struct_emits_both_an_interface_and_the_js_descriptor() {
        let mut ast = node(NodeKind::Module, "m", "");
        let mut s = node(NodeKind::StructDecl, "HabrSearch", "");
        // The parser records a struct field as an ExprIdentifier carrying the
        // declared type in `extra_type`; there is no StructField kind.
        s.children.push(node(NodeKind::ExprIdentifier, "query", "str"));
        s.children.push(node(NodeKind::ExprIdentifier, "page", "i32"));
        ast.children.push(s);

        let out = generate(&ast, "t.t27").unwrap();
        assert!(out.contains("  readonly query: string;\n"), "{}", out);
        assert!(out.contains("  readonly page: number;\n"), "{}", out);
        // The descriptor keeps the SPEC's spelling, not TypeScript's -- the same
        // bytes `gen-js` prints.
        assert!(
            out.contains(r#"fields: [["query", "str"], ["page", "i32"]]"#),
            "{}",
            out
        );
    }

    #[test]
    fn a_keyword_is_refused_by_the_shared_layer_under_the_ts_name() {
        let mut ast = node(NodeKind::Module, "m", "");
        let mut c = node(NodeKind::ConstDecl, "class", "i32");
        let mut lit = node(NodeKind::ExprLiteral, "", "");
        lit.value = "1".to_string();
        c.children.push(lit);
        ast.children.push(c);

        let out = generate(&ast, "t.t27").unwrap();
        // The point of `Target`: the caller ran `gen-ts`, so the reason says so.
        assert!(out.contains("// t27c gen-ts: const class was not emitted"), "{}", out);
        assert!(out.contains("TypeScript keyword"), "{}", out);
        // And the refusal is data as well as prose, so the catalog can read it.
        assert!(out.contains("__NOT_EMITTED__ = Object.freeze([ { what: \"const class\","), "{}", out);
        // The one const in the module did not make it, so nothing claims it did.
        assert!(out.contains("__DECL_ORDER__ = [] as const"), "{}", out);
    }

    #[test]
    fn one_unprintable_const_does_not_cost_the_rest_of_the_module() {
        // The defect this rewrite was written for. `gf16::GF16::ONE` lives in
        // another spec, so its const cannot be printed -- and the whole module
        // used to fail with it, taking forty consts that were fine along with
        // it. Six other backends emit those specs; `gen-ts` alone called them
        // broken.
        let mut ast = node(NodeKind::Module, "m", "");

        let mut good = node(NodeKind::ConstDecl, "PAGE_MIN", "i32");
        let mut lit = node(NodeKind::ExprLiteral, "", "");
        lit.value = "20".to_string();
        good.children.push(lit);
        ast.children.push(good);

        let mut elsewhere = node(NodeKind::ConstDecl, "ONE", "");
        elsewhere.children.push(node(NodeKind::ExprIdentifier, "gf16::GF16::ONE", ""));
        ast.children.push(elsewhere);

        let out = generate(&ast, "t.t27").unwrap();
        assert!(out.contains("export const PAGE_MIN = 20 satisfies number;"), "{}", out);
        assert!(out.contains("// t27c gen-ts: const ONE was not emitted"), "{}", out);
        assert!(out.contains("another module"), "{}", out);
        assert!(out.contains("__DECL_ORDER__ = [\"PAGE_MIN\"] as const"), "{}", out);
    }
}
