//! `t27c gen-python` -- a Python module of the declarations a spec holds.
//!
//! The same contract as `gen-js`/`gen-ts`, stated once there and honored here:
//! the artifact is DATA. A spec's consts, enums and structs are lowered as
//! plain module-level assignments; its fn/test/bench/invariant blocks are
//! ANNOUNCED in a comment, never silently dropped and never faked with a
//! `def` stub whose signature this backend would be inventing rather than
//! reading. (The earlier `codegen_python.t27` stub sketched classes and defs;
//! the data-only philosophy that gen-js settled on supersedes that sketch, and
//! this file is the full implementation the stub deferred as P1.)
//!
//! Every spelling difference from JavaScript lives in the value layer the two
//! backends share (`codegen_js.rs`, parametrized by `Target`): True/False/None
//! words, `and`/`or`/`not`, `//` for integer division, arbitrary-precision
//! ints masked to the declared width instead of `>>> 0`, dict literals instead
//! of `Object.freeze`. Nothing here re-decides a value; this file only decides
//! where the newlines and `=` signs go.
//!
//! Two honest limits, both said out loud in the artifact header rather than
//! papered over: the module imports nothing, so a dict is mutable where the
//! JS artifact is frozen; and a name Python cannot bind (`$`, a hard keyword)
//! is refused here with a sentence, exactly as the JS path refuses its own.

use crate::codegen_js::{
    block_what, const_value, describe, enum_variants, js_name, js_string, list, struct_fields,
    Bound, NotEmitted, BLOCK_NOT_EMITTED, FN_NOT_LOWERED, PY,
};
use crate::compiler::{Node, NodeKind};

pub fn generate(ast: &Node, source_name: &str) -> Result<String, String> {
    generate_reported(ast, source_name).map(|(code, _)| code)
}

/// The artifact and its announced-omission count, mirroring
/// `codegen_js::generate_reported` so a corpus catalog reads both backends the
/// same way.
pub fn generate_reported(ast: &Node, source_name: &str) -> Result<(String, usize), String> {
    let mut out = String::new();
    out.push_str("# Generated by `t27c gen-python` from ");
    out.push_str(source_name);
    out.push_str(". Do not edit.\n");
    out.push_str("#\n");
    out.push_str("# Every name and every value here comes from that spec. Change the spec and\n");
    out.push_str("# regenerate; an edit made here is lost the next time anyone builds.\n");
    out.push_str("#\n");
    out.push_str("# Plain assignments: this module imports nothing, so the dicts below\n");
    out.push_str("# are mutable where the JavaScript artifact is frozen. Read them; do\n");
    out.push_str("# not rewrite them.\n\n");

    let mut struct_order: Vec<String> = Vec::new();
    let mut decl_order: Vec<String> = Vec::new();
    let mut missing = NotEmitted::default();
    let mut bound = Bound::in_spec(ast);

    for node in &ast.children {
        match node.kind {
            NodeKind::ConstDecl => {
                match js_name(&PY, &node.name)
                    .and_then(|name| Ok((name, const_value(&PY, node, &bound)?)))
                    .and_then(|(name, value)| {
                        bound.claim(&PY, &name)?;
                        Ok((name, value))
                    })
                {
                    Ok((name, value)) => {
                        out.push_str(&format!("{name} = {value}\n"));
                        decl_order.push(node.name.clone());
                    }
                    Err(why) => {
                        bound.refuse(&node.name);
                        missing.record(&mut out, &PY, &format!("const {}", describe(node)), &why)
                    }
                }
            }
            NodeKind::EnumDecl => {
                // The body renders before the name is claimed, for the reason
                // the const arm states in gen-js: a name claimed against a
                // declaration that then fails to print is a name that resolves
                // here and does not exist in the artifact.
                match js_name(&PY, &node.name)
                    .and_then(|name| Ok((name, enum_variants(&PY, node, &bound)?)))
                    .and_then(|(name, body)| {
                        bound.claim(&PY, &name)?;
                        Ok((name, body))
                    }) {
                    Ok((name, body)) => {
                        out.push_str(&format!("{name} = {{ {} }}\n", body.body));
                        for (what, why) in &body.dropped {
                            missing.record(&mut out, &PY, what, why);
                        }
                        decl_order.push(node.name.clone());
                    }
                    Err(why) => {
                        bound.refuse(&node.name);
                        missing.record(&mut out, &PY, &format!("enum {}", describe(node)), &why)
                    }
                }
            }
            NodeKind::StructDecl => {
                let name = match js_name(&PY, &node.name)
                    .and_then(|name| {
                        bound.claim(&PY, &name)?;
                        Ok(name)
                    }) {
                    Ok(name) => name,
                    Err(why) => {
                        bound.refuse(&node.name);
                        missing.record(&mut out, &PY, &format!("struct {}", describe(node)), &why);
                        continue;
                    }
                };
                let fields = struct_fields(node);
                out.push_str(&format!(
                    "{name} = {{\"__struct__\": {}, \"fields\": [{}]}}\n",
                    js_string(&node.name),
                    fields.join(", ")
                ));
                struct_order.push(node.name.clone());
                decl_order.push(node.name.clone());
            }
            NodeKind::UseDecl => {}
            // Announced, never dropped in silence -- and never stubbed: a
            // `def` line here would be a signature this backend invented, not
            // one it read. Listed in `__NOT_EMITTED__` as well, as gen-js and
            // gen-ts list it: the comment alone left the list empty while
            // every fn was missing (#6559).
            NodeKind::FnDecl => missing.record(
                &mut out,
                &PY,
                &format!("fn {}", node.name),
                FN_NOT_LOWERED,
            ),
            NodeKind::TestBlock | NodeKind::BenchBlock | NodeKind::InvariantBlock => {
                out.push_str(&format!(
                    "# t27c gen-python: a {:?} was not emitted -- {}\n",
                    node.kind, BLOCK_NOT_EMITTED
                ));
                missing.note(&block_what(node), BLOCK_NOT_EMITTED);
            }
            _ => missing.record(
                &mut out,
                &PY,
                &format!("a {:?} {}", node.kind, describe(node)),
                "this backend lowers declarations, and a statement is not one",
            ),
        }
    }

    out.push_str("\n# Declaration order, which the spec's own laws depend on.\n");
    out.push_str(&format!("__STRUCT_ORDER__ = [{}]\n", list(&struct_order)));
    out.push_str(&format!("__DECL_ORDER__ = [{}]\n", list(&decl_order)));
    out.push_str(&missing.finish(&PY));
    Ok((out, missing.len()))
}


#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen_js::{expr, expr_typed};

    /// A scope holding exactly the names a test says the spec declared above,
    /// spelled out per test for the reason the gen-js suite states: a
    /// permissive scope passes the very artifacts this check exists to refuse.
    fn scope(names: &[&str]) -> Bound {
        let mut b = Bound::default();
        for n in names {
            b.claim(&PY, n).unwrap();
        }
        b
    }

    fn lit(value: &str, kind: &str) -> Node {
        Node {
            kind: NodeKind::ExprLiteral,
            value: value.to_string(),
            extra_kind: kind.to_string(),
            ..Default::default()
        }
    }

    fn binary(op: &str, left: Node, right: Node) -> Node {
        Node {
            kind: NodeKind::ExprBinary,
            extra_op: op.to_string(),
            children: vec![left, right],
            ..Default::default()
        }
    }

    fn ident(name: &str) -> Node {
        Node { kind: NodeKind::ExprIdentifier, name: name.to_string(), ..Default::default() }
    }

    fn unary(op: &str, child: Node) -> Node {
        Node {
            kind: NodeKind::ExprUnary,
            extra_op: op.to_string(),
            children: vec![child],
            ..Default::default()
        }
    }

    fn decl(name: &str, ty: &str, value: Node) -> Node {
        Node {
            kind: NodeKind::ConstDecl,
            name: name.to_string(),
            extra_type: ty.to_string(),
            children: vec![value],
            ..Default::default()
        }
    }

    fn py(src: &str) -> String {
        generate(&crate::compiler::Compiler::parse_ast_strict(src).expect("parse"), "test.t27")
            .expect("generate")
    }

    /// The three literals JavaScript spells lowercase and Python spells as
    /// words -- the defect a shared value layer exists to prevent, one wrong
    /// word per backend instead of one wrong convention everywhere.
    #[test]
    fn literal_words() {
        assert_eq!(expr(&PY, &lit("true", ""), &scope(&[])).unwrap(), "True");
        assert_eq!(expr(&PY, &lit("false", ""), &scope(&[])).unwrap(), "False");
        assert_eq!(expr(&PY, &lit("null", ""), &scope(&[])).unwrap(), "None");
    }

    /// `&&`/`||`/`!` in the spec read as Python's word operators, with the
    /// parenthesization the value layer already guarantees for precedence.
    #[test]
    fn boolean_operators_are_words() {
        let s = scope(&["A", "B"]);
        assert_eq!(
            expr(&PY, &binary("&&", ident("A"), ident("B")), &s).unwrap(),
            "(A and B)"
        );
        assert_eq!(
            expr(&PY, &binary("||", ident("A"), ident("B")), &s).unwrap(),
            "(A or B)"
        );
        assert_eq!(expr(&PY, &unary("!", ident("A")), &s).unwrap(), "(not A)");
        // The spec's own spelling is accepted alongside, so a spec and its
        // artifact never disagree about which language they mean.
        assert_eq!(
            expr(&PY, &binary("and", ident("A"), ident("B")), &s).unwrap(),
            "(A and B)"
        );
    }

    /// Integer division floors with `//` at the declared integer type, and
    /// stays `/` where the declared type is a float -- the same split the
    /// gen-js tests pin with `Math.trunc`, spelled the way Python spells it.
    #[test]
    fn integer_division_floors_and_float_does_not() {
        assert_eq!(
            expr_typed(&PY, &binary("/", lit("7", ""), lit("2", "")), "u8", &scope(&[]))
                .unwrap(),
            "(7 // 2)"
        );
        assert_eq!(
            expr_typed(&PY, &binary("/", lit("7.0", ""), lit("2.0", "")), "f32", &scope(&[]))
                .unwrap(),
            "(7.0 / 2.0)"
        );
    }

    /// Equality is one `=`, comparison is two; the C spelling carries over and
    /// the assignment spelling does not appear in a value position.
    #[test]
    fn equality_and_inequality() {
        let s = scope(&["A", "B"]);
        assert_eq!(expr(&PY, &binary("==", ident("A"), ident("B")), &s).unwrap(), "(A == B)");
        assert_eq!(expr(&PY, &binary("!=", ident("A"), ident("B")), &s).unwrap(), "(A != B)");
    }

    /// Bitwise ops are masked to the declared width, because a Python int is
    /// unbounded and the spec's type is not: `~u8 0` must read 255 when
    /// evaluated, not -1. Any width is fine -- there is no 32-bit wall here --
    /// and a right shift needs no mask because it cannot grow.
    #[test]
    fn bitwise_masked_to_any_declared_width() {
        let flip = decl("FLIP", "u8", unary("~", lit("0", "")));
        assert_eq!(const_value(&PY, &flip, &scope(&[])).unwrap(), "((~0) & 0xFF)");

        let wide = decl("BIG", "u64", binary("<<", lit("1", ""), lit("40", "")));
        assert_eq!(const_value(&PY, &wide, &scope(&[])).unwrap(), "((1 << 40) & 0xFFFFFFFFFFFFFFFF)");

        let shr = decl("HALF", "u32", binary(">>", ident("X"), lit("1", "")));
        assert_eq!(const_value(&PY, &shr, &scope(&["X"])).unwrap(), "(X >> 1)");
    }

    /// A field reads as a dict subscript: `point.x` in the spec becomes
    /// `point["x"]` in the artifact, which is the same value in a language
    /// whose objects are dictionaries.
    #[test]
    fn field_access_is_a_dict_subscript() {
        let node = Node {
            kind: NodeKind::ExprFieldAccess,
            name: "x".to_string(),
            children: vec![ident("point")],
            ..Default::default()
        };
        assert_eq!(expr(&PY, &node, &scope(&["point"])).unwrap(), "point[\"x\"]");
    }

    /// A name Python cannot bind is refused with a sentence naming the
    /// backend, not shipped as a module that dies at import. (`$` is legal
    /// JavaScript; hard keywords are refused for both.)
    #[test]
    fn names_python_cannot_bind_are_refused() {
        assert!(js_name(&PY, "$x").unwrap_err().contains("not a name"));
        assert!(js_name(&PY, "class").unwrap_err().contains("keyword"));
        // Soft keywords stay legal, exactly as contextual keywords stay legal
        // on the TypeScript side.
        assert_eq!(js_name(&PY, "match").unwrap(), "match");
    }

    /// End to end: a module of assignments, from parse to artifact.
    #[test]
    fn module_of_assignments() {
        let out = py("module m;\npub const TAG : str = \"GET\";\npub const N : u8 = 3;");
        assert!(out.contains("TAG = \"GET\"\n"), "{}", out);
        assert!(out.contains("N = 3\n"), "{}", out);
        assert!(out.contains("__DECL_ORDER__ = [\"TAG\", \"N\"]\n"), "{}", out);
        assert!(out.contains("__NOT_EMITTED__ = []\n"), "{}", out);
        // No JavaScript furniture survives into the artifact.
        assert!(!out.contains("export "), "{}", out);
        assert!(!out.contains("Object.freeze"), "{}", out);
    }

    /// Enum discriminants: explicit value kept, count resumed from it, keys
    /// always quoted -- `Low` unquoted would be a name lookup at import.
    #[test]
    fn enum_discriminants_resume() {
        let out = py("module m; pub const Level = enum { Low, High = 7, Top, }");
        assert!(out.contains("Level = { \"Low\": 0, \"High\": 7, \"Top\": 8 }\n"), "{}", out);
    }

    /// A struct descriptor carries the declared t27 field types, not types
    /// this backend guessed.
    #[test]
    fn struct_descriptor() {
        let out = py("module m;\npub const Point = struct { x : u8, y : u16, }");
        assert!(
            out.contains("Point = {\"__struct__\": \"Point\", \"fields\": [[\"x\", \"u8\"], [\"y\", \"u16\"]]}\n"),
            "{}",
            out
        );
    }

    /// Byte-array consts keep their element spelling across backends.
    #[test]
    fn byte_array() {
        let out = py("module m; pub const VER : [4]u8 = \"v1.2\";");
        assert!(out.contains("VER = [118, 49, 46, 50]\n"), "{}", out);
    }

    /// A fn is announced, not stubbed: no `def` line exists, because a `def`
    /// here would be a signature this backend invented rather than read.
    /// Tests, benches and invariants are announced the same way.
    #[test]
    fn fn_is_announced_not_stubbed() {
        let out = py("module m;\nfn f(a : u8) -> u8 { return a; }\ntest t1 { assert 1 > 2; }");
        assert!(out.contains("# t27c gen-python: fn f was not emitted"), "{}", out);
        assert!(out.contains("# t27c gen-python: a TestBlock was not emitted"), "{}", out);
        assert!(!out.contains("def "), "{}", out);
    }

    /// The two backends agree on WHAT was declared even where they differ on
    /// spelling: same declaration order, same omission count.
    #[test]
    fn parity_with_gen_js() {
        let src = "module m;\n"
            .to_owned()
            + "pub const A : u8 = 1;\n"
            + "pub const Level = enum { Low, High, };\n"
            + "pub const Point = struct { x : u8, };\n"
            + "fn g() -> u8 { return 1; }\n";
        let ast = crate::compiler::Compiler::parse_ast_strict(&src).unwrap();
        let (py_out, py_missing) = generate_reported(&ast, "t").unwrap();
        let (js_out, js_missing) = crate::codegen_js::generate_reported(&ast, "t").unwrap();
        assert_eq!(py_missing, js_missing);
        let order = |s: &str, marker: &str| {
            s.split(marker).nth(1).unwrap().split(']').next().unwrap().to_string()
        };
        assert_eq!(order(&py_out, "__DECL_ORDER__ = ["), order(&js_out, "__DECL_ORDER__ = ["));
        assert_eq!(order(&py_out, "__STRUCT_ORDER__ = ["), order(&js_out, "__STRUCT_ORDER__ = ["));
    }
}
