//! The JavaScript backend: `t27c gen-js`.
//!
//! Why it exists. Our MCP servers run on JavaScript, and a .t27 spec that
//! describes one had no way to reach them -- so every such spec grew a
//! hand-written generator in a foreign language beside it, and the generator,
//! not the compiler, became the thing that decided what the artifact said.
//! That is a hole in the compiler wearing the costume of a build script. With
//! this backend the artifact is printed by t27c, and the bespoke generator
//! does not exist.
//!
//! Scope, stated plainly: this lowers *declarations* -- consts, enums and
//! structs -- into an ES module. It does not lower function bodies. A `fn` in
//! the input is not dropped in silence; it is announced in a comment in the
//! output, because an artifact that is quietly missing something is worse than
//! one that says what it left out.
//!
//! The emitted module is data. Nothing in it runs, so a spec cannot smuggle
//! behaviour into a server through its own description.

use crate::compiler::{quote_string_literal, Node, NodeKind, StrTarget};

/// Reserved in a module context; `export const` with one of these is a syntax
/// error, so it is refused here with a sentence rather than there with a stack.
const RESERVED: &[&str] = &[
    "await", "break", "case", "catch", "class", "const", "continue", "debugger", "default",
    "delete", "do", "else", "enum", "export", "extends", "false", "finally", "for", "function",
    "if", "import", "in", "instanceof", "let", "new", "null", "return", "static", "super",
    "switch", "this", "throw", "true", "try", "typeof", "var", "void", "while", "with", "yield",
];

pub fn generate(ast: &Node, source_name: &str) -> Result<String, String> {
    let mut out = String::new();
    out.push_str("// Generated by `t27c gen-js` from ");
    out.push_str(source_name);
    out.push_str(". Do not edit.\n");
    out.push_str("//\n");
    out.push_str("// Every name and every value here comes from that spec. Change the spec and\n");
    out.push_str("// regenerate; an edit made here is lost the next time anyone builds.\n\n");

    let mut struct_order: Vec<String> = Vec::new();
    let mut decl_order: Vec<String> = Vec::new();

    for node in &ast.children {
        match node.kind {
            NodeKind::ConstDecl => {
                let name = js_name(&node.name)?;
                let value = const_value(node)?;
                out.push_str(&format!("export const {} = {};\n", name, value));
                decl_order.push(node.name.clone());
            }
            NodeKind::EnumDecl => {
                let name = js_name(&node.name)?;
                out.push_str(&format!("export const {} = Object.freeze({{ ", name));
                let mut next = 0i64;
                let mut first = true;
                for variant in &node.children {
                    if variant.kind != NodeKind::EnumVariant {
                        continue;
                    }
                    let value = match variant.children.first() {
                        Some(child) => {
                            let rendered = expr(child)?;
                            next = rendered.parse::<i64>().unwrap_or(next) + 1;
                            rendered
                        }
                        None => {
                            let v = next.to_string();
                            next += 1;
                            v
                        }
                    };
                    if !first {
                        out.push_str(", ");
                    }
                    first = false;
                    out.push_str(&format!("{}: {}", key(&variant.name), value));
                }
                out.push_str(" });\n");
                decl_order.push(node.name.clone());
            }
            NodeKind::StructDecl => {
                let name = js_name(&node.name)?;
                let mut fields: Vec<String> = Vec::new();
                for field in &node.children {
                    if field.name.is_empty() {
                        continue;
                    }
                    fields.push(format!(
                        "[{}, {}]",
                        js_string(&field.name),
                        js_string(&field.extra_type)
                    ));
                }
                out.push_str(&format!(
                    "export const {} = Object.freeze({{ __struct__: {}, fields: [{}] }});\n",
                    name,
                    js_string(&node.name),
                    fields.join(", ")
                ));
                struct_order.push(node.name.clone());
                decl_order.push(node.name.clone());
            }
            NodeKind::UseDecl => {}
            // Announced, never dropped in silence.
            NodeKind::FnDecl => out.push_str(&format!(
                "// t27c gen-js: fn {} was not emitted -- this backend lowers declarations, not bodies.\n",
                node.name
            )),
            NodeKind::TestBlock | NodeKind::BenchBlock | NodeKind::InvariantBlock => {
                out.push_str(&format!(
                    "// t27c gen-js: a {:?} was not emitted -- it is checked by the compiler, not by the artifact.\n",
                    node.kind
                ))
            }
            _ => {
                return Err(format!(
                    "gen-js: {:?} at line {} is not something a declarations module can hold",
                    node.kind, node.line
                ))
            }
        }
    }

    out.push_str("\n// Declaration order, which the spec's own laws depend on.\n");
    out.push_str(&format!("export const __STRUCT_ORDER__ = [{}];\n", list(&struct_order)));
    out.push_str(&format!("export const __DECL_ORDER__ = [{}];\n", list(&decl_order)));
    Ok(out)
}

fn list(names: &[String]) -> String {
    names.iter().map(|n| js_string(n)).collect::<Vec<_>>().join(", ")
}

/// A const's value, read with its declared type in hand.
fn const_value(node: &Node) -> Result<String, String> {
    let child = node
        .children
        .first()
        .ok_or_else(|| format!("gen-js: const {} has no value", node.name))?;

    // `[4]str = [POST, PUT, PATCH, DELETE]` -- the parser hands back the whole
    // bracketed text as one bare word, so the element type has to come from the
    // declaration. The declared length is then a real check: a literal that
    // does not have the length its own type claims is refused here rather than
    // shipped as a short array.
    if let Some((count, elem)) = array_type(&node.extra_type) {
        let items = array_items(child)?;
        if items.len() != count {
            return Err(format!(
                "gen-js: {} is declared [{}]{} but its literal has {} element(s)",
                node.name,
                count,
                elem,
                items.len()
            ));
        }
        let rendered: Result<Vec<String>, String> = items
            .iter()
            .map(|item| {
                if elem == "str" {
                    Ok(js_string(item))
                } else if is_number(item) {
                    Ok(item.clone())
                } else {
                    Err(format!(
                        "gen-js: {} is declared [{}]{} but {:?} is not a {}",
                        node.name, count, elem, item, elem
                    ))
                }
            })
            .collect();
        return Ok(format!("[{}]", rendered?.join(", ")));
    }

    expr(child)
}

fn array_type(t: &str) -> Option<(usize, String)> {
    let rest = t.strip_prefix('[')?;
    let (count, elem) = rest.split_once(']')?;
    Some((count.trim().parse().ok()?, elem.trim().to_string()))
}

fn array_items(child: &Node) -> Result<Vec<String>, String> {
    if child.kind == NodeKind::ExprArrayLiteral {
        return child
            .children
            .iter()
            .map(|c| Ok(if c.value.is_empty() { c.name.clone() } else { c.value.clone() }))
            .collect();
    }
    // The bare-word path: the parser hands the whole bracketed text back as one
    // word with the element quotes already gone, so there is nothing to strip.
    let text = if child.name.is_empty() { &child.value } else { &child.name };
    let inner = text
        .trim()
        .strip_prefix('[')
        .and_then(|s| s.strip_suffix(']'))
        .ok_or_else(|| format!("gen-js: {:?} is not an array literal", text))?;
    if inner.trim().is_empty() {
        return Ok(Vec::new());
    }
    Ok(inner
        .split(',')
        .map(|p| p.trim().to_string())
        .collect())
}

fn expr(node: &Node) -> Result<String, String> {
    match &node.kind {
        NodeKind::ExprLiteral => {
            // `is_string_literal` asks the one question that matters: was this
            // written in quotes? The answer is the difference between a string
            // and a reference to something with the same spelling.
            //
            // `node.value` is the DECODED text, already without its quotes.
            // Stripping a leading and trailing quote here as well -- which this
            // backend used to do, to tolerate an older parser -- eats the real
            // ones off a value like `"\"wrapped\""` and emits `"wrapped"`.
            if node.is_string_literal() || node.extra_kind == "char" {
                return Ok(js_string(&node.value));
            }
            if is_number(&node.value) {
                return Ok(node.value.clone());
            }
            match node.value.as_str() {
                "true" | "false" | "null" => Ok(node.value.clone()),
                other => Err(format!(
                    "gen-js: literal {:?} at line {} has no JavaScript spelling",
                    other, node.line
                )),
            }
        }
        NodeKind::ExprIdentifier => match node.name.as_str() {
            "true" | "false" | "null" => Ok(node.name.clone()),
            name if name.starts_with('[') => {
                // An array without a declared length: the elements are taken as
                // written, which is all the parser preserved of them.
                let items = array_items(node)?;
                Ok(format!(
                    "[{}]",
                    items
                        .iter()
                        .map(|i| if is_number(i) { i.clone() } else { js_string(i) })
                        .collect::<Vec<_>>()
                        .join(", ")
                ))
            }
            name if is_number(name) => Ok(name.to_string()),
            name => Ok(js_name(name)?), // a reference to a const declared above
        },
        NodeKind::ExprEnumValue => {
            let holder = if node.name.is_empty() { &node.extra_type } else { &node.name };
            let variant = if node.extra_field.is_empty() { &node.value } else { &node.extra_field };
            if holder.is_empty() || variant.is_empty() {
                return Err(format!("gen-js: an enum value at line {} names no variant", node.line));
            }
            Ok(format!("{}[{}]", js_name(holder)?, js_string(variant)))
        }
        NodeKind::ExprArrayLiteral => {
            let items: Result<Vec<String>, String> = node.children.iter().map(expr).collect();
            Ok(format!("[{}]", items?.join(", ")))
        }
        other => Err(format!(
            "gen-js: {:?} at line {} is not a constant expression. This backend emits data, never code.",
            other, node.line
        )),
    }
}

fn is_number(s: &str) -> bool {
    let s = s.strip_prefix('-').unwrap_or(s);
    if s.is_empty() {
        return false;
    }
    let lower = s.to_ascii_lowercase();
    for (prefix, radix) in [("0x", 16u32), ("0b", 2), ("0o", 8)] {
        if let Some(digits) = lower.strip_prefix(prefix) {
            return !digits.is_empty()
                && digits.chars().all(|c| c == '_' || c.is_digit(radix));
        }
    }
    let mut seen_digit = false;
    let mut seen_dot = false;
    for c in s.chars() {
        match c {
            '0'..='9' => seen_digit = true,
            '_' => {}
            '.' if !seen_dot => seen_dot = true,
            _ => return false,
        }
    }
    seen_digit
}

fn js_name(name: &str) -> Result<String, String> {
    let mut chars = name.chars();
    let valid = match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' || c == '$' => {
            chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
        }
        _ => false,
    };
    if !valid {
        return Err(format!("gen-js: {:?} is not a name JavaScript can bind", name));
    }
    if RESERVED.contains(&name) {
        return Err(format!("gen-js: {:?} is a JavaScript keyword; rename it in the spec", name));
    }
    Ok(name.to_string())
}

/// An object key: quoted unless it is plainly an identifier, so a variant named
/// `default` is legal in the output.
fn key(name: &str) -> String {
    match js_name(name) {
        Ok(n) => n,
        Err(_) => js_string(name),
    }
}

/// The escape table lives in `compiler::quote_string_literal`, once, for every
/// backend. This is the JavaScript arm of it and nothing more -- a second copy
/// here would be a rule written down twice, which is how the copies drift.
fn js_string(s: &str) -> String {
    quote_string_literal(s, StrTarget::Js)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn lit(value: &str, kind: &str) -> Node {
        Node {
            kind: NodeKind::ExprLiteral,
            value: value.to_string(),
            extra_kind: kind.to_string(),
            ..Default::default()
        }
    }

    #[test]
    fn a_string_keeps_its_quotes() {
        // The defect this backend was written beside: every other emitter
        // printed `habr_search` where `"habr_search"` belonged.
        assert_eq!(expr(&lit("habr_search", "string")).unwrap(), "\"habr_search\"");
    }

    #[test]
    fn a_value_wrapped_in_real_quotes_keeps_them() {
        // `pub const W: str = "\"wrapped\"";` decodes to a value whose first and
        // last characters are quotes. The tolerate-an-older-parser strip this
        // backend used to do ate them and emitted `"wrapped"` -- the string
        // without the quotes that were its content.
        assert_eq!(
            expr(&lit("\"wrapped\"", "string")).unwrap(),
            "\"\\\"wrapped\\\"\""
        );
    }

    #[test]
    fn a_line_separator_cannot_break_the_emitted_module() {
        // U+2028 ends a line inside a JS string literal even between quotes, so
        // an unescaped one is a syntax error in the artifact, not a character.
        assert_eq!(
            expr(&lit("a\u{2028}b", "string")).unwrap(),
            "\"a\\u2028b\""
        );
    }

    #[test]
    fn a_number_is_not_a_string() {
        assert_eq!(expr(&lit("20", "")).unwrap(), "20");
        assert_eq!(expr(&lit("0x1f", "")).unwrap(), "0x1f");
    }

    #[test]
    fn an_unquoted_word_is_a_reference_not_a_string() {
        let node = Node {
            kind: NodeKind::ExprIdentifier,
            name: "PAGE_MIN".to_string(),
            ..Default::default()
        };
        assert_eq!(expr(&node).unwrap(), "PAGE_MIN");
    }

    #[test]
    fn quotes_and_newlines_survive_a_description() {
        assert_eq!(js_string("say \"no\"\n"), "\"say \\\"no\\\"\\n\"");
    }

    #[test]
    fn a_keyword_is_refused_rather_than_emitted() {
        assert!(js_name("class").is_err());
        assert!(js_name("2fast").is_err());
        assert!(js_name("HabrSearch").is_ok());
    }

    #[test]
    fn a_short_array_is_refused_by_its_own_declared_length() {
        let node = Node {
            kind: NodeKind::ConstDecl,
            name: "WRITE_METHODS".to_string(),
            extra_type: "[4]str".to_string(),
            children: vec![Node {
                kind: NodeKind::ExprIdentifier,
                name: "[POST,PUT,DELETE]".to_string(),
                ..Default::default()
            }],
            ..Default::default()
        };
        let err = const_value(&node).unwrap_err();
        assert!(err.contains("3 element"), "{}", err);
    }

    #[test]
    fn an_array_of_strings_is_quoted_elementwise() {
        let node = Node {
            kind: NodeKind::ConstDecl,
            name: "WRITE_METHODS".to_string(),
            extra_type: "[2]str".to_string(),
            children: vec![Node {
                kind: NodeKind::ExprIdentifier,
                name: "[POST, PUT]".to_string(),
                ..Default::default()
            }],
            ..Default::default()
        };
        assert_eq!(const_value(&node).unwrap(), "[\"POST\", \"PUT\"]");
    }

    #[test]
    fn a_function_is_announced_not_dropped() {
        let ast = Node {
            kind: NodeKind::Module,
            children: vec![Node {
                kind: NodeKind::FnDecl,
                name: "helper".to_string(),
                ..Default::default()
            }],
            ..Default::default()
        };
        let out = generate(&ast, "x.t27").unwrap();
        assert!(out.contains("fn helper was not emitted"), "{}", out);
    }
}
