//! Phi-invariant golden-identity self-check emitter (Wave 35, R-SC-1).
//!
//! Emits a self-contained SystemVerilog snippet that verifies the sacred
//! trinity numeric kernel identity `phi^2 + 1/phi^2 = 3` at elaboration time
//! via an `initial begin ... $fatal(...) ... end` block.
//!
//! Algorithm ported from `gHashTag/vibee-lang`
//! `src/vibeec/verilog_codegen.zig` lines 2388-2403 (sacred identity localparam
//! block plus initial $fatal). Original author: Dmitrii Vasilev.
//!
//! Constitutional notes:
//!   L2: lives only under `bootstrap/`; emits a snippet — it does NOT modify
//!       the numeric kernel itself (L5) nor any spec (L6).
//!   L3: ASCII source, English doc-comments only.
//!   L7: no `*.sh` invoked.

/// High-precision decimal approximation of the golden ratio (phi).
///
/// 19 decimal digits — sufficient for any IEEE-754 `real` evaluation
/// performed by SystemVerilog simulators during elaboration.
pub const PHI_LITERAL: &str = "1.6180339887498948482";

/// Default symmetric tolerance window around the expected value `3.0`.
///
/// Matches the vibee-lang upstream window `[2.99, 3.01]` (i.e. 0.01).
pub const DEFAULT_TOLERANCE: f64 = 0.01;

/// Build the golden-identity self-check snippet.
///
/// The returned string contains, in order:
///   * a banner comment block,
///   * `localparam real PHI`,
///   * `localparam real GOLDEN_IDENTITY = PHI*PHI + 1.0/(PHI*PHI)`,
///   * an `initial begin` block whose body fires `$fatal(1, ...)` when the
///     identity drifts outside `[3.0 - tolerance, 3.0 + tolerance]`.
///
/// The snippet is meant to be pasted inside a `module ... endmodule` body
/// guarded by `` `ifdef FORMAL `` (consistent with vibee-lang's emission).
///
/// `tolerance` must be strictly positive; non-finite or non-positive values
/// fall back to `DEFAULT_TOLERANCE` to preserve the kernel invariant.
pub fn build_phi_selfcheck(tolerance: f64) -> String {
    let tol = if tolerance.is_finite() && tolerance > 0.0 {
        tolerance
    } else {
        DEFAULT_TOLERANCE
    };
    let lower = 3.0_f64 - tol;
    let upper = 3.0_f64 + tol;

    let mut out = String::new();
    out.push_str("// ===========================================================================\n");
    out.push_str("// SACRED IDENTITY ASSERTION (phi^2 + 1/phi^2 = 3)\n");
    out.push_str("// ===========================================================================\n");
    out.push_str("// Generated by t27c gen-phi-selfcheck (Wave 35, R-SC-1).\n");
    out.push_str("// Verifies the trinity numeric kernel invariant at elaboration time.\n");
    out.push_str("\n");
    out.push_str(&format!("localparam real PHI = {};\n", PHI_LITERAL));
    out.push_str("localparam real GOLDEN_IDENTITY = PHI * PHI + 1.0 / (PHI * PHI);\n");
    out.push_str("\n");
    out.push_str("// Compile-time / elaboration-time check (synthesis will optimize this).\n");
    out.push_str("initial begin\n");
    out.push_str(&format!(
        "    if (GOLDEN_IDENTITY < {:.6} || GOLDEN_IDENTITY > {:.6})\n",
        lower, upper
    ));
    out.push_str(
        "        $fatal(1, \"Golden Identity violated: phi^2 + 1/phi^2 != 3\");\n",
    );
    out.push_str("end\n");

    out
}

/// Build a fully self-contained SystemVerilog formal module that wraps the
/// self-check snippet, suitable for direct simulation.
///
/// The wrapper module is named `<module_name>` and is enclosed in an
/// `` `ifdef FORMAL `` / `` `endif `` guard, mirroring the convention used by
/// vibee-lang for sacred-identity emission.
pub fn build_phi_selfcheck_module(module_name: &str, tolerance: f64) -> String {
    let inner = build_phi_selfcheck(tolerance);
    let mut out = String::new();
    out.push_str("`ifdef FORMAL\n");
    out.push_str(&format!("module {} ();\n", module_name));
    for line in inner.lines() {
        if line.is_empty() {
            out.push('\n');
        } else {
            out.push_str("    ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str("endmodule\n");
    out.push_str("`endif // FORMAL\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn snippet_contains_phi_literal() {
        let s = build_phi_selfcheck(DEFAULT_TOLERANCE);
        assert!(s.contains("1.6180339887498948482"));
    }

    #[test]
    fn snippet_contains_golden_identity_localparam() {
        let s = build_phi_selfcheck(DEFAULT_TOLERANCE);
        assert!(s.contains("localparam real GOLDEN_IDENTITY ="));
        assert!(s.contains("PHI * PHI + 1.0 / (PHI * PHI)"));
    }

    #[test]
    fn snippet_contains_initial_begin_end() {
        let s = build_phi_selfcheck(DEFAULT_TOLERANCE);
        assert!(s.contains("initial begin"));
        assert!(s.contains("end\n"));
    }

    #[test]
    fn snippet_contains_fatal_call() {
        let s = build_phi_selfcheck(DEFAULT_TOLERANCE);
        assert!(s.contains("$fatal(1,"));
        assert!(s.contains("Golden Identity violated"));
    }

    #[test]
    fn default_tolerance_window_is_2_99_to_3_01() {
        let s = build_phi_selfcheck(DEFAULT_TOLERANCE);
        assert!(s.contains("2.990000"));
        assert!(s.contains("3.010000"));
    }

    #[test]
    fn custom_tolerance_propagates() {
        let s = build_phi_selfcheck(0.005);
        assert!(s.contains("2.995000"));
        assert!(s.contains("3.005000"));
    }

    #[test]
    fn nonpositive_tolerance_falls_back_to_default() {
        let s = build_phi_selfcheck(0.0);
        assert!(s.contains("2.990000"));
        assert!(s.contains("3.010000"));
    }

    #[test]
    fn negative_tolerance_falls_back_to_default() {
        let s = build_phi_selfcheck(-1.0);
        assert!(s.contains("2.990000"));
        assert!(s.contains("3.010000"));
    }

    #[test]
    fn nan_tolerance_falls_back_to_default() {
        let s = build_phi_selfcheck(f64::NAN);
        assert!(s.contains("2.990000"));
        assert!(s.contains("3.010000"));
    }

    #[test]
    fn module_wrapper_has_formal_guard() {
        let m = build_phi_selfcheck_module("phi_selfcheck", DEFAULT_TOLERANCE);
        assert!(m.starts_with("`ifdef FORMAL"));
        assert!(m.trim_end().ends_with("`endif // FORMAL"));
        assert!(m.contains("module phi_selfcheck ();"));
        assert!(m.contains("endmodule"));
    }

    #[test]
    fn module_wrapper_indents_inner_lines() {
        let m = build_phi_selfcheck_module("phi_selfcheck", DEFAULT_TOLERANCE);
        // Every non-empty body line that is not the module/endmodule/ifdef
        // markers must start with four spaces.
        for line in m.lines() {
            if line.is_empty() {
                continue;
            }
            if line.starts_with('`') {
                continue;
            }
            if line.starts_with("module ") || line.starts_with("endmodule") {
                continue;
            }
            assert!(
                line.starts_with("    "),
                "expected 4-space indent for line: {:?}",
                line
            );
        }
    }

    #[test]
    fn module_wrapper_uses_custom_name() {
        let m = build_phi_selfcheck_module("custom_top", DEFAULT_TOLERANCE);
        assert!(m.contains("module custom_top ();"));
    }

    #[test]
    fn snippet_is_ascii_only() {
        let s = build_phi_selfcheck(DEFAULT_TOLERANCE);
        assert!(s.is_ascii(), "snippet must be ASCII-only (L3)");
        let m = build_phi_selfcheck_module("phi_selfcheck", DEFAULT_TOLERANCE);
        assert!(m.is_ascii(), "module wrapper must be ASCII-only (L3)");
    }
}
