//! W599: per-test pass/fail for one spec, as a command.
//!
//! ## Why this exists
//!
//! Zig's default test runner aborts the process on the first panic, so a spec
//! that fails its fifth test reports "4 passed" and stops. W596 could therefore
//! say only *"cordic.t27 runs, four tests pass, then it stops"* — a floor, not
//! a measurement. W597 got the real number (321 of 336) by driving
//! `zig test --test-filter` in a shell loop, once per test.
//!
//! That loop cost **45 minutes and 6.1 GB of build cache, and it filled the
//! disk**, because `--test-filter` recompiles the entire file for every filter:
//! 336 tests meant 336 full compilations of the same source.
//!
//! ## What this does instead
//!
//! Compile **once** with a custom test runner that runs exactly one test per
//! process, selected by index:
//!
//! ```text
//!   ./bin              -> lists "index<TAB>name" for every test
//!   ./bin 47           -> runs test 47 only; exit 0 = pass, 1 = fail
//! ```
//!
//! One compilation, then N process spawns. The same 336 tests that took 45
//! minutes take **1.1 seconds**, and the answer is identical: 330 pass, 6 fail.
//!
//! Every number this chain trusts is a command — `lex-conform`,
//! `parse-conform`, `cc-gate`, `check-calls`, `impl-status`, `parse-complete`.
//! This was the last one still done by hand.

use crate::compiler::{Compiler, Node, NodeKind};
use std::path::Path;
use std::process::Command;

pub struct Outcome {
    pub name: String,
    pub passed: bool,
}

pub struct Report {
    pub spec: String,
    pub total: usize,
    pub passed: usize,
    pub failed: usize,
    pub outcomes: Vec<Outcome>,
    /// W601: `invariant` blocks lower to comptime assertions, not test
    /// functions -- so a spec that asserts six invariants and no tests shows
    /// `tests 0` and would be filed under NO TESTS. It is not: **if the spec
    /// compiles, every one of its invariants held.** Counting them separately
    /// is what keeps the corpus table honest.
    pub invariants: usize,
    /// W602: the spec declares NOTHING -- no fn, no const, no struct. It is a
    /// module header and a comment banner, typically ~327 bytes. Calling these
    /// L4 TESTABILITY violations overstates the debt by nearly double: they are
    /// **unwritten**, which is W586's category, and the remedy is to write the
    /// spec, not to add a test to a file with nothing in it.
    pub stub: bool,
    /// Set when the spec never got as far as a runnable binary.
    pub blocked: Option<String>,
}

impl Report {
    fn blocked(spec: &str, why: impl Into<String>) -> Self {
        Report {
            spec: spec.to_string(),
            total: 0,
            passed: 0,
            failed: 0,
            outcomes: Vec::new(),
            invariants: 0,
            stub: false,
            blocked: Some(why.into()),
        }
    }
}

/// A test runner that runs ONE test per process. Written next to the generated
/// source so `zig test --test-runner` can find it.
const RUNNER: &str = r#"//! Generated by `t27c test-report`. Runs one test per process.
const builtin = @import("builtin");
const std = @import("std");

pub fn main(init: std.process.Init.Minimal) void {
    @disableInstrumentation();
    const tests = builtin.test_functions;
    var fba_buf: [8192]u8 = undefined;
    var fba: std.heap.FixedBufferAllocator = .init(&fba_buf);
    const args = init.args.toSlice(fba.allocator()) catch std.process.exit(3);

    if (args.len < 2) {
        var buf: [4096]u8 = undefined;
        var w: std.Io.File.Writer = .initStreaming(
            .stdout(),
            std.Io.Threaded.global_single_threaded.io(),
            &buf,
        );
        for (tests, 0..) |t, i| w.interface.print("{d}\t{s}\n", .{ i, t.name }) catch {};
        w.interface.flush() catch {};
        std.process.exit(0);
    }
    const i = std.fmt.parseInt(usize, args[1], 10) catch std.process.exit(3);
    if (i >= tests.len) std.process.exit(3);
    tests[i].func() catch std.process.exit(1);
    std.process.exit(0);
}
"#;

fn zig_available() -> bool {
    Command::new("zig")
        .arg("version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

pub fn run(spec: &Path, specs_root: &Path) -> Report {
    let label = spec.to_string_lossy().to_string();
    if !zig_available() {
        return Report::blocked(&label, "zig not on PATH");
    }
    let raw = match std::fs::read_to_string(spec) {
        Ok(s) => s,
        Err(e) => return Report::blocked(&label, format!("unreadable: {}", e)),
    };
    // Same resolution `gen` performs, so this measures what the command emits.
    let resolved = crate::use_resolve::resolve(spec, &raw);
    let code = match Compiler::compile(&resolved).or_else(|_| Compiler::compile(&raw)) {
        Ok(c) if !c.is_empty() => c,
        Ok(_) => return Report::blocked(&label, "generated no code"),
        Err(e) => return Report::blocked(&label, format!("codegen failed: {}", e)),
    };
    let _ = specs_root;
    // Counted from the AST, because they never reach `builtin.test_functions`.
    let ast = Compiler::parse_ast(&resolved).or_else(|_| Compiler::parse_ast(&raw));
    let invariants = ast
        .as_ref()
        .map(|a| {
            a.children
                .iter()
                .filter(|c| c.kind == NodeKind::InvariantBlock)
                .count()
        })
        .unwrap_or(0);
    let declares = |a: &Node| {
        a.children.iter().any(|c| {
            matches!(
                c.kind,
                NodeKind::FnDecl | NodeKind::ConstDecl | NodeKind::StructDecl
            )
        })
    };
    let stub = ast.as_ref().map(|a| !declares(a)).unwrap_or(false);

    // The process id is part of the name: two specs share a stem more often
    // than not (`pattern.t27` lives in three directories), and `seal --save`
    // now runs this for every spec it seals -- so a bulk reseal running two
    // at once would otherwise delete each other's binaries mid-measurement.
    let dir = std::env::temp_dir().join(format!(
        "t27c-test-report-{}-{}",
        spec.file_stem().map(|s| s.to_string_lossy().to_string()).unwrap_or_default(),
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&dir);
    if std::fs::create_dir_all(&dir).is_err() {
        return Report::blocked(&label, "could not create a working directory");
    }
    let src = dir.join("spec.zig");
    let runner = dir.join("runner.zig");
    let bin = dir.join("spec_tests");
    if std::fs::write(&src, &code).is_err() || std::fs::write(&runner, RUNNER).is_err() {
        return Report::blocked(&label, "could not write the generated source");
    }

    // ONE compilation. This is the whole point.
    let build = Command::new("zig")
        .arg("test")
        .arg("--test-runner")
        .arg(&runner)
        .arg("--test-no-exec")
        .arg(format!("-femit-bin={}", bin.display()))
        .arg(&src)
        .output();
    let build = match build {
        Ok(o) => o,
        Err(e) => return Report::blocked(&label, format!("could not run zig: {}", e)),
    };
    if !build.status.success() {
        let err = String::from_utf8_lossy(&build.stderr);
        let first = err
            .lines()
            .find(|l| l.contains("error:"))
            .unwrap_or("(no error line)")
            .trim()
            .to_string();
        // A comptime-folded assertion reports at the helper, and names the
        // author's line only on the following `note:` -- which is the line
        // anyone reading this actually wants. Carry it through.
        let site = err
            .lines()
            .find(|l| l.contains("note:") && l.contains("comptime"))
            .map(|l| l.trim().to_string());
        let _ = std::fs::remove_dir_all(&dir);
        // #6083: a `zig test` failure names machine-local directories -- the
        // temp dir in a genuine block, the owner's home in a cache miss -- and
        // both reached the printed report and the seal verbatim. Reduce every
        // absolute path to its file name before the message is stored.
        let msg = match site {
            Some(s) => format!(
                "does not compile: {}\n           {}",
                strip_paths(&first),
                strip_paths(&s)
            ),
            None => format!("does not compile: {}", strip_paths(&first)),
        };
        return Report::blocked(&label, msg);
    }

    let listing = match Command::new(&bin).output() {
        Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout).to_string(),
        _ => {
            let _ = std::fs::remove_dir_all(&dir);
            return Report::blocked(&label, "the test binary would not list its tests");
        }
    };

    let mut outcomes = Vec::new();
    for line in listing.lines() {
        let mut parts = line.splitn(2, '\t');
        let (idx, name) = match (parts.next(), parts.next()) {
            (Some(i), Some(n)) => (i, n),
            _ => continue,
        };
        let passed = Command::new(&bin)
            .arg(idx)
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false);
        // Strip the `spec.test.` prefix the runner reports.
        let name = name.rsplit(".test.").next().unwrap_or(name).to_string();
        outcomes.push(Outcome { name, passed });
    }
    let _ = std::fs::remove_dir_all(&dir);

    let passed = outcomes.iter().filter(|o| o.passed).count();
    let total = outcomes.len();
    Report {
        spec: label,
        total,
        passed,
        failed: total - passed,
        outcomes,
        invariants,
        stub,
        blocked: None,
    }
}

/// What `t27c seal --save` does with a spec's own tests (#5577).
///
/// A seal records that a spec produced these four outputs, and every reader
/// of the store takes it as "this spec is in order". `seal --save` used to
/// refuse only when a backend could not GENERATE, and never ran a test: #5578
/// resealed 336 specs that way, 13 of them with tests that fail (merge_sort
/// 0/2, mse_loss 0/3, timing_tb 9/10). The seal-coverage gate compares hashes,
/// so from that commit on those seals read as holding.
///
/// The three outcomes are kept apart on purpose, the way `test-report` keeps
/// them apart. BLOCKED never produced a binary -- no zig, or generated Zig that
/// does not compile -- and the repository's rule is that blocked is not
/// failing, so it does not stop a seal; it is printed and recorded. A FAIL is
/// a test the spec wrote about itself coming back false, and that stops it.
#[derive(Debug, PartialEq)]
pub enum SealVerdict {
    /// Every test that ran passed (or there were none to run).
    Pass,
    /// No per-test result exists. Saved, with the reason on the record.
    Blocked(String),
    /// At least one test failed. Not saved.
    Refuse(Vec<String>),
    /// At least one test failed and `--force` was given. Saved, and the
    /// failures go into the seal so it cannot be read as vouching for them.
    Forced(Vec<String>),
}

pub fn seal_verdict(r: &Report, force: bool) -> SealVerdict {
    if let Some(why) = &r.blocked {
        return SealVerdict::Blocked(why.clone());
    }
    let failed: Vec<String> = r
        .outcomes
        .iter()
        .filter(|o| !o.passed)
        .map(|o| o.name.clone())
        .collect();
    // `failed` is the field every printer reads; the names are what a person
    // needs. Either one being non-zero is a failure.
    if failed.is_empty() && r.failed == 0 {
        SealVerdict::Pass
    } else if force {
        SealVerdict::Forced(failed)
    } else {
        SealVerdict::Refuse(failed)
    }
}

/// The `tests` object written into a seal: what was measured when it was minted.
///
/// `tools/check_seal_coverage.py` reads `failed` back. A seal that records a
/// failing test is reported as `tests-fail`, so a forced seal is on the record
/// the same way a hollow (`gen_hash=none`) one is, rather than reading as
/// holding.
pub fn seal_record(r: &Report, v: &SealVerdict) -> serde_json::Value {
    match v {
        SealVerdict::Blocked(why) => serde_json::json!({
            "blocked": why.lines().next().unwrap_or(""),
        }),
        SealVerdict::Pass | SealVerdict::Refuse(_) | SealVerdict::Forced(_) => {
            let failing: Vec<&String> = match v {
                SealVerdict::Refuse(f) | SealVerdict::Forced(f) => f.iter().collect(),
                _ => Vec::new(),
            };
            serde_json::json!({
                "total": r.total,
                "passed": r.passed,
                "failed": r.failed,
                "failing": failing,
                "forced": matches!(v, SealVerdict::Forced(_)),
            })
        }
    }
}

/// W600: the same measurement over a whole tree.
///
/// Reports are returned in path order. A spec that never reaches a binary comes
/// back `blocked` and contributes nothing to the totals -- the distinction
/// W586 drew between *unwritten* and *broken* applies here too, and collapsing
/// it is the mistake that took twenty-five waves to notice the first time.
pub struct TreeReport {
    pub reports: Vec<Report>,
    /// Compiled AND declares at least one test. Only these have a rate.
    pub measured: usize,
    /// Compiled but declares NOTHING AT ALL -- no fn, no const, no struct.
    /// Unwritten, not untested (W602).
    pub stubs: usize,
    /// Compiled, has declarations, but nothing to check AT ALL -- no tests and no
    /// invariants. **This is an L4 TESTABILITY violation**, not a spec with a
    /// 0% pass rate; the first run of this command reported 68 "measured" of
    /// which 38 were this, and averaging them in as zeroes is the same collapse
    /// W586 removed from the harness.
    pub no_tests: usize,
    /// Compiled and has invariants but no tests. Its invariants are comptime,
    /// so **compiling IS the verification** -- these are checked, not unchecked.
    pub invariants_only: usize,
    /// Total invariant blocks proved by compilation, across every spec.
    pub invariants: usize,
    /// Never produced a binary.
    pub blocked: usize,
    pub tests: usize,
    pub passed: usize,
    pub failed: usize,
    /// Specs measured at 100%.
    pub perfect: usize,
}

fn spec_files(root: &Path, include_scratch: bool) -> Vec<std::path::PathBuf> {
    let mut files = Vec::new();
    let mut stack = vec![root.to_path_buf()];
    while let Some(dir) = stack.pop() {
        let entries = match std::fs::read_dir(&dir) {
            Ok(e) => e,
            Err(_) => continue,
        };
        for entry in entries.flatten() {
            let p = entry.path();
            if p.is_dir() {
                if !include_scratch && p.file_name().map(|n| n == "scratch").unwrap_or(false) {
                    continue;
                }
                stack.push(p);
            } else if p.extension().and_then(|e| e.to_str()) == Some("t27") {
                files.push(p);
            }
        }
    }
    files.sort();
    files
}

pub fn run_tree(specs_root: &Path, include_scratch: bool) -> TreeReport {
    let mut t = TreeReport {
        reports: Vec::new(),
        measured: 0,
        stubs: 0,
        no_tests: 0,
        invariants_only: 0,
        invariants: 0,
        blocked: 0,
        tests: 0,
        passed: 0,
        failed: 0,
        perfect: 0,
    };
    for f in spec_files(specs_root, include_scratch) {
        let r = run(&f, specs_root);
        if r.blocked.is_some() {
            t.blocked += 1;
        } else if r.total == 0 {
            t.invariants += r.invariants;
            if r.invariants > 0 {
                t.invariants_only += 1;
            } else if r.stub {
                t.stubs += 1;
            } else {
                t.no_tests += 1;
            }
        } else {
            t.invariants += r.invariants;
            t.measured += 1;
            t.tests += r.total;
            t.passed += r.passed;
            t.failed += r.failed;
            if r.failed == 0 {
                t.perfect += 1;
            }
        }
        t.reports.push(r);
    }
    t
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_blocked_spec_contributes_nothing_to_the_totals() {
        // The distinction W586 drew: a spec that never produced a binary is
        // not a spec with a 0% pass rate.
        let t = TreeReport {
            reports: vec![Report::blocked("x.t27", "no binary")],
            measured: 0,
            stubs: 0,
            no_tests: 0,
            invariants_only: 0,
            invariants: 0,
            blocked: 1,
            tests: 0,
            passed: 0,
            failed: 0,
            perfect: 0,
        };
        assert_eq!(t.tests, 0);
        assert_eq!(t.measured, 0);
    }

    #[test]
    fn the_runner_selects_one_test_by_index() {
        // The contract this module depends on, stated as text so a change to
        // the runner that breaks it is visible here.
        assert!(RUNNER.contains("tests[i].func()"));
        assert!(RUNNER.contains("std.process.exit(1)"));
        assert!(RUNNER.contains("args.len < 2"));
    }

    fn measured(results: &[(&str, bool)]) -> Report {
        let outcomes: Vec<Outcome> = results
            .iter()
            .map(|(n, p)| Outcome { name: n.to_string(), passed: *p })
            .collect();
        let passed = outcomes.iter().filter(|o| o.passed).count();
        Report {
            spec: "x.t27".into(),
            total: outcomes.len(),
            passed,
            failed: outcomes.len() - passed,
            outcomes,
            invariants: 0,
            stub: false,
            blocked: None,
        }
    }

    #[test]
    fn a_failing_test_refuses_the_seal_and_names_the_test() {
        let r = measured(&[("sort_basic_case", false), ("sort_empty", true)]);
        assert_eq!(
            seal_verdict(&r, false),
            SealVerdict::Refuse(vec!["sort_basic_case".into()])
        );
    }

    #[test]
    fn force_records_the_failure_instead_of_hiding_it() {
        let r = measured(&[("a", false)]);
        let v = seal_verdict(&r, true);
        assert_eq!(v, SealVerdict::Forced(vec!["a".into()]));
        let rec = seal_record(&r, &v);
        assert_eq!(rec["failed"], 1);
        assert_eq!(rec["forced"], true);
        assert_eq!(rec["failing"][0], "a");
    }

    #[test]
    fn all_passing_and_no_tests_both_seal() {
        assert_eq!(seal_verdict(&measured(&[("a", true)]), false), SealVerdict::Pass);
        assert_eq!(seal_verdict(&measured(&[]), false), SealVerdict::Pass);
    }

    #[test]
    fn blocked_is_not_failing() {
        let r = Report::blocked("x.t27", "zig not on PATH");
        let v = seal_verdict(&r, false);
        assert_eq!(v, SealVerdict::Blocked("zig not on PATH".into()));
        assert_eq!(seal_record(&r, &v)["blocked"], "zig not on PATH");
    }

    #[test]
    fn a_blocked_report_counts_nothing() {
        let r = Report::blocked("x.t27", "no zig");
        assert_eq!(r.total, 0);
        assert_eq!(r.passed, 0);
        assert!(r.blocked.is_some());
    }
}
