//! Wave 32 -- R-TS-1 (Trit Stdlib #1)
//!
//! Synthesizable balanced-ternary HW primitive library.
//!
//! Emits one self-contained Verilog file with 7 modules:
//!     trit_not, trit_and, trit_or,
//!     trit_half_adder, trit_full_adder, trit_multiply,
//!     trit3_add
//!
//! Encoding (all modules): 2'b00 = -1 (TRIT_N), 2'b01 = 0 (TRIT_Z), 2'b10 = +1 (TRIT_P).
//! 2'b11 is reserved/invalid and falls through to TRIT_Z in muxes (safe default).
//!
//! Algorithms and truth-tables ported from gHashTag/vibee-lang
//! src/vibeec/verilog_codegen.zig (Zig). Original author: Dmitrii Vasilev.
//!
//! Zero dependencies on other bootstrap modules. Pure string emission.
//!
//! Closes #751.

/// Build the complete trit-stdlib Verilog source as one string.
///
/// The output is fully synthesizable by Yosys 0.36+ and iverilog 11+.
/// All modules use only `wire` ports and `assign` statements (combinational),
/// except `trit3_add` which is structural (3 x trit_full_adder instances).
pub fn build_trit_stdlib_verilog() -> String {
    let mut out = String::with_capacity(8192);
    out.push_str(HEADER);
    out.push_str(MOD_TRIT_NOT);
    out.push_str(MOD_TRIT_AND);
    out.push_str(MOD_TRIT_OR);
    out.push_str(MOD_TRIT_HALF_ADDER);
    out.push_str(MOD_TRIT_FULL_ADDER);
    out.push_str(MOD_TRIT_MULTIPLY);
    out.push_str(MOD_TRIT3_ADD);
    out.push_str(FOOTER);
    out
}

const HEADER: &str = "\
// ============================================================================
// Trit Stdlib -- synthesizable balanced-ternary HW primitive library
// Generated by t27c gen-trit-stdlib (Wave 32, R-TS-1, Closes #751)
//
// Encoding: 2'b00 = -1 (TRIT_N), 2'b01 = 0 (TRIT_Z), 2'b10 = +1 (TRIT_P)
// 2'b11 is reserved/invalid (mux fall-through is TRIT_Z).
//
// Algorithms ported from gHashTag/vibee-lang src/vibeec/verilog_codegen.zig.
// Original ternary primitive author: Dmitrii Vasilev.
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

";

const FOOTER: &str = "\
`default_nettype wire
// ============================================================================
// End of trit stdlib (7 modules).
// ============================================================================
";

const MOD_TRIT_NOT: &str = "\
// ----------------------------------------------------------------------------
// trit_not -- Ternary negation
//   NOT(-1) = +1, NOT(0) = 0, NOT(+1) = -1
// ----------------------------------------------------------------------------
module trit_not (
    input  wire [1:0] a,
    output wire [1:0] result
);
    localparam [1:0] TRIT_N = 2'b00;
    localparam [1:0] TRIT_Z = 2'b01;
    localparam [1:0] TRIT_P = 2'b10;

    assign result = (a == TRIT_Z) ? TRIT_Z :
                    (a == TRIT_N) ? TRIT_P :
                    (a == TRIT_P) ? TRIT_N :
                                    TRIT_Z;
endmodule

";

const MOD_TRIT_AND: &str = "\
// ----------------------------------------------------------------------------
// trit_and -- Kleene logic minimum (AND = min in balanced ternary)
//   If either input is -1, result is -1.
//   Else if either is 0, result is 0.
//   Else result is +1.
// ----------------------------------------------------------------------------
module trit_and (
    input  wire [1:0] a,
    input  wire [1:0] b,
    output wire [1:0] result
);
    localparam [1:0] TRIT_N = 2'b00;
    localparam [1:0] TRIT_Z = 2'b01;
    localparam [1:0] TRIT_P = 2'b10;

    assign result = (a == TRIT_N || b == TRIT_N) ? TRIT_N :
                    (a == TRIT_Z || b == TRIT_Z) ? TRIT_Z :
                                                   TRIT_P;
endmodule

";

const MOD_TRIT_OR: &str = "\
// ----------------------------------------------------------------------------
// trit_or -- Kleene logic maximum (OR = max in balanced ternary)
//   If either input is +1, result is +1.
//   Else if either is 0, result is 0.
//   Else result is -1.
// ----------------------------------------------------------------------------
module trit_or (
    input  wire [1:0] a,
    input  wire [1:0] b,
    output wire [1:0] result
);
    localparam [1:0] TRIT_N = 2'b00;
    localparam [1:0] TRIT_Z = 2'b01;
    localparam [1:0] TRIT_P = 2'b10;

    assign result = (a == TRIT_P || b == TRIT_P) ? TRIT_P :
                    (a == TRIT_Z || b == TRIT_Z) ? TRIT_Z :
                                                   TRIT_N;
endmodule

";

const MOD_TRIT_HALF_ADDER: &str = "\
// ----------------------------------------------------------------------------
// trit_half_adder -- Balanced ternary half adder: a + b = (sum, carry)
//   Truth table (signed sum of trits, mapped back to balanced ternary):
//     -1 + -1 = -2 -> sum=+1, carry=-1   (because -2 = -3 + 1)
//     -1 +  0 = -1 -> sum=-1, carry= 0
//     -1 + +1 =  0 -> sum= 0, carry= 0
//      0 + -1 = -1 -> sum=-1, carry= 0
//      0 +  0 =  0 -> sum= 0, carry= 0
//      0 + +1 = +1 -> sum=+1, carry= 0
//     +1 + -1 =  0 -> sum= 0, carry= 0
//     +1 +  0 = +1 -> sum=+1, carry= 0
//     +1 + +1 = +2 -> sum=-1, carry=+1   (because +2 = +3 - 1)
// ----------------------------------------------------------------------------
module trit_half_adder (
    input  wire [1:0] a,
    input  wire [1:0] b,
    output wire [1:0] sum,
    output wire [1:0] carry
);
    localparam [1:0] TRIT_N = 2'b00;
    localparam [1:0] TRIT_Z = 2'b01;
    localparam [1:0] TRIT_P = 2'b10;

    // Convert balanced-ternary encoding to signed integer in {-1, 0, +1}
    wire signed [2:0] a_val = (a == TRIT_N) ? -3'sd1 :
                              (a == TRIT_P) ?  3'sd1 :
                                               3'sd0;
    wire signed [2:0] b_val = (b == TRIT_N) ? -3'sd1 :
                              (b == TRIT_P) ?  3'sd1 :
                                               3'sd0;
    wire signed [2:0] total = a_val + b_val;

    // Map signed total back to (sum_trit, carry_trit)
    assign sum   = (total == -3'sd2) ? TRIT_P :
                   (total == -3'sd1) ? TRIT_N :
                   (total ==  3'sd0) ? TRIT_Z :
                   (total ==  3'sd1) ? TRIT_P :
                   (total ==  3'sd2) ? TRIT_N :
                                       TRIT_Z;

    assign carry = (total == -3'sd2) ? TRIT_N :
                   (total ==  3'sd2) ? TRIT_P :
                                       TRIT_Z;
endmodule

";

const MOD_TRIT_FULL_ADDER: &str = "\
// ----------------------------------------------------------------------------
// trit_full_adder -- a + b + cin = (sum, cout)
//   Built from two half adders + a carry-combine via trit_or (Kleene max).
//   When both half-adder carries are nonzero they always share the same sign,
//   so trit_or correctly combines them without overflow.
// ----------------------------------------------------------------------------
module trit_full_adder (
    input  wire [1:0] a,
    input  wire [1:0] b,
    input  wire [1:0] cin,
    output wire [1:0] sum,
    output wire [1:0] cout
);
    wire [1:0] sum1;
    wire [1:0] carry1;
    wire [1:0] carry2;

    trit_half_adder ha1 (.a(a),    .b(b),   .sum(sum1), .carry(carry1));
    trit_half_adder ha2 (.a(sum1), .b(cin), .sum(sum),  .carry(carry2));

    trit_or carry_combine (.a(carry1), .b(carry2), .result(cout));
endmodule

";

const MOD_TRIT_MULTIPLY: &str = "\
// ----------------------------------------------------------------------------
// trit_multiply -- Single-trit multiplication (no actual multiplier needed)
//   If either input is 0, result is 0.
//   Else if signs match, result is +1.
//   Else result is -1.
// ----------------------------------------------------------------------------
module trit_multiply (
    input  wire [1:0] a,
    input  wire [1:0] b,
    output wire [1:0] result
);
    localparam [1:0] TRIT_N = 2'b00;
    localparam [1:0] TRIT_Z = 2'b01;
    localparam [1:0] TRIT_P = 2'b10;

    wire a_zero    = (a == TRIT_Z);
    wire b_zero    = (b == TRIT_Z);
    wire same_sign = (a == b);

    assign result = (a_zero || b_zero) ? TRIT_Z :
                    same_sign          ? TRIT_P :
                                         TRIT_N;
endmodule

";

const MOD_TRIT3_ADD: &str = "\
// ----------------------------------------------------------------------------
// trit3_add -- 3-trit ripple-carry adder (range: -13 to +13)
//   Trit layout: a[5:4] = t2 (most significant), a[3:2] = t1, a[1:0] = t0.
// ----------------------------------------------------------------------------
module trit3_add (
    input  wire [5:0] a,
    input  wire [5:0] b,
    output wire [5:0] sum,
    output wire [1:0] cout
);
    localparam [1:0] TRIT_Z = 2'b01;

    wire [1:0] c0;
    wire [1:0] c1;

    trit_full_adder fa0 (.a(a[1:0]), .b(b[1:0]), .cin(TRIT_Z), .sum(sum[1:0]), .cout(c0));
    trit_full_adder fa1 (.a(a[3:2]), .b(b[3:2]), .cin(c0),     .sum(sum[3:2]), .cout(c1));
    trit_full_adder fa2 (.a(a[5:4]), .b(b[5:4]), .cin(c1),     .sum(sum[5:4]), .cout(cout));
endmodule

";

#[cfg(test)]
mod tests {
    use super::*;

    /// Basic structural sanity: emitted text contains all 7 module headers and
    /// the shared encoding constants. These are the same invariants that the
    /// integration test (bootstrap/tests/trit_stdlib.rs) checks against the
    /// CLI output.
    #[test]
    fn emits_all_seven_modules() {
        let v = build_trit_stdlib_verilog();
        for name in [
            "module trit_not (",
            "module trit_and (",
            "module trit_or (",
            "module trit_half_adder (",
            "module trit_full_adder (",
            "module trit_multiply (",
            "module trit3_add (",
        ] {
            assert!(v.contains(name), "missing module header: {}", name);
        }
    }

    #[test]
    fn encoding_constants_are_canonical() {
        let v = build_trit_stdlib_verilog();
        assert!(v.contains("TRIT_N = 2'b00"), "TRIT_N must be 2'b00");
        assert!(v.contains("TRIT_Z = 2'b01"), "TRIT_Z must be 2'b01");
        assert!(v.contains("TRIT_P = 2'b10"), "TRIT_P must be 2'b10");
    }

    #[test]
    fn full_adder_uses_two_half_adders_and_or_combine() {
        let v = build_trit_stdlib_verilog();
        // Two trit_half_adder instances inside trit_full_adder.
        let count = v.matches("trit_half_adder ha").count();
        assert_eq!(count, 2, "trit_full_adder must instantiate exactly 2 half adders, got {}", count);
        assert!(v.contains("trit_or carry_combine"), "trit_full_adder must combine carries via trit_or");
    }

    #[test]
    fn trit3_add_uses_three_full_adders() {
        let v = build_trit_stdlib_verilog();
        let count = v.matches("trit_full_adder fa").count();
        assert_eq!(count, 3, "trit3_add must instantiate exactly 3 full adders, got {}", count);
    }

    #[test]
    fn default_nettype_is_balanced() {
        let v = build_trit_stdlib_verilog();
        assert!(v.contains("`default_nettype none"));
        assert!(v.contains("`default_nettype wire"));
    }
}
