//! Wave 32 -- R-TS-1 (Trit Stdlib #1)
//! Wave 33 -- R-TS-2 (Trit Stdlib #2: 27-trit MAC primitives)
//!
//! Synthesizable balanced-ternary HW primitive library.
//!
//! Emits one self-contained Verilog file with 11 modules:
//!     Wave 32 (R-TS-1, base 7):
//!         trit_not, trit_and, trit_or,
//!         trit_half_adder, trit_full_adder, trit_multiply,
//!         trit3_add
//!     Wave 33 (R-TS-2, MAC 4):
//!         trit_compare, trit27_parallel_multiply, adder_tree_27,
//!         trit27_dot_product
//!
//! Encoding (all modules): 2'b00 = -1 (TRIT_N), 2'b01 = 0 (TRIT_Z), 2'b10 = +1 (TRIT_P).
//! 2'b11 is reserved/invalid and falls through to TRIT_Z in muxes (safe default).
//!
//! With this encoding the unsigned 2-bit comparison N(00) < Z(01) < P(10) yields
//! the natural balanced-ternary ordering, so trit_compare uses a direct `<` op.
//!
//! Algorithms and truth-tables ported from gHashTag/vibee-lang
//! src/vibeec/verilog_codegen.zig (Zig). Original author: Dmitrii Vasilev.
//!
//! Zero dependencies on other bootstrap modules. Pure string emission.
//!
//! Closes #751 (Wave 32). Closes #754 (Wave 33).

/// Build the complete trit-stdlib Verilog source as one string.
///
/// The output is fully synthesizable by Yosys 0.36+ and iverilog 11+.
/// All modules use only `wire` ports and `assign` statements (combinational),
/// except `trit3_add` which is structural (3 x trit_full_adder instances).
pub fn build_trit_stdlib_verilog() -> String {
    let mut out = String::with_capacity(16384);
    out.push_str(HEADER);
    // Wave 32 base primitives (R-TS-1)
    out.push_str(MOD_TRIT_NOT);
    out.push_str(MOD_TRIT_AND);
    out.push_str(MOD_TRIT_OR);
    out.push_str(MOD_TRIT_HALF_ADDER);
    out.push_str(MOD_TRIT_FULL_ADDER);
    out.push_str(MOD_TRIT_MULTIPLY);
    out.push_str(MOD_TRIT3_ADD);
    // Wave 33 MAC primitives (R-TS-2)
    out.push_str(MOD_TRIT_COMPARE);
    out.push_str(MOD_TRIT27_PARALLEL_MULTIPLY);
    out.push_str(MOD_ADDER_TREE_27);
    out.push_str(MOD_TRIT27_DOT_PRODUCT);
    out.push_str(FOOTER);
    out
}

const HEADER: &str = "\
// ============================================================================
// Trit Stdlib -- synthesizable balanced-ternary HW primitive library
// Generated by t27c gen-trit-stdlib (Wave 32, R-TS-1, Closes #751)
//
// Encoding: 2'b00 = -1 (TRIT_N), 2'b01 = 0 (TRIT_Z), 2'b10 = +1 (TRIT_P)
// 2'b11 is reserved/invalid (mux fall-through is TRIT_Z).
//
// Algorithms ported from gHashTag/vibee-lang src/vibeec/verilog_codegen.zig.
// Original ternary primitive author: Dmitrii Vasilev.
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

";

const FOOTER: &str = "\
`default_nettype wire
// ============================================================================
// End of trit stdlib (11 modules: 7 base + 4 MAC).
// ============================================================================
";

const MOD_TRIT_NOT: &str = "\
// ----------------------------------------------------------------------------
// trit_not -- Ternary negation
//   NOT(-1) = +1, NOT(0) = 0, NOT(+1) = -1
// ----------------------------------------------------------------------------
module trit_not (
    input  wire [1:0] a,
    output wire [1:0] result
);
    localparam [1:0] TRIT_N = 2'b00;
    localparam [1:0] TRIT_Z = 2'b01;
    localparam [1:0] TRIT_P = 2'b10;

    assign result = (a == TRIT_Z) ? TRIT_Z :
                    (a == TRIT_N) ? TRIT_P :
                    (a == TRIT_P) ? TRIT_N :
                                    TRIT_Z;
endmodule

";

const MOD_TRIT_AND: &str = "\
// ----------------------------------------------------------------------------
// trit_and -- Kleene logic minimum (AND = min in balanced ternary)
//   If either input is -1, result is -1.
//   Else if either is 0, result is 0.
//   Else result is +1.
// ----------------------------------------------------------------------------
module trit_and (
    input  wire [1:0] a,
    input  wire [1:0] b,
    output wire [1:0] result
);
    localparam [1:0] TRIT_N = 2'b00;
    localparam [1:0] TRIT_Z = 2'b01;
    localparam [1:0] TRIT_P = 2'b10;

    assign result = (a == TRIT_N || b == TRIT_N) ? TRIT_N :
                    (a == TRIT_Z || b == TRIT_Z) ? TRIT_Z :
                                                   TRIT_P;
endmodule

";

const MOD_TRIT_OR: &str = "\
// ----------------------------------------------------------------------------
// trit_or -- Kleene logic maximum (OR = max in balanced ternary)
//   If either input is +1, result is +1.
//   Else if either is 0, result is 0.
//   Else result is -1.
// ----------------------------------------------------------------------------
module trit_or (
    input  wire [1:0] a,
    input  wire [1:0] b,
    output wire [1:0] result
);
    localparam [1:0] TRIT_N = 2'b00;
    localparam [1:0] TRIT_Z = 2'b01;
    localparam [1:0] TRIT_P = 2'b10;

    assign result = (a == TRIT_P || b == TRIT_P) ? TRIT_P :
                    (a == TRIT_Z || b == TRIT_Z) ? TRIT_Z :
                                                   TRIT_N;
endmodule

";

const MOD_TRIT_HALF_ADDER: &str = "\
// ----------------------------------------------------------------------------
// trit_half_adder -- Balanced ternary half adder: a + b = (sum, carry)
//   Truth table (signed sum of trits, mapped back to balanced ternary):
//     -1 + -1 = -2 -> sum=+1, carry=-1   (because -2 = -3 + 1)
//     -1 +  0 = -1 -> sum=-1, carry= 0
//     -1 + +1 =  0 -> sum= 0, carry= 0
//      0 + -1 = -1 -> sum=-1, carry= 0
//      0 +  0 =  0 -> sum= 0, carry= 0
//      0 + +1 = +1 -> sum=+1, carry= 0
//     +1 + -1 =  0 -> sum= 0, carry= 0
//     +1 +  0 = +1 -> sum=+1, carry= 0
//     +1 + +1 = +2 -> sum=-1, carry=+1   (because +2 = +3 - 1)
// ----------------------------------------------------------------------------
module trit_half_adder (
    input  wire [1:0] a,
    input  wire [1:0] b,
    output wire [1:0] sum,
    output wire [1:0] carry
);
    localparam [1:0] TRIT_N = 2'b00;
    localparam [1:0] TRIT_Z = 2'b01;
    localparam [1:0] TRIT_P = 2'b10;

    // Convert balanced-ternary encoding to signed integer in {-1, 0, +1}
    wire signed [2:0] a_val = (a == TRIT_N) ? -3'sd1 :
                              (a == TRIT_P) ?  3'sd1 :
                                               3'sd0;
    wire signed [2:0] b_val = (b == TRIT_N) ? -3'sd1 :
                              (b == TRIT_P) ?  3'sd1 :
                                               3'sd0;
    wire signed [2:0] total = a_val + b_val;

    // Map signed total back to (sum_trit, carry_trit)
    assign sum   = (total == -3'sd2) ? TRIT_P :
                   (total == -3'sd1) ? TRIT_N :
                   (total ==  3'sd0) ? TRIT_Z :
                   (total ==  3'sd1) ? TRIT_P :
                   (total ==  3'sd2) ? TRIT_N :
                                       TRIT_Z;

    assign carry = (total == -3'sd2) ? TRIT_N :
                   (total ==  3'sd2) ? TRIT_P :
                                       TRIT_Z;
endmodule

";

const MOD_TRIT_FULL_ADDER: &str = "\
// ----------------------------------------------------------------------------
// trit_full_adder -- a + b + cin = (sum, cout)
//   Built from two half adders. The two half-adder carries are combined
//   by a dedicated carry-add: carry1 + carry2 produces values in {-2..+2},
//   mapped to balanced-ternary carry via sign detection.
// ----------------------------------------------------------------------------
module trit_full_adder (
    input  wire [1:0] a,
    input  wire [1:0] b,
    input  wire [1:0] cin,
    output wire [1:0] sum,
    output wire [1:0] cout
);
    wire [1:0] sum1;
    wire [1:0] carry1;
    wire [1:0] carry2;

    trit_half_adder ha1 (.a(a),    .b(b),   .sum(sum1), .carry(carry1));
    trit_half_adder ha2 (.a(sum1), .b(cin), .sum(sum),  .carry(carry2));

    // carry1 + carry2 ∈ {-2, -1, 0, +1, +2}
    // Balanced-ternary: cout = sign(carry1+carry2), encoded as TRIT_N/TRIT_Z/TRIT_P
    // Intermediate sum remainder absorbed into final sum via half-adder chain.
    wire signed [2:0] c1 = carry1 == 2'b10 ? 3'sd1 : (carry1 == 2'b01 ? 3'sd0 : -3'sd1);
    wire signed [2:0] c2 = carry2 == 2'b10 ? 3'sd1 : (carry2 == 2'b01 ? 3'sd0 : -3'sd1);
    wire signed [3:0] csum = c1 + c2;
    assign cout = (csum > 0) ? 2'b10 : (csum < 0) ? 2'b00 : 2'b01;
endmodule

";

const MOD_TRIT_MULTIPLY: &str = "\
// ----------------------------------------------------------------------------
// trit_multiply -- Single-trit multiplication (no actual multiplier needed)
//   If either input is 0, result is 0.
//   Else if signs match, result is +1.
//   Else result is -1.
// ----------------------------------------------------------------------------
module trit_multiply (
    input  wire [1:0] a,
    input  wire [1:0] b,
    output wire [1:0] result
);
    localparam [1:0] TRIT_N = 2'b00;
    localparam [1:0] TRIT_Z = 2'b01;
    localparam [1:0] TRIT_P = 2'b10;

    wire a_zero    = (a == TRIT_Z);
    wire b_zero    = (b == TRIT_Z);
    wire same_sign = (a == b);

    assign result = (a_zero || b_zero) ? TRIT_Z :
                    same_sign          ? TRIT_P :
                                         TRIT_N;
endmodule

";

const MOD_TRIT3_ADD: &str = "\
// ----------------------------------------------------------------------------
// trit3_add -- 3-trit ripple-carry adder (range: -13 to +13)
//   Trit layout: a[5:4] = t2 (most significant), a[3:2] = t1, a[1:0] = t0.
// ----------------------------------------------------------------------------
module trit3_add (
    input  wire [5:0] a,
    input  wire [5:0] b,
    output wire [5:0] sum,
    output wire [1:0] cout
);
    localparam [1:0] TRIT_Z = 2'b01;

    wire [1:0] c0;
    wire [1:0] c1;

    trit_full_adder fa0 (.a(a[1:0]), .b(b[1:0]), .cin(TRIT_Z), .sum(sum[1:0]), .cout(c0));
    trit_full_adder fa1 (.a(a[3:2]), .b(b[3:2]), .cin(c0),     .sum(sum[3:2]), .cout(c1));
    trit_full_adder fa2 (.a(a[5:4]), .b(b[5:4]), .cin(c1),     .sum(sum[5:4]), .cout(cout));
endmodule

";

// ============================================================================
// Wave 33 (R-TS-2) -- 27-trit MAC primitives
// ============================================================================

const MOD_TRIT_COMPARE: &str = "\
// ----------------------------------------------------------------------------
// trit_compare -- Ternary comparison
//   Returns TRIT_N (-1) if a<b, TRIT_Z (0) if a==b, TRIT_P (+1) if a>b.
//   The unsigned 2-bit ordering of the encoding N(00) < Z(01) < P(10) matches
//   the balanced-ternary ordering exactly, so a single `<` operator suffices.
//   (Invalid 2'b11 inputs are excluded by construction.)
// ----------------------------------------------------------------------------
module trit_compare (
    input  wire [1:0] a,
    input  wire [1:0] b,
    output wire [1:0] result
);
    localparam [1:0] TRIT_N = 2'b00;
    localparam [1:0] TRIT_Z = 2'b01;
    localparam [1:0] TRIT_P = 2'b10;

    assign result = (a == b) ? TRIT_Z :
                    (a <  b) ? TRIT_N :
                               TRIT_P;
endmodule

";

const MOD_TRIT27_PARALLEL_MULTIPLY: &str = "\
// ----------------------------------------------------------------------------
// trit27_parallel_multiply -- 27-way SIMD ternary multiplication.
//   Vector layout: bits [i*2 +: 2] hold trit i (i = 0..26), so total width 54.
//   BitNet core operation: no real multipliers -- pure sign comparison per lane.
// ----------------------------------------------------------------------------
module trit27_parallel_multiply (
    input  wire [53:0] a,
    input  wire [53:0] b,
    output wire [53:0] result
);
    localparam [1:0] TRIT_Z = 2'b01;
    localparam [1:0] TRIT_P = 2'b10;
    localparam [1:0] TRIT_N = 2'b00;

    genvar i;
    generate
        for (i = 0; i < 27; i = i + 1) begin : mult_gen
            wire [1:0] ai        = a[i*2 +: 2];
            wire [1:0] bi        = b[i*2 +: 2];
            wire       a_zero    = (ai == TRIT_Z);
            wire       b_zero    = (bi == TRIT_Z);
            wire       same_sign = (ai == bi);

            assign result[i*2 +: 2] = (a_zero || b_zero) ? TRIT_Z :
                                      same_sign          ? TRIT_P :
                                                           TRIT_N;
        end
    endgenerate
endmodule

";

const MOD_ADDER_TREE_27: &str = "\
// ----------------------------------------------------------------------------
// adder_tree_27 -- Reduce 27 trits to a single signed sum in [-27, +27].
//   3-level structural tree: 27 -> 9 -> 3 -> 1.
//   Each trit is first decoded to signed {-1, 0, +1}; then ordinary signed
//   integer addition combines them. The output is signed [5:0].
// ----------------------------------------------------------------------------
module adder_tree_27 (
    input  wire [53:0]       trits,
    output wire signed [5:0] sum
);
    localparam [1:0] TRIT_N = 2'b00;
    localparam [1:0] TRIT_P = 2'b10;

    // Decode each trit to signed {-1, 0, +1} (2-bit signed, range [-1, +1]).
    wire signed [1:0] val [0:26];
    genvar i;
    generate
        for (i = 0; i < 27; i = i + 1) begin : convert
            wire [1:0] t = trits[i*2 +: 2];
            assign val[i] = (t == TRIT_N) ? -2'sd1 :
                            (t == TRIT_P) ?  2'sd1 :
                                             2'sd0;
        end
    endgenerate

    // Level 1: 9 groups of 3, range [-3, +3] -> signed [2:0].
    wire signed [2:0] l1 [0:8];
    generate
        for (i = 0; i < 9; i = i + 1) begin : level1
            assign l1[i] = val[i*3] + val[i*3+1] + val[i*3+2];
        end
    endgenerate

    // Level 2: 3 groups of 3, range [-9, +9] -> signed [4:0].
    //
    // FIVE bits, not four. A 4-bit signed value spans [-8, +7] and cannot hold
    // this level's own stated range: any group of nine trits summing to +8, +9
    // or -9 wrapped by 16. Found in Wave 628 by the first exhaustive proof of
    // this primitive -- the tree returned -14 for a vector whose balanced sum
    // is +2. The comment above had the correct range in it the whole time while
    // the declaration below contradicted it. See FORMAL_FOUNDATIONS Prop. 80.
    wire signed [4:0] l2 [0:2];
    assign l2[0] = l1[0] + l1[1] + l1[2];
    assign l2[1] = l1[3] + l1[4] + l1[5];
    assign l2[2] = l1[6] + l1[7] + l1[8];

    // Level 3: final sum, range [-27, +27] -> signed [5:0].
    assign sum = l2[0] + l2[1] + l2[2];
endmodule

";

const MOD_TRIT27_DOT_PRODUCT: &str = "\
// ----------------------------------------------------------------------------
// trit27_dot_product -- Complete BitNet MAC: 27-element trit dot product.
//   Step 1: 27 parallel sign-only multiplies (trit27_parallel_multiply).
//   Step 2: 3-level reduction (adder_tree_27).
//   Output: signed [5:0] in [-27, +27].
// ----------------------------------------------------------------------------
module trit27_dot_product (
    input  wire [53:0]       input_vec,
    input  wire [53:0]       weight_vec,
    output wire signed [5:0] result
);
    wire [53:0] products;

    trit27_parallel_multiply mult_unit (
        .a(input_vec),
        .b(weight_vec),
        .result(products)
    );

    adder_tree_27 tree (
        .trits(products),
        .sum(result)
    );
endmodule

";

#[cfg(test)]
mod tests {
    use super::*;

    /// Basic structural sanity: emitted text contains all 11 module headers and
    /// the shared encoding constants. These are the same invariants that the
    /// integration test (bootstrap/tests/trit_stdlib.rs) checks against the
    /// CLI output.
    #[test]
    fn emits_all_eleven_modules() {
        let v = build_trit_stdlib_verilog();
        for name in [
            "module trit_not (",
            "module trit_and (",
            "module trit_or (",
            "module trit_half_adder (",
            "module trit_full_adder (",
            "module trit_multiply (",
            "module trit3_add (",
            "module trit_compare (",
            "module trit27_parallel_multiply (",
            "module adder_tree_27 (",
            "module trit27_dot_product (",
        ] {
            assert!(v.contains(name), "missing module header: {}", name);
        }
    }

    #[test]
    fn encoding_constants_are_canonical() {
        let v = build_trit_stdlib_verilog();
        assert!(v.contains("TRIT_N = 2'b00"), "TRIT_N must be 2'b00");
        assert!(v.contains("TRIT_Z = 2'b01"), "TRIT_Z must be 2'b01");
        assert!(v.contains("TRIT_P = 2'b10"), "TRIT_P must be 2'b10");
    }

    #[test]
    fn full_adder_uses_two_half_adders_and_or_combine() {
        let v = build_trit_stdlib_verilog();
        let count = v.matches("trit_half_adder ha").count();
        assert_eq!(count, 2, "trit_full_adder must instantiate exactly 2 half adders, got {}", count);
        assert!(v.contains("c1 + c2"), "trit_full_adder must combine carries via signed addition");
    }

    #[test]
    fn trit3_add_uses_three_full_adders() {
        let v = build_trit_stdlib_verilog();
        let count = v.matches("trit_full_adder fa").count();
        assert_eq!(count, 3, "trit3_add must instantiate exactly 3 full adders, got {}", count);
    }

    #[test]
    fn dot_product_composes_parallel_multiply_and_adder_tree() {
        let v = build_trit_stdlib_verilog();
        assert!(
            v.contains("trit27_parallel_multiply mult_unit"),
            "trit27_dot_product must instantiate trit27_parallel_multiply as mult_unit"
        );
        assert!(
            v.contains("adder_tree_27 tree"),
            "trit27_dot_product must instantiate adder_tree_27 as tree"
        );
    }

    #[test]
    fn parallel_multiply_uses_part_select_loop() {
        let v = build_trit_stdlib_verilog();
        // 27-lane SIMD requires a genvar loop with +: part-select.
        assert!(v.contains("for (i = 0; i < 27; i = i + 1) begin : mult_gen"));
        assert!(v.contains("a[i*2 +: 2]"));
        assert!(v.contains("b[i*2 +: 2]"));
    }

    #[test]
    fn adder_tree_has_three_levels() {
        let v = build_trit_stdlib_verilog();
        // Level 1 generate-loop, level 2 explicit triples, level 3 single line.
        assert!(v.contains("begin : convert"), "adder_tree_27 must have decode loop");
        assert!(v.contains("begin : level1"), "adder_tree_27 must have level1 loop");
        assert!(v.contains("assign l2[0] = l1[0] + l1[1] + l1[2];"));
        assert!(v.contains("assign sum = l2[0] + l2[1] + l2[2];"));
    }

    #[test]
    fn trit_compare_uses_direct_ordering() {
        let v = build_trit_stdlib_verilog();
        // Direct < op relies on the encoding ordering N(00)<Z(01)<P(10).
        assert!(v.contains("(a == b) ? TRIT_Z :"));
        assert!(v.contains("(a <  b) ? TRIT_N :"));
    }

    #[test]
    fn default_nettype_is_balanced() {
        let v = build_trit_stdlib_verilog();
        assert!(v.contains("`default_nettype none"));
        assert!(v.contains("`default_nettype wire"));
    }
}
