//! BitNet weight_bram dual-port BRAM emitter (Wave 36a, R-BN-1).
//!
//! Emits a self-contained SystemVerilog `weight_bram` module suitable for the
//! BitNet ternary-weight engine: a parameterizable dual-port BRAM with
//! synchronous 1-cycle read latency and synchronous write. The default
//! geometry matches the upstream vibee-lang emitter (DEPTH = 4096,
//! ADDR_WIDTH = 12, DATA_WIDTH = 54 bits = 27 trits packed 2 bits/trit).
//!
//! Algorithm ported from `gHashTag/vibee-lang`
//! `src/vibeec/verilog_codegen.zig` lines 1062-1097 (`writeWeightBram`).
//! Original author: Dmitrii Vasilev.
//!
//! Constitutional notes:
//!   L2: lives only under `bootstrap/`; pure additive emitter, no edits
//!       under `gen/`, `coq/`, `trios-coq/`, `proofs/`, `specs/`,
//!       `conformance/`, `architecture/`, `rings/`, root `Cargo.toml`.
//!   L3: ASCII source, English doc-comments only.
//!   L5: numeric kernel untouched -- this emitter declares storage cells,
//!       it does not redefine any constant inside the trinity invariant.
//!   L7: no `*.sh` invoked.

/// Default BRAM depth (number of words), matching vibee-lang upstream.
pub const DEFAULT_DEPTH: u32 = 4096;

/// Default address width (bits), matching `log2(DEFAULT_DEPTH)`.
pub const DEFAULT_ADDR_WIDTH: u32 = 12;

/// Default data width (bits): 27 ternary trits packed 2 bits/trit = 54 bits.
pub const DEFAULT_DATA_WIDTH: u32 = 54;

/// Default module identifier.
pub const DEFAULT_MODULE_NAME: &str = "weight_bram";

/// Configuration for a single `weight_bram` emission.
///
/// All four geometry knobs are sanitized: zero / pathological values fall
/// back to the matching `DEFAULT_*` constant so the emitter cannot produce
/// a syntactically broken module.
#[derive(Debug, Clone, Copy)]
pub struct WeightBramConfig<'a> {
    /// Number of storage words (>= 1).
    pub depth: u32,
    /// Address bus width in bits (>= 1).
    pub addr_width: u32,
    /// Word width in bits (>= 1).
    pub data_width: u32,
    /// Verilog module identifier. Must be a non-empty ASCII identifier;
    /// otherwise falls back to `DEFAULT_MODULE_NAME`.
    pub module_name: &'a str,
}

impl<'a> Default for WeightBramConfig<'a> {
    fn default() -> Self {
        Self {
            depth: DEFAULT_DEPTH,
            addr_width: DEFAULT_ADDR_WIDTH,
            data_width: DEFAULT_DATA_WIDTH,
            module_name: DEFAULT_MODULE_NAME,
        }
    }
}

/// Return `true` if `s` is a syntactically valid Verilog identifier:
/// non-empty, ASCII, starts with `[A-Za-z_]`, followed by `[A-Za-z0-9_]*`.
fn is_valid_verilog_ident(s: &str) -> bool {
    let mut chars = s.chars();
    let first = match chars.next() {
        Some(c) => c,
        None => return false,
    };
    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

/// Build the `weight_bram` SystemVerilog module text.
///
/// The output is a free-standing, synthesizable module with:
///   * `parameter DEPTH = <depth>`,
///   * `parameter ADDR_WIDTH = <addr_width>`,
///   * a `<data_width>-1:0` data bus on both ports,
///   * a `reg [<DW>-1:0] mem [0:DEPTH-1]` storage array,
///   * one read port with 1-cycle latency,
///   * one write port enabled by `wr_en`.
///
/// Zero or one of the numeric knobs being `0` is treated as "use the
/// upstream default"; module-name validity is checked via
/// [`is_valid_verilog_ident`].
pub fn build_weight_bram(config: WeightBramConfig<'_>) -> String {
    let depth = if config.depth == 0 { DEFAULT_DEPTH } else { config.depth };
    let addr_width = if config.addr_width == 0 {
        DEFAULT_ADDR_WIDTH
    } else {
        config.addr_width
    };
    let data_width = if config.data_width == 0 {
        DEFAULT_DATA_WIDTH
    } else {
        config.data_width
    };
    let module_name = if is_valid_verilog_ident(config.module_name) {
        config.module_name
    } else {
        DEFAULT_MODULE_NAME
    };

    // Pre-compute the high bit indices once so the format strings stay clean.
    let dw_hi = data_width - 1;
    let aw_token = "ADDR_WIDTH-1";

    let mut out = String::new();
    out.push_str("// ===========================================================================\n");
    out.push_str("// WEIGHT BRAM - Dual-port BRAM for ternary weights\n");
    out.push_str("// ===========================================================================\n");
    out.push_str("// Generated by t27c gen-weight-bram (Wave 36a, R-BN-1).\n");
    out.push_str("// Synchronous 1-cycle read latency, synchronous write.\n");
    out.push_str("\n");
    out.push_str(&format!("module {} #(\n", module_name));
    out.push_str(&format!("    parameter DEPTH = {},\n", depth));
    out.push_str(&format!("    parameter ADDR_WIDTH = {}\n", addr_width));
    out.push_str(") (\n");
    out.push_str("    input  wire                  clk,\n");
    out.push_str(&format!("    input  wire [{}:0] rd_addr,\n", aw_token));
    out.push_str(&format!("    output reg  [{}:0]           rd_data,\n", dw_hi));
    out.push_str(&format!("    input  wire [{}:0] wr_addr,\n", aw_token));
    out.push_str(&format!("    input  wire [{}:0]           wr_data,\n", dw_hi));
    out.push_str("    input  wire                  wr_en\n");
    out.push_str(");\n");
    out.push_str("\n");
    out.push_str("    // BRAM storage\n");
    out.push_str(&format!("    reg [{}:0] mem [0:DEPTH-1];\n", dw_hi));
    out.push_str("\n");
    out.push_str("    // Read port (1 cycle latency)\n");
    out.push_str("    always @(posedge clk) rd_data <= mem[rd_addr];\n");
    out.push_str("\n");
    out.push_str("    // Write port\n");
    out.push_str("    always @(posedge clk) if (wr_en) mem[wr_addr] <= wr_data;\n");
    out.push_str("\n");
    out.push_str("endmodule\n");

    out
}

/// Convenience: emit with all defaults (matches vibee-lang upstream).
pub fn build_default_weight_bram() -> String {
    build_weight_bram(WeightBramConfig::default())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_emits_module_header() {
        let v = build_default_weight_bram();
        assert!(v.contains("module weight_bram #("));
        assert!(v.contains("endmodule"));
    }

    #[test]
    fn default_uses_upstream_geometry() {
        let v = build_default_weight_bram();
        assert!(v.contains("parameter DEPTH = 4096,"));
        assert!(v.contains("parameter ADDR_WIDTH = 12"));
        assert!(v.contains("[53:0]"));
    }

    #[test]
    fn ports_include_dual_address_buses() {
        let v = build_default_weight_bram();
        assert!(v.contains("input  wire [ADDR_WIDTH-1:0] rd_addr,"));
        assert!(v.contains("input  wire [ADDR_WIDTH-1:0] wr_addr,"));
    }

    #[test]
    fn read_port_is_synchronous_with_one_cycle_latency() {
        let v = build_default_weight_bram();
        assert!(v.contains("always @(posedge clk) rd_data <= mem[rd_addr];"));
    }

    #[test]
    fn write_port_is_guarded_by_wr_en() {
        let v = build_default_weight_bram();
        assert!(v.contains("always @(posedge clk) if (wr_en) mem[wr_addr] <= wr_data;"));
    }

    #[test]
    fn storage_array_is_declared() {
        let v = build_default_weight_bram();
        assert!(v.contains("reg [53:0] mem [0:DEPTH-1];"));
    }

    #[test]
    fn custom_geometry_is_propagated() {
        let v = build_weight_bram(WeightBramConfig {
            depth: 1024,
            addr_width: 10,
            data_width: 32,
            module_name: "custom_bram",
        });
        assert!(v.contains("module custom_bram #("));
        assert!(v.contains("parameter DEPTH = 1024,"));
        assert!(v.contains("parameter ADDR_WIDTH = 10"));
        assert!(v.contains("[31:0]"));
        assert!(v.contains("reg [31:0] mem [0:DEPTH-1];"));
    }

    #[test]
    fn zero_depth_falls_back_to_default() {
        let v = build_weight_bram(WeightBramConfig {
            depth: 0,
            ..Default::default()
        });
        assert!(v.contains("parameter DEPTH = 4096,"));
    }

    #[test]
    fn zero_addr_width_falls_back_to_default() {
        let v = build_weight_bram(WeightBramConfig {
            addr_width: 0,
            ..Default::default()
        });
        assert!(v.contains("parameter ADDR_WIDTH = 12"));
    }

    #[test]
    fn zero_data_width_falls_back_to_default() {
        let v = build_weight_bram(WeightBramConfig {
            data_width: 0,
            ..Default::default()
        });
        assert!(v.contains("[53:0]"));
    }

    #[test]
    fn invalid_module_name_falls_back_to_default() {
        let v = build_weight_bram(WeightBramConfig {
            module_name: "9invalid-name",
            ..Default::default()
        });
        assert!(v.contains("module weight_bram #("));
    }

    #[test]
    fn empty_module_name_falls_back_to_default() {
        let v = build_weight_bram(WeightBramConfig {
            module_name: "",
            ..Default::default()
        });
        assert!(v.contains("module weight_bram #("));
    }

    #[test]
    fn output_is_ascii_only() {
        let v = build_default_weight_bram();
        assert!(v.is_ascii(), "emitted module must be ASCII-only (L3)");
    }

    #[test]
    fn ident_validator_accepts_letter_start() {
        assert!(is_valid_verilog_ident("foo"));
        assert!(is_valid_verilog_ident("Foo123"));
        assert!(is_valid_verilog_ident("_bar"));
        assert!(is_valid_verilog_ident("a_b_c_42"));
    }

    #[test]
    fn ident_validator_rejects_bad_inputs() {
        assert!(!is_valid_verilog_ident(""));
        assert!(!is_valid_verilog_ident("9foo"));
        assert!(!is_valid_verilog_ident("foo-bar"));
        assert!(!is_valid_verilog_ident("foo bar"));
        assert!(!is_valid_verilog_ident("foo.bar"));
    }
}
