[build]
builder = "DOCKERFILE"
dockerfilePath = "bootstrap/Dockerfile"

[deploy]
startCommand = "/t27c serve --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
