[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildTimeout = 1200

[deploy]
startCommand = "t27c serve --port 8080"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
