// ============================================================================
// Generated from t27 spec: Axi4
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module Axi4 (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Parameters (from const declarations)
    // -------------------------------------------------------
    parameter [31:0] MAX_BUS_PORTS = 32;
    parameter [31:0] AXI_ADDR_WIDTH = 32;
    parameter [31:0] AXI_DATA_WIDTH = 32;
    parameter [31:0] AXI_STRB_WIDTH = 4;
    parameter [31:0] AXI_ID_WIDTH = 4;
    parameter [31:0] AXI_LEN_WIDTH = 8;
    parameter [31:0] AXI_SIZE_WIDTH = 3;
    parameter [31:0] AXI_BURST_WIDTH = 2;
    parameter [31:0] AXI_RESP_WIDTH = 2;
    parameter [31:0] AXI_CACHE_WIDTH = 4;
    parameter [31:0] AXI_PROT_WIDTH = 3;
    parameter [31:0] AXI_QOS_WIDTH = 4;
    parameter [31:0] AXI_REGION_WIDTH = 4;
    parameter [31:0] AXI_USER_WIDTH = 1;
    parameter signed [7:0] CH_AW = 0;
    parameter signed [7:0] CH_AR = 1;
    parameter signed [7:0] CH_W = 2;
    parameter signed [7:0] CH_R = 3;
    parameter signed [7:0] CH_B = 4;

    // -------------------------------------------------------
    // Enum constants
    // -------------------------------------------------------
    // enum AxiKind
    localparam AxiKind_axi4_lite = 0;
    localparam AxiKind_axi4_full = 1;

    // -------------------------------------------------------
    // Registers (from struct declarations)
    // -------------------------------------------------------
    // struct AxiBusConfig
    reg [31:0] axibusconfig_name; // AxiBusConfig.name
    reg signed [7:0] axibusconfig_kind; // AxiBusConfig.kind
    reg [31:0] axibusconfig_addr_width; // AxiBusConfig.addr_width
    reg [31:0] axibusconfig_data_width; // AxiBusConfig.data_width
    reg [31:0] axibusconfig_id_width; // AxiBusConfig.id_width
    reg axibusconfig_has_region; // AxiBusConfig.has_region
    reg axibusconfig_has_cache; // AxiBusConfig.has_cache
    reg axibusconfig_has_prot; // AxiBusConfig.has_prot
    reg axibusconfig_has_qos; // AxiBusConfig.has_qos
    reg axibusconfig_has_user; // AxiBusConfig.has_user
    reg axibusconfig_has_lock; // AxiBusConfig.has_lock
    // struct BusPort
    reg [31:0] busport_name; // BusPort.name
    reg signed [7:0] busport_direction; // BusPort.direction
    reg [31:0] busport_width; // BusPort.width
    reg signed [7:0] busport_channel; // BusPort.channel

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: axi4_lite_slave
    function [31:0] axi4_lite_slave; // -> AxiBusConfig
        input [31:0] name;
        input [31:0] tr;
        input [31:0] addr_width;
        input [31:0] data_width;
        begin
            axi4_lite_slave = 0 /* AxiBusConfig {...} */;
        end
    endfunction

    // function: axi4_lite_master
    function [31:0] axi4_lite_master; // -> AxiBusConfig
        input [31:0] name;
        input [31:0] tr;
        input [31:0] addr_width;
        input [31:0] data_width;
        begin
            axi4_lite_master = 0 /* AxiBusConfig {...} */;
        end
    endfunction

    // function: axi4_full_slave
    function [31:0] axi4_full_slave; // -> AxiBusConfig
        input [31:0] name;
        input [31:0] tr;
        input [31:0] addr_width;
        input [31:0] data_width;
        input [31:0] id_width;
        begin
            axi4_full_slave = 0 /* AxiBusConfig {...} */;
        end
    endfunction

    // function: axi4_full_master
    function [31:0] axi4_full_master; // -> AxiBusConfig
        input [31:0] name;
        input [31:0] tr;
        input [31:0] addr_width;
        input [31:0] data_width;
        input [31:0] id_width;
        begin
            axi4_full_master = 0 /* AxiBusConfig {...} */;
        end
    endfunction

    // function: is_lite
    function is_lite; // -> bool
        input [31:0] cfg;
        begin
            is_lite = (cfg_kind == 0);
        end
    endfunction

    // function: is_full
    function is_full; // -> bool
        input [31:0] cfg;
        begin
            is_full = (cfg_kind == 1);
        end
    endfunction

    // function: strb_width
    function [31:0] strb_width; // -> u32
        input [31:0] cfg;
        begin
            strb_width = (cfg_data_width / 8);
        end
    endfunction

    // function: is_master
    function is_master; // -> bool
        input [31:0] cfg;
        begin
            is_master = 1'b1;
        end
    endfunction

    // function: slave_port_count
    function [31:0] slave_port_count; // -> u32
        input [31:0] cfg;
        begin
            reg [31:0] count = 0;
            count = (count + 1);
            count = (count + 1);
            count = (count + 1);
            count = (count + 1);
            count = (count + 1);
            count = (count + 1);
            count = (count + 1);
            count = (count + 1);
            count = (count + 1);
            count = (count + 1);
            count = (count + 1);
            slave_port_count = count;
        end
    endfunction

    // function: total_bus_bits
    function [31:0] total_bus_bits; // -> u32
        input [31:0] cfg;
        begin
            reg [31:0] bits = 0;
            bits = (bits + cfg_addr_width);
            bits = (bits + cfg_data_width);
            bits = (bits + (cfg_data_width / 8));
            bits = (bits + 2);
            bits = (bits + 2);
            bits = (bits + 3);
            bits = (bits + 2);
            bits = (bits + 8);
            total_bus_bits = bits;
        end
    endfunction

    // function: validate_axi
    function [31:0] validate_axi; // -> u32
        input [31:0] cfg;
        begin
            reg [31:0] errors = 0;
            if ((cfg_name == "")) begin
                errors = (errors + 1);
            end
            if ((cfg_addr_width == 0)) begin
                errors = (errors + 1);
            end
            if ((cfg_data_width == 0)) begin
                errors = (errors + 1);
            end
            if (((cfg_data_width % 8) != 0)) begin
                errors = (errors + 1);
            end
            if (((cfg_kind == 1) && (cfg_id_width == 0))) begin
                errors = (errors + 1);
            end
            validate_axi = errors;
        end
    endfunction
    // -------------------------------------------------------
    // Test assertions (from test blocks)
    // -------------------------------------------------------
    // synthesis translate_off
    // test: axi4_lite_is_lite
    initial begin : axi4_lite_is_lite_test
        $display("[TEST] axi4_lite_is_lite : starting");
        $display("[TEST] axi4_lite_is_lite : PASSED");
    end
    // test: axi4_full_is_full
    initial begin : axi4_full_is_full_test
        $display("[TEST] axi4_full_is_full : starting");
        $display("[TEST] axi4_full_is_full : PASSED");
    end
    // test: strb_width_32bit
    initial begin : strb_width_32bit_test
        $display("[TEST] strb_width_32bit : starting");
        $display("[TEST] strb_width_32bit : PASSED");
    end
    // test: strb_width_64bit
    initial begin : strb_width_64bit_test
        $display("[TEST] strb_width_64bit : starting");
        $display("[TEST] strb_width_64bit : PASSED");
    end
    // test: validate_lite_ok
    initial begin : validate_lite_ok_test
        $display("[TEST] validate_lite_ok : starting");
        $display("[TEST] validate_lite_ok : PASSED");
    end
    // test: validate_full_ok
    initial begin : validate_full_ok_test
        $display("[TEST] validate_full_ok : starting");
        $display("[TEST] validate_full_ok : PASSED");
    end
    // test: validate_empty_name
    initial begin : validate_empty_name_test
        $display("[TEST] validate_empty_name : starting");
        $display("[TEST] validate_empty_name : PASSED");
    end
    // test: validate_zero_addr
    initial begin : validate_zero_addr_test
        $display("[TEST] validate_zero_addr : starting");
        $display("[TEST] validate_zero_addr : PASSED");
    end
    // test: validate_zero_data
    initial begin : validate_zero_data_test
        $display("[TEST] validate_zero_data : starting");
        $display("[TEST] validate_zero_data : PASSED");
    end
    // test: validate_non_byte_data
    initial begin : validate_non_byte_data_test
        $display("[TEST] validate_non_byte_data : starting");
        $display("[TEST] validate_non_byte_data : PASSED");
    end
    // test: validate_full_no_id
    initial begin : validate_full_no_id_test
        $display("[TEST] validate_full_no_id : starting");
        $display("[TEST] validate_full_no_id : PASSED");
    end
    // test: slave_port_count_lite
    initial begin : slave_port_count_lite_test
        $display("[TEST] slave_port_count_lite : starting");
        $display("[TEST] slave_port_count_lite : PASSED");
    end
    // test: total_bus_bits_positive
    initial begin : total_bus_bits_positive_test
        $display("[TEST] total_bus_bits_positive : starting");
        $display("[TEST] total_bus_bits_positive : PASSED");
    end
    // test: lite_no_id
    initial begin : lite_no_id_test
        $display("[TEST] lite_no_id : starting");
        $display("[TEST] lite_no_id : PASSED");
    end
    // test: full_has_id
    initial begin : full_has_id_test
        $display("[TEST] full_has_id : starting");
        $display("[TEST] full_has_id : PASSED");
    end
    // test: full_has_extras
    initial begin : full_has_extras_test
        $display("[TEST] full_has_extras : starting");
        $display("[TEST] full_has_extras : PASSED");
    end
    // synthesis translate_on

    // -------------------------------------------------------
    // Invariant checks (compile-time assertions)
    // -------------------------------------------------------
    // invariant: addr_width_positive
    // invariant: data_width_byte_aligned
    // invariant: strb_width_matches_data
    // invariant: lite_has_zero_id
    // invariant: full_has_nonzero_id
    // invariant: validate_non_negative
    // invariant: total_bus_bits_positive

    // -------------------------------------------------------
    // Benchmark blocks (simulation only)
    // -------------------------------------------------------
    initial begin : validate_latency_bench // synthesis translate_off
        $display("[BENCH] validate_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] validate_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] validate_latency : DONE");
    end // synthesis translate_on
    initial begin : port_count_latency_bench // synthesis translate_off
        $display("[BENCH] port_count_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] port_count_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] port_count_latency : DONE");
    end // synthesis translate_on

endmodule

`default_nettype wire
