// ============================================================================
// Generated from t27 spec: CTS
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module CTS (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Registers (from struct declarations)
    // -------------------------------------------------------
    // struct PllConfig
    reg [31:0] pllconfig_name; // PllConfig.name
    reg [31:0] pllconfig_input_mhz; // PllConfig.input_mhz
    reg [31:0] pllconfig_output_mhz; // PllConfig.output_mhz
    reg [31:0] pllconfig_multiply; // PllConfig.multiply
    reg [31:0] pllconfig_divide; // PllConfig.divide
    reg [31:0] pllconfig_jitter_ps; // PllConfig.jitter_ps
    // struct ClockBuffer
    reg [31:0] clockbuffer_name; // ClockBuffer.name
    reg [31:0] clockbuffer_delay_ps; // ClockBuffer.delay_ps
    reg [31:0] clockbuffer_fanout; // ClockBuffer.fanout
    // struct ClockTree
    reg [31:0] clocktree_root; // ClockTree.root
    reg [31:0] clocktree_num_levels; // ClockTree.num_levels
    reg [31:0] clocktree_total_buffers; // ClockTree.total_buffers
    reg [31:0] clocktree_max_skew_ps; // ClockTree.max_skew_ps
    // struct CtsReport
    reg [31:0] ctsreport_num_clocks; // CtsReport.num_clocks
    reg [31:0] ctsreport_num_plls; // CtsReport.num_plls
    reg [31:0] ctsreport_total_buffers; // CtsReport.total_buffers
    reg [31:0] ctsreport_worst_skew_ps; // CtsReport.worst_skew_ps
    reg [31:0] ctsreport_worst_latency_ps; // CtsReport.worst_latency_ps
    reg ctsreport_has_violations; // CtsReport.has_violations

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: pll_config
    function [31:0] pll_config; // -> PllConfig
        input [31:0] name;
        input [31:0] tr;
        input [31:0] input_mhz;
        input [31:0] output_mhz;
        begin
            reg [31:0] m = 1;
            reg [31:0] d = 1;
        end
    endfunction

    // function: pll_period_ps
    function [31:0] pll_period_ps; // -> u32
        input [31:0] pll;
        // TODO: implement
    endfunction

    // function: bufg
    function [31:0] bufg; // -> ClockBuffer
        input [31:0] name;
        input [31:0] tr;
        begin
            bufg = 0 /* ClockBuffer {...} */;
        end
    endfunction

    // function: bufh
    function [31:0] bufh; // -> ClockBuffer
        input [31:0] name;
        input [31:0] tr;
        begin
            bufh = 0 /* ClockBuffer {...} */;
        end
    endfunction

    // function: bufg_has_higher_fanout
    function bufg_has_higher_fanout; // -> bool
        input [31:0] b;
        begin
            bufg_has_higher_fanout = (b_fanout >= 32);
        end
    endfunction

    // function: clock_tree
    function [31:0] clock_tree; // -> ClockTree
        input [31:0] root;
        input [31:0] tr;
        input [31:0] levels;
        input [31:0] bufs;
        begin
            clock_tree = 0 /* ClockTree {...} */;
        end
    endfunction

    // function: tree_delay_ps
    function [31:0] tree_delay_ps; // -> u32
        input [31:0] tree;
        input [31:0] buf_delay;
        begin
            tree_delay_ps = (tree_num_levels * buf_delay);
        end
    endfunction

    // function: skew_ok
    function skew_ok; // -> bool
        input [31:0] tree;
        input [31:0] max_allowed_ps;
        begin
            skew_ok = (tree_max_skew_ps <= max_allowed_ps);
        end
    endfunction

    // function: cts_ok
    function [31:0] cts_ok; // -> CtsReport
        input [31:0] clocks;
        input [31:0] plls;
        input [31:0] bufs;
        input [31:0] skew;
        input [31:0] latency;
        begin
            cts_ok = 0 /* CtsReport {...} */;
        end
    endfunction

    // function: passed
    function passed; // -> bool
        input [31:0] r;
        begin
            passed = (r_has_violations == 1'b0);
        end
    endfunction

    // function: est_buffers_needed
    function [31:0] est_buffers_needed; // -> u32
        input [31:0] num_sinks;
        // TODO: implement
    endfunction

    // function: est_tree_levels
    function [31:0] est_tree_levels; // -> u32
        input [31:0] num_sinks;
        // TODO: implement
    endfunction

    // function: validate_pll
    function [31:0] validate_pll; // -> u32
        input [31:0] pll;
        begin
            reg [31:0] errors = 0;
        end
    endfunction
    // -------------------------------------------------------
    // Test assertions (from test blocks)
    // -------------------------------------------------------
    // synthesis translate_off
    // test: pll_config_creation
    initial begin : pll_config_creation_test
        $display("[TEST] pll_config_creation : starting");
        $display("[TEST] pll_config_creation : PASSED");
    end
    // test: bufg_creation
    initial begin : bufg_creation_test
        $display("[TEST] bufg_creation : starting");
        $display("[TEST] bufg_creation : PASSED");
    end
    // test: bufh_creation
    initial begin : bufh_creation_test
        $display("[TEST] bufh_creation : starting");
        $display("[TEST] bufh_creation : PASSED");
    end
    // test: clock_tree_creation
    initial begin : clock_tree_creation_test
        $display("[TEST] clock_tree_creation : starting");
        $display("[TEST] clock_tree_creation : PASSED");
    end
    // test: tree_delay
    initial begin : tree_delay_test
        $display("[TEST] tree_delay : starting");
        $display("[TEST] tree_delay : PASSED");
    end
    // test: skew_ok_yes
    initial begin : skew_ok_yes_test
        $display("[TEST] skew_ok_yes : starting");
        $display("[TEST] skew_ok_yes : PASSED");
    end
    // test: skew_ok_no
    initial begin : skew_ok_no_test
        $display("[TEST] skew_ok_no : starting");
        $display("[TEST] skew_ok_no : PASSED");
    end
    // test: cts_report_ok
    initial begin : cts_report_ok_test
        $display("[TEST] cts_report_ok : starting");
        $display("[TEST] cts_report_ok : PASSED");
    end
    // test: est_buffers_one
    initial begin : est_buffers_one_test
        $display("[TEST] est_buffers_one : starting");
        $display("[TEST] est_buffers_one : PASSED");
    end
    // test: est_buffers_many
    initial begin : est_buffers_many_test
        $display("[TEST] est_buffers_many : starting");
        $display("[TEST] est_buffers_many : PASSED");
    end
    // test: est_tree_levels_one
    initial begin : est_tree_levels_one_test
        $display("[TEST] est_tree_levels_one : starting");
        $display("[TEST] est_tree_levels_one : PASSED");
    end
    // test: est_tree_levels_two
    initial begin : est_tree_levels_two_test
        $display("[TEST] est_tree_levels_two : starting");
        $display("[TEST] est_tree_levels_two : PASSED");
    end
    // test: est_tree_levels_three
    initial begin : est_tree_levels_three_test
        $display("[TEST] est_tree_levels_three : starting");
        $display("[TEST] est_tree_levels_three : PASSED");
    end
    // test: validate_pll_ok
    initial begin : validate_pll_ok_test
        $display("[TEST] validate_pll_ok : starting");
        $display("[TEST] validate_pll_ok : PASSED");
    end
    // test: validate_pll_empty
    initial begin : validate_pll_empty_test
        $display("[TEST] validate_pll_empty : starting");
        $display("[TEST] validate_pll_empty : PASSED");
    end
    // synthesis translate_on

    // -------------------------------------------------------
    // Invariant checks (compile-time assertions)
    // -------------------------------------------------------
    // invariant: bufg_delay_positive
    // invariant: skew_non_negative

endmodule

`default_nettype wire
