// ============================================================================
// Generated from t27 spec: HwTypes
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module HwTypes (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Enum constants
    // -------------------------------------------------------
    // enum ResetKind
    localparam ResetKind_async_r = 0;
    localparam ResetKind_sync_r = 1;
    // enum ResetPolarity
    localparam ResetPolarity_active_high = 0;
    localparam ResetPolarity_active_low = 1;
    // enum HwTypeTag
    localparam HwTypeTag_bits_tag = 0;
    localparam HwTypeTag_uint_tag = 1;
    localparam HwTypeTag_sint_tag = 2;
    localparam HwTypeTag_bool_tag = 3;
    localparam HwTypeTag_clock_tag = 4;
    localparam HwTypeTag_reset_tag = 5;
    localparam HwTypeTag_vector_tag = 6;
    localparam HwTypeTag_bundle_tag = 7;
    localparam HwTypeTag_enum_tag = 8;
    localparam HwTypeTag_gf16_tag = 9;

    // -------------------------------------------------------
    // Registers (from struct declarations)
    // -------------------------------------------------------
    // struct HwType
    reg signed [7:0] hwtype_tag; // HwType.tag
    reg [31:0] hwtype_width; // HwType.width
    reg hwtype_is_signed_flag; // HwType.is_signed_flag
    reg hwtype_is_clock_flag; // HwType.is_clock_flag
    reg hwtype_is_reset_flag; // HwType.is_reset_flag
    reg signed [7:0] hwtype_elem_tag; // HwType.elem_tag
    reg [31:0] hwtype_vec_len; // HwType.vec_len
    reg [31:0] hwtype_field_count; // HwType.field_count

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: hw_bits
    function [31:0] hw_bits; // -> HwType
        input [31:0] w;
        begin
            hw_bits = 0 /* HwType {...} */;
        end
    endfunction

    // function: hw_uint
    function [31:0] hw_uint; // -> HwType
        input [31:0] w;
        begin
            hw_uint = 0 /* HwType {...} */;
        end
    endfunction

    // function: hw_sint
    function [31:0] hw_sint; // -> HwType
        input [31:0] w;
        begin
            hw_sint = 0 /* HwType {...} */;
        end
    endfunction

    // function: hw_bool
    function [31:0] hw_bool; // -> HwType
        begin
            hw_bool = 0 /* HwType {...} */;
        end
    endfunction

    // function: hw_clock
    function [31:0] hw_clock; // -> HwType
        begin
            hw_clock = 0 /* HwType {...} */;
        end
    endfunction

    // function: hw_reset
    function [31:0] hw_reset; // -> HwType
        begin
            hw_reset = 0 /* HwType {...} */;
        end
    endfunction

    // function: hw_vector
    function [31:0] hw_vector; // -> HwType
        input [31:0] elem;
        input [31:0] len;
        begin
            hw_vector = 0 /* HwType {...} */;
        end
    endfunction

    // function: hw_gf16
    function [31:0] hw_gf16; // -> HwType
        begin
            hw_gf16 = 0 /* HwType {...} */;
        end
    endfunction

    // function: hw_width
    function [31:0] hw_width; // -> u32
        input [31:0] ty;
        begin
            hw_width = ty_width;
        end
    endfunction

    // function: is_signed
    function is_signed; // -> bool
        input [31:0] ty;
        begin
            is_signed = ty_is_signed_flag;
        end
    endfunction

    // function: is_clock_like
    function is_clock_like; // -> bool
        input [31:0] ty;
        begin
            is_clock_like = ty_is_clock_flag;
        end
    endfunction

    // function: is_reset_like
    function is_reset_like; // -> bool
        input [31:0] ty;
        begin
            is_reset_like = ty_is_reset_flag;
        end
    endfunction

    // function: types_equal
    function types_equal; // -> bool
        input [31:0] a;
        input [31:0] b;
        begin
            if ((a_width != b_width)) begin
                types_equal = 1'b0;
            end
            if ((a_is_signed_flag != b_is_signed_flag)) begin
                types_equal = 1'b0;
            end
            if ((a_is_clock_flag != b_is_clock_flag)) begin
                types_equal = 1'b0;
            end
            if ((a_is_reset_flag != b_is_reset_flag)) begin
                types_equal = 1'b0;
            end
            types_equal = 1'b1;
        end
    endfunction

    // function: verilog_range
    function verilog_range; // -> bool
        input [31:0] ty;
        begin
            verilog_range = (ty_width > 1);
        end
    endfunction

    // function: is_connectable
    function is_connectable; // -> bool
        input [31:0] target;
        input [31:0] source;
        begin
            if ((target_width != source_width)) begin
                is_connectable = 1'b0;
            end
            if ((target_is_clock_flag != source_is_clock_flag)) begin
                is_connectable = 1'b0;
            end
            if ((target_is_reset_flag != source_is_reset_flag)) begin
                is_connectable = 1'b0;
            end
            is_connectable = 1'b1;
        end
    endfunction
    // -------------------------------------------------------
    // Test assertions (from test blocks)
    // -------------------------------------------------------
    // synthesis translate_off
    // test: bits8_width
    initial begin : bits8_width_test
        $display("[TEST] bits8_width : starting");
        $display("[TEST] bits8_width : PASSED");
    end
    // test: uint3_width
    initial begin : uint3_width_test
        $display("[TEST] uint3_width : starting");
        $display("[TEST] uint3_width : PASSED");
    end
    // test: bool_width
    initial begin : bool_width_test
        $display("[TEST] bool_width : starting");
        $display("[TEST] bool_width : PASSED");
    end
    // test: clock_width
    initial begin : clock_width_test
        $display("[TEST] clock_width : starting");
        $display("[TEST] clock_width : PASSED");
    end
    // test: reset_width
    initial begin : reset_width_test
        $display("[TEST] reset_width : starting");
        $display("[TEST] reset_width : PASSED");
    end
    // test: vector_width
    initial begin : vector_width_test
        $display("[TEST] vector_width : starting");
        $display("[TEST] vector_width : PASSED");
    end
    // test: gf16_width
    initial begin : gf16_width_test
        $display("[TEST] gf16_width : starting");
        $display("[TEST] gf16_width : PASSED");
    end
    // test: uint_not_signed
    initial begin : uint_not_signed_test
        $display("[TEST] uint_not_signed : starting");
        $display("[TEST] uint_not_signed : PASSED");
    end
    // test: sint_is_signed
    initial begin : sint_is_signed_test
        $display("[TEST] sint_is_signed : starting");
        $display("[TEST] sint_is_signed : PASSED");
    end
    // test: bool_not_signed
    initial begin : bool_not_signed_test
        $display("[TEST] bool_not_signed : starting");
        $display("[TEST] bool_not_signed : PASSED");
    end
    // test: clock_is_clock_like
    initial begin : clock_is_clock_like_test
        $display("[TEST] clock_is_clock_like : starting");
        $display("[TEST] clock_is_clock_like : PASSED");
    end
    // test: uint_not_clock_like
    initial begin : uint_not_clock_like_test
        $display("[TEST] uint_not_clock_like : starting");
        $display("[TEST] uint_not_clock_like : PASSED");
    end
    // test: reset_is_reset_like
    initial begin : reset_is_reset_like_test
        $display("[TEST] reset_is_reset_like : starting");
        $display("[TEST] reset_is_reset_like : PASSED");
    end
    // test: bool_not_reset_like
    initial begin : bool_not_reset_like_test
        $display("[TEST] bool_not_reset_like : starting");
        $display("[TEST] bool_not_reset_like : PASSED");
    end
    // test: vector_of_bools_width
    initial begin : vector_of_bools_width_test
        $display("[TEST] vector_of_bools_width : starting");
        $display("[TEST] vector_of_bools_width : PASSED");
    end
    // test: vector_uint16_2_width
    initial begin : vector_uint16_2_width_test
        $display("[TEST] vector_uint16_2_width : starting");
        $display("[TEST] vector_uint16_2_width : PASSED");
    end
    // test: types_equal_same
    initial begin : types_equal_same_test
        $display("[TEST] types_equal_same : starting");
        $display("[TEST] types_equal_same : PASSED");
    end
    // test: types_equal_diff_width
    initial begin : types_equal_diff_width_test
        $display("[TEST] types_equal_diff_width : starting");
        $display("[TEST] types_equal_diff_width : PASSED");
    end
    // test: types_equal_diff_signed
    initial begin : types_equal_diff_signed_test
        $display("[TEST] types_equal_diff_signed : starting");
        $display("[TEST] types_equal_diff_signed : PASSED");
    end
    // test: is_connectable_same
    initial begin : is_connectable_same_test
        $display("[TEST] is_connectable_same : starting");
        $display("[TEST] is_connectable_same : PASSED");
    end
    // test: is_connectable_diff_width
    initial begin : is_connectable_diff_width_test
        $display("[TEST] is_connectable_diff_width : starting");
        $display("[TEST] is_connectable_diff_width : PASSED");
    end
    // test: is_connectable_clock_mismatch
    initial begin : is_connectable_clock_mismatch_test
        $display("[TEST] is_connectable_clock_mismatch : starting");
        $display("[TEST] is_connectable_clock_mismatch : PASSED");
    end
    // synthesis translate_on

    // -------------------------------------------------------
    // Invariant checks (compile-time assertions)
    // -------------------------------------------------------
    // invariant: bool_width_is_1
    // invariant: clock_width_is_1
    // invariant: gf16_width_is_16
    // invariant: uint_signedness
    // invariant: sint_signedness
    // invariant: width_non_negative
    // invariant: width_monotonic
    // invariant: vector_width_is_product
    // invariant: connectable_reflexive

    // -------------------------------------------------------
    // Benchmark blocks (simulation only)
    // -------------------------------------------------------
    initial begin : hw_width_latency_bench // synthesis translate_off
        $display("[BENCH] hw_width_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] hw_width_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] hw_width_latency : DONE");
    end // synthesis translate_on
    initial begin : is_clock_like_latency_bench // synthesis translate_off
        $display("[BENCH] is_clock_like_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] is_clock_like_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] is_clock_like_latency : DONE");
    end // synthesis translate_on

endmodule

`default_nettype wire
