// ============================================================================
// Generated from t27 spec: Memory
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module Memory (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Parameters (from const declarations)
    // -------------------------------------------------------
    parameter [31:0] MAX_MEM_PORTS = 8;

    // -------------------------------------------------------
    // Enum constants
    // -------------------------------------------------------
    // enum MemKind
    localparam MemKind_bram = 0;
    localparam MemKind_dram = 1;
    localparam MemKind_rom = 2;
    // enum MemPortKind
    localparam MemPortKind_read_port = 0;
    localparam MemPortKind_write_port = 1;
    localparam MemPortKind_readwrite_port = 2;
    // enum MemLatency
    localparam MemLatency_comb_read = 0;
    localparam MemLatency_reg_read = 1;

    // -------------------------------------------------------
    // Registers (from struct declarations)
    // -------------------------------------------------------
    // struct MemPort
    reg [31:0] memport_name; // MemPort.name
    reg signed [7:0] memport_kind; // MemPort.kind
    reg [31:0] memport_addr_width; // MemPort.addr_width
    reg [31:0] memport_data_width; // MemPort.data_width
    reg signed [7:0] memport_latency; // MemPort.latency
    // struct MemDesc
    reg [31:0] memdesc_name; // MemDesc.name
    reg signed [7:0] memdesc_kind; // MemDesc.kind
    reg [31:0] memdesc_depth; // MemDesc.depth
    reg [31:0] memdesc_data_width; // MemDesc.data_width
    reg [31:0] memdesc_addr_width; // MemDesc.addr_width
    reg [31:0] memdesc_ports; // MemDesc.ports
    reg [31:0] memdesc_port_count; // MemDesc.port_count

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: empty_mem_port
    function [31:0] empty_mem_port; // -> MemPort
        begin
            empty_mem_port = 0 /* MemPort {...} */;
        end
    endfunction

    // function: make_mem_port
    function [31:0] make_mem_port; // -> MemPort
        input [31:0] name;
        input [31:0] tr;
        input signed [7:0] kind;
        input [31:0] addr_width;
        input [31:0] data_width;
        begin
            make_mem_port = 0 /* MemPort {...} */;
        end
    endfunction

    // function: empty_mem
    function [31:0] empty_mem; // -> MemDesc
        input [31:0] name;
        input [31:0] tr;
        input signed [7:0] kind;
        begin
            empty_mem = 0 /* MemDesc {...} */;
        end
    endfunction

    // function: make_bram
    function [31:0] make_bram; // -> MemDesc
        input [31:0] name;
        input [31:0] tr;
        input [31:0] depth;
        input [31:0] data_width;
        begin
            reg [31:0] addr_width = 0;
            reg [31:0] d = depth;
            while ((d > 1)) begin
                addr_width = (addr_width + 1);
                d = (d / 2);
            end
            if ((addr_width == 0)) begin
                addr_width = 1;
            end
            make_bram = 0 /* MemDesc {...} */;
        end
    endfunction

    // function: make_rom
    function [31:0] make_rom; // -> MemDesc
        input [31:0] name;
        input [31:0] tr;
        input [31:0] depth;
        input [31:0] data_width;
        begin
            reg [31:0] addr_width = 0;
            reg [31:0] d = depth;
            while ((d > 1)) begin
                addr_width = (addr_width + 1);
                d = (d / 2);
            end
            if ((addr_width == 0)) begin
                addr_width = 1;
            end
            make_rom = 0 /* MemDesc {...} */;
        end
    endfunction

    // function: add_read_port
    function [31:0] add_read_port; // -> MemDesc
        input [31:0] mem;
        input [31:0] name;
        input [31:0] tr;
        begin
            reg [31:0] result = mem;
            if ((result_port_count < 8)) begin
                result_ports[result_port_count] = make_mem_port(name, 0, result_addr_width, result_data_width);
                result_port_count = (result_port_count + 1);
            end
            add_read_port = result;
        end
    endfunction

    // function: add_write_port
    function [31:0] add_write_port; // -> MemDesc
        input [31:0] mem;
        input [31:0] name;
        input [31:0] tr;
        begin
            reg [31:0] result = mem;
            if ((result_port_count < 8)) begin
                result_ports[result_port_count] = make_mem_port(name, 1, result_addr_width, result_data_width);
                result_port_count = (result_port_count + 1);
            end
            add_write_port = result;
        end
    endfunction

    // function: add_rw_port
    function [31:0] add_rw_port; // -> MemDesc
        input [31:0] mem;
        input [31:0] name;
        input [31:0] tr;
        begin
            reg [31:0] result = mem;
            if ((result_port_count < 8)) begin
                result_ports[result_port_count] = make_mem_port(name, 2, result_addr_width, result_data_width);
                result_port_count = (result_port_count + 1);
            end
            add_rw_port = result;
        end
    endfunction

    // function: port_count
    function [31:0] port_count; // -> u32
        input [31:0] mem;
        begin
            port_count = mem_port_count;
        end
    endfunction

    // function: total_bits
    function [31:0] total_bits; // -> u32
        input [31:0] mem;
        begin
            total_bits = (mem_depth * mem_data_width);
        end
    endfunction

    // function: has_read_port
    function has_read_port; // -> bool
        input [31:0] mem;
        begin
            reg [31:0] i = 0;
            while ((i < mem_port_count)) begin
                if (((kind == 0) || (kind == 2))) begin
                    has_read_port = 1'b1;
                end
                i = (i + 1);
            end
            has_read_port = 1'b0;
        end
    endfunction

    // function: has_write_port
    function has_write_port; // -> bool
        input [31:0] mem;
        begin
            reg [31:0] i = 0;
            while ((i < mem_port_count)) begin
                if (((kind == 1) || (kind == 2))) begin
                    has_write_port = 1'b1;
                end
                i = (i + 1);
            end
            has_write_port = 1'b0;
        end
    endfunction

    // function: is_rom
    function is_rom; // -> bool
        input [31:0] mem;
        begin
            is_rom = (mem_kind == 2);
        end
    endfunction

    // function: is_bram
    function is_bram; // -> bool
        input [31:0] mem;
        begin
            is_bram = (mem_kind == 0);
        end
    endfunction

    // function: addr_width
    function [31:0] addr_width; // -> u32
        input [31:0] mem;
        begin
            addr_width = mem_addr_width;
        end
    endfunction

    // function: bram18_count
    function [31:0] bram18_count; // -> u32
        input [31:0] mem;
        begin
            reg [31:0] bits = (mem_depth * mem_data_width);
            reg [31:0] count = (bits / 18432);
            if (((bits % 18432) > 0)) begin
                count = (count + 1);
            end
            bram18_count = count;
        end
    endfunction

    // function: validate_mem
    function [31:0] validate_mem; // -> u32
        input [31:0] mem;
        begin
            reg [31:0] errors = 0;
            if ((mem_name == "")) begin
                errors = (errors + 1);
            end
            if ((mem_depth == 0)) begin
                errors = (errors + 1);
            end
            if ((mem_data_width == 0)) begin
                errors = (errors + 1);
            end
            if (((mem_kind == 2) && has_write_port(mem))) begin
                errors = (errors + 1);
            end
            validate_mem = errors;
        end
    endfunction
    // -------------------------------------------------------
    // Test assertions (from test blocks)
    // -------------------------------------------------------
    // synthesis translate_off
    // test: empty_mem_has_no_ports
    initial begin : empty_mem_has_no_ports_test
        $display("[TEST] empty_mem_has_no_ports : starting");
        $display("[TEST] empty_mem_has_no_ports : PASSED");
    end
    // test: make_bram_has_depth
    initial begin : make_bram_has_depth_test
        $display("[TEST] make_bram_has_depth : starting");
        $display("[TEST] make_bram_has_depth : PASSED");
    end
    // test: make_bram_small
    initial begin : make_bram_small_test
        $display("[TEST] make_bram_small : starting");
        $display("[TEST] make_bram_small : PASSED");
    end
    // test: make_bram_single
    initial begin : make_bram_single_test
        $display("[TEST] make_bram_single : starting");
        $display("[TEST] make_bram_single : PASSED");
    end
    // test: add_read_port_increments
    initial begin : add_read_port_increments_test
        $display("[TEST] add_read_port_increments : starting");
        $display("[TEST] add_read_port_increments : PASSED");
    end
    // test: add_write_port_increments
    initial begin : add_write_port_increments_test
        $display("[TEST] add_write_port_increments : starting");
        $display("[TEST] add_write_port_increments : PASSED");
    end
    // test: add_rw_port
    initial begin : add_rw_port_test
        $display("[TEST] add_rw_port : starting");
        $display("[TEST] add_rw_port : PASSED");
    end
    // test: is_rom
    initial begin : is_rom_test
        $display("[TEST] is_rom : starting");
        $display("[TEST] is_rom : PASSED");
    end
    // test: total_bits
    initial begin : total_bits_test
        $display("[TEST] total_bits : starting");
        $display("[TEST] total_bits : PASSED");
    end
    // test: bram18_count_small
    initial begin : bram18_count_small_test
        $display("[TEST] bram18_count_small : starting");
        $display("[TEST] bram18_count_small : PASSED");
    end
    // test: bram18_count_large
    initial begin : bram18_count_large_test
        $display("[TEST] bram18_count_large : starting");
        $display("[TEST] bram18_count_large : PASSED");
    end
    // test: validate_ok
    initial begin : validate_ok_test
        $display("[TEST] validate_ok : starting");
        $display("[TEST] validate_ok : PASSED");
    end
    // test: validate_empty_name
    initial begin : validate_empty_name_test
        $display("[TEST] validate_empty_name : starting");
        $display("[TEST] validate_empty_name : PASSED");
    end
    // test: validate_zero_depth
    initial begin : validate_zero_depth_test
        $display("[TEST] validate_zero_depth : starting");
        $display("[TEST] validate_zero_depth : PASSED");
    end
    // test: rom_with_write_port_invalid
    initial begin : rom_with_write_port_invalid_test
        $display("[TEST] rom_with_write_port_invalid : starting");
        $display("[TEST] rom_with_write_port_invalid : PASSED");
    end
    // synthesis translate_on

    // -------------------------------------------------------
    // Invariant checks (compile-time assertions)
    // -------------------------------------------------------
    // invariant: bram_depth_positive
    // invariant: bram_data_width_positive
    // invariant: addr_width_positive_for_nonzero_depth
    // invariant: total_bits_non_negative
    // invariant: port_count_within_bounds
    // invariant: bram18_count_positive

    // -------------------------------------------------------
    // Benchmark blocks (simulation only)
    // -------------------------------------------------------
    initial begin : bram18_count_latency_bench // synthesis translate_off
        $display("[BENCH] bram18_count_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] bram18_count_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] bram18_count_latency : DONE");
    end // synthesis translate_on

endmodule

`default_nettype wire
