// ============================================================================
// Generated from t27 spec: Power
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module Power (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Registers (from struct declarations)
    // -------------------------------------------------------
    // struct PowerDomain
    reg [31:0] powerdomain_name; // PowerDomain.name
    reg [31:0] powerdomain_voltage_mv; // PowerDomain.voltage_mv
    reg [31:0] powerdomain_clock_mhz; // PowerDomain.clock_mhz
    reg [31:0] powerdomain_toggle_rate; // PowerDomain.toggle_rate
    // struct PowerEstimate
    reg [31:0] powerestimate_dynamic_mw; // PowerEstimate.dynamic_mw
    reg [31:0] powerestimate_static_mw; // PowerEstimate.static_mw
    reg [31:0] powerestimate_total_mw; // PowerEstimate.total_mw
    reg [31:0] powerestimate_lut_power_uw; // PowerEstimate.lut_power_uw
    reg [31:0] powerestimate_ff_power_uw; // PowerEstimate.ff_power_uw
    reg [31:0] powerestimate_bram_power_uw; // PowerEstimate.bram_power_uw
    reg [31:0] powerestimate_dsp_power_uw; // PowerEstimate.dsp_power_uw

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: power_domain
    function [31:0] power_domain; // -> PowerDomain
        input [31:0] name;
        input [31:0] tr;
        input [31:0] clock_mhz;
        begin
            power_domain = 0 /* PowerDomain {...} */;
        end
    endfunction

    // function: lut_power_uw_per_mhz
    function [31:0] lut_power_uw_per_mhz; // -> u32
        begin
            lut_power_uw_per_mhz = 10;
        end
    endfunction

    // function: ff_power_uw_per_mhz
    function [31:0] ff_power_uw_per_mhz; // -> u32
        begin
            ff_power_uw_per_mhz = 5;
        end
    endfunction

    // function: bram_power_uw_per_mhz
    function [31:0] bram_power_uw_per_mhz; // -> u32
        begin
            bram_power_uw_per_mhz = 50;
        end
    endfunction

    // function: dsp_power_uw_per_mhz
    function [31:0] dsp_power_uw_per_mhz; // -> u32
        begin
            dsp_power_uw_per_mhz = 100;
        end
    endfunction

    // function: io_power_uw_per_mhz
    function [31:0] io_power_uw_per_mhz; // -> u32
        begin
            io_power_uw_per_mhz = 20;
        end
    endfunction

    // function: static_base_mw
    function [31:0] static_base_mw; // -> u32
        begin
            static_base_mw = 50;
        end
    endfunction

    // function: static_per_resource_uw
    function [31:0] static_per_resource_uw; // -> u32
        begin
            static_per_resource_uw = 100;
        end
    endfunction

    // function: power_estimate
    function [31:0] power_estimate; // -> PowerEstimate
        input [31:0] dynamic;
        input [31:0] static_p;
        begin
            power_estimate = 0 /* PowerEstimate {...} */;
        end
    endfunction

    // function: zero_power
    function [31:0] zero_power; // -> PowerEstimate
        begin
            zero_power = power_estimate(0, 0);
        end
    endfunction

    // function: est_lut_dynamic
    function [31:0] est_lut_dynamic; // -> u32
        input [31:0] luts;
        input [31:0] clock_mhz;
        input [31:0] toggle_rate;
        begin
            est_lut_dynamic = (((((luts * lut_power_uw_per_mhz()) * clock_mhz) * toggle_rate) / 1000) / 100);
        end
    endfunction

    // function: est_ff_dynamic
    function [31:0] est_ff_dynamic; // -> u32
        input [31:0] ffs;
        input [31:0] clock_mhz;
        input [31:0] toggle_rate;
        begin
            est_ff_dynamic = (((((ffs * ff_power_uw_per_mhz()) * clock_mhz) * toggle_rate) / 1000) / 100);
        end
    endfunction

    // function: est_bram_dynamic
    function [31:0] est_bram_dynamic; // -> u32
        input [31:0] brams;
        input [31:0] clock_mhz;
        begin
            est_bram_dynamic = (((brams * bram_power_uw_per_mhz()) * clock_mhz) / 1000);
        end
    endfunction

    // function: est_dsp_dynamic
    function [31:0] est_dsp_dynamic; // -> u32
        input [31:0] dsps;
        input [31:0] clock_mhz;
        begin
            est_dsp_dynamic = (((dsps * dsp_power_uw_per_mhz()) * clock_mhz) / 1000);
        end
    endfunction

    // function: est_static
    function [31:0] est_static; // -> u32
        input [31:0] total_resources;
        begin
            est_static = (static_base_mw() + ((total_resources * static_per_resource_uw()) / 1000));
        end
    endfunction

    // function: total_resources
    function [31:0] total_resources; // -> u32
        input [31:0] luts;
        input [31:0] ffs;
        input [31:0] brams;
        input [31:0] dsps;
        begin
            total_resources = (((luts + ffs) + brams) + dsps);
        end
    endfunction

    // function: est_total_power
    function [31:0] est_total_power; // -> PowerEstimate
        input [31:0] luts;
        input [31:0] ffs;
        input [31:0] brams;
        input [31:0] dsps;
        input [31:0] clock_mhz;
        input [31:0] toggle_rate;
        begin
            reg [31:0] lut_p = est_lut_dynamic(luts, clock_mhz, toggle_rate);
            reg [31:0] ff_p = est_ff_dynamic(ffs, clock_mhz, toggle_rate);
            reg [31:0] bram_p = est_bram_dynamic(brams, clock_mhz);
            reg [31:0] dsp_p = est_dsp_dynamic(dsps, clock_mhz);
            reg [31:0] dyn = (((lut_p + ff_p) + bram_p) + dsp_p);
            reg [31:0] stat = est_static(total_resources(luts, ffs, brams, dsps));
            est_total_power = 0 /* PowerEstimate {...} */;
        end
    endfunction

    // function: validate_domain
    function [31:0] validate_domain; // -> u32
        input [31:0] d;
        begin
            reg [31:0] errors = 0;
        end
    endfunction
    // -------------------------------------------------------
    // Test assertions (from test blocks)
    // -------------------------------------------------------
    // synthesis translate_off
    // test: power_domain_creation
    initial begin : power_domain_creation_test
        $display("[TEST] power_domain_creation : starting");
        $display("[TEST] power_domain_creation : PASSED");
    end
    // test: zero_power
    initial begin : zero_power_test
        $display("[TEST] zero_power : starting");
        $display("[TEST] zero_power : PASSED");
    end
    // test: power_estimate_creation
    initial begin : power_estimate_creation_test
        $display("[TEST] power_estimate_creation : starting");
        $display("[TEST] power_estimate_creation : PASSED");
    end
    // test: est_lut_dynamic
    initial begin : est_lut_dynamic_test
        $display("[TEST] est_lut_dynamic : starting");
        $display("[TEST] est_lut_dynamic : PASSED");
    end
    // test: est_ff_dynamic
    initial begin : est_ff_dynamic_test
        $display("[TEST] est_ff_dynamic : starting");
        $display("[TEST] est_ff_dynamic : PASSED");
    end
    // test: est_bram_dynamic
    initial begin : est_bram_dynamic_test
        $display("[TEST] est_bram_dynamic : starting");
        $display("[TEST] est_bram_dynamic : PASSED");
    end
    // test: est_dsp_dynamic
    initial begin : est_dsp_dynamic_test
        $display("[TEST] est_dsp_dynamic : starting");
        $display("[TEST] est_dsp_dynamic : PASSED");
    end
    // test: est_static
    initial begin : est_static_test
        $display("[TEST] est_static : starting");
        $display("[TEST] est_static : PASSED");
    end
    // test: est_static_base
    initial begin : est_static_base_test
        $display("[TEST] est_static_base : starting");
        $display("[TEST] est_static_base : PASSED");
    end
    // test: total_resources_calc
    initial begin : total_resources_calc_test
        $display("[TEST] total_resources_calc : starting");
        $display("[TEST] total_resources_calc : PASSED");
    end
    // test: est_total_power_arty
    initial begin : est_total_power_arty_test
        $display("[TEST] est_total_power_arty : starting");
        $display("[TEST] est_total_power_arty : PASSED");
    end
    // test: power_constants
    initial begin : power_constants_test
        $display("[TEST] power_constants : starting");
        $display("[TEST] power_constants : PASSED");
    end
    // test: validate_domain_ok
    initial begin : validate_domain_ok_test
        $display("[TEST] validate_domain_ok : starting");
        $display("[TEST] validate_domain_ok : PASSED");
    end
    // test: validate_domain_empty
    initial begin : validate_domain_empty_test
        $display("[TEST] validate_domain_empty : starting");
        $display("[TEST] validate_domain_empty : PASSED");
    end
    // test: validate_domain_zero_clock
    initial begin : validate_domain_zero_clock_test
        $display("[TEST] validate_domain_zero_clock : starting");
        $display("[TEST] validate_domain_zero_clock : PASSED");
    end
    // synthesis translate_on

    // -------------------------------------------------------
    // Invariant checks (compile-time assertions)
    // -------------------------------------------------------
    // invariant: power_non_negative
    // invariant: static_base_positive

    // -------------------------------------------------------
    // Benchmark blocks (simulation only)
    // -------------------------------------------------------
    initial begin : power_est_latency_bench // synthesis translate_off
        $display("[BENCH] power_est_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] power_est_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] power_est_latency : DONE");
    end // synthesis translate_on

endmodule

`default_nettype wire
