// ============================================================================
// Generated from t27 spec: Timing
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module Timing (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Enum constants
    // -------------------------------------------------------
    // enum ArcKind
    localparam ArcKind_comb = 0;
    localparam ArcKind_reg_to_reg = 1;
    localparam ArcKind_reg_to_output = 2;
    localparam ArcKind_input_to_reg = 3;
    localparam ArcKind_input_to_output = 4;

    // -------------------------------------------------------
    // Registers (from struct declarations)
    // -------------------------------------------------------
    // struct TimingArc
    reg [31:0] timingarc_source; // TimingArc.source
    reg [31:0] timingarc_sink; // TimingArc.sink
    reg [31:0] timingarc_delay_ps; // TimingArc.delay_ps
    reg signed [7:0] timingarc_kind; // TimingArc.kind
    // struct TimingPath
    reg [31:0] timingpath_startpoint; // TimingPath.startpoint
    reg [31:0] timingpath_endpoint; // TimingPath.endpoint
    reg [31:0] timingpath_total_delay_ps; // TimingPath.total_delay_ps
    reg signed [63:0] timingpath_slack_ps; // TimingPath.slack_ps
    reg [31:0] timingpath_num_arcs; // TimingPath.num_arcs
    // struct TimingConstraint
    reg [31:0] timingconstraint_name; // TimingConstraint.name
    reg [31:0] timingconstraint_period_ps; // TimingConstraint.period_ps
    reg [31:0] timingconstraint_clock_name; // TimingConstraint.clock_name
    // struct TimingReport
    reg [31:0] timingreport_total_paths; // TimingReport.total_paths
    reg [31:0] timingreport_met_paths; // TimingReport.met_paths
    reg [31:0] timingreport_violated_paths; // TimingReport.violated_paths
    reg signed [63:0] timingreport_worst_slack_ps; // TimingReport.worst_slack_ps
    reg [31:0] timingreport_critical_path_ps; // TimingReport.critical_path_ps
    reg [31:0] timingreport_fmax_mhz; // TimingReport.fmax_mhz
    reg timingreport_has_violations; // TimingReport.has_violations

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: comb_arc
    function [31:0] comb_arc; // -> TimingArc
        input [31:0] source;
        input [31:0] tr;
        input [31:0] sink;
        input [31:0] tr;
        input [31:0] delay_ps;
        begin
            comb_arc = 0 /* TimingArc {...} */;
        end
    endfunction

    // function: reg_to_reg
    function [31:0] reg_to_reg; // -> TimingArc
        input [31:0] source;
        input [31:0] tr;
        input [31:0] sink;
        input [31:0] tr;
        input [31:0] delay_ps;
        begin
            reg_to_reg = 0 /* TimingArc {...} */;
        end
    endfunction

    // function: input_to_reg
    function [31:0] input_to_reg; // -> TimingArc
        input [31:0] source;
        input [31:0] tr;
        input [31:0] sink;
        input [31:0] tr;
        input [31:0] delay_ps;
        begin
            input_to_reg = 0 /* TimingArc {...} */;
        end
    endfunction

    // function: timing_path
    function [31:0] timing_path; // -> TimingPath
        input [31:0] start;
        input [31:0] tr;
        input [31:0] end;
        input [31:0] tr;
        input [31:0] delay;
        input signed [63:0] slack;
        begin
            timing_path = 0 /* TimingPath {...} */;
        end
    endfunction

    // function: is_met
    function is_met; // -> bool
        input [31:0] path;
        begin
            is_met = (path_slack_ps >= 0);
        end
    endfunction

    // function: is_violated
    function is_violated; // -> bool
        input [31:0] path;
        begin
            is_violated = (path_slack_ps < 0);
        end
    endfunction

    // function: clock_constraint
    function [31:0] clock_constraint; // -> TimingConstraint
        input [31:0] name;
        input [31:0] tr;
        input [31:0] period_ps;
        begin
            clock_constraint = 0 /* TimingConstraint {...} */;
        end
    endfunction

    // function: clock_mhz
    function [31:0] clock_mhz; // -> TimingConstraint
        input [31:0] name;
        input [31:0] tr;
        input [31:0] mhz;
        // TODO: implement
    endfunction

    // function: timing_ok
    function [31:0] timing_ok; // -> TimingReport
        input [31:0] critical_ps;
        input [31:0] fmax;
        begin
            timing_ok = 0 /* TimingReport {...} */;
        end
    endfunction

    // function: timing_fail
    function [31:0] timing_fail; // -> TimingReport
        input [31:0] critical_ps;
        begin
            timing_fail = 0 /* TimingReport {...} */;
        end
    endfunction

    // function: passed
    function passed; // -> bool
        input [31:0] report;
        begin
            passed = (report_has_violations == 1'b0);
        end
    endfunction

    // function: lut_delay_ps
    function [31:0] lut_delay_ps; // -> u32
        begin
            lut_delay_ps = 100;
        end
    endfunction

    // function: bram_delay_ps
    function [31:0] bram_delay_ps; // -> u32
        begin
            bram_delay_ps = 2000;
        end
    endfunction

    // function: dsp_delay_ps
    function [31:0] dsp_delay_ps; // -> u32
        begin
            dsp_delay_ps = 2500;
        end
    endfunction

    // function: routing_delay_ps
    function [31:0] routing_delay_ps; // -> u32
        begin
            routing_delay_ps = 300;
        end
    endfunction

    // function: setup_time_ps
    function [31:0] setup_time_ps; // -> u32
        begin
            setup_time_ps = 200;
        end
    endfunction

    // function: hold_time_ps
    function [31:0] hold_time_ps; // -> u32
        begin
            hold_time_ps = 50;
        end
    endfunction

    // function: path_delay
    function [31:0] path_delay; // -> u32
        input [31:0] arcs;
        input [31:0] count;
        begin
            reg [31:0] total = 0;
            reg [31:0] i = 0;
        end
    endfunction

    // function: slack
    function signed [63:0] slack; // -> i64
        input [31:0] delay_ps;
        input [31:0] constraint_ps;
        begin
            slack = constraint_ps;
            as;
            (i64 - delay_ps);
            as;
            i64;
        end
    endfunction

    // function: fmax_from_delay
    function [31:0] fmax_from_delay; // -> u32
        input [31:0] delay_ps;
        // TODO: implement
    endfunction

    // function: est_comb_delay
    function [31:0] est_comb_delay; // -> u32
        input [31:0] num_luts;
        begin
            est_comb_delay = ((num_luts * lut_delay_ps()) + routing_delay_ps());
        end
    endfunction

    // function: est_reg_to_reg_delay
    function [31:0] est_reg_to_reg_delay; // -> u32
        input [31:0] num_luts;
        begin
            est_reg_to_reg_delay = (((num_luts * lut_delay_ps()) + routing_delay_ps()) + setup_time_ps());
        end
    endfunction

    // function: worst_path
    function [31:0] worst_path; // -> u32
        input [31:0] paths;
        input [31:0] count;
        begin
            reg [31:0] i = 1;
        end
    endfunction

    // function: validate_constraint
    function [31:0] validate_constraint; // -> u32
        input [31:0] tc;
        begin
            reg [31:0] errors = 0;
        end
    endfunction

    // function: validate_arc
    function [31:0] validate_arc; // -> u32
        input [31:0] arc;
        begin
            reg [31:0] errors = 0;
        end
    endfunction
    // -------------------------------------------------------
    // Test assertions (from test blocks)
    // -------------------------------------------------------
    // synthesis translate_off
    // test: comb_arc_creation
    initial begin : comb_arc_creation_test
        $display("[TEST] comb_arc_creation : starting");
        $display("[TEST] comb_arc_creation : PASSED");
    end
    // test: reg_to_reg_creation
    initial begin : reg_to_reg_creation_test
        $display("[TEST] reg_to_reg_creation : starting");
        $display("[TEST] reg_to_reg_creation : PASSED");
    end
    // test: input_to_reg_creation
    initial begin : input_to_reg_creation_test
        $display("[TEST] input_to_reg_creation : starting");
        $display("[TEST] input_to_reg_creation : PASSED");
    end
    // test: timing_path_met
    initial begin : timing_path_met_test
        $display("[TEST] timing_path_met : starting");
        $display("[TEST] timing_path_met : PASSED");
    end
    // test: timing_path_violated
    initial begin : timing_path_violated_test
        $display("[TEST] timing_path_violated : starting");
        $display("[TEST] timing_path_violated : PASSED");
    end
    // test: clock_constraint_creation
    initial begin : clock_constraint_creation_test
        $display("[TEST] clock_constraint_creation : starting");
        $display("[TEST] clock_constraint_creation : PASSED");
    end
    // test: clock_mhz_creation
    initial begin : clock_mhz_creation_test
        $display("[TEST] clock_mhz_creation : starting");
        $display("[TEST] clock_mhz_creation : PASSED");
    end
    // test: clock_mhz_zero
    initial begin : clock_mhz_zero_test
        $display("[TEST] clock_mhz_zero : starting");
        $display("[TEST] clock_mhz_zero : PASSED");
    end
    // test: timing_ok_report
    initial begin : timing_ok_report_test
        $display("[TEST] timing_ok_report : starting");
        $display("[TEST] timing_ok_report : PASSED");
    end
    // test: timing_fail_report
    initial begin : timing_fail_report_test
        $display("[TEST] timing_fail_report : starting");
        $display("[TEST] timing_fail_report : PASSED");
    end
    // test: path_delay_calc
    initial begin : path_delay_calc_test
        $display("[TEST] path_delay_calc : starting");
        $display("[TEST] path_delay_calc : PASSED");
    end
    // test: slack_positive
    initial begin : slack_positive_test
        $display("[TEST] slack_positive : starting");
        $display("[TEST] slack_positive : PASSED");
    end
    // test: slack_negative
    initial begin : slack_negative_test
        $display("[TEST] slack_negative : starting");
        $display("[TEST] slack_negative : PASSED");
    end
    // test: fmax_from_delay
    initial begin : fmax_from_delay_test
        $display("[TEST] fmax_from_delay : starting");
        $display("[TEST] fmax_from_delay : PASSED");
    end
    // test: fmax_zero_delay
    initial begin : fmax_zero_delay_test
        $display("[TEST] fmax_zero_delay : starting");
        $display("[TEST] fmax_zero_delay : PASSED");
    end
    // test: est_comb_delay
    initial begin : est_comb_delay_test
        $display("[TEST] est_comb_delay : starting");
        $display("[TEST] est_comb_delay : PASSED");
    end
    // test: est_reg_to_reg_delay
    initial begin : est_reg_to_reg_delay_test
        $display("[TEST] est_reg_to_reg_delay : starting");
        $display("[TEST] est_reg_to_reg_delay : PASSED");
    end
    // test: worst_path
    initial begin : worst_path_test
        $display("[TEST] worst_path : starting");
        $display("[TEST] worst_path : PASSED");
    end
    // test: worst_path_empty
    initial begin : worst_path_empty_test
        $display("[TEST] worst_path_empty : starting");
        $display("[TEST] worst_path_empty : PASSED");
    end
    // test: validate_constraint_ok
    initial begin : validate_constraint_ok_test
        $display("[TEST] validate_constraint_ok : starting");
        $display("[TEST] validate_constraint_ok : PASSED");
    end
    // test: validate_constraint_empty_name
    initial begin : validate_constraint_empty_name_test
        $display("[TEST] validate_constraint_empty_name : starting");
        $display("[TEST] validate_constraint_empty_name : PASSED");
    end
    // test: validate_arc_ok
    initial begin : validate_arc_ok_test
        $display("[TEST] validate_arc_ok : starting");
        $display("[TEST] validate_arc_ok : PASSED");
    end
    // test: validate_arc_empty_source
    initial begin : validate_arc_empty_source_test
        $display("[TEST] validate_arc_empty_source : starting");
        $display("[TEST] validate_arc_empty_source : PASSED");
    end
    // test: timing_model_constants
    initial begin : timing_model_constants_test
        $display("[TEST] timing_model_constants : starting");
        $display("[TEST] timing_model_constants : PASSED");
    end
    // synthesis translate_on

    // -------------------------------------------------------
    // Invariant checks (compile-time assertions)
    // -------------------------------------------------------
    // invariant: slack_consistent_with_fmax
    // invariant: timing_constants_positive

    // -------------------------------------------------------
    // Benchmark blocks (simulation only)
    // -------------------------------------------------------
    initial begin : timing_analysis_bench // synthesis translate_off
        $display("[BENCH] timing_analysis : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] timing_analysis : %%0d cycles", _bench_cycles);
        $display("[BENCH] timing_analysis : DONE");
    end // synthesis translate_on

endmodule

`default_nettype wire
