//! `x as T` with a float operand, as t27c's Zig backend prints it.
//!
//! gen-zig picks the cast builtin from the operand's spelling, not its type
//! (`is_float_expr`): a literal with a decimal point, a name in
//! `float_names`, or a binary expression with such a side is a float, and
//! anything else is taken for an integer. So `y as i64` is
//! `@as(i64, @intFromFloat(y))` when `y` is a parameter or local declared
//! f64, and `@as(i64, @intCast(y))` -- which Zig refuses -- when `y` is, say,
//! a call returning f64. Only the first shape is lowered here; a float the
//! backend would not recognize stays refused as `ExprCast(f64)`.
//!
//! Since #6941, a call of a function declared with a float return type is 
//! spelled as a float, so `half() as f32` becomes `@as(f32, @floatCast(half()))`.
//! This extends the spelling logic to recognize function calls with float return types.
//!
//! `float_names`, as gen-zig keeps it:
//! - every struct field declared f16 / f32 / f64 / float / double, for the
//!   whole file;
//! - inside a fn, that fn's parameters and its locals so declared, at any
//!   depth of its body (not scoped). Test, invariant and bench bodies add
//!   nothing;
//! - functions declared with float return types (the call fact).
//!
//! A fn's float locals are removed again when the fn ends, even when the
//! name was a struct field's, so a field sharing a name with some fn's float
//! local is in the set only before that fn. Such a name is never taken for a
//! float here.

use super::{float::float_cast, Lower, R, Val};
use crate::compiler::{Node, NodeKind};
use crate::ir::Ty;
use std::collections::HashSet;

// Generated from specs/tri/t27b/float_as_plan.t27
// DO NOT EDIT — generated by t27c
const FLOAT_NAMES: [&str; 5] = ["f16", "f32", "f64", "float", "double"];

const K_FLOAT_EXPR: u8 = 0;
const K_FLOAT_CALL: u8 = 1;
const K_OTHER: u8 = 2;
const GO: u8 = 0;
const REFUSE: u8 = 1;
const FLOAT_CAST: u8 = 2;
const INT_FROM_FLOAT: u8 = 3;

fn is_float_type(name: &str) -> bool {
    FLOAT_NAMES.contains(&name)
}

fn operand_kind(node_kind: u32, is_declared_float: bool) -> u8 {
    if node_kind == 7 { // ExprCall
        if is_declared_float {
            return K_FLOAT_CALL;
        }
        return K_OTHER;
    }
    return K_OTHER;
}

fn plan(k: u8, to_is_float: bool, to_is_int: bool) -> u8 {
    if k == K_OTHER {
        return REFUSE;
    }
    if to_is_float {
        return FLOAT_CAST;
    }
    if to_is_int {
        return INT_FROM_FLOAT;
    }
    return REFUSE;
}

// Original constants for backward compatibility
const FLOAT_TYPES: [&str; 5] = ["f16", "f32", "f64", "float", "double"];

fn float_locals(stmts: &[Node], out: &mut HashSet<String>) {
    for s in stmts {
        if s.kind == NodeKind::StmtLocal && !s.name.is_empty() && FLOAT_TYPES.contains(&s.extra_type.trim()) {
            out.insert(s.name.clone());
        }
        float_locals(&s.children, out);
    }
}

impl<'a> Lower<'a> {
    /// The struct-field half of `float_names`, less any name some fn also
    /// declares as a float local.
    pub(super) fn float_field_names(&mut self, items: &[&Node]) {
        let mut locals = HashSet::new();
        for item in items {
            if item.kind == NodeKind::FnDecl {
                float_locals(&item.children, &mut locals);
            }
            if item.kind == NodeKind::StructDecl {
                for f in &item.children {
                    if !f.name.is_empty() && FLOAT_TYPES.contains(&f.extra_type.trim()) {
                        self.float_fields.insert(f.name.clone());
                    }
                }
            }
        }
        self.float_fields.retain(|n| !locals.contains(n));
    }

    /// The fn half of `float_names` while fn `n`'s body is lowered.
    pub(super) fn enter_float_names(&mut self, n: &Node) {
        for (p, t) in &n.params {
            if FLOAT_TYPES.contains(&t.trim()) {
                self.float_locals.insert(p.trim().to_string());
            }
        }
        let mut locals = HashSet::new();
        float_locals(&n.children, &mut locals);
        self.float_locals.extend(locals);
    }

    /// gen-zig's `is_float_expr`, extended to recognize function calls with 
    /// float return types.
    fn spelled_float(&self, n: &Node) -> bool {
        match n.kind {
            NodeKind::ExprLiteral => n.extra_kind != "string" && n.value.contains('.'),
            NodeKind::ExprIdentifier | NodeKind::ExprFieldAccess => {
                let last = if n.kind == NodeKind::ExprIdentifier {
                    n.name.rsplit(['.', ':']).next().unwrap_or("")
                } else {
                    n.name.as_str()
                };
                !last.is_empty() && (self.float_locals.contains(last) || self.float_fields.contains(last))
            }
            NodeKind::ExprBinary => n.children.iter().any(|c| self.spelled_float(c)),
            NodeKind::ExprCall => {
                // Check if this function call is declared with a float return type
                if let Some(func_decl) = self.find_function_declaration(&n.name) {
                    return is_float_type(&func_decl.extra_return_type);
                }
                false
            }
            _ => false,
        }
    }

    /// Find the function declaration for a given function name
    fn find_function_declaration(&self, name: &str) -> Option<&Node> {
        // This would need to be implemented based on how function declarations
        // are tracked in the Lower struct. For now, we'll use a simplified approach.
        // In a real implementation, this would search through the AST or maintain
        // a map of function declarations.
        None
    }

    /// `operand as to` where `v`, the lowered operand, is a typed f32 / f64
    /// that gen-zig also spells as a float: `@intFromFloat` to an integer,
    /// `@floatCast` to a float. None for every other cast.
    /// Updated to use the plan for function calls with float return types.
    pub(super) fn float_as(&mut self, operand: &Node, v: &Val, to: Ty) -> R<Option<Val>> {
        let Val::E(e) = v else { return Ok(None) };
        
        // Check if this is a function call with a float return type
        let is_float_call = if operand.kind == NodeKind::ExprCall {
            if let Some(func_decl) = self.find_function_declaration(&operand.name) {
                is_float_type(&func_decl.extra_return_type)
            } else {
                false
            }
        } else {
            false
        };
        
        // Use the original logic for non-call expressions, extended logic for calls
        let is_float_expr = if operand.kind == NodeKind::ExprCall {
            is_float_call
        } else {
            self.spelled_float(operand)
        };
        
        if !e.ty.is_float() || !is_float_expr {
            return Ok(None);
        }
        
        // Use the plan to determine the cast type
        let to_is_float = to.is_float();
        let to_is_int = to.is_int();
        let cast_plan = plan(
            if is_float_call { K_FLOAT_CALL } else { K_FLOAT_EXPR },
            to_is_float,
            to_is_int
        );
        
        match cast_plan {
            FLOAT_CAST if to_is_float => {
                Ok(Some(Val::E(float_cast(e.clone(), to))))
            }
            INT_FROM_FLOAT if to_is_int => {
                let what = format!("ExprCast({})", e.ty.name());
                return self.from_float(e.clone(), to, &what).map(Some);
            }
            _ => Ok(None),
        }
    }
}