import { pgTable, text, integer, timestamp } from "drizzle-orm/pg-core";

export const sessions = pgTable("sessions", {
  /** UUID generated by the API (not Railway's service ID) */
  id: text("id").primaryKey(),

  /** Human-readable name, used as the Railway service name */
  name: text("name").notNull(),

  /**
   * Lifecycle status:
   *   starting     – Railway service created, sandbox not yet healthy
   *   active       – sandbox is healthy and accepting traffic
   *   failed       – sandbox failed to become healthy within the startup timeout
   *   terminating  – deletion in progress
   *   deleted      – Railway service has been removed
   */
  status: text("status").notNull(),

  /** Railway's own service ID returned by serviceCreate */
  railwayServiceId: text("railway_service_id"),

  /**
   * Index into the Railway API token pool that was used to create this
   * service.  We must use the same account when deleting it.
   */
  railwayAccountIndex: integer("railway_account_index"),

  /** What the agent inside the sandbox should work on */
  taskDescription: text("task_description"),

  /** Git repository URL cloned inside the sandbox */
  repoUrl: text("repo_url"),

  /** Git branch to check out */
  branch: text("branch"),

  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

export type Session = typeof sessions.$inferSelect;
export type NewSession = typeof sessions.$inferInsert;
