set_property -dict { PACKAGE_PIN M21 IOSTANDARD LVCMOS33 } [get_ports sys_clk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets sys_clk_IBUF]
set_property -dict { PACKAGE_PIN H7 IOSTANDARD LVCMOS33 } [get_ports sys_rst_n]
set_property -dict { PACKAGE_PIN G20 IOSTANDARD LVCMOS33 } [get_ports led_g20]
set_property -dict { PACKAGE_PIN G21 IOSTANDARD LVCMOS33 } [get_ports led_g21]
set_property -dict { PACKAGE_PIN R23 IOSTANDARD LVCMOS33 } [get_ports led_r23]
set_property -dict { PACKAGE_PIN T23 IOSTANDARD LVCMOS33 } [get_ports led_t23]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLDOWN [current_design]
