// Generated from t27 spec: port::trinity::tri::gen_hazard_pointers (module name)
// DO NOT EDIT — generated by t27c
// phi^2 + 1/phi^2 = 3 | TRINITY

const std = @import("std");
fn __t27_assert_fail(comptime fmt: []const u8, args: anytype) noreturn {
    if (@inComptime()) {
        @compileError("assertion failed");
    } else {
        std.debug.print(fmt, args);
        @panic("assertion failed");
    }
}
fn assert_eq(a: anytype, b: anytype) void {
    if (a != b) __t27_assert_fail("\n  {any}\n  != {any}\n", .{ a, b });
}

const MAX_HAZARDS = 10;
pub const HazardPointer = struct {
    pointer: ?*anyopaque,
    active: bool,
};
pub const HazardRegistry = struct {
    hazards: [MAX_HAZARDS]HazardPointer,
    allocator: ?*anyopaque,
};
pub fn HazardRegistry_init(allocator: ?*anyopaque) HazardRegistry {
    var hazards: [MAX_HAZARDS]HazardPointer = undefined;
    _ = &hazards;
    var i: usize = 0;
    _ = &i;
    while (i < 10) {
        hazards[i] = HazardPointer{ .pointer = null, .active = false };
        i += 1;
    }
    return HazardRegistry{ .hazards = hazards, .allocator = allocator };
}
pub fn HazardRegistry_acquire(registry: *HazardRegistry) ?*HazardPointer {
    var i: usize = 0;
    _ = &i;
    while (i < 10) {
        var h = &registry.hazards[i];
        _ = &h;
        if (!h.active) {
            h.active = true;
            return h;
        }
        i += 1;
    }
    return null;
}
pub fn HazardRegistry_release(hazard_arg: *HazardPointer) void {
    var hazard = hazard_arg;
    hazard.pointer = null;
    hazard.active = false;
}
pub fn HazardRegistry_deinit(registry: *HazardRegistry) void {
    var i: usize = 0;
    _ = &i;
    while (i < 10) {
        var h = &registry.hazards[i];
        _ = &h;
        if (h.active) {
            h.pointer = null;
            h.active = false;
        }
        i += 1;
    }
}
test "hazard_pointer_basic" {
    var registry = HazardRegistry_init(null);
    _ = &registry;
    var hazard = HazardRegistry_acquire(&registry);
    _ = &hazard;
    if (!(hazard != null)) __t27_assert_fail("\n  assertion failed:\n    hazard = {any}\n    null = {any}\n", .{ hazard, null });
}
test "hazard_pointer_acquire_multiple" {
    var registry = HazardRegistry_init(null);
    _ = &registry;
    var hazard1 = HazardRegistry_acquire(&registry);
    _ = &hazard1;
    var hazard2 = HazardRegistry_acquire(&registry);
    _ = &hazard2;
    if (!(hazard1 != null)) __t27_assert_fail("\n  assertion failed:\n    hazard1 = {any}\n    null = {any}\n", .{ hazard1, null });
    if (!(hazard2 != null)) __t27_assert_fail("\n  assertion failed:\n    hazard2 = {any}\n    null = {any}\n", .{ hazard2, null });
    if (!(hazard1 != hazard2)) __t27_assert_fail("\n  assertion failed:\n    hazard1 = {any}\n    hazard2 = {any}\n", .{ hazard1, hazard2 });
}
test "hazard_pointer_acquire_full" {
    var registry = HazardRegistry_init(null);
    _ = &registry;
    var i: usize = 0;
    _ = &i;
    while (i < 10) {
        var hazard = HazardRegistry_acquire(&registry);
        _ = &hazard;
        if (!(hazard != null)) __t27_assert_fail("\n  assertion failed:\n    hazard = {any}\n    null = {any}\n", .{ hazard, null });
        i += 1;
    }
    var extra = HazardRegistry_acquire(&registry);
    _ = &extra;
    if (!(extra == null)) __t27_assert_fail("\n  assertion failed:\n    extra = {any}\n    null = {any}\n", .{ extra, null });
}
test "hazard_pointer_release" {
    var registry = HazardRegistry_init(null);
    _ = &registry;
    var hazard = HazardRegistry_acquire(&registry);
    _ = &hazard;
    if (!(hazard != null)) __t27_assert_fail("\n  assertion failed:\n    hazard = {any}\n    null = {any}\n", .{ hazard, null });
    var i: usize = 0;
    _ = &i;
    while (i < 10) {
        if (&registry.hazards[i] == hazard) {
            HazardRegistry_release(&registry.hazards[i]);
break;
        }
        i += 1;
    }
}
