// Generated from t27 spec: tri::t27b::conformance::opaque_pointer (module name)
// DO NOT EDIT — generated by t27c
// phi^2 + 1/phi^2 = 3 | TRINITY

const std = @import("std");
fn __t27_assert_fail(comptime fmt: []const u8, args: anytype) noreturn {
    if (@inComptime()) {
        @compileError("assertion failed");
    } else {
        std.debug.print(fmt, args);
        @panic("assertion failed");
    }
}
fn assert_eq(a: anytype, b: anytype) void {
    if (a != b) __t27_assert_fail("\n  {any}\n  != {any}\n", .{ a, b });
}

fn test_param(ptr: ?*anyopaque) bool {
    return ptr != null;
}
const TestStruct = struct {
    field: ?*anyopaque,
};
fn test_field() bool {
    var s = TestStruct{ .field = null };
    _ = &s;
    return s.field == null;
}
fn test_local() bool {
    var ptr: ?*anyopaque = null;
    _ = &ptr;
    return ptr == null;
}
fn test_ptr_from_int_zero() bool {
    const ptr = @ptrFromInt(0);
    return ptr == null;
}
fn test_ptr_from_int_eight() bool {
    const ptr = @ptrFromInt(8);
    return ptr != null;
}
fn test_ptr_from_int_runtime(n: u64) bool {
    const ptr = @ptrFromInt(n);
    return if (n == 0) ptr == null else ptr != null;
}
fn helper(ptr: ?*anyopaque) bool {
    return ptr != null;
}
test "param_test" {
    if (!(test_param(null))) @panic("assertion failed");
    if (!(test_param(@ptrFromInt(1)))) @panic("assertion failed");
}
test "field_test" {
    if (!(test_field())) @panic("assertion failed");
}
test "local_test" {
    if (!(test_local())) @panic("assertion failed");
}
test "ptr_from_int_zero_test" {
    if (!(test_ptr_from_int_zero())) @panic("assertion failed");
}
test "ptr_from_int_eight_test" {
    if (!(test_ptr_from_int_eight())) @panic("assertion failed");
}
test "ptr_from_int_runtime_test" {
    if (!(test_ptr_from_int_runtime(0))) @panic("assertion failed");
    if (!(test_ptr_from_int_runtime(8))) @panic("assertion failed");
    if (!(test_ptr_from_int_runtime(16))) @panic("assertion failed");
}
test "helper_test" {
    if (!(helper(null))) @panic("assertion failed");
    if (!(helper(@ptrFromInt(1)))) @panic("assertion failed");
}
