// Generated from .t27 spec: enrichment::youtube_transcript
// DO NOT EDIT — generated by t27c
// phi^2 + 1/phi^2 = 3 | TRINITY

use serde::{Deserialize, Serialize};

/// YouTube video source
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct YouTubeSource {
    pub url: String,
    pub video_id: Option<String>,
    pub title: String,
}

/// Extracted transcript
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Transcript {
    pub video_id: String,
    pub title: String,
    pub text: String,
    pub lang: String,
    pub size_bytes: u32,
}

/// Enrichment result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnrichmentReport {
    pub sources_added: u32,
    pub transcripts_added: u32,
    pub transcripts_failed: u32,
    pub errors: Vec<String>,
}

/// Error codes for transcript operations
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ErrorCode {
    Success = 0,
    YtDlpNotFound = 1,
    VideoUnavailable = 2,
    NoSubtitles = 3,
    TranscriptTooLarge = 4,
    InvalidYouTubeUrl = 5,
    TranscriptTimeout = 6,
    EncodingError = 7,
    ApiAuthFailed = 8,
    NetworkError = 9,
    UnknownError = 99,
}

/// YouTube domains for URL detection
pub const YOUTUBE_DOMAINS: &[&str] = &[
    "youtube.com",
    "www.youtube.com",
    "m.youtube.com",
    "music.youtube.com",
    "youtu.be",
];

/// Maximum transcript size (10MB)
pub const MAX_TRANSCRIPT_SIZE: u32 = 10 * 1024 * 1024;

/// YouTube timeout in seconds
pub const YOUTUBE_TIMEOUT_SECONDS: u32 = 60;

/// yt-dlp version check timeout
pub const YTDLP_CHECK_TIMEOUT_SECONDS: u32 = 10;

/// Check if URL is a YouTube URL
pub fn is_youtube_url(url: &str) -> bool {
    let trimmed = url.trim();
    let lower = trimmed.to_lowercase();

    for domain in YOUTUBE_DOMAINS {
        if lower.contains(domain) {
            return true;
        }
    }
    false
}

/// Extract YouTube video ID from URL
/// Handles: youtu.be/VIDEO_ID, youtube.com/watch?v=VIDEO_ID, shorts/, embed/, live/, v/
pub fn extract_video_id(url: &str) -> Option<String> {
    let trimmed = url.trim();

    // youtu.be short URLs
    if trimmed.starts_with("youtu.be/") {
        let path = &trimmed[9..];
        if let Some(slash_idx) = path.find('/') {
            let id = &path[..slash_idx];
            if !id.is_empty() {
                return Some(id.to_string());
            }
        } else {
            let id = path;
            return Some(id.to_string());
        }
    }

    // youtube.com path-based formats
    if trimmed.contains("youtube.com/") {
        if let Some(path_start) = trimmed.find("youtube.com/") {
            let path = &trimmed[path_start + 11..];
            let segments: Vec<&str> = path.split('/').filter(|s| !s.is_empty()).collect();

            // Handle shorts/, embed/, live/, v/ prefixes
            if segments.len() >= 2 {
                let first = segments[0];
                if matches!(first, "shorts" | "embed" | "live" | "v") {
                    if segments.len() >= 2 {
                        return Some(segments[1].to_string());
                    }
                }
            }
        }
    }

    // Query param ?v=VIDEO_ID
    if let Some(v_param) = trimmed.find("v=") {
        let id_start = v_param + 2;
        if let Some(amp_idx) = trimmed[id_start..].find('&') {
            return Some(trimmed[id_start..amp_idx].to_string());
        } else {
            return Some(trimmed[id_start..].to_string());
        }
    }

    None
}

/// Convert SRT subtitle format to plain text
/// Filters out timestamps, line numbers, keeps only subtitle text
pub fn srt_to_text(srt_content: &str) -> String {
    let mut result_lines: Vec<String> = Vec::new();
    let mut in_text_block = false;
    let mut was_empty_line = true;

    for line in srt_content.lines() {
        let trimmed = line.trim();

        // Skip timestamps (contain -->)
        if trimmed.contains("-->") {
            in_text_block = false;
            continue;
        }

        // Check if line is just a number
        let is_line_number = trimmed.chars().all(|c| c.is_ascii_digit());
        if !is_line_number && !trimmed.is_empty() {
            if !in_text_block && was_empty_line {
                in_text_block = true;
            }
            if in_text_block && !trimmed.is_empty() {
                result_lines.push(trimmed.to_string());
            }
        }

        was_empty_line = trimmed.is_empty();
    }

    result_lines.join("\n")
}

/// Extract transcript using yt-dlp subprocess
/// Returns (transcript, error_code) tuple
pub fn extract_transcript(video_url: &str) -> (Transcript, ErrorCode) {
    // Extract video ID for identification
    let video_id = extract_video_id(video_url)
        .unwrap_or_else(|| "unknown".to_string());

    // Run yt-dlp --version to check availability (timeout 10s)
    let ytdlp_check = std::process::Command::new("yt-dlp")
        .arg("--version")
        .output();

    let ytdlp_result = ytdlp_check
        .timeout(std::time::Duration::from_secs(YTDLP_CHECK_TIMEOUT_SECONDS as u64));

    if ytdlp_result.is_err() || !ytdlp_result.unwrap().status.success() {
        let error_result = Transcript {
            video_id: video_id.clone(),
            title: String::new(),
            text: String::new(),
            lang: String::new(),
            size_bytes: 0,
        };
        return (error_result, ErrorCode::YtDlpNotFound);
    }

    // Create temp directory for SRT files
    let temp_dir = match tempfile::tempdir() {
        Ok(dir) => dir,
        Err(_) => {
            let error_result = Transcript {
                video_id: video_id.clone(),
                title: String::new(),
                text: String::new(),
                lang: String::new(),
                size_bytes: 0,
            };
            return (error_result, ErrorCode::UnknownError);
        }
    };

    // Build yt-dlp command
    // Skip download, write subtitles, auto-subs, English only, SRT format
    let output_template = temp_dir.path().join("%(title)s.%(ext)s");

    let output = match std::process::Command::new("yt-dlp")
        .arg("--no-update")
        .arg("--skip-download")
        .arg("--write-subs")
        .arg("--write-auto-subs")
        .arg("--sub-langs")
        .arg("en")
        .arg("--sub-format")
        .arg("srt")
        .arg("-o")
        .arg(&output_template)
        .arg(video_url)
        .output() {
            Ok(output) => output,
            Err(e) => {
                let stderr = String::from_utf8_lossy(&e.stderr);
                let error_result = Transcript {
                    video_id: video_id.clone(),
                    title: String::new(),
                    text: String::new(),
                    lang: String::new(),
                    size_bytes: 0,
                };
                let error = match stderr {
                    s if s.contains("unavailable") || s.contains("video has been removed") => ErrorCode::VideoUnavailable,
                    s if s.contains("subtitles") || s.contains("no subtitles available") => ErrorCode::NoSubtitles,
                    _ => ErrorCode::UnknownError,
                };
                return (error_result, error);
            }
        };

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        let error_result = Transcript {
            video_id: video_id.clone(),
            title: String::new(),
            text: String::new(),
            lang: String::new(),
            size_bytes: 0,
        };
        let error = if stderr.contains("unavailable") || stderr.contains("video has been removed") {
            ErrorCode::VideoUnavailable
        } else if stderr.contains("subtitles") || stderr.contains("no subtitles available") {
            ErrorCode::NoSubtitles
        } else {
            ErrorCode::UnknownError
        };
        return (error_result, error);
    }

    // Find SRT files in temp directory
    let srt_files: Vec<std::path::PathBuf> = std::fs::read_dir(temp_dir.path())
        .unwrap_or_default()
        .filter(|e| e.path().extension().map_or(String::new(), |ext| ext == "srt"))
        .map(|e| e.path())
        .collect();

    if srt_files.is_empty() {
        let error_result = Transcript {
            video_id: video_id.clone(),
            title: String::new(),
            text: String::new(),
            lang: String::new(),
            size_bytes: 0,
        };
        return (error_result, ErrorCode::NoSubtitles);
    }

    // Read the first SRT file
    let srt_path = &srt_files[0];
    let srt_content_result = std::fs::read_to_string(srt_path);

    let srt_content = match srt_content_result {
        Ok(content) => content,
        Err(_) => {
            let error_result = Transcript {
                video_id: video_id.clone(),
                title: String::new(),
                text: String::new(),
                lang: String::new(),
                size_bytes: 0,
            };
            return (error_result, ErrorCode::EncodingError);
        }
    };

    // Convert SRT to plain text
    let transcript_text = srt_to_text(&srt_content);

    // Check if transcript is empty
    let trimmed_text = transcript_text.trim();
    if trimmed_text.is_empty() {
        let error_result = Transcript {
            video_id: video_id.clone(),
            title: String::new(),
            text: String::new(),
            lang: String::new(),
            size_bytes: 0,
        };
        return (error_result, ErrorCode::NoSubtitles);
    }

    // Check size limit
    let size_bytes = transcript_text.len() as u32;
    if size_bytes > MAX_TRANSCRIPT_SIZE {
        let error_result = Transcript {
            video_id: video_id.clone(),
            title: String::new(),
            text: String::new(),
            lang: String::new(),
            size_bytes: 0,
        };
        return (error_result, ErrorCode::TranscriptTooLarge);
    }

    // Extract title from filename (stem)
    let filename = srt_path.file_name().unwrap_or_default().to_string_lossy();
    let title = filename.strip_suffix(".srt").unwrap_or(&filename).to_string();

    let transcript = Transcript {
        video_id: video_id,
        title,
        text: transcript_text,
        lang: "en".to_string(),
        size_bytes,
    };

    (transcript, ErrorCode::Success)
}

/// Upload transcript to NotebookLM via Discovery Engine REST API
pub fn upload_transcript(
    notebook_id: &str,
    transcript: &Transcript,
    api_token: &str,
) -> ErrorCode {
    use base64::Engine;

    // Build REST API URL
    let url = format!("https://discoveryengine.googleapis.com/v1alpha/{}:addSource", notebook_id);

    // Build request body with base64 encoded content
    let encoded_content = base64::engine::general_purpose::STANDARD.encode(&transcript.text);
    let display_title = format!("🎥 {} (transcript)", transcript.title);

    let body = serde_json::json!({
        "rawContent": encoded_content,
        "mimeType": "text/plain",
        "title": display_title,
    });

    // Send HTTP POST request
    let client = reqwest::blocking::Client::new();
    match client
        .post(&url)
        .header("Authorization", format!("Bearer {}", api_token))
        .header("Content-Type", "application/json")
        .json(&body)
        .send()
    {
        Ok(response) => {
            let status = response.status();
            let code = status.as_u16();
            if code == 401 || code == 403 {
                return ErrorCode::ApiAuthFailed;
            }
            if code < 200 || code >= 300 {
                return ErrorCode::NetworkError;
            }
            ErrorCode::Success
        }
        Err(_) => ErrorCode::NetworkError,
    }
}

/// Enrich notebook with YouTube transcripts
/// Iterates through sources, extracts and uploads transcripts for YouTube URLs
pub fn enrich_with_transcripts(
    notebook_id: &str,
    sources: &[String],
    api_token: &str,
) -> EnrichmentReport {
    let mut report = EnrichmentReport {
        sources_added: 0,
        transcripts_added: 0,
        transcripts_failed: 0,
        errors: Vec::new(),
    };

    for url in sources {
        // Check if URL is YouTube
        if !is_youtube_url(url) {
            continue; // Skip non-YouTube URLs
        }

        // Extract transcript
        let (transcript, error) = extract_transcript(url);

        if error != ErrorCode::Success {
            report.transcripts_failed += 1;
            let error_msg = match error {
                ErrorCode::VideoUnavailable => format!("Video unavailable: {}", url),
                ErrorCode::NoSubtitles => format!("No subtitles: {}", url),
                ErrorCode::YtDlpNotFound => "yt-dlp not found".to_string(),
                ErrorCode::TranscriptTooLarge => format!("Transcript too large: {}", url),
                ErrorCode::TranscriptTimeout => format!("Timeout: {}", url),
                _ => format!("Unknown error: {}", url),
            };
            report.errors.push(error_msg);
            continue;
        }

        // Upload transcript
        let upload_error = upload_transcript(notebook_id, &transcript, api_token);

        if upload_error != ErrorCode::Success {
            report.transcripts_failed += 1;
            let error_msg = match upload_error {
                ErrorCode::ApiAuthFailed => format!("API auth failed: {}", transcript.title),
                ErrorCode::NetworkError => format!("Network error: {}", transcript.title),
                _ => format!("Upload failed: {}", transcript.title),
            };
            report.errors.push(error_msg);
            continue;
        }

        // Success
        report.transcripts_added += 1;
    }

    report
}
