// Generated from t27 spec: PocStatic (module name)
// DO NOT EDIT — generated by t27c
// phi^2 + 1/phi^2 = 3 | TRINITY

const std = @import("std");
fn __t27_assert_fail(comptime fmt: []const u8, args: anytype) noreturn {
    if (@inComptime()) {
        @compileError("assertion failed");
    } else {
        std.debug.print(fmt, args);
        @panic("assertion failed");
    }
}
fn assert_eq(a: anytype, b: anytype) void {
    if (a != b) __t27_assert_fail("\n  {any}\n  != {any}\n", .{ a, b });
}

var counter: u8 = 0;
fn on_clock() void {
    counter = counter + 1;
}
test "static_counter_increments" {
    assert_eq(counter, 0);
    on_clock();
    assert_eq(counter, 1);
    on_clock();
    assert_eq(counter, 2);
}
