//! Behavioural tests for `t27c gen-python`: does the emitted module PARSE,
//! does it IMPORT, and does every constant read back the value the spec wrote?
//!
//! The unit tests in `src/codegen_python.rs` read the emitted TEXT. That is the
//! blind spot `backend_behaviour.rs` was written for on the C and Rust side: a
//! `true` printed as `true`, a field read as `.x` from a dict, a `//` that
//! should have been `/` -- each is a green exit over a module that dies at
//! import or reads the wrong number. So each test here generates through the
//! real binary (imports spliced, as a user gets it), hands the artifact to
//! `python3`, and checks what Python says the values ARE.
//!
//! A test that cannot find `python3` still checks the text, then skips the
//! Python half loudly -- an absent interpreter is not a passing test.
//!
//! Measured over the corpus when this backend landed (1184 specs under
//! `specs/`): 1172 artifacts parse with `ast.parse` and execute; 12 specs are
//! refused before generation by the parser, identically for every backend; no
//! artifact failed to parse. One test holds `bootstrap/src/codegen_python.t27`
//! to the lines it says this backend prints. The last test pins one category
//! the backend still announces instead of emitting, so the fix that closes it
//! flips the test on purpose rather than by accident.

use std::process::Command;

fn tool_present(tool: &str) -> bool {
    Command::new(tool)
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// Per-test and per-process, for the reason `backend_behaviour.rs` gives: a
/// failing run leaves its artifact at a path someone can find again, and two
/// concurrent runs never delete each other's directory.
fn tmp_dir(tag: &str) -> std::path::PathBuf {
    let d = std::env::temp_dir().join(format!("t27c-gen-python-{tag}-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&d);
    std::fs::create_dir_all(&d).expect("create temp dir");
    d
}

fn repo_spec(rel: &str) -> std::path::PathBuf {
    let mut p = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.pop();
    p.join(rel)
}

/// Run `t27c gen-python` on a file and return (exit ok, stdout, stderr).
fn gen_python_file(path: &std::path::Path) -> (bool, String, String) {
    let out = Command::new(env!("CARGO_BIN_EXE_t27c"))
        .arg("gen-python")
        .arg(path)
        .output()
        .expect("run t27c");
    (
        out.status.success(),
        String::from_utf8_lossy(&out.stdout).to_string(),
        String::from_utf8_lossy(&out.stderr).to_string(),
    )
}

fn gen_python(spec: &str, dir: &std::path::Path, tag: &str) -> String {
    let spec_path = dir.join("in.t27");
    std::fs::write(&spec_path, spec).expect("write spec");
    let (ok, out, err) = gen_python_file(&spec_path);
    assert!(ok, "{tag}: `t27c gen-python` failed: {err}");
    assert!(!out.is_empty(), "{tag}: `t27c gen-python` printed an EMPTY module");
    out
}

/// `ast.parse` the artifact, execute it, and print `NAME=repr(value)` for each
/// name asked for, one per line. `None` when there is no `python3`.
fn python_says(module: &str, names: &[&str], tag: &str) -> Option<String> {
    if !tool_present("python3") {
        eprintln!("SKIP {tag}: no python3 on PATH -- the artifact text was checked, its values were not");
        return None;
    }
    let dir = tmp_dir(tag);
    let py_path = dir.join("artifact.py");
    std::fs::write(&py_path, module).expect("write artifact");
    let probe = "import ast, sys\n\
                 src = open(sys.argv[1]).read()\n\
                 ast.parse(src, sys.argv[1])\n\
                 ns = {}\n\
                 exec(compile(src, sys.argv[1], 'exec'), ns)\n\
                 for name in sys.argv[2:]:\n    print(name + '=' + repr(ns[name]))\n";
    let run = Command::new("python3")
        .arg("-c")
        .arg(probe)
        .arg(&py_path)
        .args(names)
        .output()
        .expect("run python3");
    assert!(
        run.status.success(),
        "{tag}: the generated module does not parse or import:\n{}\n--- module ---\n{module}",
        String::from_utf8_lossy(&run.stderr)
    );
    Some(String::from_utf8_lossy(&run.stdout).trim_end().to_string())
}

/// The spec the corpus opens on. Its artifact must parse and import, and the
/// four declarations it holds must be the four the module binds -- its three
/// fns, two tests and two invariants announced, not stubbed.
#[test]
fn gen_python_hello_world_parses_and_imports() {
    let (ok, module, err) = gen_python_file(&repo_spec("specs/demos/hello_world.t27"));
    assert!(ok, "gen-python refused hello_world.t27: {err}");
    assert!(module.starts_with("# Generated by `t27c gen-python` from hello_world.t27."), "{module}");
    assert!(module.contains("\nMAGIC_NUMBER = 0xDEADBEEF\n"), "{module}");
    assert!(module.contains("\nFLAG_ENABLE = True\n"), "{module}");
    assert!(
        module.contains("__DECL_ORDER__ = [\"MAGIC_NUMBER\", \"VERSION\", \"FLAG_ENABLE\", \"ConfigPacked\"]\n"),
        "{module}"
    );
    // Three fns, two tests and two invariants: each is announced in a comment
    // AND listed. The list used to stay empty while all seven were missing,
    // and this test pinned that empty list (#6559).
    assert_eq!(module.matches("was not emitted -- this backend lowers declarations").count(), 3, "{module}");
    assert_eq!(module.matches("{ \"what\": \"fn ").count(), 3, "{module}");
    assert_eq!(module.matches("{ \"what\": \"test ").count(), 2, "{module}");
    assert_eq!(module.matches("{ \"what\": \"invariant ").count(), 2, "{module}");
    assert!(!module.contains("def "), "a fn must be announced, never stubbed:\n{module}");
    assert!(!module.contains("export "), "{module}");

    if let Some(said) = python_says(
        &module,
        &["MAGIC_NUMBER", "VERSION", "FLAG_ENABLE", "ConfigPacked", "__NOT_EMITTED__"],
        "hello_world",
    ) {
        assert_eq!(
            said,
            "MAGIC_NUMBER=3735928559\n\
             VERSION=1\n\
             FLAG_ENABLE=True\n\
             ConfigPacked={'__struct__': 'ConfigPacked', 'fields': [['width', 'u8'], ['height', 'u8'], ['depth', 'u8'], ['enable', 'bool']]}\n\
             __NOT_EMITTED__=[{'what': 'fn create_config', 'why': 'this backend lowers declarations, not bodies.'}, \
             {'what': 'fn calculate_area', 'why': 'this backend lowers declarations, not bodies.'}, \
             {'what': 'fn is_config_valid', 'why': 'this backend lowers declarations, not bodies.'}, \
             {'what': 'test \"basic_config_creation\"', 'why': 'it is checked by the compiler, not by the artifact.'}, \
             {'what': 'test \"area_calculation\"', 'why': 'it is checked by the compiler, not by the artifact.'}, \
             {'what': 'invariant \"config_field_bounds\"', 'why': 'it is checked by the compiler, not by the artifact.'}, \
             {'what': 'invariant \"area_consistency\"', 'why': 'it is checked by the compiler, not by the artifact.'}]"
        );
    }
}

const SPEC_CONSTANTS: &str = r#"module Consts;

pub const COUNT : u32 = 42;
pub const MASK : u32 = 0xFF00;
pub const NEG : i32 = -7;
pub const RATIO : f64 = 1.618033988749895;
pub const ENABLED : bool = true;
pub const DISABLED : bool = false;
pub const TAG : str = "GET";
pub const HALF : u8 = 7 / 2;
pub const BOTH : bool = ENABLED && !DISABLED;
pub const WIDE : u64 = 1 << 40;
pub const VER : [4]u8 = "v1.2";
pub const Level = enum { Low, High = 7, Top, };

test count_is_the_answer {
    assert COUNT == 42;
}
"#;

/// Every constant keeps its VALUE, read back by Python rather than by eye:
/// hex stays the same number, `true` is `True`, `7 / 2` on a u8 is 3 and not
/// 3.5, `1 << 40` on a u64 survives (the JS path refuses it past 32 bits), a
/// byte string is its bytes, and an enum resumes counting after `High = 7`.
#[test]
fn gen_python_constants_keep_their_values() {
    let tag = "constants";
    let dir = tmp_dir(tag);
    let module = gen_python(SPEC_CONSTANTS, &dir, tag);
    for line in [
        "COUNT = 42\n",
        "MASK = 0xFF00\n",
        "NEG = -7\n",
        "RATIO = 1.618033988749895\n",
        "ENABLED = True\n",
        "DISABLED = False\n",
        "TAG = \"GET\"\n",
        "HALF = (7 // 2)\n",
        "BOTH = (ENABLED and (not DISABLED))\n",
        "WIDE = ((1 << 40) & 0xFFFFFFFFFFFFFFFF)\n",
        "VER = [118, 49, 46, 50]\n",
        "Level = { \"Low\": 0, \"High\": 7, \"Top\": 8 }\n",
        // The spec's one test block, listed rather than left out of the list.
        "__NOT_EMITTED__ = [ { \"what\": \"test \\\"count_is_the_answer\\\"\", \"why\": \"it is checked by the compiler, not by the artifact.\" } ]\n",
    ] {
        assert!(module.contains(line), "missing {line:?} in:\n{module}");
    }

    let names = [
        "COUNT", "MASK", "NEG", "RATIO", "ENABLED", "DISABLED", "TAG", "HALF", "BOTH", "WIDE", "VER",
        "Level",
    ];
    if let Some(said) = python_says(&module, &names, tag) {
        assert_eq!(
            said,
            "COUNT=42\n\
             MASK=65280\n\
             NEG=-7\n\
             RATIO=1.618033988749895\n\
             ENABLED=True\n\
             DISABLED=False\n\
             TAG='GET'\n\
             HALF=3\n\
             BOTH=True\n\
             WIDE=1099511627776\n\
             VER=[118, 49, 46, 50]\n\
             Level={'Low': 0, 'High': 7, 'Top': 8}"
        );
    }
}

/// A spec the parser refuses yields no artifact at all -- not a header, not a
/// half module. This is the largest refusal group in the corpus measurement
/// (six specs refused at module level on a stray identifier, five of them a
/// Markdown body under a `## Specification` heading), and every backend
/// refuses them identically, in the parser, before gen-python runs.
#[test]
fn gen_python_refuses_a_spec_that_does_not_parse_and_prints_nothing() {
    let dir = tmp_dir("unparsed");
    let spec_path = dir.join("in.t27");
    std::fs::write(&spec_path, "module Prose;\n## Specification\n\nSome words about it.\n")
        .expect("write spec");
    let (ok, out, err) = gen_python_file(&spec_path);
    assert!(!ok, "a spec that does not parse must fail gen-python; stdout:\n{out}");
    assert!(out.is_empty(), "no artifact may be printed for an unparsed spec:\n{out}");
    assert!(err.contains("Parse error"), "{err}");
}

/// Read a Python string body as `codegen_js::js_string` writes it, for the two
/// escapes a claim line uses. Any other escape is refused rather than guessed.
fn unescape_claim(body: &str) -> String {
    let mut out = String::with_capacity(body.len());
    let mut chars = body.chars();
    while let Some(c) = chars.next() {
        if c != '\\' {
            out.push(c);
            continue;
        }
        match chars.next() {
            Some('"') => out.push('"'),
            Some('\\') => out.push('\\'),
            other => panic!("a claim line holds an escape this test does not read: \\{other:?} in {body:?}"),
        }
    }
    out
}

/// `bootstrap/src/codegen_python.t27` describes this backend, and it is held
/// to it: each SAMPLE constant there sits beside a `_LINE` string naming the
/// line gen-python prints for it. Generate that spec and every one of those
/// strings must be a whole line of the artifact. The stub that spec replaced
/// asserted a `def` and a `class` this backend never prints, and nothing
/// noticed; this is the test that would have.
#[test]
fn gen_python_its_own_spec_states_what_it_prints() {
    let (ok, module, err) = gen_python_file(&repo_spec("bootstrap/src/codegen_python.t27"));
    assert!(ok, "gen-python refused bootstrap/src/codegen_python.t27: {err}");
    let lines: Vec<&str> = module.lines().collect();
    let mut claims: Vec<(String, String)> = Vec::new();
    for line in &lines {
        let Some((name, rest)) = line.split_once(" = \"") else { continue };
        if !name.ends_with("_LINE") || !rest.ends_with('"') {
            continue;
        }
        claims.push((name.to_string(), unescape_claim(&rest[..rest.len() - 1])));
    }
    // Exact, not a floor: a claim the parser dropped would otherwise vanish
    // without a sound. A new claim in the spec raises this number.
    assert_eq!(claims.len(), 10, "the spec's _LINE claims as the artifact holds them: {claims:?}");
    let unkept: Vec<&(String, String)> =
        claims.iter().filter(|(_, want)| !lines.contains(&want.as_str())).collect();
    assert!(unkept.is_empty(), "claims the artifact does not keep: {unkept:#?}\n--- module ---\n{module}");
    assert!(
        !lines.iter().any(|l| l.starts_with("def ") || l.starts_with("class ") || l.starts_with("import ")),
        "{module}"
    );

    if let Some(said) = python_says(
        &module,
        &["EMITS_FUNCTIONS", "SAMPLE_HALF", "SAMPLE_WIDE", "SampleLevel", "__NOT_EMITTED__"],
        "own_spec",
    ) {
        assert_eq!(
            said,
            "EMITS_FUNCTIONS=False\n\
             SAMPLE_HALF=3\n\
             SAMPLE_WIDE=1099511627776\n\
             SampleLevel={'Low': 0, 'High': 7, 'Top': 8}\n\
             __NOT_EMITTED__=[{'what': 'fn sample_double', 'why': 'this backend lowers declarations, not bodies.'}, \
             {'what': 'test \"the_artifact_is_data_and_lists_what_it_left_out\"', 'why': 'it is checked by the compiler, not by the artifact.'}, \
             {'what': 'test \"the_samples_hold_the_values_python_reads_back\"', 'why': 'it is checked by the compiler, not by the artifact.'}, \
             {'what': 'invariant \"python_spells_its_literals_and_operators_as_words\"', 'why': 'it is checked by the compiler, not by the artifact.'}]"
        );
    }
}

/// PINNED, on purpose. A type-suffixed literal (`0xA5A5A5Au32`,
/// `0.27398563520394157868_f64`) has no spelling in the shared value layer, so
/// the const is announced in `__NOT_EMITTED__` instead of emitted -- three such
/// entries across two corpus specs (`specs/physics/gamma_conjecture.t27`,
/// `specs/port/fpga/verilog/mvp_ternary_classifier_jtag_noport.t27`), and
/// gen-js refuses the same three. The C backend passes the suffix through.
/// (The fourth "has no Python spelling" entry in the corpus, `0xT27B007` in
/// `specs/fpga/testbench/bootrom_tb.t27`, is not a number and stays refused.)
/// When the value layer learns to strip the suffix, this test fails: rewrite it to expect `MAGIC = 0xA5A5A5A` and an
/// empty `__NOT_EMITTED__`, and say so in that change.
#[test]
fn gen_python_pinned_a_suffixed_literal_is_announced_not_emitted() {
    let tag = "suffixed";
    let dir = tmp_dir(tag);
    let module = gen_python(
        "module Suffix;\npub const MAGIC : u32 = 0xA5A5A5Au32;\npub const PLAIN : u32 = 5;\n",
        &dir,
        tag,
    );
    assert!(!module.contains("\nMAGIC = "), "{module}");
    assert!(
        module.contains(
            "# t27c gen-python: const MAGIC was not emitted -- literal \"0xA5A5A5Au32\" at line 0 has no Python spelling\n"
        ),
        "{module}"
    );
    assert!(module.contains("\nPLAIN = 5\n"), "{module}");
    assert!(module.contains("__DECL_ORDER__ = [\"PLAIN\"]\n"), "{module}");

    if let Some(said) = python_says(&module, &["PLAIN", "__NOT_EMITTED__"], tag) {
        assert_eq!(
            said,
            "PLAIN=5\n\
             __NOT_EMITTED__=[{'what': 'const MAGIC', 'why': 'literal \"0xA5A5A5Au32\" at line 0 has no Python spelling'}]"
        );
    }
}
