#!/usr/bin/env python3
"""The t27b steward's decisions live in t27, not in Python (#6198).

Owner's rule, 2026-10-05 (AGENTS.md "t27b is written in t27"): t27b and the
tools that measure it are written in t27. `tri t27b delta` used to classify
each per-spec transition with a hand-written Python `if` chain; that logic
now lives in specs/tri/t27b/steward.t27 and reaches Python only as
gen/c/tri/t27b/steward.c, generated by `t27c gen-c` and loaded by
scripts/tri_loop/t27b_rules.py.

Checks:
  1. the generated C, built with the spec's own test runner, passes the
     spec's tests;
  2. a mutant of that C (pct_tenths rounds down) fails them -- the mutation
     control, so check 1 can go red;
  3. the loader answers what the spec says for the cases the lab produces;
  4. t27b.py's delta has no verdict tuple of its own any more;
  5. if a t27c is present, `t27c gen-c` of the spec is byte-identical to the
     committed C (in CI there is no t27c in this job, and the output says
     "not checked" rather than "ok").
"""

import os
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SPEC = ROOT / "specs/tri/t27b/steward.t27"
GEN = ROOT / "gen/c/tri/t27b/steward.c"
TOOL = ROOT / "scripts/tri_loop/t27b.py"
fails = 0


def check(ok, what):
    global fails
    print(("ok      " if ok else "FAIL    ") + what)
    fails += 0 if ok else 1


def runs_tests(src: Path) -> tuple[int, str]:
    with tempfile.TemporaryDirectory() as tmp:
        exe = os.path.join(tmp, "steward_tests")
        b = subprocess.run([os.environ.get("CC", "cc"), "-DT27_TEST_MAIN", "-w", "-o", exe, str(src)],
                           capture_output=True, text=True)
        if b.returncode != 0:
            return -1, b.stderr[:300]
        r = subprocess.run([exe], capture_output=True, text=True)
        return r.returncode, r.stdout.strip()


code, out = runs_tests(GEN)
check(code == 0 and "111 tests passed" in out, f"the generated C passes the spec's tests ({code}: {out})")

text = GEN.read_text()
needle = "return (((in_ref * 1000) + (reference / 2)) / reference);"
check(text.count(needle) == 1, "mutation: the rounding to remove is present exactly once")
with tempfile.TemporaryDirectory() as tmp:
    mutant = Path(tmp) / "steward.c"
    mutant.write_text(text.replace(needle, "return ((in_ref * 1000) / reference);"))
    code, out = runs_tests(mutant)
    check(code not in (0, -1), f"mutation: a C that rounds down fails the spec's tests (exit {code})")

sys.path.insert(0, str(ROOT / "scripts/tri_loop"))
import t27b_rules as r  # noqa: E402

cases = [
    (("pass", "pass", "pass", "frontend", 3, 0), "REGRESSED"),
    (("pass", "pass", "pass", "pass_vacuous", 3, 0), "REGRESSED"),
    (("pass", "pass", "blocked", "fail", 0, 1), "NEW-MISMATCH"),
    (("pass", "pass", "mismatch", "fail", 0, 1), None),
    (("pass", "pass", "blocked", "pass", 0, 0), "GAINED"),
    (("pass", "pass", "pass", "pass", 2, 0), "CHECK-LOST"),
    (("blocked", "pass", "blocked", "pass", 0, 1), "REF-MOVED"),
    (("fail", "fail", "blocked", "pass", 0, 1), None),
]
got = [r.delta(*a) for a, _ in cases]
check(got == [w for _, w in cases], f"the loader answers what the spec says ({got})")
check([d for d in r.DELTAS if d and r.is_red(d)] == ["REGRESSED", "NEW-MISMATCH", "CHECK-LOST"],
      "red transitions come from delta_is_red")
check((r.pct(56, 648), r.pct(75, 657), r.pct(0, 0)) == ("8.6", "11.4", "0.0"), "the honest percentage")
try:
    r.verdict("passed")
    check(False, "an unknown lab verdict is an error, not a guess")
except r.RulesUnavailable:
    check(True, "an unknown lab verdict is an error, not a guess")

rcases = [
    (("pass", "pass", "pass", True, True), None),
    (("pass", "pass", "pass_vacuous", False, True), "VACUITY MEASURED"),
    (("pass", "pass", "pass_vacuous", True, True), "UNEXPECTED FAILURE"),
    (("pass_vacuous", "pass", "pass", True, True), "UNEXPECTED PASS"),
    (("blocked", "pass", "pass", True, True), "UNEXPECTED PASS"),
    (("blocked", "pass", "blocked", True, False), "MOVED"),
    (("blocked", "fail", "blocked", True, True), "STALE"),
    (("blocked", "not run", "blocked", True, True), "UNJUDGED"),
    (("missing", "pass", "fail", True, True), None),
    (("missing", "pass", "fail", True, False), "MOVED"),
]
got = [r.entry(*a) for a, _ in rcases]
check(got == [w for _, w in rcases], f"the ratchet entry finding is the spec's ({got})")
check([k for k in r.RATCHETS if k and r.ratchet_is_red(k)]
      == ["UNEXPECTED FAILURE", "UNEXPECTED PASS", "STALE", "UNLISTED", "OVER CAP", "BAD REASON"],
      "red ratchet findings come from ratchet_is_red")
check((r.unlisted("pass", False), r.unlisted("pass", True), r.unlisted("fail", False)) == (True, False, False),
      "unlisted: only a reference pass the ledger does not name")
check((r.over_cap(5, 5), r.over_cap(6, 5), r.over_cap(0, None), r.over_cap(0, "7"), r.over_cap(0, True))
      == (False, True, True, True, True), "over_cap: the cap only moves down; no whole-number cap is over")

check((r.bless_reason("fail", "reference-bug"), r.bless_reason("frontend", None), r.bless_reason("mismatch", None),
       r.bless_reason("timeout", "bogus")) == ("reference-bug", "unimplemented", None, None),
      "bless: a written reason is kept, a rejected construct is unimplemented, a defect is refused")
check((r.cap_rises(6, 5), r.cap_rises(5, 5), r.cap_rises(9, None)) == (True, False, False),
      "bless: the cap may fall, never rise; a ledger without one sets it")

check((r.lab_stale(361, 360), r.lab_stale(360, 360), r.lab_stale(-5, 0), r.ledger_quiet(181, 180),
       r.ledger_quiet(180.9, 180)) == (True, False, False, True, False),
      "doctor: stale and quiet are strictly past the limit, in whole minutes; clock skew is age 0")
check((r.claim(False, 1, 100), r.claim(True, 101, 100), r.claim(True, 100, 100), r.claim(None, 999, 100),
       r.claim(True, None, 100)) == ("CLAIM-DEAD", "CLAIM-OLD", None, None, None),
      "doctor: a dead pid frees the claim at any age; an unknown pid says nothing")
check((r.railway_old(4), r.railway_old(5)) == (True, False), "doctor: railway 4.x is old, 5.x is not")
check((r.checkout(False, False), r.checkout(False, True), r.checkout(True, True), r.checkout(True, False))
      == ("LAB-CHECKOUT", "LAB-CHECKOUT", "LAB-RECLONED", None),
      "doctor: a failed checkout outranks a heal; a heal is reported")

check((r.cap_rise_is_new(594, 582, 41), r.cap_rise_is_new(624, 582, 41), r.cap_rise_is_new(583, 582, 0))
      == (True, False, False), "bless: a cap rise is covered only by specs new to the ledger (#6237)")
check((r.is_alarm("fail", "pass"), r.is_alarm("fail", "fail"), r.is_alarm("timeout", "timeout"),
       r.is_alarm("crash", "fail"), r.is_alarm("mismatch", "blocked"), r.is_alarm("blocked", "pass"))
      == (True, False, False, True, True, False),
      "doctor: a fail or timeout the reference shares is no alarm; a crash or mismatch always is")

check((r.check_effect("FAILURE", "SUCCESS", False), r.check_effect("FAILURE", "FAILURE", False),
       r.check_effect("FAILURE", "ABSENT", False), r.check_effect("QUEUED", "SUCCESS", True),
       r.check_effect("SKIPPED", "SUCCESS", True), r.check_effect("SUCCESS", "FAILURE", True))
      == ("BLOCK", None, None, "WAIT", "WAIT", None),
      "ready: a non-required red blocks only if master is green; a required check must be SUCCESS (#6244)")
check(r.check_effect("FAILURE", "PENDING", False) == "WAIT",
      "ready: a non-required red waits while master's newest run of it is still going (Q29)")
check((r.master_state(False, "SUCCESS"), r.master_state(False, "FAILURE"), r.master_state(False, "ABSENT"),
       r.master_state(True, "FAILURE"), r.master_state(True, "SUCCESS"), r.master_state(True, "ABSENT"))
      == ("SUCCESS", "FAILURE", "ABSENT", "FAILURE", "PENDING", "PENDING"),
      "ready: past a running master tip red stays red; green or no verdict is PENDING (#6334)")
check(r.pr_ready(True, "MERGEABLE", True, [None], ["WAIT"]) == "WAIT",
      "ready: a non-required WAIT holds the PR -- #6333 merged on 'master PENDING' (#6334)")
check((r.pr_ready(True, "MERGEABLE", True, [None, None], [None]), r.pr_ready(True, "MERGEABLE", True, [None], ["BLOCK"]),
       r.pr_ready(True, "CONFLICTING", True, ["BLOCK"], []), r.pr_ready(False, "MERGEABLE", True, [], []))
      == ("READY", "BLOCKED", "CONFLICT", "CLOSED"), "ready: the spec folds the effects into one verdict")

check(tuple(r.watch_action(v, "NONE") for v in r.READINESS)
      == ("MERGE", "WAIT", "STOP", "STOP", "STOP", "STOP", "DONE"),
      "watch: READY merges, WAIT waits, CLOSED is done, every red verdict stops the chain (#6285)")
check(tuple(r.watch_action("RETARGET", p) for p in r.PARENTS) == ("STOP", "RETARGET", "WAIT", "STOP"),
      "watch: a stacked PR is retargeted only once its parent merged (Q33)")

check((r.lane_kind("pass", "blocked"), r.lane_kind("blocked", "blocked"), r.lane_kind("fail", "blocked"),
       r.lane_kind("lab_error", "blocked"), r.lane_kind("pass", "frontend"), r.lane_kind("pass", "pass"))
      == ("LANE", "REFERENCE-BUG", "REFERENCE-BUG", None, None, None),
      "next: a lane is a t27b block where the reference passes; a reference failure is a bug to file (Q38, #6317)")
check(r.lane_score(1, 0) > r.lane_score(0, 999) and r.lane_score(3, 10) > r.lane_score(3, 9)
      and (r.with_tests(720, 271), r.with_tests(3, 5)) == (449, 0),
      "next: sole outranks first, first breaks ties; the with-tests denominator never wraps")

tool = TOOL.read_text()
body = tool[tool.index("def delta("):tool.index("def previous_run(")]
check('("fail", "mismatch", "crash")' not in body and "rules().delta(" in body,
      "t27b.py delta asks the spec and keeps no verdict tuple of its own")
body = tool[tool.index("def ratchet("):tool.index("def bless(")]
check("r.entry(" in body and "got in PASSES" not in body and "want not in PASSES" not in body,
      "t27b.py ratchet asks the spec and keeps no branch of its own")
body = tool[tool.index("def bless("):tool.index("def dump_ledger(")]
check("r.bless_reason(" in body and "r.cap_rises(" in body and "r.cap_rise_is_new(" in body and "UNIMPLEMENTED" not in tool and "PASSES" not in tool,
      "t27b.py bless asks the spec and keeps no verdict tuple of its own")

body = tool[tool.index("def ready("):tool.index("def ready_main(")]
check("r.check_effect(" in body and "r.pr_ready(" in body and '"SUCCESS"' not in body and '"FAILURE"' not in body,
      "t27b.py ready asks the spec and keeps no check-state branch of its own")

body = tool[tool.index("def watch_step("):tool.index("def watch_act(")]
check("rules().watch_action(" in body and '"RETARGET"' not in body and '"MERGED"' not in body,
      "t27b.py watch asks the spec what to do and keeps no verdict branch of its own")

body = tool[tool.index("def next_lanes("):tool.index("def next_card(")]
check(all(f"R.{f}(" in body for f in ("lane_kind", "lane_score", "with_tests"))
      and '== "blocked"' not in body and "1000" not in body,
      "t27b.py next asks the spec which files count and how families rank, and keeps no rule of its own")

body = tool[tool.index("def anomalies("):tool.index("def lab_card(")]
check(all(f"rules().{f}(" in body for f in ("lab_stale", "claim", "railway_old", "ledger_quiet", "checkout",
                                                     "is_alarm"))
      and "< 5" not in body and "age > args" not in body and "hrs > args" not in body,
      "t27b.py doctor asks the spec for every threshold it judges")

t27c = os.environ.get("TRI_T27C") or next(
    (str(p) for p in (ROOT / "target/release/t27c", ROOT / "target/debug/t27c") if os.access(p, os.X_OK)), None)
if t27c:
    g = subprocess.run([t27c, "gen-c", str(SPEC)], capture_output=True, text=True)
    check(g.returncode == 0 and g.stdout == text,
          f"gen/c/tri/t27b/steward.c is `t27c gen-c {SPEC.relative_to(ROOT)}` byte for byte")
else:
    print("not checked: no t27c here, so gen/c/tri/t27b/steward.c is not compared with a fresh gen-c")

print()
print(("PASS" if fails == 0 else "FAIL") + f": {fails} failure(s)")
sys.exit(1 if fails else 0)
