#!/usr/bin/env python3
"""Ratchet the bootstrap test suite over a baseline of failing test NAMES.

Why a ratchet and not a gate: `cargo test -p t27c --tests --no-fail-fast` has 383
failures on master (2026-08-22, e53b9d048). A plain gate would land red, and a gate
that lands red gets disabled rather than obeyed.

Why names and not a count: a count of 383 still passes when one failure is fixed and
a different one appears. Only a set catches that.

Why --no-fail-fast matters, and this is the whole reason the suite was invisible:
without it `cargo test` stops after the FIRST failing target. The unit-test target
fails, so the other 72 targets compile and never run — every integration test under
bootstrap/tests/ among them. The recorded "13 failures" figure is that artefact.
See #2382.

Usage:
    cargo test -p t27c --tests --no-fail-fast 2>&1 | tee log.txt
    scripts/ci/test_ratchet.py --log log.txt --emit-baseline > scripts/ci/test-baseline.txt
    scripts/ci/test_ratchet.py --log log.txt --baseline scripts/ci/test-baseline.txt
"""

import argparse
import os
import re
import sys

RUNNING = re.compile(r"^\s+Running (?:unittests )?(\S+)")
FAILED = re.compile(r"^test (\S+) \.\.\. FAILED")
RESULT = re.compile(r"^test result: (?:ok|FAILED)\.")


def parse(path):
    """Return (failures, targets_seen, result_lines).

    A failure is keyed "target\ttest" so the same test name in two targets stays
    distinct. `target` is the source path cargo prints, not the hashed binary.
    """
    failures = set()
    targets = []
    results = 0
    current = None
    with open(path, encoding="utf-8", errors="replace") as fh:
        for line in fh:
            m = RUNNING.match(line)
            if m:
                # "tests/foo.rs (…/deps/foo-1a2b)" -> "tests/foo.rs"; unittests -> "unittests"
                raw = m.group(1)
                current = "unittests" if raw.endswith(")") and "deps/" in raw and "tests/" not in raw else raw
                if current not in targets:
                    targets.append(current)
                continue
            m = FAILED.match(line)
            if m and current:
                failures.add(f"{current}\t{m.group(1)}")
                continue
            if RESULT.match(line):
                results += 1
    return failures, targets, results


def load_baseline(path):
    out = set()
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if line and not line.startswith("#"):
                out.add(line)
    return out


def notice(msg):
    if os.environ.get("GITHUB_ACTIONS"):
        print(f"::notice title=test ratchet::{msg}")
    print(msg)


def error(msg):
    if os.environ.get("GITHUB_ACTIONS"):
        print(f"::error title=test ratchet::{msg}")
    print(msg, file=sys.stderr)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--log", required=True)
    ap.add_argument("--baseline")
    ap.add_argument("--emit-baseline", action="store_true")
    args = ap.parse_args()

    if not os.path.exists(args.log):
        error(f"test set NOT evaluated: no log at {args.log}")
        return 2

    failures, targets, results = parse(args.log)

    # Refuse rather than certify. An empty or truncated log has no failures in it,
    # and reading that as a clean set is the fail-open this repo has closed ten times.
    if not targets or results == 0:
        error(
            "test set NOT evaluated: the log has "
            f"{len(targets)} target(s) and {results} 'test result:' line(s). "
            "A run that did not happen is not a run that passed."
        )
        return 2

    # One target means --no-fail-fast was missing (or everything but one was filtered).
    # That is the exact condition that hid 72 targets; do not let it read as success.
    if len(targets) == 1:
        error(
            "test set NOT evaluated: only 1 target ran. cargo test stops after the "
            "first failing target unless --no-fail-fast is passed, so this log "
            "cannot speak for the suite. See #2382."
        )
        return 2

    if args.emit_baseline:
        print("# Generated by scripts/ci/test_ratchet.py --emit-baseline.")
        print("# Do not hand-edit: regenerate from a real --no-fail-fast log.")
        print("# Each line is target<TAB>test for a test failing on master.")
        print(f"# {len(targets)} targets ran; {len(failures)} failing tests.")
        for key in sorted(failures):
            print(key)
        return 0

    if not args.baseline:
        error("--baseline is required unless --emit-baseline is given")
        return 2

    base = load_baseline(args.baseline)
    new = sorted(failures - base)
    recovered = sorted(base - failures)

    notice(
        f"{len(targets)} targets ran; {len(failures)} failing test(s) "
        f"(baseline {len(base)})"
    )

    # Recovery is reported, never failed on — but it must be visible, or the
    # baseline rots into a list nobody can tell is stale.
    if recovered:
        print(f"\n{len(recovered)} baselined test(s) now PASS — prune them from the baseline:")
        for key in recovered:
            tgt, name = key.split("\t", 1)
            print(f"  - {name}   ({tgt})")

    if new:
        error(f"the failing set grew by {len(new)}")
        print("\n**FAILED — these tests are newly failing:**")
        for key in new:
            tgt, name = key.split("\t", 1)
            print(f"  - `{name}`   ({tgt})")
        print(
            "\nIf a failure is expected, regenerate the baseline from a master log "
            "with --emit-baseline and say why in the PR."
        )
        return 1

    print("\nNo new failures. Baseline holds.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
