[features]
seeds = false
skip-lint = false

[programs.devnet]
tri_mining = "GAoPb3sVjtg1ey7gRtVGWtWFxGhK1eazdKanz3LZKmqV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsc --outDir tests-compiled --declaration false && npx mocha --timeout 1000000 tests-compiled/**/*.js"
