// Generated from t27 spec: TernaryBigInt (module name)
// DO NOT EDIT — generated by t27c
// phi^2 + 1/phi^2 = 3 | TRINITY

const std = @import("std");
fn __t27_assert_fail(comptime fmt: []const u8, args: anytype) noreturn {
    if (@inComptime()) {
        @compileError("assertion failed");
    } else {
        std.debug.print(fmt, args);
        @panic("assertion failed");
    }
}
fn assert_eq(a: anytype, b: anytype) void {
    if (a != b) __t27_assert_fail("\n  {any}\n  != {any}\n", .{ a, b });
}

// use Trit: no references in this module
// use trit_negate: no references in this module
// use trit_multiply: no references in this module
pub const MAX_TRITS: usize = 256;
pub const TRIT_NEG: Trit;
pub const TRIT_ZERO: Trit;
pub const TRIT_POS: Trit;
pub const SIMD_CHUNK_SIZE: usize = 32;
pub const SIMD_CHUNKS: usize = MAX_TRITS / SIMD_CHUNK_SIZE;
pub const KARATSUBA_THRESHOLD: usize = 32;
pub const SIMD_THRESHOLD: usize = 64;
pub const I64_DIV_THRESHOLD: usize = 40;
pub const DivResult = struct {
    q: BigInt,
    r: BigInt,
};
pub const BigInt = struct {
    trits: [MAX_TRITS]Trit,
    len: usize,
};
test "big_int_zero_creation" {
    const z = BigInt.zero();
    try std.testing.expect(z.is_zero() == true);
    try std.testing.expect(z.len == 1);
    try std.testing.expect(z.trits[0] == TRIT_ZERO);
}
test "big_int_from_i64_zero" {
    const z = BigInt.from_i64(0);
    try std.testing.expect(z.is_zero() == true);
}
test "big_int_from_i64_positive" {
    const a = BigInt.from_i64(42);
    const b = BigInt.from_i64(100);
    const c = BigInt.from_i64(1);
    try std.testing.expectEqual(@as(i64, 42), a.to_i64());
    try std.testing.expectEqual(@as(i64, 100), b.to_i64());
    try std.testing.expectEqual(@as(i64, 1), c.to_i64());
}
test "big_int_from_i64_negative" {
    const a = BigInt.from_i64(-42);
    const b = BigInt.from_i64(-100);
    const c = BigInt.from_i64(-1);
    try std.testing.expectEqual(@as(i64, -42), a.to_i64());
    try std.testing.expectEqual(@as(i64, -100), b.to_i64());
    try std.testing.expectEqual(@as(i64, -1), c.to_i64());
}
test "big_int_to_i64_roundtrip" {
    const values = .{ 0, 1, -1, 2, -2, 10, -10, 100, -100, 1000, -1000, 12345, -12345 };
    for (values) |val| {
        const big = BigInt.from_i64(val);
        const back = big.to_i64();
        try std.testing.expectEqual(val, back);
    }
}
test "big_int_normalize" {
    var a = BigInt.zero();
    _ = &a;
    a.trits[0] = TRIT_POS;
    a.trits[1] = TRIT_ZERO;
    a.trits[2] = TRIT_ZERO;
    a.trits[3] = TRIT_ZERO;
    a.len = 4;
    a.normalize();
    try std.testing.expect(a.len == 1);
    try std.testing.expect(a.trits[0] == TRIT_POS);
}
test "big_int_is_negative" {
    const pos = BigInt.from_i64(42);
    const neg = BigInt.from_i64(-42);
    const z = BigInt.zero();
    try std.testing.expect(pos.is_negative() == false);
    try std.testing.expect(neg.is_negative() == true);
    try std.testing.expect(z.is_negative() == false);
}
test "big_int_is_positive" {
    const pos = BigInt.from_i64(42);
    const neg = BigInt.from_i64(-42);
    const z = BigInt.zero();
    try std.testing.expect(pos.is_positive() == true);
    try std.testing.expect(neg.is_positive() == false);
    try std.testing.expect(z.is_positive() == false);
}
test "big_int_signum" {
    const pos = BigInt.from_i64(42);
    const neg = BigInt.from_i64(-42);
    const z = BigInt.zero();
    try std.testing.expectEqual(@as(i8, 1), pos.signum());
    try std.testing.expectEqual(@as(i8, -1), neg.signum());
    try std.testing.expectEqual(@as(i8, 0), z.signum());
}
test "big_int_negate" {
    const a = BigInt.from_i64(42);
    const b = BigInt.from_i64(-42);
    const c = BigInt.zero();
    const neg_a = a.negate();
    const neg_b = b.negate();
    const neg_c = c.negate();
    try std.testing.expectEqual(@as(i64, -42), neg_a.to_i64());
    try std.testing.expectEqual(@as(i64, 42), neg_b.to_i64());
    try std.testing.expectEqual(@as(i64, 0), neg_c.to_i64());
}
test "big_int_abs" {
    const a = BigInt.from_i64(42);
    const b = BigInt.from_i64(-42);
    const c = BigInt.zero();
    try std.testing.expectEqual(@as(i64, 42), a.abs().to_i64());
    try std.testing.expectEqual(@as(i64, 42), b.abs().to_i64());
    try std.testing.expectEqual(@as(i64, 0), c.abs().to_i64());
}
test "big_int_add_positive" {
    const a = BigInt.from_i64(123);
    const b = BigInt.from_i64(456);
    const sum = a.add(b);
    try std.testing.expectEqual(@as(i64, 579), sum.to_i64());
}
test "big_int_add_negative" {
    const a = BigInt.from_i64(-100);
    const b = BigInt.from_i64(50);
    const sum = a.add(b);
    try std.testing.expectEqual(@as(i64, -50), sum.to_i64());
}
test "big_int_add_zero" {
    const a = BigInt.from_i64(42);
    const z = BigInt.zero();
    const sum1 = a.add(z);
    const sum2 = z.add(a);
    try std.testing.expectEqual(@as(i64, 42), sum1.to_i64());
    try std.testing.expectEqual(@as(i64, 42), sum2.to_i64());
}
test "big_int_add_commutative" {
    const a = BigInt.from_i64(123);
    const b = BigInt.from_i64(456);
    const sum1 = a.add(b);
    const sum2 = b.add(a);
    try std.testing.expect(sum1.compare(sum2) == 0);
}
test "big_int_sub" {
    const a = BigInt.from_i64(1000);
    const b = BigInt.from_i64(300);
    const diff = a.sub(b);
    try std.testing.expectEqual(@as(i64, 700), diff.to_i64());
}
test "big_int_sub_negative" {
    const a = BigInt.from_i64(100);
    const b = BigInt.from_i64(300);
    const diff = a.sub(b);
    try std.testing.expectEqual(@as(i64, -200), diff.to_i64());
}
test "big_int_mul_simple_positive" {
    const a = BigInt.from_i64(12);
    const b = BigInt.from_i64(34);
    const prod = a.mul_simple(b);
    try std.testing.expectEqual(@as(i64, 408), prod.to_i64());
}
test "big_int_mul_simple_negative" {
    const a = BigInt.from_i64(-7);
    const b = BigInt.from_i64(8);
    const prod = a.mul_simple(b);
    try std.testing.expectEqual(@as(i64, -56), prod.to_i64());
}
test "big_int_mul_zero" {
    const a = BigInt.from_i64(12345);
    const z = BigInt.zero();
    const prod = a.mul(z);
    try std.testing.expect(prod.is_zero() == true);
}
test "big_int_mul_karatsuba" {
    const a = BigInt.from_i64(12345);
    const b = BigInt.from_i64(67890);
    const prod = a.mul_karatsuba(b);
    try std.testing.expectEqual(@as(i64, 838102050), prod.to_i64());
}
test "big_int_mul_consistency" {
    const a = BigInt.from_i64(12345);
    const b = BigInt.from_i64(67890);
    const prod_simple = a.mul_simple(b);
    const prod_karat = a.mul_karatsuba(b);
    try std.testing.expect(prod_simple.compare(prod_karat) == 0);
}
test "big_int_compare_equal" {
    const a = BigInt.from_i64(42);
    const b = BigInt.from_i64(42);
    try std.testing.expect(a.compare(b) == 0);
}
test "big_int_compare_less" {
    const a = BigInt.from_i64(42);
    const b = BigInt.from_i64(100);
    try std.testing.expect(a.compare(b) == -1);
}
test "big_int_compare_greater" {
    const a = BigInt.from_i64(100);
    const b = BigInt.from_i64(42);
    try std.testing.expect(a.compare(b) == 1);
}
test "big_int_compare_negative" {
    const a = BigInt.from_i64(-100);
    const b = BigInt.from_i64(-42);
    try std.testing.expect(a.compare(b) == -1);
}
test "big_int_div_exact" {
    const a = BigInt.from_i64(81);
    const b = BigInt.from_i64(9);
    const result = a.div_rem(b);
    try std.testing.expectEqual(@as(i64, 9), result.q.to_i64());
    try std.testing.expect(result.r.is_zero() == true);
}
test "big_int_div_with_remainder" {
    const a = BigInt.from_i64(10);
    const b = BigInt.from_i64(3);
    const result = a.div_rem(b);
    try std.testing.expectEqual(@as(i64, 3), result.q.to_i64());
    try std.testing.expectEqual(@as(i64, 1), result.r.to_i64());
}
test "big_int_div_negative" {
    const a = BigInt.from_i64(-100);
    const b = BigInt.from_i64(7);
    const result = a.div_rem(b);
    try std.testing.expectEqual(@as(i64, -14), result.q.to_i64());
    try std.testing.expectEqual(@as(i64, -2), result.r.to_i64());
}
test "big_int_div_by_negative" {
    const a = BigInt.from_i64(100);
    const b = BigInt.from_i64(-7);
    const result = a.div_rem(b);
    try std.testing.expectEqual(@as(i64, -14), result.q.to_i64());
    try std.testing.expectEqual(@as(i64, 2), result.r.to_i64());
}
test "big_int_shift_left" {
    const a = BigInt.from_i64(10);
    const shifted = a.shift_left(2);
    try std.testing.expectEqual(@as(i64, 90), shifted.to_i64());
}
test "big_int_shift_right" {
    const a = BigInt.from_i64(27);
    const shifted = a.shift_right(1);
    try std.testing.expectEqual(@as(i64, 9), shifted.to_i64());
}
test "big_int_shift_identity" {
    const a = BigInt.from_i64(42);
    const shifted = a.shift_left(0);
    try std.testing.expect(shifted.compare(a) == 0);
}
test "big_int_newton_div" {
    const a = BigInt.from_i64(1000000);
    const b = BigInt.from_i64(1234);
    const result = a.div_newton(b);
    try std.testing.expectEqual(@as(i64, 810), result.q.to_i64());
    try std.testing.expectEqual(@as(i64, 460), result.r.to_i64());
}
test "big_int_newton_div_consistency" {
    const a = BigInt.from_i64(1000000);
    const b = BigInt.from_i64(1234);
    const result_newton = a.div_newton(b);
    const result_regular = a.div_rem(b);
    try std.testing.expect(result_newton.q.compare(result_regular.q) == 0);
    try std.testing.expect(result_newton.r.compare(result_regular.r) == 0);
}
test "big_int_large_add" {
    const a = BigInt.from_i64(1000000000);
    const b = BigInt.from_i64(999999999);
    const sum = a.add(b);
    try std.testing.expectEqual(@as(i64, 1999999999), sum.to_i64());
}
test "big_int_large_mul" {
    const a = BigInt.from_i64(123456);
    const b = BigInt.from_i64(789012);
    const prod = a.mul(b);
    try std.testing.expectEqual(@as(i64, 97406197072), prod.to_i64());
}
comptime {
    // invariant: big_int_zero_is_neutral_add
    const values = .{ 1, -1, 42, -42, 100, -100 };
    for (values) |val| {
        const a = BigInt.from_i64(val);
        const z = BigInt.zero();
        if (!(a.add(z).compare(a) == 0)) __t27_assert_fail("\n  assertion failed:\n    a.add(z).compare(a) = {any}\n", .{ a.add(z).compare(a) });
        if (!(z.add(a).compare(a) == 0)) __t27_assert_fail("\n  assertion failed:\n    z.add(a).compare(a) = {any}\n", .{ z.add(a).compare(a) });
    }
}
comptime {
    // invariant: big_int_zero_is_annihilator_mul
    const values = .{ 1, -1, 42, -42, 100, -100 };
    for (values) |val| {
        const a = BigInt.from_i64(val);
        const z = BigInt.zero();
        if (!(a.mul(z).is_zero() == true)) __t27_assert_fail("\n  assertion failed:\n    a.mul(z).is_zero() = {any}\n", .{ a.mul(z).is_zero() });
    }
}
comptime {
    // invariant: big_int_add_commutative
    const vals_a = .{ 1, 2, 10, 100 };
    const vals_b = .{ 1, 2, 10, 100 };
    for (vals_a) |a_val| {
        for (vals_b) |b_val| {
            const a = BigInt.from_i64(a_val);
            const b = BigInt.from_i64(b_val);
            if (!(a.add(b).compare(b.add(a)) == 0)) __t27_assert_fail("\n  assertion failed:\n    a.add(b).compare(b.add(a)) = {any}\n", .{ a.add(b).compare(b.add(a)) });
        }
    }
}
comptime {
    // invariant: big_int_add_associative
    const a = BigInt.from_i64(12);
    const b = BigInt.from_i64(34);
    const c = BigInt.from_i64(56);
    if (!(a.add(b).add(c).compare(a.add(b.add(c))) == 0)) __t27_assert_fail("\n  assertion failed:\n    a.add(b).add(c).compare(a.add(b.add(c))) = {any}\n", .{ a.add(b).add(c).compare(a.add(b.add(c))) });
}
comptime {
    // invariant: big_int_mul_commutative
    const vals_a = .{ 1, 2, 10 };
    const vals_b = .{ 1, 2, 10 };
    for (vals_a) |a_val| {
        for (vals_b) |b_val| {
            const a = BigInt.from_i64(a_val);
            const b = BigInt.from_i64(b_val);
            if (!(a.mul(b).compare(b.mul(a)) == 0)) __t27_assert_fail("\n  assertion failed:\n    a.mul(b).compare(b.mul(a)) = {any}\n", .{ a.mul(b).compare(b.mul(a)) });
        }
    }
}
comptime {
    // invariant: big_int_mul_associative
    const a = BigInt.from_i64(3);
    const b = BigInt.from_i64(5);
    const c = BigInt.from_i64(7);
    if (!(a.mul(b).mul(c).compare(a.mul(b.mul(c))) == 0)) __t27_assert_fail("\n  assertion failed:\n    a.mul(b).mul(c).compare(a.mul(b.mul(c))) = {any}\n", .{ a.mul(b).mul(c).compare(a.mul(b.mul(c))) });
}
comptime {
    // invariant: big_int_distributive
    const a = BigInt.from_i64(3);
    const b = BigInt.from_i64(5);
    const c = BigInt.from_i64(7);
    if (!(a.mul(b.add(c)).compare(a.mul(b).add(a.mul(c))) == 0)) __t27_assert_fail("\n  assertion failed:\n    a.mul(b.add(c)).compare(a.mul(b).add(a.mul(c))) = {any}\n", .{ a.mul(b.add(c)).compare(a.mul(b).add(a.mul(c))) });
}
comptime {
    // invariant: big_int_negate_twice
    const values = .{ 1, -1, 42, -42, 100 };
    for (values) |val| {
        const a = BigInt.from_i64(val);
        if (!(a.negate().negate().compare(a) == 0)) __t27_assert_fail("\n  assertion failed:\n    a.negate().negate().compare(a) = {any}\n", .{ a.negate().negate().compare(a) });
    }
}
comptime {
    // invariant: big_int_abs_idempotent
    const values = .{ 1, -1, 42, -42, 100, -100 };
    for (values) |val| {
        const a = BigInt.from_i64(val);
        if (!(a.abs().abs().compare(a.abs()) == 0)) __t27_assert_fail("\n  assertion failed:\n    a.abs().abs().compare(a.abs()) = {any}\n", .{ a.abs().abs().compare(a.abs()) });
    }
}
comptime {
    // invariant: big_int_sub_equals_add_negate
    const vals_a = .{ 10, 100 };
    const vals_b = .{ 3, 7 };
    for (vals_a) |a_val| {
        for (vals_b) |b_val| {
            const a = BigInt.from_i64(a_val);
            const b = BigInt.from_i64(b_val);
            if (!(a.sub(b).compare(a.add(b.negate())) == 0)) __t27_assert_fail("\n  assertion failed:\n    a.sub(b).compare(a.add(b.negate())) = {any}\n", .{ a.sub(b).compare(a.add(b.negate())) });
        }
    }
}
comptime {
    // invariant: big_int_division_invariant
    const vals_a = .{ 10, 100, 1000 };
    const vals_b = .{ 3, 7, 13 };
    for (vals_a) |a_val| {
        for (vals_b) |b_val| {
            const a = BigInt.from_i64(a_val);
            const b = BigInt.from_i64(b_val);
            const result = a.div_rem(b);
            const reconstructed = result.q.mul(b).add(result.r);
            if (!(reconstructed.compare(a) == 0)) __t27_assert_fail("\n  assertion failed:\n    reconstructed.compare(a) = {any}\n", .{ reconstructed.compare(a) });
            if (!((result.r.compare_abs(b) < 0) or result.r.is_zero())) __t27_assert_fail("\n  assertion failed:\n    result.r.compare_abs(b) = {any}\n", .{ result.r.compare_abs(b) });
        }
    }
}
comptime {
    // invariant: big_int_compare_transitive
    const a = BigInt.from_i64(1);
    const b = BigInt.from_i64(10);
    const c = BigInt.from_i64(100);
    if (!(a.compare(b) < 0)) __t27_assert_fail("\n  assertion failed:\n    a.compare(b) = {any}\n", .{ a.compare(b) });
    if (!(b.compare(c) < 0)) __t27_assert_fail("\n  assertion failed:\n    b.compare(c) = {any}\n", .{ b.compare(c) });
    if (!(a.compare(c) < 0)) __t27_assert_fail("\n  assertion failed:\n    a.compare(c) = {any}\n", .{ a.compare(c) });
}
comptime {
    // invariant: big_int_compare_total_ordering
    const vals_a = .{ 1, -1, 42, -42 };
    const vals_b = .{ 1, -1, 42, -42 };
    for (vals_a) |a_val| {
        for (vals_b) |b_val| {
            const a = BigInt.from_i64(a_val);
            const b = BigInt.from_i64(b_val);
            const cmp = a.compare(b);
            if (!(((cmp == -1) or (cmp == 0)) or (cmp == 1))) __t27_assert_fail("\n  assertion failed:\n    cmp = {any}\n    -1 = {any}\n", .{ cmp, -1 });
        }
    }
}
comptime {
    // invariant: big_int_shift_consistency
    const values = .{ 10, 100, 1000 };
    for (values) |val| {
        const a = BigInt.from_i64(val);
        const shifted = a.shift_left(2);
        const restored = shifted.shift_right(2);
        if (!(restored.compare(a) == 0)) __t27_assert_fail("\n  assertion failed:\n    restored.compare(a) = {any}\n", .{ restored.compare(a) });
    }
}
fn bench_big_int_add_latency() void {
    // bench: big_int_add_latency
    @setEvalBranchQuota(10000);
    var result: BigInt = undefined;
    _ = &result;
    const a = BigInt.from_i64(12345);
    const b = BigInt.from_i64(6789);
    for (0 .. 1000) |_| {
        result = a.add(b);
    }
    }
fn bench_big_int_sub_latency() void {
    // bench: big_int_sub_latency
    @setEvalBranchQuota(10000);
    var result: BigInt = undefined;
    _ = &result;
    const a = BigInt.from_i64(12345);
    const b = BigInt.from_i64(6789);
    for (0 .. 1000) |_| {
        result = a.sub(b);
    }
    }
fn bench_big_int_mul_simple_latency() void {
    // bench: big_int_mul_simple_latency
    @setEvalBranchQuota(10000);
    var result: BigInt = undefined;
    _ = &result;
    const a = BigInt.from_i64(12345);
    const b = BigInt.from_i64(6789);
    for (0 .. 100) |_| {
        result = a.mul_simple(b);
    }
    }
fn bench_big_int_mul_karatsuba_latency() void {
    // bench: big_int_mul_karatsuba_latency
    @setEvalBranchQuota(10000);
    var result: BigInt = undefined;
    _ = &result;
    const a = BigInt.from_i64(123456789);
    const b = BigInt.from_i64(987654321);
    for (0 .. 100) |_| {
        result = a.mul_karatsuba(b);
    }
    }
fn bench_big_int_div_latency() void {
    // bench: big_int_div_latency
    @setEvalBranchQuota(10000);
    var result: BigInt = undefined;
    _ = &result;
    const a = BigInt.from_i64(1000000);
    const b = BigInt.from_i64(1234);
    for (0 .. 100) |_| {
        result = a.div(b);
    }
    }
fn bench_big_int_shift_latency() void {
    // bench: big_int_shift_latency
    @setEvalBranchQuota(10000);
    var result: BigInt = undefined;
    _ = &result;
    const a = BigInt.from_i64(12345);
    for (0 .. 1000) |_| {
        result = a.shift_left(10);
        _ = result.shift_right(10);
    }
    }
fn bench_big_int_normalize_latency() void {
    // bench: big_int_normalize_latency
    @setEvalBranchQuota(10000);
    var a = BigInt.from_i64(12345);
    _ = &a;
    a.trits[10] = TRIT_ZERO;
    a.trits[11] = TRIT_ZERO;
    a.len = 12;
    for (0 .. 1000) |_| {
        a.normalize();
    }
    }
fn bench_big_int_compare_latency() void {
    // bench: big_int_compare_latency
    @setEvalBranchQuota(10000);
    var cmp: i8 = 0;
    _ = &cmp;
    const a = BigInt.from_i64(12345);
    const b = BigInt.from_i64(6789);
    for (0 .. 1000) |_| {
        cmp = a.compare(b);
    }
    }
fn bench_big_int_negate_latency() void {
    // bench: big_int_negate_latency
    @setEvalBranchQuota(10000);
    var result: BigInt = undefined;
    _ = &result;
    const a = BigInt.from_i64(12345);
    for (0 .. 1000) |_| {
        result = a.negate();
    }
    }
fn bench_big_int_abs_latency() void {
    // bench: big_int_abs_latency
    @setEvalBranchQuota(10000);
    var result: BigInt = undefined;
    _ = &result;
    const a = BigInt.from_i64(-12345);
    for (0 .. 1000) |_| {
        result = a.abs();
    }
    }
fn bench_big_int_to_i64_latency() void {
    // bench: big_int_to_i64_latency
    @setEvalBranchQuota(10000);
    var result: i64 = 0;
    _ = &result;
    const a = BigInt.from_i64(12345);
    for (0 .. 1000) |_| {
        result = a.to_i64();
    }
    }
fn bench_big_int_from_i64_latency() void {
    // bench: big_int_from_i64_latency
    @setEvalBranchQuota(10000);
    var result: BigInt = undefined;
    _ = &result;
    for (0 .. 1000) |i| {
        result = BigInt.from_i64(@intCast(i));
    }
    }
