// ============================================================================
// Generated from t27 spec: QMTech_A100T_Integration
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module QMTech_A100T_Integration (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Parameters (from const declarations)
    // -------------------------------------------------------
    localparam [31:0] BOARD_NAME = qmtech-xc7a100t;
    localparam [31:0] QMTECH_PINS = PinMapping;
    localparam [31:0] SYS_CONFIG = SystemConfig;

    // -------------------------------------------------------
    // Registers (from struct declarations)
    // -------------------------------------------------------
    // struct PinMapping
    reg [31:0] pinmapping_clk_pin; // PinMapping.clk_pin
    reg [31:0] pinmapping_rst_pin; // PinMapping.rst_pin
    reg [31:0] pinmapping_uart_tx_pin; // PinMapping.uart_tx_pin
    reg [31:0] pinmapping_uart_rx_pin; // PinMapping.uart_rx_pin
    reg [31:0] pinmapping_led_pins; // PinMapping.led_pins
    // struct SystemConfig
    reg [31:0] systemconfig_clock_hz; // SystemConfig.clock_hz
    reg [31:0] systemconfig_baud_rate; // SystemConfig.baud_rate
    reg [31:0] systemconfig_mem_size; // SystemConfig.mem_size
    reg [31:0] systemconfig_fifo_depth; // SystemConfig.fifo_depth

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: calc_baud_divisor
    function [31:0] calc_baud_divisor; // -> u32
        input [31:0] clock_hz;
        input [31:0] baud;
        begin
            calc_baud_divisor = (clock_hz / (16 * baud));
        end
    endfunction
    // -------------------------------------------------------
    // Test assertions (from test blocks)
    // -------------------------------------------------------
    // synthesis translate_off
    // test: test_baud_divisor
    initial begin : test_baud_divisor_test
        $display("[TEST] test_baud_divisor : starting");
        //         reg [31:0] divisor = calc_baud_divisor(CLOCK_FREQ_HZ, UART_BAUD);
        $display("[TEST] test_baud_divisor : PASSED");
    end
    // test: test_system_config
    initial begin : test_system_config_test
        $display("[TEST] test_system_config : starting");
        $display("[TEST] test_system_config : PASSED");
    end
    // test: test_fpga_part
    initial begin : test_fpga_part_test
        $display("[TEST] test_fpga_part : starting");
        $display("[TEST] test_fpga_part : PASSED");
    end
    // test: test_clock_freq
    initial begin : test_clock_freq_test
        $display("[TEST] test_clock_freq : starting");
        $display("[TEST] test_clock_freq : PASSED");
    end
    // test: test_clk_pin_is_e3
    initial begin : test_clk_pin_is_e3_test
        $display("[TEST] test_clk_pin_is_e3 : starting");
        $display("[TEST] test_clk_pin_is_e3 : PASSED");
    end
    // test: test_rst_pin_is_c18
    initial begin : test_rst_pin_is_c18_test
        $display("[TEST] test_rst_pin_is_c18 : starting");
        $display("[TEST] test_rst_pin_is_c18 : PASSED");
    end
    // test: test_uart_pins_match_xdc
    initial begin : test_uart_pins_match_xdc_test
        $display("[TEST] test_uart_pins_match_xdc : starting");
        $display("[TEST] test_uart_pins_match_xdc : PASSED");
    end
    // synthesis translate_on

    // -------------------------------------------------------
    // Invariant checks (compile-time assertions)
    // -------------------------------------------------------
    // invariant: clock_positive
    // invariant: baud_valid
    // invariant: board_name_set

    // -------------------------------------------------------
    // Benchmark blocks (simulation only)
    // -------------------------------------------------------
    initial begin : bench_qmtech_config_bench // synthesis translate_off
        $display("[BENCH] bench_qmtech_config : starting");
        integer _bench_cycles = 0;
        // calc_baud_divisor(CLOCK_FREQ_HZ, UART_BAUD);
        _bench_cycles = _bench_cycles + 1;
        $display("[BENCH] bench_qmtech_config : %%0d cycles", _bench_cycles);
        $display("[BENCH] bench_qmtech_config : DONE");
    end // synthesis translate_on

endmodule

`default_nettype wire
