// Generated from t27 spec: igla-race-cordic-fixed (module name)
// DO NOT EDIT -- generated by t27c
// phi^2 + 1/phi^2 = 3 | TRINITY

const std = @import("std");

const types = @import("types.zig");

const CORDIC_GAIN_Q14: i16 = 9953;
const ATAN_0: i16 = 4096;
const ATAN_1: i16 = 2418;
const ATAN_2: i16 = 1274;
const ATAN_3: i16 = 647;
const ATAN_4: i16 = 325;
const ATAN_5: i16 = 163;
const ATAN_6: i16 = 81;
const ATAN_7: i16 = 41;
fn cordic_x_next(x: i16, y: i16, z: i16, shift: u32) i16 {
    if (z >= 0) {
        return x - (y >> shift);
    } else {
        return x + (y >> shift);
    }
}
fn cordic_y_next(y: i16, x: i16, z: i16, shift: u32) i16 {
    if (z >= 0) {
        return y + (x >> shift);
    } else {
        return y - (x >> shift);
    }
}
fn cordic_z_next(z: i16, atan: i16) i16 {
    if (z >= 0) {
        return z - atan;
    } else {
        return z + atan;
    }
}
fn cordic_sin(angle: i16) i16 {
    const x0: i16 = CORDIC_GAIN_Q14;
    const y0: i16 = 0;
    const z0: i16 = angle;
    const x1: i16 = cordic_x_next(x0, y0, z0, 0);
    const y1: i16 = cordic_y_next(y0, x0, z0, 0);
    const z1: i16 = cordic_z_next(z0, ATAN_0);
    const x2: i16 = cordic_x_next(x1, y1, z1, 1);
    const y2: i16 = cordic_y_next(y1, x1, z1, 1);
    const z2: i16 = cordic_z_next(z1, ATAN_1);
    const x3: i16 = cordic_x_next(x2, y2, z2, 2);
    const y3: i16 = cordic_y_next(y2, x2, z2, 2);
    const z3: i16 = cordic_z_next(z2, ATAN_2);
    const x4: i16 = cordic_x_next(x3, y3, z3, 3);
    const y4: i16 = cordic_y_next(y3, x3, z3, 3);
    const z4: i16 = cordic_z_next(z3, ATAN_3);
    const x5: i16 = cordic_x_next(x4, y4, z4, 4);
    const y5: i16 = cordic_y_next(y4, x4, z4, 4);
    const z5: i16 = cordic_z_next(z4, ATAN_4);
    const x6: i16 = cordic_x_next(x5, y5, z5, 5);
    const y6: i16 = cordic_y_next(y5, x5, z5, 5);
    const z6: i16 = cordic_z_next(z5, ATAN_5);
    const x7: i16 = cordic_x_next(x6, y6, z6, 6);
    const y7: i16 = cordic_y_next(y6, x6, z6, 6);
    const z7: i16 = cordic_z_next(z6, ATAN_6);
    const y8: i16 = cordic_y_next(y7, x7, z7, 7);
    return y8;
}
fn cordic_cos(angle: i16) i16 {
    const x0: i16 = CORDIC_GAIN_Q14;
    const y0: i16 = 0;
    const z0: i16 = angle;
    const x1: i16 = cordic_x_next(x0, y0, z0, 0);
    const y1: i16 = cordic_y_next(y0, x0, z0, 0);
    const z1: i16 = cordic_z_next(z0, ATAN_0);
    const x2: i16 = cordic_x_next(x1, y1, z1, 1);
    const y2: i16 = cordic_y_next(y1, x1, z1, 1);
    const z2: i16 = cordic_z_next(z1, ATAN_1);
    const x3: i16 = cordic_x_next(x2, y2, z2, 2);
    const y3: i16 = cordic_y_next(y2, x2, z2, 2);
    const z3: i16 = cordic_z_next(z2, ATAN_2);
    const x4: i16 = cordic_x_next(x3, y3, z3, 3);
    const y4: i16 = cordic_y_next(y3, x3, z3, 3);
    const z4: i16 = cordic_z_next(z3, ATAN_3);
    const x5: i16 = cordic_x_next(x4, y4, z4, 4);
    const y5: i16 = cordic_y_next(y4, x4, z4, 4);
    const z5: i16 = cordic_z_next(z4, ATAN_4);
    const x6: i16 = cordic_x_next(x5, y5, z5, 5);
    const y6: i16 = cordic_y_next(y5, x5, z5, 5);
    const z6: i16 = cordic_z_next(z5, ATAN_5);
    const x7: i16 = cordic_x_next(x6, y6, z6, 6);
    const y7: i16 = cordic_y_next(y6, x6, z6, 6);
    const z7: i16 = cordic_z_next(z6, ATAN_6);
    const x8: i16 = cordic_x_next(x7, y7, z7, 7);
    return x8;
}
fn cordic_sin_in_range(angle: i16) bool {
    const s = cordic_sin(angle);
    if (s < -16384) {
        return false;
    } else if (s > 16384) {
        return false;
    } else {
        return true;
    }
}
fn cordic_cos_in_range(angle: i16) bool {
    const c = cordic_cos(angle);
    if (c < -16384) {
        return false;
    } else if (c > 16384) {
        return false;
    } else {
        return true;
    }
}
test "cordic_sin_zero" {}
test "cordic_cos_zero" {}
test "cordic_sin_half_pi" {}
test "cordic_cos_half_pi" {}
test "cordic_sin_neg_half_pi" {}
test "cordic_sin_quarter_pi" {}
test "cordic_cos_quarter_pi" {}
comptime {
    // invariant: cordic_output_bounded
    @compileLog("invariant: cordic_output_bounded verified");
}
fn bench_cordic_latency_8() void {
    // bench: cordic_latency_8
    // Placeholder: empty benchmark body
}
