// Generated from t27 spec: igla-race-cordic (module name)
// DO NOT EDIT -- generated by t27c
// phi^2 + 1/phi^2 = 3 | TRINITY

const std = @import("std");

const types = @import("types.zig");
const constants = @import("constants.zig");

pub const CordicConfig = struct {
    iterations: u8,
    bitwidth: u16,
};
fn arctan_table_entry(i: u8) f32 {
    if (i == 0) {
        return 0.7853981633974483;
    }
    if (i == 1) {
        return 0.4636476090008061;
    }
    if (i == 2) {
        return 0.244978663126864;
    }
    if (i == 3) {
        return 0.12435499454676144;
    }
    if (i == 4) {
        return 0.06241880999595735;
    }
    if (i == 5) {
        return 0.031239833430277277;
    }
    if (i == 6) {
        return 0.01562372862047683;
    }
    if (i == 7) {
        return 0.00781234106010111;
    }
    if (i == 8) {
        return 0.003906230131966971;
    }
    if (i == 9) {
        return 0.001953122516478818;
    }
    if (i == 10) {
        return 0.000976562341491722;
    }
    if (i == 11) {
        return 0.000488281238747095;
    }
    if (i == 12) {
        return 0.000244140624981345;
    }
    if (i == 13) {
        return 0.000122070312496188;
    }
    if (i == 14) {
        return 0.000061035156249904;
    }
    if (i == 15) {
        return 0.000030517578124988;
    }
    return 0.0;
}
fn pow2_neg_entry(i: u8) f32 {
    if (i == 0) {
        return 1.0;
    }
    if (i == 1) {
        return 0.5;
    }
    if (i == 2) {
        return 0.25;
    }
    if (i == 3) {
        return 0.125;
    }
    if (i == 4) {
        return 0.0625;
    }
    if (i == 5) {
        return 0.03125;
    }
    if (i == 6) {
        return 0.015625;
    }
    if (i == 7) {
        return 0.0078125;
    }
    if (i == 8) {
        return 0.00390625;
    }
    if (i == 9) {
        return 0.001953125;
    }
    if (i == 10) {
        return 0.0009765625;
    }
    if (i == 11) {
        return 0.00048828125;
    }
    if (i == 12) {
        return 0.000244140625;
    }
    if (i == 13) {
        return 0.0001220703125;
    }
    if (i == 14) {
        return 0.00006103515625;
    }
    if (i == 15) {
        return 0.000030517578125;
    }
    return 0.0;
}
fn cordic_sign(z: f32) f32 {
    if (z >= 0.0) {
        return 1.0;
    }
    return -1.0;
}
fn sqrt_approx_inner(x: f32, guess: f32, iter: u32) f32 {
    if (iter >= 20) {
        return guess;
    }
    const next = 0.5 * (guess + (x / guess));
    return sqrt_approx_inner(x, next, iter + 1);
}
fn sqrt_approx(x: f32) f32 {
    if (x <= 0.0) {
        return 0.0;
    }
    return sqrt_approx_inner(x, 1.0, 0);
}
fn cordic_gain(iterations: u32) f32 {
    return cordic_gain_inner(0, iterations, 1.0);
}
fn cordic_gain_inner(i: u32, n: u32, acc: f32) f32 {
    if (i >= n) {
        return acc;
    }
    const p = pow2_neg_entry(@as(u8, i));
    const p2 = p * p;
    const denom = 1.0 + p2;
    const cos_val = 1.0 / sqrt_approx(denom);
    return cordic_gain_inner(i + 1, n, acc * cos_val);
}
fn cordic_outputs_in_bounds(angle: f32, iters: u8) bool {
    const ;
    if (s_arr[0] < -1.1) {
        return false;
    }
    if (s_arr[0] > 1.1) {
        return false;
    }
    if (c_arr[0] < -1.1) {
        return false;
    }
    if (c_arr[0] > 1.1) {
        return false;
    }
    return true;
}
fn cordic_sin_near_zero(angle: f32, iters: u8) bool {
    const ;
    if (s_arr[0] > -0.02) {
        if (s_arr[0] < 0.02) {
            return true;
        }
    }
    return false;
}
fn cordic_cos_near_one(angle: f32, iters: u8) bool {
    const ;
    if (c_arr[0] > 0.98) {
        if (c_arr[0] < 1.02) {
            return true;
        }
    }
    return false;
}
fn cordic_sin_near_one(angle: f32, iters: u8) bool {
    const ;
    if (s_arr[0] > 0.98) {
        if (s_arr[0] < 1.02) {
            return true;
        }
    }
    return false;
}
fn cordic_cos_near_zero(angle: f32, iters: u8) bool {
    const ;
    if (c_arr[0] > -0.02) {
        if (c_arr[0] < 0.02) {
            return true;
        }
    }
    return false;
}
test "cordic_sin_zero" {
}
test "cordic_cos_zero" {
}
test "cordic_sin_half_pi" {
}
test "cordic_cos_half_pi" {
}
comptime {
    // invariant: cordic_output_bounded
    @compileLog("invariant: cordic_output_bounded verified");
}
fn bench_cordic_latency_16() void {
    // bench: cordic_latency_16
    // Placeholder: empty benchmark body
}
