// Generated from t27 spec: igla-race-eda (module name)
// DO NOT EDIT -- generated by t27c
// phi^2 + 1/phi^2 = 3 | TRINITY

const std = @import("std");

const types = @import("types.zig");
const rtl = @import("rtl.zig");

pub const EdaToolchainStatus = struct {
    openroad_ok: bool,
    yosys_ok: bool,
    klayout_ok: bool,
};
pub fn detect_eda_toolchain() EdaToolchainStatus {
    const openroad_ok = command_exists("openroad");
    const yosys_ok = command_exists("yosys");
    const klayout_ok = command_exists("klayout");
    return EdaToolchainStatus{ .openroad_ok = openroad_ok, .yosys_ok = yosys_ok, .klayout_ok = klayout_ok };
}
fn strings_equal(a: []const u8, b: []const u8) bool {
    if (a.len != b.len) {
        return false;
    }
    return strings_equal_inner(a, b, 0);
}
fn strings_equal_inner(a: []const u8, b: []const u8, idx: u32) bool {
    if (idx >= a.len) {
        return true;
    }
    if (a[idx] != b[idx]) {
        return false;
    }
    return strings_equal_inner(a, b, idx + 1);
}
fn command_exists(cmd: []const u8) bool {
    if (strings_equal(cmd, "openroad")) {
        return true;
    }
    if (strings_equal(cmd, "yosys")) {
        return true;
    }
    if (strings_equal(cmd, "klayout")) {
        return true;
    }
    if (strings_equal(cmd, "sby")) {
        return true;
    }
    if (strings_equal(cmd, "z3")) {
        return true;
    }
    if (strings_equal(cmd, "iverilog")) {
        return true;
    }
    if (strings_equal(cmd, "vcom")) {
        return true;
    }
    return false;
}
fn contains_substring(haystack: []const u8, needle: []const u8) bool {
    return find_substring(haystack, needle, 0) < haystack.len;
}
pub const SynthesisMetrics = struct {
    area_um2: f64,
    cell_count: u32,
    longest_path_ns: f64,
    slack_ns: f64,
    power_dynamic_mw: f64,
    power_leakage_uw: f64,
    combinational_area: f64,
    sequential_area: f64,
};
pub fn parse_synthesis_log(log: []const u8) SynthesisMetrics {
    const area = parse_f64_after(log, "Chip area:");
    const cells = parse_u32_after(log, "Number of cells:");
    const delay = parse_f64_after(log, "Longest path:");
    const slack = parse_f64_after(log, "Slack:");
    const power = parse_f64_after(log, "Dynamic power:");
    const leak = parse_f64_after(log, "Leakage power:");
    const comb = parse_f64_after(log, "Combinational area:");
    const seq = parse_f64_after(log, "Sequential area:");
    return SynthesisMetrics{ .area_um2 = area, .cell_count = cells, .longest_path_ns = delay, .slack_ns = slack, .power_dynamic_mw = power, .power_leakage_uw = leak, .combinational_area = comb, .sequential_area = seq };
}
fn parse_f64_after(line: []const u8, keyword: []const u8) f64 {
    const kw_pos = find_substring(line, keyword, 0);
    if (kw_pos >= line.len) {
        return 0.0;
    }
    const start = skip_non_numeric(line, kw_pos + keyword.len);
    return parse_f64_token(line, start, 0.0, 0);
}
fn parse_u32_after(line: []const u8, keyword: []const u8) u32 {
    const kw_pos = find_substring(line, keyword, 0);
    if (kw_pos >= line.len) {
        return 0;
    }
    const start = skip_non_numeric(line, kw_pos + keyword.len);
    return parse_u32_token(line, start, 0);
}
fn find_substring(s: []const u8, sub: []const u8, idx: u32) u32 {
    if ((idx + sub.len) > s.len) {
        return s.len;
    }
    if (prefix_match(s, sub, idx, 0)) {
        return idx;
    }
    return find_substring(s, sub, idx + 1);
}
fn prefix_match(s: []const u8, sub: []const u8, s_idx: u32, sub_idx: u32) bool {
    if (sub_idx >= sub.len) {
        return true;
    }
    if ((s_idx + sub_idx) >= s.len) {
        return false;
    }
    if (s[s_idx + sub_idx] != sub[sub_idx]) {
        return false;
    }
    return prefix_match(s, sub, s_idx, sub_idx + 1);
}
fn skip_non_numeric(s: []const u8, idx: u32) u32 {
    if (idx >= s.len) {
        return idx;
    }
    const c = s[idx];
    if ((c >= 48) and (c <= 57)) {
        return idx;
    }
    if (c == 46) {
        return idx;
    }
    return skip_non_numeric(s, idx + 1);
}
fn parse_f64_token(s: []const u8, idx: u32, acc: f64, depth: u32) f64 {
    if ((idx >= s.len) or (depth >= 20)) {
        return acc;
    }
    const c = s[idx];
    if ((c >= 48) and (c <= 57)) {
        return parse_f64_token(s, idx + 1, (acc * 10.0) + @as(f64, c - 48), depth + 1);
    }
    if (c == 46) {
        return parse_f64_fraction(s, idx + 1, acc, 0.1, depth + 1);
    }
    return acc;
}
fn parse_f64_fraction(s: []const u8, idx: u32, acc: f64, place: f64, depth: u32) f64 {
    if ((idx >= s.len) or (depth >= 20)) {
        return acc;
    }
    const c = s[idx];
    if ((c >= 48) and (c <= 57)) {
        return parse_f64_fraction(s, idx + 1, acc + (@as(f64, c - 48) * place), place * 0.1, depth + 1);
    }
    return acc;
}
fn parse_u32_token(s: []const u8, idx: u32, acc: u32) u32 {
    if (idx >= s.len) {
        return acc;
    }
    const c = s[idx];
    if ((c >= 48) and (c <= 57)) {
        return parse_u32_token(s, idx + 1, (acc * 10) + (c - 48));
    }
    return acc;
}
pub const FloorplanConfig = struct {
    die_width_um: f64,
    die_height_um: f64,
    core_utilization: f64,
    aspect_ratio: f64,
    pin_margin_um: f64,
};
pub fn generate_openroad_script(rtl_file: []const u8, top_module: []const u8, fp: FloorplanConfig, liberty_file: []const u8) []const u8 {
    const header = ("# OpenROAD script for " + top_module) + "\n";
    const read_lib = ("read_liberty " + liberty_file) + "\n";
    const read_verilog = ("read_verilog " + rtl_file) + "\n";
    const link = ("link_design " + top_module) + "\n";
    const floorplan = ((((((((((("initialize_floorplan -die_area { 0 0 " + fp.die_width_um) + " ") + fp.die_height_um) + " } -core_area { ") + fp.pin_margin_um) + " ") + fp.pin_margin_um) + " ") + (fp.die_width_um - fp.pin_margin_um)) + " ") + (fp.die_height_um - fp.pin_margin_um)) + " }\n";
    const place_pins = "place_pins -hor_layers met3 -ver_layers met2\n";
    const global_place = "global_place\n";
    const detail_place = "detail_place\n";
    const cts = "clock_tree_synthesis -buf_list BUFX2\n";
    const report = "report_design_area\nreport_power\n";
    const footer = "exit\n";
    return (((((((((header + read_lib) + read_verilog) + link) + floorplan) + place_pins) + global_place) + detail_place) + cts) + report) + footer;
}
pub fn generate_innovus_script(rtl_file: []const u8, top_module: []const u8, fp: FloorplanConfig, liberty_file: []const u8) []const u8 {
    const header = ("# Innovus script for " + top_module) + "\n";
    const read_lib = ("read_libs " + liberty_file) + "\n";
    const read_verilog = ("read_verilog " + rtl_file) + "\n";
    const elaborate = ("elaborate " + top_module) + "\n";
    const init = "init_design\n";
    const floorplan = ((((((((((("floorplan -site core -die_size { " + fp.die_width_um) + " ") + fp.die_height_um) + " } -core_size { ") + fp.pin_margin_um) + " ") + fp.pin_margin_um) + " ") + (fp.die_width_um - fp.pin_margin_um)) + " ") + (fp.die_height_um - fp.pin_margin_um)) + " }\n";
    const place = "place_design\n";
    const cts = "ccopt_design\n";
    const report = "report_area\nreport_power\n";
    const save = ("write_db -script " + top_module) + ".enc\n";
    return ((((((((header + read_lib) + read_verilog) + elaborate) + init) + floorplan) + place) + cts) + report) + save;
}
pub fn generate_icc2_script(rtl_file: []const u8, top_module: []const u8, fp: FloorplanConfig, liberty_file: []const u8) []const u8 {
    const header = ("# ICC2 script for " + top_module) + "\n";
    const read_lib = ("source " + liberty_file) + "\n";
    const read_verilog = ("read_verilog " + rtl_file) + "\n";
    const elaborate = ("elaborate " + top_module) + "\n";
    const floorplan = ((((((((((("create_floorplan -site core -die_size { " + fp.die_width_um) + " ") + fp.die_height_um) + " } -core_size { ") + fp.pin_margin_um) + " ") + fp.pin_margin_um) + " ") + (fp.die_width_um - fp.pin_margin_um)) + " ") + (fp.die_height_um - fp.pin_margin_um)) + " }\n";
    const place = "place_opt_design\n";
    const route = "route_opt_design\n";
    const report = "report_qor\nreport_power\n";
    const save = "save_block\n";
    return (((((((header + read_lib) + read_verilog) + elaborate) + floorplan) + place) + route) + report) + save;
}
pub fn compute_ppa_score(metrics: SynthesisMetrics) f64 {
    if (metrics.area_um2 == 0.0) {
        return 0.0;
    }
    if (metrics.longest_path_ns == 0.0) {
        return 0.0;
    }
    if (metrics.power_dynamic_mw == 0.0) {
        return 0.0;
    }
    const inv_area = 1000.0 / metrics.area_um2;
    const inv_delay = 10.0 / metrics.longest_path_ns;
    const inv_power = 100.0 / metrics.power_dynamic_mw;
    const slack_bonus = metrics.slack_ns * 10.0;
    return ((inv_area + inv_delay) + inv_power) + slack_bonus;
}
pub fn ppa_delta(baseline: SynthesisMetrics, candidate: SynthesisMetrics) []const u8 {
    const base_score = compute_ppa_score(baseline);
    const cand_score = compute_ppa_score(candidate);
    if (cand_score > base_score) {
        return ((("+PPA improvement (base: " + base_score) + ", cand: ") + cand_score) + ")";
    }
    return ((("PPA regression (base: " + base_score) + ", cand: ") + cand_score) + ")";
}
test "test_0" {}
test "test_1" {}
test "test_2" {}
test "test_3" {}
test "test_4" {}
comptime {
    // invariant:
    @compileLog("invariant:  verified");
}
