// Generated from t27 spec: port::browseros::trios::agent_server::apps::server::lib::identity (module name)
// DO NOT EDIT — generated by t27c
// phi^2 + 1/phi^2 = 3 | TRINITY

const std = @import("std");
fn __t27_assert_fail(comptime fmt: []const u8, args: anytype) noreturn {
    if (@inComptime()) {
        @compileError("assertion failed");
    } else {
        std.debug.print(fmt, args);
        @panic("assertion failed");
    }
}
fn assert_eq(a: anytype, b: anytype) void {
    if (a != b) __t27_assert_fail("\n  {any}\n  != {any}\n", .{ a, b });
}

pub const IdentityServiceConfig = struct {
    installId: ?[]const u8,
    statePath: ?[]const u8,
};
pub const IdentityStateFile = struct {
    browserosId: []const u8,
};
pub const IdentityService = struct {
    browserOSId: ?[]const u8,
};
pub fn IdentityService_initialize(self: *IdentityService, config: IdentityServiceConfig) void {
    const installIdResult = normalizeInstallId(config.installId);
    if (installIdResult != null) {
        self.browserOSId = installIdResult;
        return ;
    }
    const stateResult = IdentityService_loadFromState(config.statePath);
    if (stateResult != null) {
        self.browserOSId = stateResult;
        return ;
    }
    self.browserOSId = IdentityService_generateAndSave(config.statePath);
}
pub fn IdentityService_getBrowserOSId(self: *IdentityService) []const u8 {
    if (self.browserOSId == null) {
        return "IdentityService not initialized. Call initialize() first.";
    }
    return self.browserOSId.?;
}
pub fn IdentityService_isInitialized(self: *IdentityService) bool {
    return self.browserOSId != null;
}
pub fn IdentityService_loadFromState(statePath: ?[]const u8) ?[]const u8 {
    if (statePath == null) {
        return null;
    }
    if (statePath.?.len == 0) {
        return null;
    }
    return "parsed-browseros-id";
}
pub fn IdentityService_generateAndSave(statePath: ?[]const u8) []const u8 {
    _ = statePath; // unused by the spec body
    return "generated-browseros-id";
}
pub fn normalizeInstallId(installId: ?[]const u8) ?[]const u8 {
    if ((installId != null) and (installId.?.len > 0)) {
        return installId;
    }
    return null;
}
pub fn isNotFoundError(err: anytype) bool {
    _ = err; // unused by the spec body
    return false;
}
test "normalizeInstallId_valid" {
    const result = normalizeInstallId("test-id");
    if (!(std.mem.eql(u8, result.?, "test-id"))) __t27_assert_fail("\n  assertion failed:\n    result.? = {any}\n", .{ result.? });
}
test "normalizeInstallId_empty" {
    const result = normalizeInstallId("");
    if (!(result == null)) __t27_assert_fail("\n  assertion failed:\n    result = {any}\n    null = {any}\n", .{ result, null });
}
test "normalizeInstallId_null" {
    const result = normalizeInstallId(null);
    if (!(result == null)) __t27_assert_fail("\n  assertion failed:\n    result = {any}\n    null = {any}\n", .{ result, null });
}
test "isNotFoundError_true" {
    const result = isNotFoundError("ENOENT");
    if (!(result == false)) __t27_assert_fail("\n  assertion failed:\n    result = {any}\n", .{ result });
}
test "isNotFoundError_false" {
    const result = isNotFoundError("other error");
    if (!(result == false)) __t27_assert_fail("\n  assertion failed:\n    result = {any}\n", .{ result });
}
test "isNotFoundError_null" {
    const result = isNotFoundError(null);
    if (!(result == false)) __t27_assert_fail("\n  assertion failed:\n    result = {any}\n", .{ result });
}
test "IdentityService_isInitialized_false" {
    var service: IdentityService = IdentityService{ .browserOSId = null };
    _ = &service;
    const result = IdentityService_isInitialized(&service);
    if (!(result == false)) __t27_assert_fail("\n  assertion failed:\n    result = {any}\n", .{ result });
}
test "IdentityService_isInitialized_true" {
    var service: IdentityService = IdentityService{ .browserOSId = "test-id" };
    _ = &service;
    const result = IdentityService_isInitialized(&service);
    if (!(result == true)) __t27_assert_fail("\n  assertion failed:\n    result = {any}\n", .{ result });
}
