// Generated from t27 spec: igla-coder-arch (module name)
// DO NOT EDIT -- generated by t27c
// phi^2 + 1/phi^2 = 3 | TRINITY

const types = @import("types.zig");
const constants = @import("constants.zig");
const igla_primitives = @import("igla_primitives.zig");

pub const MAX_PARAMS: u32 = 1_000_000_000;
pub const VOCAB_SIZE: u32 = 32000;
pub const MAX_SEQ_LEN: u32 = 8192;
pub const D_MODEL: u32 = 768;
pub const N_LAYERS: u32 = 12;
pub const N_HEADS: u32 = 12;
pub const N_KV_HEADS: u32 = 4;
pub const D_FF: u32 = 2048;
pub const ROPE_THETA: f32 = 10000.0;
pub const RMS_NORM_EPS: f32 = 0.000001;
pub const DROPOUT_RATE: f32 = 0.0;
pub const SACRED_OPCODE_COUNT: u8 = 10;
pub const OPCODE_EMBED_DIM: u32 = 64;
pub const ModelConfig = struct {
    vocab_size: u32,
    max_seq_len: u32,
    d_model: u32,
    n_layers: u32,
    n_heads: u32,
    n_kv_heads: u32,
    d_ff: u32,
    rope_theta: f32,
    rms_norm_eps: f32,
    dropout_rate: f32,
    use_gqa: bool,
    use_rope: bool,
    use_sacred_embed: bool,
};
pub const AttentionConfig = struct {
    n_heads: u32,
    n_kv_heads: u32,
    head_dim: u32,
    max_seq_len: u32,
};
pub const LayerOutput = struct {
    hidden_states: []f32,
    past_kv: []f32,
};
pub const CoderForwardOutput = struct {
    logits: []f32,
    hidden_states: []f32,
    past_key_values: [][]f32,
};
pub const KVCache = struct {
    key_cache: [][]f32,
    value_cache: [][]f32,
};
fn empty_kv_cache() KVCache {
    @panic("not yet implemented");
}
