# ALINX AX7203 (xc7a200tfbg484-2): E1 Ethernet beacon, specs/fpga/eth_beacon.t27.
# Pins from the ALINX AX7103/AX7203 manual (Gigabit Ethernet tables, user LEDs); bank 16 is 3.3 V.
# One port per line: nextpnr's XDC reader does not expand [*].
set_property -dict {PACKAGE_PIN R4 IOSTANDARD DIFF_SSTL15} [get_ports clk200_p]
set_property -dict {PACKAGE_PIN T4 IOSTANDARD DIFF_SSTL15} [get_ports clk200_n]
create_clock -period 5.000 -name clk200 [get_ports clk200_p]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports e1_txc]
set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports e1_txctl]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {e1_txd[0]}]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {e1_txd[1]}]
set_property -dict {PACKAGE_PIN A19 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {e1_txd[2]}]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {e1_txd[3]}]
set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVCMOS33} [get_ports e1_rxctl]
set_property -dict {PACKAGE_PIN A16 IOSTANDARD LVCMOS33} [get_ports {e1_rxd[0]}]
set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVCMOS33} [get_ports {e1_rxd[1]}]
set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVCMOS33} [get_ports {e1_rxd[2]}]
set_property -dict {PACKAGE_PIN C19 IOSTANDARD LVCMOS33} [get_ports {e1_rxd[3]}]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS33} [get_ports e1_rst_n]
set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports e2_txc]
set_property -dict {PACKAGE_PIN D17 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports e2_txctl]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {e2_txd[0]}]
set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {e2_txd[1]}]
set_property -dict {PACKAGE_PIN C15 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {e2_txd[2]}]
set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {e2_txd[3]}]
set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVCMOS33} [get_ports e2_rxctl]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS33} [get_ports {e2_rxd[0]}]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS33} [get_ports {e2_rxd[1]}]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33} [get_ports {e2_rxd[2]}]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS33} [get_ports {e2_rxd[3]}]
set_property -dict {PACKAGE_PIN B22 IOSTANDARD LVCMOS33} [get_ports e2_rst_n]
set_property -dict {PACKAGE_PIN B13 IOSTANDARD LVCMOS33} [get_ports {led[0]}]
set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVCMOS33} [get_ports {led[1]}]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33} [get_ports {led[2]}]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33} [get_ports {led[3]}]
