# E2e (#8770): pins of trinet_eth_top.v on the ALINX AX7203 (PHY 1, KSZ9031 RGMII; ALINX AX7203 manual).
set_property -dict {PACKAGE_PIN R4 IOSTANDARD DIFF_SSTL15} [get_ports clk200_p]
set_property -dict {PACKAGE_PIN T4 IOSTANDARD DIFF_SSTL15} [get_ports clk200_n]
create_clock -period 5.000 -name clk200 [get_ports clk200_p]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS33} [get_ports e1_rxc]
create_clock -period 40.000 -name e1_rxc [get_ports e1_rxc]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS33} [get_ports e1_rst_n]
set_property -dict {PACKAGE_PIN B22 IOSTANDARD LVCMOS33} [get_ports e2_rst_n]
set_property -dict {PACKAGE_PIN B16 IOSTANDARD LVCMOS33} [get_ports e1_mdc]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS33} [get_ports e1_mdio]
set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVCMOS33} [get_ports e1_rxctl]
set_property -dict {PACKAGE_PIN A16 IOSTANDARD LVCMOS33} [get_ports {e1_rxd[0]}]
set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVCMOS33} [get_ports {e1_rxd[1]}]
set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVCMOS33} [get_ports {e1_rxd[2]}]
set_property -dict {PACKAGE_PIN C19 IOSTANDARD LVCMOS33} [get_ports {e1_rxd[3]}]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports e1_txc]
set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports e1_txctl]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {e1_txd[0]}]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {e1_txd[1]}]
set_property -dict {PACKAGE_PIN A19 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {e1_txd[2]}]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {e1_txd[3]}]
set_property -dict {PACKAGE_PIN B13 IOSTANDARD LVCMOS33} [get_ports {led[0]}]
set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVCMOS33} [get_ports {led[1]}]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33} [get_ports {led[2]}]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33} [get_ports {led[3]}]
