/* phi^2 + phi^-2 = 3 | TRINITY */

// Re-export C ABI generated by cbindgen (included automatically)
// The actual FFI bindings will be generated in OUT_DIR by build.rs

// ============================================================================
// Type Definitions (matching C ABI)
// ============================================================================

// Re-export types from generated C code
// These will be defined by cbindgen in a separate module

// ============================================================================
// Field Extraction (all formats)
// ============================================================================

#[no_mangle]
pub extern "C" fn gf4_extract_sign(value: u8) -> i8 {
    // Extract sign bit from GF4
    ((value >> 3) & 1) as i8
}

#[no_mangle]
pub extern "C" fn gf4_extract_exponent(value: u8) -> i8 {
    // Extract exponent from GF4
    ((value >> 2) & 1) as i8
}

#[no_mangle]
pub extern "C" fn gf4_extract_mantissa(value: u8) -> i16 {
    // Extract mantissa from GF4
    (value & 3) as i16
}

#[no_mangle]
pub extern "C" fn gf8_extract_sign(value: u8) -> i8 {
    // Extract sign bit from GF8
    ((value >> 7) & 1) as i8
}

#[no_mangle]
pub extern "C" fn gf8_extract_exponent(value: u8) -> i8 {
    // Extract exponent from GF8 (bits 6:4)
    ((value >> 4) & 7) as i8
}

#[no_mangle]
pub extern "C" fn gf8_extract_mantissa(value: u8) -> i16 {
    // Extract mantissa from GF8 (bits 3:0)
    (value & 15) as i16
}

#[no_mangle]
pub extern "C" fn gf12_extract_sign(value: u16) -> i8 {
    ((value >> 11) & 1) as i8
}

#[no_mangle]
pub extern "C" fn gf12_extract_exponent(value: u16) -> i8 {
    ((value >> 7) & 15) as i8
}

#[no_mangle]
pub extern "C" fn gf12_extract_mantissa(value: u16) -> i16 {
    (value & 127) as i16
}

#[no_mangle]
pub extern "C" fn gf16_extract_sign(value: u16) -> i8 {
    ((value >> 15) & 1) as i8
}

#[no_mangle]
pub extern "C" fn gf16_extract_exponent(value: u16) -> i8 {
    ((value >> 9) & 63) as i8
}

#[no_mangle]
pub extern "C" fn gf16_extract_mantissa(value: u16) -> i16 {
    (value & 511) as i16
}

#[no_mangle]
pub extern "C" fn gf20_extract_sign(value: u32) -> i8 {
    ((value >> 19) & 1) as i8
}

#[no_mangle]
pub extern "C" fn gf20_extract_exponent(value: u32) -> i8 {
    ((value >> 12) & 127) as i8
}

#[no_mangle]
pub extern "C" fn gf20_extract_mantissa(value: u32) -> i16 {
    (value & 4095) as i16
}

#[no_mangle]
pub extern "C" fn gf24_extract_sign(value: u32) -> i8 {
    ((value >> 23) & 1) as i8
}

#[no_mangle]
pub extern "C" fn gf24_extract_exponent(value: u32) -> i8 {
    ((value >> 14) & 511) as i8
}

#[no_mangle]
pub extern "C" fn gf24_extract_mantissa(value: u32) -> i16 {
    (value & 16383) as i16
}

#[no_mangle]
pub extern "C" fn gf32_extract_sign(value: u32) -> i8 {
    ((value >> 31) & 1) as i8
}

#[no_mangle]
pub extern "C" fn gf32_extract_exponent(value: u32) -> i8 {
    ((value >> 19) & 4095) as i8
}

#[no_mangle]
pub extern "C" fn gf32_extract_mantissa(value: u32) -> i16 {
    (value & 524287) as i16
}

// ============================================================================
// Classification (selected formats - others follow same pattern)
// ============================================================================

// For now, we provide thin wrappers that implement the logic directly
// Full integration with compiled C library will be in future enhancement

#[no_mangle]
pub extern "C" fn gf16_is_zero(value: u16) -> bool {
    // Delegate to C implementation
    value == 0x0000 || value == 0x8000
}

#[no_mangle]
pub extern "C" fn gf16_is_inf(value: u16) -> bool {
    let exp = (value >> 9) & 63;
    let mant = value & 511;
    exp == 63 && mant == 0
}

#[no_mangle]
pub extern "C" fn gf16_is_nan(value: u16) -> bool {
    let exp = (value >> 9) & 63;
    let mant = value & 511;
    exp == 63 && mant != 0
}

// Similar classification for other formats
#[no_mangle]
pub extern "C" fn gf32_is_zero(value: u32) -> bool {
    value == 0
}

#[no_mangle]
pub extern "C" fn gf32_is_inf(value: u32) -> bool {
    let exp = (value >> 19) & 4095;
    exp == 4095
}

#[no_mangle]
pub extern "C" fn gf32_is_nan(value: u32) -> bool {
    let exp = (value >> 19) & 4095;
    let mant = value & 524287;
    exp == 4095 && mant != 0
}

// ============================================================================
// Encode/Decode
// ============================================================================

// Note: Full encode/decode functions will call into the compiled C library
// For initial FFI layer, we provide thin wrappers

#[no_mangle]
pub extern "C" fn gf16_from_f64(x: f64) -> u16 {
    // Convert f64 to f32 first, then encode to GF16
    let x_f32 = x as f32;
    gf16_from_f32(x_f32)
}

#[no_mangle]
pub extern "C" fn gf16_to_f64(value: u16) -> f64 {
    // Decode GF16 to f32, then convert to f64
    let f32_val = gf16_to_f32(value);
    f32_val as f64
}

#[no_mangle]
pub extern "C" fn gf16_from_f32(x: f32) -> u16 {
    // Encode f32 to GF16
    if x == 0.0 {
        return if x.is_sign_negative() { 0x8000 } else { 0x0000 };
    }

    let sign = if x < 0.0 { 0x8000u16 } else { 0u16 };
    let abs_x = x.abs();

    // Decode f32 to extract exponent and mantissa
    let bits = abs_x.to_bits();
    let f32_exp = ((bits >> 23) & 255) as i32 - 127;
    let f32_mant = bits & 0x7FFFFF;

    let mut exp = f32_exp + 31;
    if exp < 0 { exp = 0; }
    if exp > 62 { exp = 62; }

    let mut mant = (f32_mant >> 14) as u16;

    // Round to nearest
    let discarded = f32_mant & 0x3FFF;
    if discarded & 0x2000 != 0 {
        mant += 1;
        if mant > 511 {
            mant = 0;
            if exp < 62 { exp += 1; }
        }
    }

    sign | ((exp as u16) << 9) | mant
}

#[no_mangle]
pub extern "C" fn gf16_to_f32(value: u16) -> f32 {
    // Decode GF16 to f32
    if value == 0x0000 || value == 0x8000 {
        return if value == 0x8000 { -0.0 } else { 0.0 };
    }

    let sign = if (value & 0x8000) != 0 { -1.0 } else { 1.0 };
    let exp = ((value >> 9) & 63) as i32;
    let mant = (value & 511) as f32;

    if exp == 63 {
        // Special values (inf/nan)
        return if mant == 0.0 { sign * f32::INFINITY } else { f32::NAN };
    }

    let mant_norm = 1.0 + mant / 512.0;
    let exp_adj = exp - 31;
    sign * mant_norm * 2.0_f32.powi(exp_adj)
}

#[no_mangle]
pub extern "C" fn gf32_from_f64(x: f64) -> u32 {
    // Convert f64 to f32 first, then encode to GF32
    let x_f32 = x as f32;
    gf32_from_f32(x_f32)
}

#[no_mangle]
pub extern "C" fn gf32_to_f64(value: u32) -> f64 {
    // Decode GF32 to f32, then convert to f64
    let f32_val = gf32_to_f32(value);
    f32_val as f64
}

#[no_mangle]
pub extern "C" fn gf32_from_f32(x: f32) -> u32 {
    // Encode f32 to GF32
    if x == 0.0 {
        return if x.is_sign_negative() { 0x80000000 } else { 0u32 };
    }

    let sign = if x < 0.0 { 0x80000000u32 } else { 0u32 };
    let abs_x = x.abs();

    // Decode f32 to extract exponent and mantissa
    let bits = abs_x.to_bits();
    let f32_exp = ((bits >> 23) & 255) as i32 - 127;
    let f32_mant = bits & 0x7FFFFF;

    let mut exp = f32_exp + 2047;
    if exp < 0 { exp = 0; }
    if exp > 4094 { exp = 4094; }

    let mant = f32_mant as u32;

    // Scale mantissa for GF32 (19 bits vs 23 bits)
    let scaled_mant = (mant >> 4) & 524287;

    sign | ((exp as u32) << 19) | scaled_mant
}

// ============================================================================
// Arithmetic (basic operations)
// ============================================================================

// Arithmetic operations will decode to f32, operate, then re-encode
// This is a simplification for the initial FFI layer

#[no_mangle]
pub extern "C" fn gf16_add(a: u16, b: u16) -> u16 {
    let a_f32 = gf16_to_f32(a);
    let b_f32 = gf16_to_f32(b);
    let sum = a_f32 + b_f32;
    gf16_from_f32(sum)
}

#[no_mangle]
pub extern "C" fn gf16_sub(a: u16, b: u16) -> u16 {
    let a_f32 = gf16_to_f32(a);
    let b_f32 = gf16_to_f32(b);
    let diff = a_f32 - b_f32;
    gf16_from_f32(diff)
}

#[no_mangle]
pub extern "C" fn gf16_mul(a: u16, b: u16) -> u16 {
    let a_f32 = gf16_to_f32(a);
    let b_f32 = gf16_to_f32(b);
    let prod = a_f32 * b_f32;
    gf16_from_f32(prod)
}

#[no_mangle]
pub extern "C" fn gf16_div(a: u16, b: u16) -> u16 {
    let a_f32 = gf16_to_f32(a);
    let b_f32 = gf16_to_f32(b);
    if b_f32 == 0.0 {
        // Return infinity based on sign of a
        if a_f32 < 0.0 { 0xFE00 } else { 0x7E00 }
    } else {
        gf16_from_f32(a_f32 / b_f32)
    }
}

// Similar operations for GF32
#[no_mangle]
pub extern "C" fn gf32_add(a: u32, b: u32) -> u32 {
    let a_f32 = gf32_to_f32_internal(a);
    let b_f32 = gf32_to_f32_internal(b);
    let sum = a_f32 + b_f32;
    gf32_from_f32(sum)
}

#[no_mangle]
pub extern "C" fn gf32_sub(a: u32, b: u32) -> u32 {
    let a_f32 = gf32_to_f32_internal(a);
    let b_f32 = gf32_to_f32_internal(b);
    let diff = a_f32 - b_f32;
    gf32_from_f32(diff)
}

#[no_mangle]
pub extern "C" fn gf32_mul(a: u32, b: u32) -> u32 {
    let a_f32 = gf32_to_f32_internal(a);
    let b_f32 = gf32_to_f32_internal(b);
    let prod = a_f32 * b_f32;
    gf32_from_f32(prod)
}

#[no_mangle]
pub extern "C" fn gf32_div(a: u32, b: u32) -> u32 {
    let a_f32 = gf32_to_f32_internal(a);
    let b_f32 = gf32_to_f32_internal(b);
    if b_f32 == 0.0 {
        // Return infinity based on sign of a
        if a_f32 < 0.0 { 0xFFF00000 } else { 0x7FF00000 }
    } else {
        gf32_from_f32(a_f32 / b_f32)
    }
}

// ============================================================================
// GF32 f32 conversions
// ============================================================================

#[no_mangle]
pub extern "C" fn gf32_to_f32(value: u32) -> f32 {
    gf32_to_f32_internal(value)
}

// ============================================================================
// Comparison
// ============================================================================

#[no_mangle]
pub extern "C" fn gf16_eq(a: u16, b: u16) -> bool {
    if gf16_is_nan(a) || gf16_is_nan(b) { return false; }
    if gf16_is_zero(a) && gf16_is_zero(b) { return true; }
    a == b
}

#[no_mangle]
pub extern "C" fn gf16_lt(a: u16, b: u16) -> bool {
    if gf16_is_nan(a) || gf16_is_nan(b) { return false; }
    gf16_to_f32(a) < gf16_to_f32(b)
}

#[no_mangle]
pub extern "C" fn gf32_eq(a: u32, b: u32) -> bool {
    if gf32_is_nan(a) || gf32_is_nan(b) { return false; }
    a == b
}

#[no_mangle]
pub extern "C" fn gf32_lt(a: u32, b: u32) -> bool {
    if gf32_is_nan(a) || gf32_is_nan(b) { return false; }
    gf32_to_f32(a) < gf32_to_f32(b)
}

// ============================================================================
// Helper decode/encode functions (simplified)
// ============================================================================

// These are simplified implementations. For full functionality,
// they should call the compiled C library functions.

// Internal helper functions (not exported)

fn gf32_to_f32_internal(value: u32) -> f32 {
    // Simplified decode for GF32
    if value == 0 {
        return 0.0;
    }

    let sign = if (value & 0x80000000) != 0 { -1.0 } else { 1.0 };
    let exp = ((value >> 19) & 4095) as i32;
    let mant = (value & 524287) as f32;

    if exp == 4095 {
        // Special values (inf/nan)
        return if mant == 0.0 { sign * f32::INFINITY } else { f32::NAN };
    }

    let mant_norm = 1.0 + mant / 524288.0;
    let exp_adj = exp - 2047;
    sign * mant_norm * 2.0_f32.powi(exp_adj)
}
