/- Generated by `tri fpga measured-to-lean --raw-ns` from source: dry_run_live tt oscfsel 3 -/
-- operating_point source: dry_run_live
/- PVT context: { temp_c := (42 : Int), vccint_mv := 1000, vccaux_mv := 1800, process_corner := ProcessCorner.tt } -/
theorem smoke_gate_tt_oscfsel_3_dry_run_live_tt_oscfsel_3_100_50_50_satisfies_flash_spec :
  measured_cclk_from_raw_ns_with_pvt_satisfies_flash_spec 100 50 50 { temp_c := (42 : Int), vccint_mv := 1000, vccaux_mv := 1800, process_corner := ProcessCorner.tt } = true := by
  decide

theorem smoke_gate_tt_oscfsel_3_dry_run_live_tt_oscfsel_3_100_50_50_transaction_ok (bits : Nat) :
  transaction_satisfies_flash_spec (measured_boot_transaction_from_raw_ns_with_pvt 100 50 50 bits) = true := by
  apply measured_cclk_from_raw_ns_with_pvt_implies_transaction_ok 100 50 50 bits { temp_c := (42 : Int), vccint_mv := 1000, vccaux_mv := 1800, process_corner := ProcessCorner.tt }
  · decide
  · decide
  · exact smoke_gate_tt_oscfsel_3_dry_run_live_tt_oscfsel_3_100_50_50_satisfies_flash_spec
