name: Publish to Zenodo on Release

on:
  release:
    types: [published]

jobs:
  zenodo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload to Zenodo
        uses: megasanjay/upload-to-zenodo@v2.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          zenodo_token: ${{ secrets.ZENODO_TOKEN }}
          zenodo_deposition_id: "19456875"
          zenodo_publish: true
          zenodo_sandbox: false
          update_metadata_files: true
          zenodo_json: true
          citation_cff: true
