//! Codegen module
//!
//! Provides code generation for .tri specifications.
//! Part of modular compiler architecture (Ring-019 - R001).
//!
//! Re-exports codegen components with stable interface.
//!
//! This is the ONLY public entry point for compiler codegen.
//! Re-exports codegen submodules: model, lower, emit.

pub mod model;
pub mod lower;
pub mod emit;

// Re-export key types and functions
pub use model::{ModelDecl, ModelOp};
pub use lower::emit_trib;
pub use emit::emit_trib;
pub use model::lower_model;

/// Codegen façade
///
/// Orchestrates .tri spec generation with clear interface.
///
/// ## Supported Operations
///
/// ### Model Codegen (R001)
/// - `tri gen <spec>` — Generate .tri IR from model spec
///
/// ## Usage
///
/// ```bash
/// # Generate .tri IR from model spec
/// tri gen specs/trity_model.t27
///
/// # Compile to .trib bytecode
/// tri build specs/trity_model.t27
/// ```
///
pub fn compile_model(spec: &str) -> Result<String> {
    use anyhow::Result;
    use super::model::lower_model;

    // Placeholder: Returns simple .tri IR output
    // Full codegen to be implemented in future rings

    let _ir = super::model::lower_model(/* placeholder */)?;

    Ok(format!(
        "// Generated by t27c codegen v0.1.0 (R001)
// Model: {}
// {} (stub)
",
        spec
    ))
}
